/*
* hi6555c.h   --  HI6555C ALSA Soc codec driver
*/

#ifndef __HI6555C_H__
#define __HI6555C_H__


/*****************************************************************************
* MACRO DEFINE BEGIN
*****************************************************************************/

#define PAGE_SoCCODEC              0x0000
#define PAGE_PMUCODEC              0x1000
#define PAGE_PMUHKADC              0x2000
#define PAGE_PeriSCTRL             0x3000
#define PAGE_PMUCTRL               0x4000
#define PAGE_MISCCODEC             0x7000
#define PAGE_VIRCODEC              0x8000
#define PAGE_ASPCFG                0x9000
#define PAGE_AO_IOC                0xa000
#define PAGE_IOC                   0xb000
#define PAGE_PERICRG               0xc000

#define PAGE_TYPE_MASK             0xF000
#define PAGE_VALUE_MASK            0x0FFF

#define HI6555C_SoCCODEC_START    0x00
#define HI6555C_SoCCODEC_END    0xFC
#define HI6555C_PMUCODEC_START    0x260
#define HI6555C_PMUCODEC_END    0x298
#define HI6555C_PMUHKADC_START    0x00
#define HI6555C_PMUHKADC_END    0x11
#define HI6555C_PCTRL_START    0x000
#define HI6555C_PCTRL_END    0xC18
#define HI6555C_PMUCTRL_START    0x000
#define HI6555C_PMUCTRL_END    0x1A2
#define HI6555C_VIRCODEC_START    0
#define HI6555C_VIRCODEC_END    1
#define HI6555C_ASPCFG_START    0x000
#define HI6555C_ASPCFG_END    0x200
#define HI6555C_AOIOC_START    0x000
#define HI6555C_AOIOC_END    0x8B8
#define HI6555C_IOC_START    0x000
#define HI6555C_IOC_END    0xA30
#define HI6555C_PERICRG_START    0x000
#define HI6555C_PERICRG_END    0xE2C

/* codec page */
#define HI6555C_CODEC_CFG_START         (PAGE_SoCCODEC + 0x00)
#define HI6555C_CODEC_CFG_END           (PAGE_SoCCODEC + 0x8C)
#define HI6555C_CODEC_FIFO_START        (PAGE_SoCCODEC + 0xE8)
#define HI6555C_CODEC_FIFO_END          (PAGE_SoCCODEC + 0xFC)
#define HI6555C_PMU_CODEC_START         (PAGE_PMUCODEC + 0x260)
#define HI6555C_PMU_CODEC_END           (PAGE_PMUCODEC + 0x298)
#define HI6555C_PMU_HKADC_START         (PAGE_PMUHKADC + 0x00)
#define HI6555C_PMU_HKADC_END           (PAGE_PMUHKADC + 0x11)
#define HI6555C_PMU_CTRL_LDO_START         (PAGE_PMUCTRL + 0x014)
#define HI6555C_PMU_CTRL_LDO_END           (PAGE_PMUCTRL + 0x034)
#define HI6555C_PMU_CTRL_CLASSD_START        (PAGE_PMUCTRL + 0x13B)
#define HI6555C_PMU_CTRL_CLASSD_END          (PAGE_PMUCTRL + 0x13E)
#define HI6555C_PMU_CTRL_LDOV_START        (PAGE_PMUCTRL + 0x03F)
#define HI6555C_PMU_CTRL_LDOV_END          (PAGE_PMUCTRL + 0x05D)
#define HI6555C_PMU_CTRL_LDOV2             (PAGE_PMUCTRL + 0x040)
#define HI6555C_PMU_CTRL_LDOV5             (PAGE_PMUCTRL + 0x043)
#define HI6555C_PMU_CTRL_LDOV8            (PAGE_PMUCTRL + 0x045)
#define HI6555C_PMU_CTRL_LDOV23            (PAGE_PMUCTRL + 0x053)
#define HI6555C_PMU_CTRL_LDOV34            (PAGE_PMUCTRL + 0x05D)

/* tools interface */
#define HI6555C_CLASSD_POWER_IF    (0x11)
#define HI6555C_CODEC_SOCCLK_IF    (0x278)
#define HI6555C_ECO_DISABLE_IF     (0xfff)
#define HI6555C_DISABLE        (0)
#define HI6555C_ENABLE         (1)

/* virtual reg */
#define HI6555C_DDR_CODEC_VIR0_ADDR             ((PAGE_VIRCODEC) + (0x00))
#define HI6555C_DDR_CODEC_VIR1_ADDR             ((PAGE_VIRCODEC) + (0x01))

#define DDR_CODEC_BIT0  0
#define DDR_CODEC_BIT1  1
#define DDR_CODEC_BIT2  2
#define DDR_CODEC_BIT3  3
#define DDR_CODEC_BIT4  4
#define DDR_CODEC_BIT5  5
#define DDR_CODEC_BIT6  6
#define DDR_CODEC_BIT7  7
#define DDR_CODEC_BIT8  8
#define DDR_CODEC_BIT9  9
#define DDR_CODEC_BIT10 10
#define DDR_CODEC_BIT11 11
#define DDR_CODEC_BIT12 12
#define DDR_CODEC_BIT13 13
#define DDR_CODEC_BIT14 14
#define DDR_CODEC_BIT15 15
#define DDR_CODEC_BIT16 16
#define DDR_CODEC_BIT17 17
#define DDR_CODEC_BIT18 18
#define DDR_CODEC_BIT19 19
#define DDR_CODEC_BIT20 20
#define DDR_CODEC_BIT21 21
#define DDR_CODEC_BIT22 22
#define DDR_CODEC_BIT23 23
#define DDR_CODEC_BIT24 24
#define DDR_CODEC_BIT25 25
#define DDR_CODEC_BIT26 26
#define DDR_CODEC_BIT27 27
#define DDR_CODEC_BIT28 28
#define DDR_CODEC_BIT29 29
#define DDR_CODEC_BIT30 30
#define DDR_CODEC_BIT31 31

#define INVALID_REG                 0xE000
#define INVALID_REG_VALUE           0xFFFFFFFF


#define HI6555C_OFF          0
#define HI6555C_ON           1
#define HI6555C_ECO_ON       2


/* eco mode */
#define HI6555C_EXIT              0
#define HI6555C_ENTER             1
#define HI6555C_DELAY_ENTER       2

#define HI6555C_VERSION      0x30
#define STATUS_OK    0
#define STATUS_ERROR 1


/*****************************************************************************
  REG MACRO DEFINE
*****************************************************************************/

/****************************************************************************
                     (1/2) SoC CODEC
 ****************************************************************************/
#define HI6555C_SW_RST_N_ADDR                           ((PAGE_SoCCODEC) + (0x00))
#define    HI6555C_SW_RST_N_BIT_START   (0)
#define    HI6555C_SW_RST_N_BIT_END     (0)
/* reserved RO Registers */
#define    HI6555C_DIG_RO_00_BIT_START  (1)
#define    HI6555C_DIG_RO_00_BIT_END    (7)
#define    HI6555C_VERSION_BIT_START    (8)
#define    HI6555C_VERSION_BIT_END      (15)

/*use this MACRO to initialize codec sample bit to 24 bits*/
#define    HI6555C_CODEC_24BIT_SETTING  (0x3F3F0000)

#define HI6555C_IF_CLK_EN_CFG_ADDR                      ((PAGE_SoCCODEC) + (0x04))
#define    HI6555C_STEREO_UPLINK_L_EN_BIT_START  (0)
#define    HI6555C_STEREO_UPLINK_L_EN_BIT_END    (0)
#define    HI6555C_STEREO_UPLINK_R_EN_BIT_START  (1)
#define    HI6555C_STEREO_UPLINK_R_EN_BIT_END    (1)
#define    HI6555C_VOICE_UPLINK_L_EN_BIT_START   (2)
#define    HI6555C_VOICE_UPLINK_L_EN_BIT_END     (2)
#define    HI6555C_VOICE_UPLINK_R_EN_BIT_START   (3)
#define    HI6555C_VOICE_UPLINK_R_EN_BIT_END     (3)
#define    HI6555C_STEREO_DLINK_L_EN_BIT_START   (4)
#define    HI6555C_STEREO_DLINK_L_EN_BIT_END     (4)
#define    HI6555C_STEREO_DLINK_R_EN_BIT_START   (5)
#define    HI6555C_STEREO_DLINK_R_EN_BIT_END     (5)
#define    HI6555C_VOICE_DLINK_EN_BIT_START      (6)
#define    HI6555C_VOICE_DLINK_EN_BIT_END        (6)
#define    HI6555C_VOICE_DLINK_SRC_EN_BIT_START  (7)
#define    HI6555C_VOICE_DLINK_SRC_EN_BIT_END    (7)
#define    HI6555C_S1_IF_CLK_EN_BIT_START        (8)
#define    HI6555C_S1_IF_CLK_EN_BIT_END          (8)
#define    HI6555C_S1_IL_PGA_EN_BIT_START        (9)
#define    HI6555C_S1_IL_PGA_EN_BIT_END          (9)
#define    HI6555C_S1_IR_PGA_EN_BIT_START        (10)
#define    HI6555C_S1_IR_PGA_EN_BIT_END          (10)
#define    HI6555C_S2_IL_PGA_EN_BIT_START        (12)
#define    HI6555C_S2_IL_PGA_EN_BIT_END          (12)
#define    HI6555C_S2_IR_PGA_EN_BIT_START        (13)
#define    HI6555C_S2_IR_PGA_EN_BIT_END          (13)
#define    HI6555C_S2_OL_SRC_EN_BIT_START        (14)
#define    HI6555C_S2_OL_SRC_EN_BIT_END          (14)
#define    HI6555C_S2_OL_MIXER_EN_BIT_START      (15)
#define    HI6555C_S2_OL_MIXER_EN_BIT_END        (15)
#define    HI6555C_S2_IF_CLK_EN_BIT_START        (16)
#define    HI6555C_S2_IF_CLK_EN_BIT_END          (16)
#define    HI6555C_S3_IF_CLK_EN_BIT_START        (20)
#define    HI6555C_S3_IF_CLK_EN_BIT_END          (20)
#define    HI6555C_THIRDMD_DLINK_EN_BIT_START    (24)
#define    HI6555C_THIRDMD_DLINK_EN_BIT_END      (24)
#define    HI6555C_THIRDMD_UPLINK_EN_BIT_START   (25)
#define    HI6555C_THIRDMD_UPLINK_EN_BIT_END     (25)


#define HI6555C_DIG_FILTER_CLK_EN_CFG_ADDR              ((PAGE_SoCCODEC) + (0x08))
#define    HI6555C_ADCL_PGA_EN_BIT_START      (0)
#define    HI6555C_ADCL_PGA_EN_BIT_END        (0)
#define    HI6555C_ADCL_HPF_EN_BIT_START      (1)
#define    HI6555C_ADCL_HPF_EN_BIT_END        (1)
#define    HI6555C_ADCL_HBFVD_EN_BIT_START    (2)
#define    HI6555C_ADCL_HBFVD_EN_BIT_END      (2)
#define    HI6555C_ADCL_HBF2D_EN_BIT_START    (3)
#define    HI6555C_ADCL_HBF2D_EN_BIT_END      (3)
#define    HI6555C_ADCL_COMPD_EN_BIT_START    (4)
#define    HI6555C_ADCL_COMPD_EN_BIT_END      (4)
#define    HI6555C_ADCL_CIC_EN_BIT_START      (5)
#define    HI6555C_ADCL_CIC_EN_BIT_END        (5)
#define    HI6555C_SIDETONE_PGA_EN_BIT_START  (6)
#define    HI6555C_SIDETONE_PGA_EN_BIT_END    (6)
#define    HI6555C_ADCR_PGA_EN_BIT_START      (8)
#define    HI6555C_ADCR_PGA_EN_BIT_END        (8)
#define    HI6555C_ADCR_HPF_EN_BIT_START      (9)
#define    HI6555C_ADCR_HPF_EN_BIT_END        (9)
#define    HI6555C_ADCR_HBFVD_EN_BIT_START    (10)
#define    HI6555C_ADCR_HBFVD_EN_BIT_END      (10)
#define    HI6555C_ADCR_HBF2D_EN_BIT_START    (11)
#define    HI6555C_ADCR_HBF2D_EN_BIT_END      (11)
#define    HI6555C_ADCR_COMPD_EN_BIT_START    (12)
#define    HI6555C_ADCR_COMPD_EN_BIT_END      (12)
#define    HI6555C_ADCR_CIC_EN_BIT_START      (13)
#define    HI6555C_ADCR_CIC_EN_BIT_END        (13)
#define    HI6555C_DACL_AGC_EN_BIT_START      (16)
#define    HI6555C_DACL_AGC_EN_BIT_END        (16)
#define    HI6555C_DACL_MIXER_EN_BIT_START    (17)
#define    HI6555C_DACL_MIXER_EN_BIT_END      (17)
#define    HI6555C_DACL_DEEMP_EN_BIT_START    (18)
#define    HI6555C_DACL_DEEMP_EN_BIT_END      (18)
#define    HI6555C_DACL_HBF1I_EN_BIT_START    (19)
#define    HI6555C_DACL_HBF1I_EN_BIT_END      (19)
#define    HI6555C_DACL_HBF2I_EN_BIT_START    (20)
#define    HI6555C_DACL_HBF2I_EN_BIT_END      (20)
#define    HI6555C_DACL_COMPI_EN_BIT_START    (21)
#define    HI6555C_DACL_COMPI_EN_BIT_END      (21)
#define    HI6555C_DACL_SDM_EN_BIT_START      (22)
#define    HI6555C_DACL_SDM_EN_BIT_END        (22)
#define    HI6555C_DACR_AGC_EN_BIT_START      (24)
#define    HI6555C_DACR_AGC_EN_BIT_END        (24)
#define    HI6555C_DACR_MIXER_EN_BIT_START    (25)
#define    HI6555C_DACR_MIXER_EN_BIT_END      (25)
#define    HI6555C_DACR_DEEMP_EN_BIT_START    (26)
#define    HI6555C_DACR_DEEMP_EN_BIT_END      (26)
#define    HI6555C_DACR_HBF1I_EN_BIT_START    (27)
#define    HI6555C_DACR_HBF1I_EN_BIT_END      (27)
#define    HI6555C_DACR_HBF2I_EN_BIT_START    (28)
#define    HI6555C_DACR_HBF2I_EN_BIT_END      (28)
#define    HI6555C_DACR_COMPI_EN_BIT_START    (29)
#define    HI6555C_DACR_COMPI_EN_BIT_END      (29)
#define    HI6555C_DACR_SDM_EN_BIT_START      (30)
#define    HI6555C_DACR_SDM_EN_BIT_END        (30)


#define HI6555C_FS_CFG_ADDR                             ((PAGE_SoCCODEC) + (0x0C))
#define    HI6555C_FS_VOICE_DLINK_BIT_START     (0)
#define    HI6555C_FS_VOICE_DLINK_BIT_END       (2)
#define    HI6555C_FS_STEREO_DLINK_L_BIT_START  (4)
#define    HI6555C_FS_STEREO_DLINK_L_BIT_END    (6)
#define    HI6555C_FS_STEREO_DLINK_R_BIT_START  (8)
#define    HI6555C_FS_STEREO_DLINK_R_BIT_END    (10)
#define    HI6555C_FS_DACLR_BIT_START           (16)
#define    HI6555C_FS_DACLR_BIT_END             (18)
#define    HI6555C_FS_ADCLR_BIT_START           (20)
#define    HI6555C_FS_ADCLR_BIT_END             (22)
#define    HI6555C_FS_S1_BIT_START              (24)
#define    HI6555C_FS_S1_BIT_END                (26)
#define    HI6555C_FS_S2_BIT_START              (28)
#define    HI6555C_FS_S2_BIT_END                (30)


#define HI6555C_I2S_CFG_ADDR                            ((PAGE_SoCCODEC) + (0x10))
#define    HI6555C_S1_FUNC_MODE_BIT_START            (0)
#define    HI6555C_S1_FUNC_MODE_BIT_END              (2)
#define    HI6555C_S1_CODEC_DATA_FORMAT_BIT_START    (3)
#define    HI6555C_S1_CODEC_DATA_FORMAT_BIT_END      (3)
#define    HI6555C_S1_RX_CLK_SEL_BIT_START           (4)
#define    HI6555C_S1_RX_CLK_SEL_BIT_END             (4)
#define    HI6555C_S1_TX_CLK_SEL_BIT_START           (5)
#define    HI6555C_S1_TX_CLK_SEL_BIT_END             (5)
#define    HI6555C_S1_DIRECT_LOOP_BIT_START          (6)
#define    HI6555C_S1_DIRECT_LOOP_BIT_END            (7)
#define    HI6555C_S1_CODEC_IO_WORDLENGTH_BIT_START  (8)
#define    HI6555C_S1_CODEC_IO_WORDLENGTH_BIT_END    (9)
#define    HI6555C_S1_CHNNL_MODE_BIT_START           (10)
#define    HI6555C_S1_CHNNL_MODE_BIT_END             (10)
#define    HI6555C_S1_LRCLK_MODE_BIT_START           (11)
#define    HI6555C_S1_LRCLK_MODE_BIT_END             (11)
#define    HI6555C_S1_MST_SLV_BIT_START              (12)
#define    HI6555C_S1_MST_SLV_BIT_END                (12)
#define    HI6555C_S1_FRAME_MODE_BIT_START           (13)
#define    HI6555C_S1_FRAME_MODE_BIT_END             (13)
#define    HI6555C_S1_IF_RX_ENA_BIT_START            (14)
#define    HI6555C_S1_IF_RX_ENA_BIT_END              (14)
#define    HI6555C_S1_IF_TX_ENA_BIT_START            (15)
#define    HI6555C_S1_IF_TX_ENA_BIT_END              (15)
#define    HI6555C_S2_FUNC_MODE_BIT_START            (16)
#define    HI6555C_S2_FUNC_MODE_BIT_END              (18)
#define    HI6555C_S2_CODEC_DATA_FORMAT_BIT_START    (19)
#define    HI6555C_S2_CODEC_DATA_FORMAT_BIT_END      (19)
#define    HI6555C_S2_RX_CLK_SEL_BIT_START           (20)
#define    HI6555C_S2_RX_CLK_SEL_BIT_END             (20)
#define    HI6555C_S2_TX_CLK_SEL_BIT_START           (21)
#define    HI6555C_S2_TX_CLK_SEL_BIT_END             (21)
#define    HI6555C_S2_DIRECT_LOOP_BIT_START          (22)
#define    HI6555C_S2_DIRECT_LOOP_BIT_END            (23)
#define    HI6555C_S2_CODEC_IO_WORDLENGTH_BIT_START  (24)
#define    HI6555C_S2_CODEC_IO_WORDLENGTH_BIT_END    (25)
#define    HI6555C_S2_CHNNL_MODE_BIT_START           (26)
#define    HI6555C_S2_CHNNL_MODE_BIT_END             (26)
#define    HI6555C_S2_LRCLK_MODE_BIT_START           (27)
#define    HI6555C_S2_LRCLK_MODE_BIT_END             (27)
#define    HI6555C_S2_MST_SLV_BIT_START              (28)
#define    HI6555C_S2_MST_SLV_BIT_END                (28)
#define    HI6555C_S2_FRAME_MODE_BIT_START           (29)
#define    HI6555C_S2_FRAME_MODE_BIT_END             (29)
#define    HI6555C_S2_IF_RX_ENA_BIT_START            (30)
#define    HI6555C_S2_IF_RX_ENA_BIT_END              (30)
#define    HI6555C_S2_IF_TX_ENA_BIT_START            (31)
#define    HI6555C_S2_IF_TX_ENA_BIT_END              (31)


#define HI6555C_DIG_FILTER_MODULE_CFG_ADDR              ((PAGE_SoCCODEC) + (0x14))
#define    HI6555C_RM_CODEC_DAC2ADC_BIT_START     (0)
#define    HI6555C_RM_CODEC_DAC2ADC_BIT_END       (2)
#define    HI6555C_LM_CODEC_DAC2ADC_BIT_START     (4)
#define    HI6555C_LM_CODEC_DAC2ADC_BIT_END       (6)
#define    HI6555C_SW_DACL_SDM_DITHER_BIT_START   (8)
#define    HI6555C_SW_DACL_SDM_DITHER_BIT_END     (8)
#define    HI6555C_SW_DACR_SDM_DITHER_BIT_START   (9)
#define    HI6555C_SW_DACR_SDM_DITHER_BIT_END     (9)
#define    HI6555C_DACL_MIXER_IN1_MUTE_BIT_START  (16)
#define    HI6555C_DACL_MIXER_IN1_MUTE_BIT_END    (16)
#define    HI6555C_DACL_MIXER_IN2_MUTE_BIT_START  (17)
#define    HI6555C_DACL_MIXER_IN2_MUTE_BIT_END    (17)
#define    HI6555C_DACL_MIXER_IN3_MUTE_BIT_START  (18)
#define    HI6555C_DACL_MIXER_IN3_MUTE_BIT_END    (18)
#define    HI6555C_DACL_MIXER_IN4_MUTE_BIT_START  (19)
#define    HI6555C_DACL_MIXER_IN4_MUTE_BIT_END    (19)
#define    HI6555C_DACL_MIXER_GAIN_BIT_START      (20)
#define    HI6555C_DACL_MIXER_GAIN_BIT_END        (21)
#define    HI6555C_DACR_MIXER_IN1_MUTE_BIT_START  (24)
#define    HI6555C_DACR_MIXER_IN1_MUTE_BIT_END    (24)
#define    HI6555C_DACR_MIXER_IN2_MUTE_BIT_START  (25)
#define    HI6555C_DACR_MIXER_IN2_MUTE_BIT_END    (25)
#define    HI6555C_DACR_MIXER_IN3_MUTE_BIT_START  (26)
#define    HI6555C_DACR_MIXER_IN3_MUTE_BIT_END    (26)
#define    HI6555C_DACR_MIXER_IN4_MUTE_BIT_START  (27)
#define    HI6555C_DACR_MIXER_IN4_MUTE_BIT_END    (27)
#define    HI6555C_DACR_MIXER_GAIN_BIT_START      (28)
#define    HI6555C_DACR_MIXER_GAIN_BIT_END        (29)


#define HI6555C_MUX_TOP_MODULE_CFG_ADDR                 ((PAGE_SoCCODEC) + (0x18))
#define    HI6555C_VOICE_DLINK_SRC_MODE_BIT_START        (0)
#define    HI6555C_VOICE_DLINK_SRC_MODE_BIT_END          (2)
#define    HI6555C_VOICE_DLINK_SRC_RDY_BIT_START         (3)
#define    HI6555C_VOICE_DLINK_SRC_RDY_BIT_END           (3)
#define    HI6555C_S2_OL_SRC_MODE_BIT_START              (4)
#define    HI6555C_S2_OL_SRC_MODE_BIT_END                (5)
#define    HI6555C_S2_OL_SRC_RDY_BIT_START               (6)
#define    HI6555C_S2_OL_SRC_RDY_BIT_END                 (6)
#define    HI6555C_S2_OL_MIXER_IN1_MUTE_BIT_START        (8)
#define    HI6555C_S2_OL_MIXER_IN1_MUTE_BIT_END          (8)
#define    HI6555C_S2_OL_MIXER_IN2_MUTE_BIT_START        (9)
#define    HI6555C_S2_OL_MIXER_IN2_MUTE_BIT_END          (9)
#define    HI6555C_S2_OL_MIXER_GAIN_BIT_START            (10)
#define    HI6555C_S2_OL_MIXER_GAIN_BIT_END              (11)
#define    HI6555C_VOICE_DLINK_MIXER_IN1_MUTE_BIT_START  (12)
#define    HI6555C_VOICE_DLINK_MIXER_IN1_MUTE_BIT_END    (12)
#define    HI6555C_VOICE_DLINK_MIXER_IN2_MUTE_BIT_START  (13)
#define    HI6555C_VOICE_DLINK_MIXER_IN2_MUTE_BIT_END    (13)
#define    HI6555C_VOICE_DLINK_MIXER_GAIN_BIT_START      (14)
#define    HI6555C_VOICE_DLINK_MIXER_GAIN_BIT_END        (15)


#define HI6555C_ADC_PGA_CFG_ADDR                        ((PAGE_SoCCODEC) + (0x1C))
#define    HI6555C_ADCL_PGA_INTEGER_CONFIG_BIT_START  (0)
#define    HI6555C_ADCL_PGA_INTEGER_CONFIG_BIT_END    (7)
#define    HI6555C_ADCL_PGA_FRAC_CONFIG_BIT_START     (8)
#define    HI6555C_ADCL_PGA_FRAC_CONFIG_BIT_END       (8)
#define    HI6555C_ADCL_PGA_MUTE_BIT_START            (9)
#define    HI6555C_ADCL_PGA_MUTE_BIT_END              (9)
#define    HI6555C_ADCL_PGA_THR_CONFIG_BIT_START      (12)
#define    HI6555C_ADCL_PGA_THR_CONFIG_BIT_END        (13)
#define    HI6555C_ADCR_PGA_INTEGER_CONFIG_BIT_START  (16)
#define    HI6555C_ADCR_PGA_INTEGER_CONFIG_BIT_END    (23)
#define    HI6555C_ADCR_PGA_FRAC_CONFIG_BIT_START     (24)
#define    HI6555C_ADCR_PGA_FRAC_CONFIG_BIT_END       (24)
#define    HI6555C_ADCR_PGA_MUTE_BIT_START            (25)
#define    HI6555C_ADCR_PGA_MUTE_BIT_END              (25)
#define    HI6555C_ADCR_PGA_THR_CONFIG_BIT_START      (28)
#define    HI6555C_ADCR_PGA_THR_CONFIG_BIT_END        (29)


#define HI6555C_S1_INPUT_PGA_CFG_ADDR                   ((PAGE_SoCCODEC) + (0x20))
#define    HI6555C_S1_IL_PGA_INTEGER_CONFIG_BIT_START  (0)
#define    HI6555C_S1_IL_PGA_INTEGER_CONFIG_BIT_END    (7)
#define    HI6555C_S1_IL_PGA_FRAC_CONFIG_BIT_START     (8)
#define    HI6555C_S1_IL_PGA_FRAC_CONFIG_BIT_END       (8)
#define    HI6555C_S1_IL_PGA_MUTE_BIT_START            (9)
#define    HI6555C_S1_IL_PGA_MUTE_BIT_END              (9)
#define    HI6555C_S1_IL_PGA_THR_CONFIG_BIT_START      (12)
#define    HI6555C_S1_IL_PGA_THR_CONFIG_BIT_END        (13)
#define    HI6555C_S1_IR_PGA_INTEGER_CONFIG_BIT_START  (16)
#define    HI6555C_S1_IR_PGA_INTEGER_CONFIG_BIT_END    (23)
#define    HI6555C_S1_IR_PGA_FRAC_CONFIG_BIT_START     (24)
#define    HI6555C_S1_IR_PGA_FRAC_CONFIG_BIT_END       (24)
#define    HI6555C_S1_IR_PGA_MUTE_BIT_START            (25)
#define    HI6555C_S1_IR_PGA_MUTE_BIT_END              (25)
#define    HI6555C_S1_IR_PGA_THR_CONFIG_BIT_START      (28)
#define    HI6555C_S1_IR_PGA_THR_CONFIG_BIT_END        (29)


#define HI6555C_S2_INPUT_PGA_CFG_ADDR                   ((PAGE_SoCCODEC) + (0x24))
#define    HI6555C_S2_IL_PGA_INTEGER_CONFIG_BIT_START  (0)
#define    HI6555C_S2_IL_PGA_INTEGER_CONFIG_BIT_END    (7)
#define    HI6555C_S2_IL_PGA_FRAC_CONFIG_BIT_START     (8)
#define    HI6555C_S2_IL_PGA_FRAC_CONFIG_BIT_END       (8)
#define    HI6555C_S2_IL_PGA_MUTE_BIT_START            (9)
#define    HI6555C_S2_IL_PGA_MUTE_BIT_END              (9)
#define    HI6555C_S2_IL_PGA_THR_CONFIG_BIT_START      (12)
#define    HI6555C_S2_IL_PGA_THR_CONFIG_BIT_END        (13)
#define    HI6555C_S2_IR_PGA_INTEGER_CONFIG_BIT_START  (16)
#define    HI6555C_S2_IR_PGA_INTEGER_CONFIG_BIT_END    (23)
#define    HI6555C_S2_IR_PGA_FRAC_CONFIG_BIT_START     (24)
#define    HI6555C_S2_IR_PGA_FRAC_CONFIG_BIT_END       (24)
#define    HI6555C_S2_IR_PGA_MUTE_BIT_START            (25)
#define    HI6555C_S2_IR_PGA_MUTE_BIT_END              (25)
#define    HI6555C_S2_IR_PGA_THR_CONFIG_BIT_START      (28)
#define    HI6555C_S2_IR_PGA_THR_CONFIG_BIT_END        (29)


#define HI6555C_STEREO_DLINK_PGA_CFG_ADDR               ((PAGE_SoCCODEC) + (0x28))
#define    HI6555C_STEREO_DLINK_L_PGA_INTEGER_CONFIG_BIT_START  (0)
#define    HI6555C_STEREO_DLINK_L_PGA_INTEGER_CONFIG_BIT_END    (7)
#define    HI6555C_STEREO_DLINK_L_PGA_FRAC_CONFIG_BIT_START     (8)
#define    HI6555C_STEREO_DLINK_L_PGA_FRAC_CONFIG_BIT_END       (8)
#define    HI6555C_STEREO_DLINK_L_PGA_MUTE_BIT_START            (9)
#define    HI6555C_STEREO_DLINK_L_PGA_MUTE_BIT_END              (9)
#define    HI6555C_STEREO_DLINK_L_PGA_THR_CONFIG_BIT_START      (12)
#define    HI6555C_STEREO_DLINK_L_PGA_THR_CONFIG_BIT_END        (13)
#define    HI6555C_STEREO_DLINK_R_PGA_INTEGER_CONFIG_BIT_START  (16)
#define    HI6555C_STEREO_DLINK_R_PGA_INTEGER_CONFIG_BIT_END    (23)
#define    HI6555C_STEREO_DLINK_R_PGA_FRAC_CONFIG_BIT_START     (24)
#define    HI6555C_STEREO_DLINK_R_PGA_FRAC_CONFIG_BIT_END       (24)
#define    HI6555C_STEREO_DLINK_R_PGA_MUTE_BIT_START            (25)
#define    HI6555C_STEREO_DLINK_R_PGA_MUTE_BIT_END              (25)
#define    HI6555C_STEREO_DLINK_R_PGA_THR_CONFIG_BIT_START      (28)
#define    HI6555C_STEREO_DLINK_R_PGA_THR_CONFIG_BIT_END        (29)


#define HI6555C_VOICE_SIDETONE_DLINK_PGA_CFG_ADDR       ((PAGE_SoCCODEC) + (0x2C))
#define    HI6555C_VOICE_DLINK_PGA_INTEGER_CONFIG_BIT_START  (0)
#define    HI6555C_VOICE_DLINK_PGA_INTEGER_CONFIG_BIT_END    (7)
#define    HI6555C_VOICE_DLINK_PGA_FRAC_CONFIG_BIT_START     (8)
#define    HI6555C_VOICE_DLINK_PGA_FRAC_CONFIG_BIT_END       (8)
#define    HI6555C_VOICE_DLINK_PGA_MUTE_BIT_START            (9)
#define    HI6555C_VOICE_DLINK_PGA_MUTE_BIT_END              (9)
#define    HI6555C_VOICE_DLINK_PGA_THR_CONFIG_BIT_START      (12)
#define    HI6555C_VOICE_DLINK_PGA_THR_CONFIG_BIT_END        (13)
#define    HI6555C_SIDETONE_PGA_INTEGER_CONFIG_BIT_START     (16)
#define    HI6555C_SIDETONE_PGA_INTEGER_CONFIG_BIT_END       (23)
#define    HI6555C_SIDETONE_PGA_FRAC_CONFIG_BIT_START        (24)
#define    HI6555C_SIDETONE_PGA_FRAC_CONFIG_BIT_END          (24)
#define    HI6555C_SIDETONE_PGA_MUTE_BIT_START               (25)
#define    HI6555C_SIDETONE_PGA_MUTE_BIT_END                 (25)
#define    HI6555C_SIDETONE_PGA_THR_CONFIG_BIT_START         (28)
#define    HI6555C_SIDETONE_PGA_THR_CONFIG_BIT_END           (29)


#define HI6555C_APB_AFIFO_CFG_1_ADDR                    ((PAGE_SoCCODEC) + (0x30))
#define    HI6555C_STEREO_UPLINK_L_FIFO_CLR_BIT_START     (0)
#define    HI6555C_STEREO_UPLINK_L_FIFO_CLR_BIT_END       (0)
#define    HI6555C_STEREO_UPLINK_R_FIFO_CLR_BIT_START     (1)
#define    HI6555C_STEREO_UPLINK_R_FIFO_CLR_BIT_END       (1)
#define    HI6555C_VOICE_UPLINK_L_FIFO_CLR_BIT_START      (2)
#define    HI6555C_VOICE_UPLINK_L_FIFO_CLR_BIT_END        (2)
#define    HI6555C_VOICE_UPLINK_R_FIFO_CLR_BIT_START      (3)
#define    HI6555C_VOICE_UPLINK_R_FIFO_CLR_BIT_END        (3)
#define    HI6555C_STEREO_DLINK_L_FIFO_CLR_BIT_START      (4)
#define    HI6555C_STEREO_DLINK_L_FIFO_CLR_BIT_END        (4)
#define    HI6555C_STEREO_DLINK_R_FIFO_CLR_BIT_START      (5)
#define    HI6555C_STEREO_DLINK_R_FIFO_CLR_BIT_END        (5)
#define    HI6555C_VOICE_DLINK_FIFO_CLR_BIT_START         (6)
#define    HI6555C_VOICE_DLINK_FIFO_CLR_BIT_END           (6)
#define    HI6555C_THIRDMD_DLINK_FIFO_CLR_BIT_START       (7)
#define    HI6555C_THIRDMD_DLINK_FIFO_CLR_BIT_END         (7)
#define    HI6555C_THIRDMD_UPLINK_FIFO_CLR_BIT_START      (8)
#define    HI6555C_THIRDMD_UPLINK_FIFO_CLR_BIT_END        (8)
#define    HI6555C_STEREO_UPLINK_L_FIFO_WERROR_BIT_START  (16)
#define    HI6555C_STEREO_UPLINK_L_FIFO_WERROR_BIT_END    (16)
#define    HI6555C_STEREO_UPLINK_R_FIFO_WERROR_BIT_START  (17)
#define    HI6555C_STEREO_UPLINK_R_FIFO_WERROR_BIT_END    (17)
#define    HI6555C_VOICE_UPLINK_L_FIFO_WERROR_BIT_START   (18)
#define    HI6555C_VOICE_UPLINK_L_FIFO_WERROR_BIT_END     (18)
#define    HI6555C_VOICE_UPLINK_R_FIFO_WERROR_BIT_START   (19)
#define    HI6555C_VOICE_UPLINK_R_FIFO_WERROR_BIT_END     (19)
#define    HI6555C_STEREO_DLINK_L_FIFO_WERROR_BIT_START   (20)
#define    HI6555C_STEREO_DLINK_L_FIFO_WERROR_BIT_END     (20)
#define    HI6555C_STEREO_DLINK_R_FIFO_WERROR_BIT_START   (21)
#define    HI6555C_STEREO_DLINK_R_FIFO_WERROR_BIT_END     (21)
#define    HI6555C_VOICE_DLINK_FIFO_WERROR_BIT_START      (22)
#define    HI6555C_VOICE_DLINK_FIFO_WERROR_BIT_END        (22)
#define    HI6555C_STEREO_UPLINK_L_FIFO_RERROR_BIT_START  (24)
#define    HI6555C_STEREO_UPLINK_L_FIFO_RERROR_BIT_END    (24)
#define    HI6555C_STEREO_UPLINK_R_FIFO_RERROR_BIT_START  (25)
#define    HI6555C_STEREO_UPLINK_R_FIFO_RERROR_BIT_END    (25)
#define    HI6555C_VOICE_UPLINK_L_FIFO_RERROR_BIT_START   (26)
#define    HI6555C_VOICE_UPLINK_L_FIFO_RERROR_BIT_END     (26)
#define    HI6555C_VOICE_UPLINK_R_FIFO_RERROR_BIT_START   (27)
#define    HI6555C_VOICE_UPLINK_R_FIFO_RERROR_BIT_END     (27)
#define    HI6555C_STEREO_DLINK_L_FIFO_RERROR_BIT_START   (28)
#define    HI6555C_STEREO_DLINK_L_FIFO_RERROR_BIT_END     (28)
#define    HI6555C_STEREO_DLINK_R_FIFO_RERROR_BIT_START   (29)
#define    HI6555C_STEREO_DLINK_R_FIFO_RERROR_BIT_END     (29)
#define    HI6555C_VOICE_DLINK_FIFO_RERROR_BIT_START      (30)
#define    HI6555C_VOICE_DLINK_FIFO_RERROR_BIT_END        (30)


#define HI6555C_APB_AFIFO_CFG_2_ADDR                    ((PAGE_SoCCODEC) + (0x34))
#define    HI6555C_VOICE_DLINK_FIFO_AFULL_TH_BIT_START     (0)
#define    HI6555C_VOICE_DLINK_FIFO_AFULL_TH_BIT_END       (4)
#define    HI6555C_VOICE_DLINK_FIFO_AEMPTY_TH_BIT_START    (8)
#define    HI6555C_VOICE_DLINK_FIFO_AEMPTY_TH_BIT_END      (12)
#define    HI6555C_STEREO_UPLINK_L_FIFO_DIN_SEL_BIT_START  (16)
#define    HI6555C_STEREO_UPLINK_L_FIFO_DIN_SEL_BIT_END    (16)
#define    HI6555C_STEREO_UPLINK_R_FIFO_DIN_SEL_BIT_START  (17)
#define    HI6555C_STEREO_UPLINK_R_FIFO_DIN_SEL_BIT_END    (17)
#define    HI6555C_VOICE_UPLINK_L_FIFO_DIN_SEL_BIT_START   (18)
#define    HI6555C_VOICE_UPLINK_L_FIFO_DIN_SEL_BIT_END     (18)
#define    HI6555C_VOICE_UPLINK_R_FIFO_DIN_SEL_BIT_START   (19)
#define    HI6555C_VOICE_UPLINK_R_FIFO_DIN_SEL_BIT_END     (19)
#define    HI6555C_THIRDMD_UPLINK_DIN_SEL_BIT_START        (20)
#define    HI6555C_THIRDMD_UPLINK_DIN_SEL_BIT_END          (20)


#define HI6555C_STEREO_DLINK_FIFO_TH_CFG_ADDR           ((PAGE_SoCCODEC) + (0x38))
#define    HI6555C_STEREO_DLINK_L_FIFO_AFULL_TH_BIT_START   (0)
#define    HI6555C_STEREO_DLINK_L_FIFO_AFULL_TH_BIT_END     (4)
#define    HI6555C_STEREO_DLINK_L_FIFO_AEMPTY_TH_BIT_START  (8)
#define    HI6555C_STEREO_DLINK_L_FIFO_AEMPTY_TH_BIT_END    (12)
#define    HI6555C_STEREO_DLINK_R_FIFO_AFULL_TH_BIT_START   (16)
#define    HI6555C_STEREO_DLINK_R_FIFO_AFULL_TH_BIT_END     (20)
#define    HI6555C_STEREO_DLINK_R_FIFO_AEMPTY_TH_BIT_START  (24)
#define    HI6555C_STEREO_DLINK_R_FIFO_AEMPTY_TH_BIT_END    (28)


#define HI6555C_STEREO_UPLINK_FIFO_TH_CFG_ADDR          ((PAGE_SoCCODEC) + (0x3C))
#define    HI6555C_STEREO_UPLINK_L_FIFO_AFULL_TH_BIT_START   (0)
#define    HI6555C_STEREO_UPLINK_L_FIFO_AFULL_TH_BIT_END     (4)
#define    HI6555C_STEREO_UPLINK_L_FIFO_AEMPTY_TH_BIT_START  (8)
#define    HI6555C_STEREO_UPLINK_L_FIFO_AEMPTY_TH_BIT_END    (12)
#define    HI6555C_STEREO_UPLINK_R_FIFO_AFULL_TH_BIT_START   (16)
#define    HI6555C_STEREO_UPLINK_R_FIFO_AFULL_TH_BIT_END     (20)
#define    HI6555C_STEREO_UPLINK_R_FIFO_AEMPTY_TH_BIT_START  (24)
#define    HI6555C_STEREO_UPLINK_R_FIFO_AEMPTY_TH_BIT_END    (28)


#define HI6555C_VOICE_UPLINK_FIFO_TH_CFG_ADDR           ((PAGE_SoCCODEC) + (0x40))
#define    HI6555C_VOICE_UPLINK_L_FIFO_AFULL_TH_BIT_START   (0)
#define    HI6555C_VOICE_UPLINK_L_FIFO_AFULL_TH_BIT_END     (4)
#define    HI6555C_VOICE_UPLINK_L_FIFO_AEMPTY_TH_BIT_START  (8)
#define    HI6555C_VOICE_UPLINK_L_FIFO_AEMPTY_TH_BIT_END    (12)
#define    HI6555C___B1___RIGHT____BIT_START                (13)
#define    HI6555C___B1___RIGHT____BIT_END                  (15)
#define    HI6555C___B0___LEFT____BIT_START                 (16)
#define    HI6555C___B0___LEFT____BIT_END                   (20)
#define    HI6555C_VOICE_UPLINK_R_FIFO_AEMPTY_TH_BIT_START  (24)
#define    HI6555C_VOICE_UPLINK_R_FIFO_AEMPTY_TH_BIT_END    (28)


#define HI6555C_CODEC_IRQ_MASK_ADDR                     ((PAGE_SoCCODEC) + (0x44))
#define    HI6555C_CODEC_DATA_INTRP_MASK_BIT_START  (0)
#define    HI6555C_CODEC_DATA_INTRP_MASK_BIT_END    (5)


#define HI6555C_CODEC_IRQ_ADDR                          ((PAGE_SoCCODEC) + (0x48))
#define    HI6555C_CODEC_DATA_INTRP_BIT_START  (0)
#define    HI6555C_CODEC_DATA_INTRP_BIT_END    (5)


#define HI6555C_DACL_AGC_CFG_1_ADDR                     ((PAGE_SoCCODEC) + (0x4C))
#define    HI6555C_DACL_AGC_GWIN_CONFIG_BIT_START      (0)
#define    HI6555C_DACL_AGC_GWIN_CONFIG_BIT_END        (1)
#define    HI6555C_DACL_AGC_LEVELLOW_CONFIG_BIT_START  (2)
#define    HI6555C_DACL_AGC_LEVELLOW_CONFIG_BIT_END    (3)
#define    HI6555C_DACL_AGC_GSTEPD_CONFIG_BIT_START    (4)
#define    HI6555C_DACL_AGC_GSTEPD_CONFIG_BIT_END      (5)
#define    HI6555C_DACL_AGC_TIMEMUTE_CONFIG_BIT_START  (6)
#define    HI6555C_DACL_AGC_TIMEMUTE_CONFIG_BIT_END    (7)
#define    HI6555C_DACL_AGC_NGW_CONFIG_BIT_START       (8)
#define    HI6555C_DACL_AGC_NGW_CONFIG_BIT_END         (9)
#define    HI6555C_DACL_AGC_YTARGET_CONFIG_BIT_START   (10)
#define    HI6555C_DACL_AGC_YTARGET_CONFIG_BIT_END     (12)
#define    HI6555C_DACL_AGC_T_AMIN_CONFIG_BIT_START    (13)
#define    HI6555C_DACL_AGC_T_AMIN_CONFIG_BIT_END      (14)
#define    HI6555C_DACL_AGC_GSUPPRESS_BIT_START        (15)
#define    HI6555C_DACL_AGC_GSUPPRESS_BIT_END          (15)
#define    HI6555C_DACL_AGC_KFSLOW_BIT_START           (16)
#define    HI6555C_DACL_AGC_KFSLOW_BIT_END             (17)
#define    HI6555C_DACL_AGC_KFRAPID_BIT_START          (18)
#define    HI6555C_DACL_AGC_KFRAPID_BIT_END            (19)
#define    HI6555C_DACL_AGC_NGL_CONFIG_BIT_START       (20)
#define    HI6555C_DACL_AGC_NGL_CONFIG_BIT_END         (21)
#define    HI6555C_DACL_AGC_NGH_CONFIG_BIT_START       (22)
#define    HI6555C_DACL_AGC_NGH_CONFIG_BIT_END         (23)
#define    HI6555C_DACL_AGC_TIMER_BIT_START            (24)
#define    HI6555C_DACL_AGC_TIMER_BIT_END              (26)
#define    HI6555C_DACL_AGC_NGI_CONFIG_BIT_START       (27)
#define    HI6555C_DACL_AGC_NGI_CONFIG_BIT_END         (29)
#define    HI6555C_DACL_AGC_TIMENNG_CONFIG_BIT_START   (30)
#define    HI6555C_DACL_AGC_TIMENNG_CONFIG_BIT_END     (31)


#define HI6555C_DACL_AGC_CFG_2_ADDR                     ((PAGE_SoCCODEC) + (0x50))
#define    HI6555C_DACL_AGC_TIMEDECAY_CONFIG_BIT_START  (0)
#define    HI6555C_DACL_AGC_TIMEDECAY_CONFIG_BIT_END    (1)
#define    HI6555C_DACL_AGC_TIMEGHOLD_CONFIG_BIT_START  (2)
#define    HI6555C_DACL_AGC_TIMEGHOLD_CONFIG_BIT_END    (3)
#define    HI6555C_DACL_AGC_GMUTE_CONFIG_BIT_START      (4)
#define    HI6555C_DACL_AGC_GMUTE_CONFIG_BIT_END        (5)
#define    HI6555C_DACL_AGC_MUTE_BYPASS_BIT_START       (6)
#define    HI6555C_DACL_AGC_MUTE_BYPASS_BIT_END         (6)
#define    HI6555C_DACL_AGC_BYPASS_BIT_START            (7)
#define    HI6555C_DACL_AGC_BYPASS_BIT_END              (7)
#define    HI6555C_DACL_AGC_USR_GDB_INTEGER_BIT_START   (8)
#define    HI6555C_DACL_AGC_USR_GDB_INTEGER_BIT_END     (15)
#define    HI6555C_DACL_AGC_USR_GDB_FRAC_BIT_START      (16)
#define    HI6555C_DACL_AGC_USR_GDB_FRAC_BIT_END        (16)
#define    HI6555C_DACL_AGC_SW_CLR_BIT_START            (17)
#define    HI6555C_DACL_AGC_SW_CLR_BIT_END              (17)


#define HI6555C_DACR_AGC_CFG_1_ADDR                     ((PAGE_SoCCODEC) + (0x54))
#define    HI6555C_DACR_AGC_GWIN_CONFIG_BIT_START      (0)
#define    HI6555C_DACR_AGC_GWIN_CONFIG_BIT_END        (1)
#define    HI6555C_DACR_AGC_LEVELLOW_CONFIG_BIT_START  (2)
#define    HI6555C_DACR_AGC_LEVELLOW_CONFIG_BIT_END    (3)
#define    HI6555C_DACR_AGC_GSTEPD_CONFIG_BIT_START    (4)
#define    HI6555C_DACR_AGC_GSTEPD_CONFIG_BIT_END      (5)
#define    HI6555C_DACR_AGC_TIMEMUTE_CONFIG_BIT_START  (6)
#define    HI6555C_DACR_AGC_TIMEMUTE_CONFIG_BIT_END    (7)
#define    HI6555C_DACR_AGC_NGW_CONFIG_BIT_START       (8)
#define    HI6555C_DACR_AGC_NGW_CONFIG_BIT_END         (9)
#define    HI6555C_DACR_AGC_YTARGET_CONFIG_BIT_START   (10)
#define    HI6555C_DACR_AGC_YTARGET_CONFIG_BIT_END     (12)
#define    HI6555C_DACR_AGC_T_AMIN_CONFIG_BIT_START    (13)
#define    HI6555C_DACR_AGC_T_AMIN_CONFIG_BIT_END      (14)
#define    HI6555C_DACR_AGC_GSUPPRESS_BIT_START        (15)
#define    HI6555C_DACR_AGC_GSUPPRESS_BIT_END          (15)
#define    HI6555C_DACR_AGC_KFSLOW_BIT_START           (16)
#define    HI6555C_DACR_AGC_KFSLOW_BIT_END             (17)
#define    HI6555C_DACR_AGC_KFRAPID_BIT_START          (18)
#define    HI6555C_DACR_AGC_KFRAPID_BIT_END            (19)
#define    HI6555C_DACR_AGC_NGL_CONFIG_BIT_START       (20)
#define    HI6555C_DACR_AGC_NGL_CONFIG_BIT_END         (21)
#define    HI6555C_DACR_AGC_NGH_CONFIG_BIT_START       (22)
#define    HI6555C_DACR_AGC_NGH_CONFIG_BIT_END         (23)
#define    HI6555C_DACR_AGC_TIMER_BIT_START            (24)
#define    HI6555C_DACR_AGC_TIMER_BIT_END              (26)
#define    HI6555C_DACR_AGC_NGI_CONFIG_BIT_START       (27)
#define    HI6555C_DACR_AGC_NGI_CONFIG_BIT_END         (29)
#define    HI6555C_DACR_AGC_TIMENNG_CONFIG_BIT_START   (30)
#define    HI6555C_DACR_AGC_TIMENNG_CONFIG_BIT_END     (31)


#define HI6555C_DACR_AGC_CFG_2_ADDR                     ((PAGE_SoCCODEC) + (0x58))
#define    HI6555C_DACR_AGC_TIMEDECAY_CONFIG_BIT_START  (0)
#define    HI6555C_DACR_AGC_TIMEDECAY_CONFIG_BIT_END    (1)
#define    HI6555C_DACR_AGC_TIMEGHOLD_CONFIG_BIT_START  (2)
#define    HI6555C_DACR_AGC_TIMEGHOLD_CONFIG_BIT_END    (3)
#define    HI6555C_DACR_AGC_GMUTE_CONFIG_BIT_START      (4)
#define    HI6555C_DACR_AGC_GMUTE_CONFIG_BIT_END        (5)
#define    HI6555C_DACR_AGC_MUTE_BYPASS_BIT_START       (6)
#define    HI6555C_DACR_AGC_MUTE_BYPASS_BIT_END         (6)
#define    HI6555C_DACR_AGC_BYPASS_BIT_START            (7)
#define    HI6555C_DACR_AGC_BYPASS_BIT_END              (7)
#define    HI6555C_DACR_AGC_USR_GDB_INTEGER_BIT_START   (8)
#define    HI6555C_DACR_AGC_USR_GDB_INTEGER_BIT_END     (15)
#define    HI6555C_DACR_AGC_USR_GDB_FRAC_BIT_START      (16)
#define    HI6555C_DACR_AGC_USR_GDB_FRAC_BIT_END        (16)
#define    HI6555C_DACR_AGC_SW_CLR_BIT_START            (17)
#define    HI6555C_DACR_AGC_SW_CLR_BIT_END              (17)


#define HI6555C_DMIC_SIF_CFG_ADDR                       ((PAGE_SoCCODEC) + (0x5C))
#define    HI6555C_SIF_ADCL_EN_BIT_START       (0)
#define    HI6555C_SIF_ADCL_EN_BIT_END         (0)
#define    HI6555C_SIF_ADCR_EN_BIT_START       (1)
#define    HI6555C_SIF_ADCR_EN_BIT_END         (1)
#define    HI6555C_SIF_DACL_EN_BIT_START       (2)
#define    HI6555C_SIF_DACL_EN_BIT_END         (2)
#define    HI6555C_SIF_DACR_EN_BIT_START       (3)
#define    HI6555C_SIF_DACR_EN_BIT_END         (3)
#define    HI6555C_DAC_P2S_LOOPBACK_BIT_START  (4)
#define    HI6555C_DAC_P2S_LOOPBACK_BIT_END    (4)
#define    HI6555C_SIF_S2P_LOOPBACK_BIT_START  (5)
#define    HI6555C_SIF_S2P_LOOPBACK_BIT_END    (5)
#define    HI6555C_SIF_EDGE_SEL_BIT_START      (6)
#define    HI6555C_SIF_EDGE_SEL_BIT_END        (6)
#define    HI6555C_SIF_EN_BIT_START            (7)
#define    HI6555C_SIF_EN_BIT_END              (7)
#define    HI6555C_SW_DMIC_MODE_BIT_START      (16)
#define    HI6555C_SW_DMIC_MODE_BIT_END        (16)
#define    HI6555C_DMIC_REVERSE_BIT_START      (17)
#define    HI6555C_DMIC_REVERSE_BIT_END        (17)
#define    HI6555C_FS_DMIC_BIT_START           (18)
#define    HI6555C_FS_DMIC_BIT_END             (19)
#define    HI6555C_DMIC_EN_BIT_START           (20)
#define    HI6555C_DMIC_EN_BIT_END             (20)


#define HI6555C_MISC_CFG_ADDR                           ((PAGE_SoCCODEC) + (0x60))
#define    HI6555C_S2_DOUT_LEFT_SEL_BIT_START                 (0)
#define    HI6555C_S2_DOUT_LEFT_SEL_BIT_END                   (0)
#define    HI6555C_S1_DOUT_TEST_SEL_BIT_START                 (1)
#define    HI6555C_S1_DOUT_TEST_SEL_BIT_END                   (1)
#define    HI6555C_S2_DOUT_TEST_SEL_BIT_START                 (2)
#define    HI6555C_S2_DOUT_TEST_SEL_BIT_END                   (2)
#define    HI6555C_STEREO_DLINK_TEST_SEL_BIT_START            (4)
#define    HI6555C_STEREO_DLINK_TEST_SEL_BIT_END              (4)
#define    HI6555C_VOICE_DLINK_DIN_SEL_BIT_START              (6)
#define    HI6555C_VOICE_DLINK_DIN_SEL_BIT_END                (6)
#define    HI6555C_VOICE_DLINK_TEST_SEL_BIT_START             (7)
#define    HI6555C_VOICE_DLINK_TEST_SEL_BIT_END               (7)
#define    HI6555C_VOICE_DLINK_SRC_UP_DOUT_VLD_SEL_BIT_START  (8)
#define    HI6555C_VOICE_DLINK_SRC_UP_DOUT_VLD_SEL_BIT_END    (8)
#define    HI6555C_S3_DIN_TEST_SEL_BIT_START                  (12)
#define    HI6555C_S3_DIN_TEST_SEL_BIT_END                    (12)
#define    HI6555C_S3_DOUT_LEFT_SEL_BIT_START                 (13)
#define    HI6555C_S3_DOUT_LEFT_SEL_BIT_END                   (13)
#define    HI6555C_S3_DOUT_RIGHT_SEL_BIT_START                (14)
#define    HI6555C_S3_DOUT_RIGHT_SEL_BIT_END                  (15)
#define    HI6555C_THIRDMD_DLINK_DIN_SEL_BIT_START            (16)
#define    HI6555C_THIRDMD_DLINK_DIN_SEL_BIT_END              (16)
#define    HI6555C_THIRDMD_DLINK_TEST_SEL_BIT_START           (17)
#define    HI6555C_THIRDMD_DLINK_TEST_SEL_BIT_END             (17)


#define HI6555C_S2_SRC_CFG_ADDR                         ((PAGE_SoCCODEC) + (0x64))
#define    HI6555C_S2_IL_SRC_UP_EN_BIT_START         (0)
#define    HI6555C_S2_IL_SRC_UP_EN_BIT_END           (0)
#define    HI6555C_S2_IL_SRC_DOWN_EN_BIT_START       (1)
#define    HI6555C_S2_IL_SRC_DOWN_EN_BIT_END         (1)
#define    HI6555C_S2_IR_SRC_UP_EN_BIT_START         (2)
#define    HI6555C_S2_IR_SRC_UP_EN_BIT_END           (2)
#define    HI6555C_S2_IR_SRC_DOWN_EN_BIT_START       (3)
#define    HI6555C_S2_IR_SRC_DOWN_EN_BIT_END         (3)
#define    HI6555C_S2_IL_SRC_UP_SRC_RDY_BIT_START    (4)
#define    HI6555C_S2_IL_SRC_UP_SRC_RDY_BIT_END      (4)
#define    HI6555C_S2_IL_SRC_DOWN_SRC_RDY_BIT_START  (5)
#define    HI6555C_S2_IL_SRC_DOWN_SRC_RDY_BIT_END    (5)
#define    HI6555C_S2_IR_SRC_UP_SRC_RDY_BIT_START    (6)
#define    HI6555C_S2_IR_SRC_UP_SRC_RDY_BIT_END      (6)
#define    HI6555C_S2_IR_SRC_DOWN_SRC_RDY_BIT_START  (7)
#define    HI6555C_S2_IR_SRC_DOWN_SRC_RDY_BIT_END    (7)


#define HI6555C_MEM_CFG_ADDR                            ((PAGE_SoCCODEC) + (0x68))
#define    HI6555C_MEM_CTRL_S_BIT_START      (0)
#define    HI6555C_MEM_CTRL_S_BIT_END        (15)
#define    HI6555C_MEM_CTRL_D1W2R_BIT_START  (16)
#define    HI6555C_MEM_CTRL_D1W2R_BIT_END    (31)


#define HI6555C_THIRDMD_PCM_PGA_CFG_ADDR                ((PAGE_SoCCODEC) + (0x6C))
#define    HI6555C_S3_FUNC_MODE_BIT_START                      (0)
#define    HI6555C_S3_FUNC_MODE_BIT_END                        (2)
#define    HI6555C_S3_CODEC_DATA_FORMAT_BIT_START              (3)
#define    HI6555C_S3_CODEC_DATA_FORMAT_BIT_END                (3)
#define    HI6555C_S3_RX_CLK_SEL_BIT_START                     (4)
#define    HI6555C_S3_RX_CLK_SEL_BIT_END                       (4)
#define    HI6555C_S3_TX_CLK_SEL_BIT_START                     (5)
#define    HI6555C_S3_TX_CLK_SEL_BIT_END                       (5)
#define    HI6555C_S3_DIRECT_LOOP_BIT_START                    (6)
#define    HI6555C_S3_DIRECT_LOOP_BIT_END                      (7)
#define    HI6555C_S3_CODEC_IO_WORDLENGTH_BIT_START            (8)
#define    HI6555C_S3_CODEC_IO_WORDLENGTH_BIT_END              (9)
#define    HI6555C_S3_CHNNL_MODE_BIT_START                     (10)
#define    HI6555C_S3_CHNNL_MODE_BIT_END                       (10)
#define    HI6555C_S3_LRCLK_MODE_BIT_START                     (11)
#define    HI6555C_S3_LRCLK_MODE_BIT_END                       (11)
#define    HI6555C_S3_MST_SLV_BIT_START                        (12)
#define    HI6555C_S3_MST_SLV_BIT_END                          (12)
#define    HI6555C_S3_FRAME_MODE_BIT_START                     (13)
#define    HI6555C_S3_FRAME_MODE_BIT_END                       (13)
#define    HI6555C_S3_IF_RX_ENA_BIT_START                      (14)
#define    HI6555C_S3_IF_RX_ENA_BIT_END                        (14)
#define    HI6555C_S3_IF_TX_ENA_BIT_START                      (15)
#define    HI6555C_S3_IF_TX_ENA_BIT_END                        (15)
#define    HI6555C_FS_S3_BIT_START                             (16)
#define    HI6555C_FS_S3_BIT_END                               (18)
#define    HI6555C_THIRDMD_DLINK_PGA_INTEGER_CONFIG_BIT_START  (20)
#define    HI6555C_THIRDMD_DLINK_PGA_INTEGER_CONFIG_BIT_END    (27)
#define    HI6555C_THIRDMD_DLINK_PGA_FRAC_CONFIG_BIT_START     (28)
#define    HI6555C_THIRDMD_DLINK_PGA_FRAC_CONFIG_BIT_END       (28)
#define    HI6555C_THIRDMD_DLINK_PGA_MUTE_BIT_START            (29)
#define    HI6555C_THIRDMD_DLINK_PGA_MUTE_BIT_END              (29)
#define    HI6555C_THIRDMD_DLINK_PGA_THR_CONFIG_BIT_START      (30)
#define    HI6555C_THIRDMD_DLINK_PGA_THR_CONFIG_BIT_END        (31)


#define HI6555C_THIRD_MODEM_FIFO_TH_ADDR                ((PAGE_SoCCODEC) + (0x70))
#define    HI6555C_THIRDMD_DLINK_FIFO_AFULL_TH_BIT_START    (0)
#define    HI6555C_THIRDMD_DLINK_FIFO_AFULL_TH_BIT_END      (4)
#define    HI6555C_THIRDMD_DLINK_FIFO_AEMPTY_TH_BIT_START   (8)
#define    HI6555C_THIRDMD_DLINK_FIFO_AEMPTY_TH_BIT_END     (12)
#define    HI6555C_THIRDMD_UPLINK_FIFO_AFULL_TH_BIT_START   (16)
#define    HI6555C_THIRDMD_UPLINK_FIFO_AFULL_TH_BIT_END     (20)
#define    HI6555C_THIRDMD_UPLINK_FIFO_AEMPTY_TH_BIT_START  (24)
#define    HI6555C_THIRDMD_UPLINK_FIFO_AEMPTY_TH_BIT_END    (28)


#define HI6555C_S3_ANTI_FREQ_JITTER_TX_INC_CNT_ADDR     ((PAGE_SoCCODEC) + (0x74))
#define    HI6555C_S3_TX_INC_CNT_BIT_START  (0)
#define    HI6555C_S3_TX_INC_CNT_BIT_END    (7)


#define HI6555C_S3_ANTI_FREQ_JITTER_TX_DEC_CNT_ADDR     ((PAGE_SoCCODEC) + (0x78))
#define    HI6555C_S3_TX_DEC_CNT_BIT_START  (0)
#define    HI6555C_S3_TX_DEC_CNT_BIT_END    (7)


#define HI6555C_S3_ANTI_FREQ_JITTER_RX_INC_CNT_ADDR     ((PAGE_SoCCODEC) + (0x7C))
#define    HI6555C_S3_RX_INC_CNT_BIT_START  (0)
#define    HI6555C_S3_RX_INC_CNT_BIT_END    (7)


#define HI6555C_S3_ANTI_FREQ_JITTER_RX_DEC_CNT_ADDR     ((PAGE_SoCCODEC) + (0x80))
#define    HI6555C_S3_RX_DEC_CNT_BIT_START  (0)
#define    HI6555C_S3_RX_DEC_CNT_BIT_END    (7)


#define HI6555C_ANTI_FREQ_JITTER_EN_ADDR                ((PAGE_SoCCODEC) + (0x84))
#define    HI6555C_S3_TX_ANTI_FREQ_JITTER_EN_BIT_START  (0)
#define    HI6555C_S3_TX_ANTI_FREQ_JITTER_EN_BIT_END    (0)
#define    HI6555C_S3_RX_ANTI_FREQ_JITTER_EN_BIT_START  (1)
#define    HI6555C_S3_RX_ANTI_FREQ_JITTER_EN_BIT_END    (1)


#define HI6555C_CLK_SEL_ADDR                            ((PAGE_SoCCODEC) + (0x88))
#define    HI6555C_EXTERNAL_12288K_SEL_BIT_START  (0)
#define    HI6555C_EXTERNAL_12288K_SEL_BIT_END    (0)


#define HI6555C_UPLINK_TEST_SEL_ADDR                ((PAGE_SoCCODEC) + (0x8C))
#define    HI6555C_STEREO_UPLINK_R_TEST_SEL_BIT_START         (0)
#define    HI6555C_STEREO_UPLINK_R_TEST_SEL_BIT_END           (0)
#define    HI6555C_STEREO_UPLINK_L_TEST_SEL_BIT_START       (1)
#define    HI6555C_STEREO_UPLINK_L_TEST_SEL_BIT_END         (1)
#define    HI6555C_VOICE_UPLINK_L_TEST_SEL_BIT_START         (2)
#define    HI6555C_VOICE_UPLINK_L_TEST_SEL_BIT_END           (2)
#define    HI6555C_THIRDMD_UPLINK_L_TEST_SEL_BIT_START       (3)
#define    HI6555C_THIRDMD_UPLINK_L_TEST_SEL_BIT_END         (3)
#define    HI6555C_SMART_PA_FB_SEL_BIT_START    (4)
#define    HI6555C_SMART_PA_FB_SEL_BIT_END      (4)


#define HI6555C_THIRDMD_DLINK_CHANNEL_ADDR              ((PAGE_SoCCODEC) + (0xE8))
#define    HI6555C_THIRDMD_DLINK_WDATA_BIT_START  (0)
#define    HI6555C_THIRDMD_DLINK_WDATA_BIT_END    (31)


#define HI6555C_THIRDMD_UPLINK_CHANNEL_ADDR             ((PAGE_SoCCODEC) + (0xEC))
#define    HI6555C_THIRDMD_UPLINK_RDATA_BIT_START  (0)
#define    HI6555C_THIRDMD_UPLINK_RDATA_BIT_END    (31)


#define HI6555C_VOICE_DLINK_CHANNEL_ADDR                ((PAGE_SoCCODEC) + (0xF0))
#define    HI6555C_VOICE_DLINK_WDATA_BIT_START  (0)
#define    HI6555C_VOICE_DLINK_WDATA_BIT_END    (31)


#define HI6555C_STEREO_DLINK_CHANNEL_ADDR               ((PAGE_SoCCODEC) + (0xF4))
#define    HI6555C_STEREO_DLINK_WDATA_BIT_START  (0)
#define    HI6555C_STEREO_DLINK_WDATA_BIT_END    (31)


#define HI6555C_STEREO_UPLINK_CHANNEL_ADDR              ((PAGE_SoCCODEC) + (0xF8))
#define    HI6555C_STEREO_UPLINK_RDATA_BIT_START  (0)
#define    HI6555C_STEREO_UPLINK_RDATA_BIT_END    (31)


#define HI6555C_VOICE_UPLINK_CHANNEL_ADDR               ((PAGE_SoCCODEC) + (0xFC))
#define    HI6555C_VOICE_UPLINK_RDATA_BIT_START  (0)
#define    HI6555C_VOICE_UPLINK_RDATA_BIT_END    (31)




/****************************************************************************
                     (2/2) PMU CODEC
 ****************************************************************************/
#define HI6555C_SMT_VERSION_ADDR                        ((PAGE_PMUCODEC) + (0x005))
#define    HI6555C_SMT_VERSION_BIT_START  (0)
#define    HI6555C_SMT_VERSION_BIT_END    (7)


#define HI6555C_SMT_CLK_EN_CFG_ADDR                     ((PAGE_PMUCODEC) + (0x260))
#define    HI6555C_SMT_DACL_EN_BIT_START   (0)
#define    HI6555C_SMT_DACL_EN_BIT_END     (0)
#define    HI6555C_SMT_DACR_EN_BIT_START   (1)
#define    HI6555C_SMT_DACR_EN_BIT_END     (1)
#define    HI6555C_SMT_ADCL_EN_BIT_START   (2)
#define    HI6555C_SMT_ADCL_EN_BIT_END     (2)
#define    HI6555C_SMT_ADCR_EN_BIT_START   (3)
#define    HI6555C_SMT_ADCR_EN_BIT_END     (3)
#define    HI6555C_SMT_SIF_EN_BIT_START    (4)
#define    HI6555C_SMT_SIF_EN_BIT_END      (4)


#define HI6555C_SMT_CLK_EDGE_CFG_ADDR                   ((PAGE_PMUCODEC) + (0x261))
#define    HI6555C_SMT_DACL_CLK_EDGE_SEL_BIT_START  (0)
#define    HI6555C_SMT_DACL_CLK_EDGE_SEL_BIT_END    (0)
#define    HI6555C_SMT_DACR_CLK_EDGE_SEL_BIT_START  (1)
#define    HI6555C_SMT_DACR_CLK_EDGE_SEL_BIT_END    (1)
#define    HI6555C_SMT_ADCL_CLK_EDGE_SEL_BIT_START  (2)
#define    HI6555C_SMT_ADCL_CLK_EDGE_SEL_BIT_END    (2)
#define    HI6555C_SMT_ADCR_CLK_EDGE_SEL_BIT_START  (3)
#define    HI6555C_SMT_ADCR_CLK_EDGE_SEL_BIT_END    (3)


#define HI6555C_SMT_LOOPBACK_CFG_ADDR                   ((PAGE_PMUCODEC) + (0x262))
#define    HI6555C_SMT_DAC_LOOPBACK_BIT_START      (0)
#define    HI6555C_SMT_DAC_LOOPBACK_BIT_END        (0)
#define    HI6555C_SMT_ADC_LOOPBACK_BIT_START      (1)
#define    HI6555C_SMT_ADC_LOOPBACK_BIT_END        (1)
#define    HI6555C_SMT_SIF_S2P_LOOPBACK_BIT_START  (2)
#define    HI6555C_SMT_SIF_S2P_LOOPBACK_BIT_END    (2)


#define HI6555C_SMT_ANA_IRQ_SIG_STAT_ADDR               ((PAGE_PMUCODEC) + (0x263))
#define    HI6555C_SMT_HS_MIC_NOR1_IRQ_BIT_START  (0)
#define    HI6555C_SMT_HS_MIC_NOR1_IRQ_BIT_END    (0)
#define    HI6555C_SMT_HS_MIC_NOR2_IRQ_BIT_START  (1)
#define    HI6555C_SMT_HS_MIC_NOR2_IRQ_BIT_END    (1)
#define    HI6555C_SMT_HS_MIC_ECO_IRQ_BIT_START   (2)
#define    HI6555C_SMT_HS_MIC_ECO_IRQ_BIT_END     (2)
#define    HI6555C_SMT_HS_DET_IRQ_BIT_START       (3)
#define    HI6555C_SMT_HS_DET_IRQ_BIT_END         (3)


#define HI6555C_SMT_ANA_IRQM_REG0_ADDR                  ((PAGE_PMUCODEC) + (0x264))
#define    HI6555C_SMT_ANA_IRQ_MASK_BIT_START  (0)
#define    HI6555C_SMT_ANA_IRQ_MASK_BIT_END    (7)


#define HI6555C_SMT_ANA_IRQ_REG0_ADDR                   ((PAGE_PMUCODEC) + (0x265))
#define    HI6555C_SMT_HS_MIC_NOR1_IRQ_POS_BIT_START  (0)
#define    HI6555C_SMT_HS_MIC_NOR1_IRQ_POS_BIT_END    (0)
#define    HI6555C_SMT_HS_MIC_NOR1_IRQ_NEG_BIT_START  (1)
#define    HI6555C_SMT_HS_MIC_NOR1_IRQ_NEG_BIT_END    (1)
#define    HI6555C_SMT_HS_MIC_NOR2_IRQ_POS_BIT_START  (2)
#define    HI6555C_SMT_HS_MIC_NOR2_IRQ_POS_BIT_END    (2)
#define    HI6555C_SMT_HS_MIC_NOR2_IRQ_NEG_BIT_START  (3)
#define    HI6555C_SMT_HS_MIC_NOR2_IRQ_NEG_BIT_END    (3)
#define    HI6555C_SMT_HS_MIC_ECO_IRQ_POS_BIT_START   (4)
#define    HI6555C_SMT_HS_MIC_ECO_IRQ_POS_BIT_END     (4)
#define    HI6555C_SMT_HS_MIC_ECO_IRQ_NEG_BIT_START   (5)
#define    HI6555C_SMT_HS_MIC_ECO_IRQ_NEG_BIT_END     (5)
#define    HI6555C_SMT_HS_DET_IRQ_POS_BIT_START       (6)
#define    HI6555C_SMT_HS_DET_IRQ_POS_BIT_END         (6)
#define    HI6555C_SMT_HS_DET_IRQ_NEG_BIT_START       (7)
#define    HI6555C_SMT_HS_DET_IRQ_NEG_BIT_END         (7)


#define HI6555C_SMT_DEB_CNT_HS_DET_CFG_ADDR             ((PAGE_PMUCODEC) + (0x266))
#define    HI6555C_SMT_DEB_CNT_HS_DET_IRQ_BIT_START     (0)
#define    HI6555C_SMT_DEB_CNT_HS_DET_IRQ_BIT_END       (4)
#define    HI6555C_SMT_BYPASS_DEB_HS_DET_IRQ_BIT_START  (5)
#define    HI6555C_SMT_BYPASS_DEB_HS_DET_IRQ_BIT_END    (5)


#define HI6555C_SMT_DEB_CNT_HS_MIC_CFG_ADDR             ((PAGE_PMUCODEC) + (0x267))
#define    HI6555C_SMT_DEB_CNT_HS_MIC_IRQ_BIT_START     (0)
#define    HI6555C_SMT_DEB_CNT_HS_MIC_IRQ_BIT_END       (4)
#define    HI6555C_SMT_BYPASS_DEB_HS_MIC_IRQ_BIT_START  (5)
#define    HI6555C_SMT_BYPASS_DEB_HS_MIC_IRQ_BIT_END    (5)


#define HI6555C_SMT_CODEC_DIG_RES02_ADDR                ((PAGE_PMUCODEC) + (0x268))


#define HI6555C_SMT_CODEC_DIG_RES03_ADDR                ((PAGE_PMUCODEC) + (0x269))


#define HI6555C_SMT_CODEC_ANA_RW01_ADDR                 ((PAGE_PMUCODEC) + (0x26A))
#define    HI6555C_SMT_LINEPGAR_PD_BIT_START  (0)
#define    HI6555C_SMT_LINEPGAR_PD_BIT_END    (0)
#define    HI6555C_SMT_LINEPGAL_PD_BIT_START  (1)
#define    HI6555C_SMT_LINEPGAL_PD_BIT_END    (1)
#define    HI6555C_SMT_AUXPGA_PD_BIT_START    (2)
#define    HI6555C_SMT_AUXPGA_PD_BIT_END      (2)
#define    HI6555C_SMT_MAINPGA_PD_BIT_START   (3)
#define    HI6555C_SMT_MAINPGA_PD_BIT_END     (3)
#define    HI6555C_SMT_ADCR_PD_BIT_START      (4)
#define    HI6555C_SMT_ADCR_PD_BIT_END        (4)
#define    HI6555C_SMT_ADCL_PD_BIT_START      (5)
#define    HI6555C_SMT_ADCL_PD_BIT_END        (5)


#define HI6555C_SMT_CODEC_ANA_RW02_ADDR                 ((PAGE_PMUCODEC) + (0x26B))
#define    HI6555C_SMT_IBIAS_PD_BIT_START      (0)
#define    HI6555C_SMT_IBIAS_PD_BIT_END        (0)
#define    HI6555C_SMT_MBHD_BUFF_PD_BIT_START  (4)
#define    HI6555C_SMT_MBHD_BUFF_PD_BIT_END    (4)
#define    HI6555C_SMT_MBHD_COMP_PD_BIT_START  (5)
#define    HI6555C_SMT_MBHD_COMP_PD_BIT_END    (5)
#define    HI6555C_SMT_HSMICB_PD_BIT_START     (6)
#define    HI6555C_SMT_HSMICB_PD_BIT_END       (6)
#define    HI6555C_SMT_MICB1_PD_BIT_START      (7)
#define    HI6555C_SMT_MICB1_PD_BIT_END        (7)


#define HI6555C_SMT_CODEC_ANA_RW03_ADDR                 ((PAGE_PMUCODEC) + (0x26C))
#define    HI6555C_SMT_HSR_PD_BIT_START         (1)
#define    HI6555C_SMT_HSR_PD_BIT_END           (1)
#define    HI6555C_SMT_HSL_PD_BIT_START         (2)
#define    HI6555C_SMT_HSL_PD_BIT_END           (2)
#define    HI6555C_SMT_MIXOUT_HSR_PD_BIT_START  (4)
#define    HI6555C_SMT_MIXOUT_HSR_PD_BIT_END    (4)
#define    HI6555C_SMT_MIXOUT_HSL_PD_BIT_START  (5)
#define    HI6555C_SMT_MIXOUT_HSL_PD_BIT_END    (5)


#define HI6555C_SMT_CODEC_ANA_RW04_ADDR                 ((PAGE_PMUCODEC) + (0x26D))
#define    HI6555C_SMT_VREFSEL_BIT_START   (0)
#define    HI6555C_SMT_VREFSEL_BIT_END     (1)


#define HI6555C_SMT_CODEC_ANA_RW05_ADDR                 ((PAGE_PMUCODEC) + (0x26E))
#define    HI6555C_SMT_LINEPGAL_MUTE_BIT_START  (0)
#define    HI6555C_SMT_LINEPGAL_MUTE_BIT_END    (0)
#define    HI6555C_SMT_LINEPGAL_GAIN_BIT_START  (1)
#define    HI6555C_SMT_LINEPGAL_GAIN_BIT_END    (4)
#define    HI6555C_SMT_LINEPGAL_SEL_BIT_START   (5)
#define    HI6555C_SMT_LINEPGAL_SEL_BIT_END     (6)


#define HI6555C_SMT_CODEC_ANA_RW06_ADDR                 ((PAGE_PMUCODEC) + (0x26F))
#define    HI6555C_SMT_LINEPGAR_MUTE_BIT_START  (0)
#define    HI6555C_SMT_LINEPGAR_MUTE_BIT_END    (0)
#define    HI6555C_SMT_LINEPGAR_GAIN_BIT_START  (1)
#define    HI6555C_SMT_LINEPGAR_GAIN_BIT_END    (4)
#define    HI6555C_SMT_LINEPGAR_SEL_BIT_START   (5)
#define    HI6555C_SMT_LINEPGAR_SEL_BIT_END     (6)


#define HI6555C_SMT_CODEC_ANA_RW07_ADDR                 ((PAGE_PMUCODEC) + (0x270))
#define    HI6555C_SMT_AUXPGA_SEL_BIT_START         (0)
#define    HI6555C_SMT_AUXPGA_SEL_BIT_END           (1)
#define    HI6555C_SMT_AUXPGA_MUTE_BIT_START        (2)
#define    HI6555C_SMT_AUXPGA_MUTE_BIT_END          (2)
#define    HI6555C_SMT_AUXPGA_GAIN_BIT_START        (3)
#define    HI6555C_SMT_AUXPGA_GAIN_BIT_END          (5)
#define    HI6555C_SMT_AUXPGA_BOOST_BIT_START       (6)
#define    HI6555C_SMT_AUXPGA_BOOST_BIT_END         (6)
#define    HI6555C_SMT_MICPGA_UNLOCK_BPS_BIT_START  (7)
#define    HI6555C_SMT_MICPGA_UNLOCK_BPS_BIT_END    (7)


#define HI6555C_SMT_CODEC_ANA_RW08_ADDR                 ((PAGE_PMUCODEC) + (0x271))
#define    HI6555C_SMT_MAINPGA_MUTE_BIT_START   (0)
#define    HI6555C_SMT_MAINPGA_MUTE_BIT_END     (0)
#define    HI6555C_SMT_MAINPGA_GAIN_BIT_START   (1)
#define    HI6555C_SMT_MAINPGA_GAIN_BIT_END     (3)
#define    HI6555C_SMT_MAINPGA_BOOST_BIT_START  (4)
#define    HI6555C_SMT_MAINPGA_BOOST_BIT_END    (4)
#define    HI6555C_SMT_MAINPGA_SEL_BIT_START    (5)
#define    HI6555C_SMT_MAINPGA_SEL_BIT_END      (6)


#define HI6555C_SMT_CODEC_ANA_RW09_ADDR                 ((PAGE_PMUCODEC) + (0x272))
#define    HI6555C_SMT_ADCR_MIXIN_BIT_START  (0)
#define    HI6555C_SMT_ADCR_MIXIN_BIT_END    (5)


#define HI6555C_SMT_CODEC_ANA_RW10_ADDR                 ((PAGE_PMUCODEC) + (0x273))
#define    HI6555C_SMT_ADCL_MIXIN_BIT_START  (0)
#define    HI6555C_SMT_ADCL_MIXIN_BIT_END    (5)


#define HI6555C_SMT_CODEC_ANA_RW11_ADDR                 ((PAGE_PMUCODEC) + (0x274))
#define    HI6555C_SMT_ADCL_DWA_BPS_BIT_START      (0)
#define    HI6555C_SMT_ADCL_DWA_BPS_BIT_END        (0)
#define    HI6555C_SMT_ADCL_FLSTN_BIT_START        (1)
#define    HI6555C_SMT_ADCL_FLSTN_BIT_END          (2)
#define    HI6555C_SMT_ADCL_DAC_BIAS_BIT_START     (3)
#define    HI6555C_SMT_ADCL_DAC_BIAS_BIT_END       (4)
#define    HI6555C_SMT_ADCL_CLK_DELAY_0_BIT_START  (5)
#define    HI6555C_SMT_ADCL_CLK_DELAY_0_BIT_END    (5)
#define    HI6555C_SMT_ADCL_CLK_DELAY_1_BIT_START  (6)
#define    HI6555C_SMT_ADCL_CLK_DELAY_1_BIT_END    (6)
#define    HI6555C_SMT_ADCL_CLK_DELAY_2_BIT_START  (7)
#define    HI6555C_SMT_ADCL_CLK_DELAY_2_BIT_END    (7)


#define HI6555C_SMT_CODEC_ANA_RW12_ADDR                 ((PAGE_PMUCODEC) + (0x275))
#define    HI6555C_SMT_ADCR_DWA_BPS_BIT_START      (0)
#define    HI6555C_SMT_ADCR_DWA_BPS_BIT_END        (0)
#define    HI6555C_SMT_ADCR_FLSTN_BIT_START        (1)
#define    HI6555C_SMT_ADCR_FLSTN_BIT_END          (2)
#define    HI6555C_SMT_ADCR_DAC_BIAS_BIT_START     (3)
#define    HI6555C_SMT_ADCR_DAC_BIAS_BIT_END       (4)
#define    HI6555C_SMT_ADCR_CLK_DELAY_0_BIT_START  (5)
#define    HI6555C_SMT_ADCR_CLK_DELAY_0_BIT_END    (5)
#define    HI6555C_SMT_ADCR_CLK_DELAY_1_BIT_START  (6)
#define    HI6555C_SMT_ADCR_CLK_DELAY_1_BIT_END    (6)
#define    HI6555C_SMT_ADCR_CLK_DELAY_2_BIT_START  (7)
#define    HI6555C_SMT_ADCR_CLK_DELAY_2_BIT_END    (7)


#define HI6555C_SMT_CODEC_ANA_RW13_ADDR                 ((PAGE_PMUCODEC) + (0x276))
#define    HI6555C_SMT_MIXOUT_HSR_BIT_START  (0)
#define    HI6555C_SMT_MIXOUT_HSR_BIT_END    (3)
#define    HI6555C_SMT_MIXOUT_HSL_BIT_START  (4)
#define    HI6555C_SMT_MIXOUT_HSL_BIT_END    (7)


#define HI6555C_SMT_CODEC_ANA_RW14_ADDR                 ((PAGE_PMUCODEC) + (0x277))
#define    HI6555C_SMT_CR_MIXF_BIT_START     (0)
#define    HI6555C_SMT_CR_MIXF_BIT_END       (3)
#define    HI6555C_SMT_MIXOUT_EAR_BIT_START  (4)
#define    HI6555C_SMT_MIXOUT_EAR_BIT_END    (7)


#define HI6555C_SMT_CODEC_ANA_RW15_ADDR                 ((PAGE_PMUCODEC) + (0x278))
#define    HI6555C_SMT_CP_DTC_3_BIT_START    (0)
#define    HI6555C_SMT_CP_DTC_3_BIT_END      (1)
#define    HI6555C_SMT_CP_DTC_2_BIT_START    (2)
#define    HI6555C_SMT_CP_DTC_2_BIT_END      (3)
#define    HI6555C_SMT_DACR_ICTRL_BIT_START  (4)
#define    HI6555C_SMT_DACR_ICTRL_BIT_END    (5)
#define    HI6555C_SMT_DACL_ICTRL_BIT_START  (6)
#define    HI6555C_SMT_DACL_ICTRL_BIT_END    (7)


#define HI6555C_SMT_CODEC_ANA_RW16_ADDR                 ((PAGE_PMUCODEC) + (0x279))
#define    HI6555C_SMT_CP_DR_CTRL_BIT_START  (0)
#define    HI6555C_SMT_CP_DR_CTRL_BIT_END    (1)
#define    HI6555C_SMT_CLASSG_REF_BIT_START  (2)
#define    HI6555C_SMT_CLASSG_REF_BIT_END    (3)
#define    HI6555C_SMT_CP_MODE_BIT_START     (4)
#define    HI6555C_SMT_CP_MODE_BIT_END       (5)
#define    HI6555C_SMT_EN_CP_MODE_BIT_START  (6)
#define    HI6555C_SMT_EN_CP_MODE_BIT_END    (6)
#define    HI6555C_SMT_HP_SOFT_EN_BIT_START  (7)
#define    HI6555C_SMT_HP_SOFT_EN_BIT_END    (7)


#define HI6555C_SMT_CODEC_ANA_RW17_ADDR                 ((PAGE_PMUCODEC) + (0x27A))
#define    HI6555C_SMT_HSL_MIN_GAIN_BIT_START  (0)
#define    HI6555C_SMT_HSL_MIN_GAIN_BIT_END    (0)
#define    HI6555C_SMT_HSL_GAIN_BIT_START      (1)
#define    HI6555C_SMT_HSL_GAIN_BIT_END        (4)
#define    HI6555C_SMT_HSL_MUTE_BIT_START      (5)
#define    HI6555C_SMT_HSL_MUTE_BIT_END        (5)
#define    HI6555C_SMT_HS_LIT_LP_L_BIT_START   (6)
#define    HI6555C_SMT_HS_LIT_LP_L_BIT_END     (6)


#define HI6555C_SMT_CODEC_ANA_RW18_ADDR                 ((PAGE_PMUCODEC) + (0x27B))
#define    HI6555C_SMT_HSR_MIN_GAIN_BIT_START  (0)
#define    HI6555C_SMT_HSR_MIN_GAIN_BIT_END    (0)
#define    HI6555C_SMT_HSR_GAIN_BIT_START      (1)
#define    HI6555C_SMT_HSR_GAIN_BIT_END        (4)
#define    HI6555C_SMT_HSR_MUTE_BIT_START      (5)
#define    HI6555C_SMT_HSR_MUTE_BIT_END        (5)
#define    HI6555C_SMT_HS_LIT_LP_R_BIT_START   (6)
#define    HI6555C_SMT_HS_LIT_LP_R_BIT_END     (6)


#define HI6555C_SMT_CODEC_ANA_RW19_ADDR                 ((PAGE_PMUCODEC) + (0x27C))
#define    HI6555C_SMT_EAR_CM_CTRL_BIT_START  (0)
#define    HI6555C_SMT_EAR_CM_CTRL_BIT_END    (0)
#define    HI6555C_SMT_EAR_GAIN_BIT_START     (1)
#define    HI6555C_SMT_EAR_GAIN_BIT_END       (4)
#define    HI6555C_SMT_EAR_MUTE_BIT_START     (5)
#define    HI6555C_SMT_EAR_MUTE_BIT_END       (5)


#define HI6555C_SMT_CODEC_ANA_RW20_ADDR                 ((PAGE_PMUCODEC) + (0x27D))
#define    HI6555C_SMT_POP_RAMP_CT_2_0_BIT_START  (0)
#define    HI6555C_SMT_POP_RAMP_CT_2_0_BIT_END    (2)
#define    HI6555C_SMT_POP_RAMP_CT_3_BIT_START    (3)
#define    HI6555C_SMT_POP_RAMP_CT_3_BIT_END      (3)
#define    HI6555C_SMT_POP_RAMP_CT_4_BIT_START    (4)
#define    HI6555C_SMT_POP_RAMP_CT_4_BIT_END      (4)
#define    HI6555C_SMT_CLK_DL_BIT_START           (5)
#define    HI6555C_SMT_CLK_DL_BIT_END             (7)


#define HI6555C_SMT_CODEC_ANA_RW21_ADDR                 ((PAGE_PMUCODEC) + (0x27E))
#define    HI6555C_SMT_RST_N_R_BIT_START   (0)
#define    HI6555C_SMT_RST_N_R_BIT_END     (0)
#define    HI6555C_SMT_RST_N_L_BIT_START   (1)
#define    HI6555C_SMT_RST_N_L_BIT_END     (1)
#define    HI6555C_SMT_POP_DIS_BIT_START   (2)
#define    HI6555C_SMT_POP_DIS_BIT_END     (2)
#define    HI6555C_SMT_CLK_SEL_BIT_START   (3)
#define    HI6555C_SMT_CLK_SEL_BIT_END     (3)
#define    HI6555C_SMT_PDD_EN_BIT_START    (4)
#define    HI6555C_SMT_PDD_EN_BIT_END      (4)
#define    HI6555C_SMT_POP_NEW_BYPASS_BIT_START    (5)
#define    HI6555C_SMT_POP_NEW_BYPASS_BIT_END      (5)


#define HI6555C_SMT_CODEC_ANA_RW22_ADDR                 ((PAGE_PMUCODEC) + (0x27F))
#define    HI6555C_SMT_MICB1_ADJ_BIT_START   (0)
#define    HI6555C_SMT_MICB1_ADJ_BIT_END     (2)
#define    HI6555C_SMT_HSMICB_ADJ_BIT_START  (3)
#define    HI6555C_SMT_HSMICB_ADJ_BIT_END    (5)


#define HI6555C_SMT_CODEC_ANA_RW23_ADDR                 ((PAGE_PMUCODEC) + (0x280))
#define    HI6555C_SMT_MBHD_ECO_EN_BIT_START   (0)
#define    HI6555C_SMT_MBHD_ECO_EN_BIT_END     (0)
#define    HI6555C_SMT_MICB1_DSCHG_BIT_START   (1)
#define    HI6555C_SMT_MICB1_DSCHG_BIT_END     (1)
#define    HI6555C_SMT_HSMICB_DSCHG_BIT_START  (2)
#define    HI6555C_SMT_HSMICB_DSCHG_BIT_END    (2)
#define    HI6555C_SMT_HSD_CTRL_0_BIT_START    (3)
#define    HI6555C_SMT_HSD_CTRL_0_BIT_END      (3)
#define    HI6555C_SMT_HSD_CTRL_1_BIT_START    (4)
#define    HI6555C_SMT_HSD_CTRL_1_BIT_END      (4)
#define    HI6555C_SMT_HSD_CTRL_2_BIT_START    (5)
#define    HI6555C_SMT_HSD_CTRL_2_BIT_END      (5)


#define HI6555C_SMT_CODEC_ANA_RW24_ADDR                 ((PAGE_PMUCODEC) + (0x281))
#define    HI6555C_SMT_MBHD_VREF_CTRL_1_0_BIT_START  (0)
#define    HI6555C_SMT_MBHD_VREF_CTRL_1_0_BIT_END    (1)
#define    HI6555C_SMT_MBHD_VREF_CTRL_3_2_BIT_START  (2)
#define    HI6555C_SMT_MBHD_VREF_CTRL_3_2_BIT_END    (3)
#define    HI6555C_SMT_MBHD_VREF_CTRL_6_4_BIT_START  (4)
#define    HI6555C_SMT_MBHD_VREF_CTRL_6_4_BIT_END    (6)
#define    HI6555C_SMT_MBHD_VREF_PD_BIT_START        (7)
#define    HI6555C_SMT_MBHD_VREF_PD_BIT_END          (7)


#define HI6555C_SMT_CODEC_ANA_RW25_ADDR                 ((PAGE_PMUCODEC) + (0x282))
#define    HI6555C_SMT_CP_DET_SEL_BIT_START     (0)
#define    HI6555C_SMT_CP_DET_SEL_BIT_END       (1)
#define    HI6555C_SMT_CP_DET_CLK_PD_BIT_START  (2)
#define    HI6555C_SMT_CP_DET_CLK_PD_BIT_END    (2)
#define    HI6555C_SMT_CP_CLK_PD_BIT_START      (3)
#define    HI6555C_SMT_CP_CLK_PD_BIT_END        (3)
#define    HI6555C_SMT_CP_SEL_BIT_START         (4)
#define    HI6555C_SMT_CP_SEL_BIT_END           (6)
#define    HI6555C_SMT_HS_SYS_CLK_PD_BIT_START  (7)
#define    HI6555C_SMT_HS_SYS_CLK_PD_BIT_END    (7)


#define HI6555C_SMT_CODEC_ANA_RW26_ADDR                 ((PAGE_PMUCODEC) + (0x283))
#define    HI6555C_SMT_DAC_CHOP_CLK_SEL_BIT_START    (0)
#define    HI6555C_SMT_DAC_CHOP_CLK_SEL_BIT_END      (1)
#define    HI6555C_SMT_ADC_CHOP_CLK_SEL_BIT_START    (2)
#define    HI6555C_SMT_ADC_CHOP_CLK_SEL_BIT_END      (3)
#define    HI6555C_SMT_DAC_CLK_SYS_EDGE_0_BIT_START  (4)
#define    HI6555C_SMT_DAC_CLK_SYS_EDGE_0_BIT_END    (4)
#define    HI6555C_SMT_DAC_CLK_SYS_EDGE_1_BIT_START  (5)
#define    HI6555C_SMT_DAC_CLK_SYS_EDGE_1_BIT_END    (5)
#define    HI6555C_SMT_ADC_CLK_SYS_EDGE_0_BIT_START  (6)
#define    HI6555C_SMT_ADC_CLK_SYS_EDGE_0_BIT_END    (6)
#define    HI6555C_SMT_ADC_CLK_SYS_EDGE_1_BIT_START  (7)
#define    HI6555C_SMT_ADC_CLK_SYS_EDGE_1_BIT_END    (7)


#define HI6555C_SMT_CODEC_ANA_RW27_ADDR                 ((PAGE_PMUCODEC) + (0x284))
#define    HI6555C_SMT_CTCM_CHOP_BPS_BIT_START     (0)
#define    HI6555C_SMT_CTCM_CHOP_BPS_BIT_END       (0)
#define    HI6555C_SMT_MICPGA_CHOP_BPS_BIT_START   (1)
#define    HI6555C_SMT_MICPGA_CHOP_BPS_BIT_END     (1)
#define    HI6555C_SMT_LINEIN_CHOP_BPS_BIT_START   (2)
#define    HI6555C_SMT_LINEIN_CHOP_BPS_BIT_END     (2)
#define    HI6555C_SMT_ADC_SDM_CHOP_BPS_BIT_START  (3)
#define    HI6555C_SMT_ADC_SDM_CHOP_BPS_BIT_END    (3)
#define    HI6555C_SMT_RX_CHOP_BPS_BIT_START       (4)
#define    HI6555C_SMT_RX_CHOP_BPS_BIT_END         (4)


#define HI6555C_SMT_CODEC_ANA_RW28_ADDR                 ((PAGE_PMUCODEC) + (0x285))
#define    HI6555C_SMT_HS_CHOP_BPS_BIT_START       (0)
#define    HI6555C_SMT_HS_CHOP_BPS_BIT_END         (0)
#define    HI6555C_SMT_EAR_CLD_CHOP_BPS_BIT_START  (1)
#define    HI6555C_SMT_EAR_CLD_CHOP_BPS_BIT_END    (1)
#define    HI6555C_SMT_DAC_CHOP_BPS_BIT_START      (2)
#define    HI6555C_SMT_DAC_CHOP_BPS_BIT_END        (2)
#define    HI6555C_SMT_TX_CHOP_BPS_BIT_START       (3)
#define    HI6555C_SMT_TX_CHOP_BPS_BIT_END         (3)


#define HI6555C_SMT_CODEC_ANA_RW29_ADDR                 ((PAGE_PMUCODEC) + (0x286))
#define    HI6555C_SMT_IB05_MIXER_HP_BIT_START  (0)
#define    HI6555C_SMT_IB05_MIXER_HP_BIT_END    (2)
#define    HI6555C_SMT_IB05_HP_BIT_START        (3)
#define    HI6555C_SMT_IB05_HP_BIT_END          (5)


#define HI6555C_SMT_CODEC_ANA_RW30_ADDR                 ((PAGE_PMUCODEC) + (0x287))
#define    HI6555C_SMT_IB05_ADC_OPA1_BIT_START  (0)
#define    HI6555C_SMT_IB05_ADC_OPA1_BIT_END    (2)
#define    HI6555C_SMT_IB05_DAC_BIT_START       (3)
#define    HI6555C_SMT_IB05_DAC_BIT_END         (5)


#define HI6555C_SMT_CODEC_ANA_RW31_ADDR                 ((PAGE_PMUCODEC) + (0x288))
#define    HI6555C_SMT_IB05_ADC_COMP_BIT_START  (0)
#define    HI6555C_SMT_IB05_ADC_COMP_BIT_END    (2)
#define    HI6555C_SMT_IB05_ADC_OPA2_BIT_START  (3)
#define    HI6555C_SMT_IB05_ADC_OPA2_BIT_END    (5)


#define HI6555C_SMT_CODEC_ANA_RW32_ADDR                 ((PAGE_PMUCODEC) + (0x289))
#define    HI6555C_SMT_IB05_MICBIAS_BIT_START     (0)
#define    HI6555C_SMT_IB05_MICBIAS_BIT_END       (2)
#define    HI6555C_SMT_IB05_ADC_LINEIN_BIT_START  (3)
#define    HI6555C_SMT_IB05_ADC_LINEIN_BIT_END    (5)


#define HI6555C_SMT_CODEC_ANA_RW33_ADDR                 ((PAGE_PMUCODEC) + (0x28A))
#define    HI6555C_SMT_IB05_AUXMIC_BIT_START  (0)
#define    HI6555C_SMT_IB05_AUXMIC_BIT_END    (2)
#define    HI6555C_SMT_IB05_REV_BIT_START     (3)
#define    HI6555C_SMT_IB05_REV_BIT_END       (5)


#define HI6555C_SMT_CODEC_ANA_RW34_ADDR                 ((PAGE_PMUCODEC) + (0x28B))
#define    HI6555C_SMT_IB05_MIXER_EAR_BIT_START  (0)
#define    HI6555C_SMT_IB05_MIXER_EAR_BIT_END    (2)
#define    HI6555C_SMT_IB05_MAINMIC_BIT_START    (3)
#define    HI6555C_SMT_IB05_MAINMIC_BIT_END      (5)


#define HI6555C_SMT_CODEC_ANA_RW35_ADDR                 ((PAGE_PMUCODEC) + (0x28C))
#define    HI6555C_SMT_CODEC_BIAS_ADJ_BIT_START  (0)
#define    HI6555C_SMT_CODEC_BIAS_ADJ_BIT_END    (0)
#define    HI6555C_SMT_IB05_EAR_BIT_START        (1)
#define    HI6555C_SMT_IB05_EAR_BIT_END          (3)


#define HI6555C_SMT_CODEC_ANA_RW36_ADDR                 ((PAGE_PMUCODEC) + (0x28D))
#define    HI6555C_SMT_ANALOG_LOOP_BIT_START  (0)
#define    HI6555C_SMT_ANALOG_LOOP_BIT_END    (0)

#define HI6555C_SMT_CODEC_ANA_RW37_ADDR                 ((PAGE_PMUCODEC) + (0x28E))
#define    HI6555C_SMT_CP_DET_PU_BIT_START   (0)
#define    HI6555C_SMT_CP_DET_PU_BIT_END     (0)
#define    HI6555C_SMT_CP_PU_BIT_START       (1)
#define    HI6555C_SMT_CP_PU_BIT_END         (1)
#define    HI6555C_SMT_HP_BIAS_PU_BIT_START  (2)
#define    HI6555C_SMT_HP_BIAS_PU_BIT_END    (2)


#define HI6555C_SMT_CODEC_ANA_RW38_ADDR                 ((PAGE_PMUCODEC) + (0x28F))
#define    HI6555C_SMT_DACR_PU_BIT_START   (0)
#define    HI6555C_SMT_DACR_PU_BIT_END     (0)
#define    HI6555C_SMT_DACL_PU_BIT_START   (1)
#define    HI6555C_SMT_DACL_PU_BIT_END     (1)


#define HI6555C_SMT_CODEC_ANA_RW39_ADDR                 ((PAGE_PMUCODEC) + (0x290))
#define    HI6555C_SMT_EAR_PU_BIT_START         (0)
#define    HI6555C_SMT_EAR_PU_BIT_END           (0)
#define    HI6555C_SMT_MIXOUT_EAR_PU_BIT_START  (1)
#define    HI6555C_SMT_MIXOUT_EAR_PU_BIT_END    (1)
#define    HI6555C_SMT_EAR_VREF_EN_BIT_START  (2)
#define    HI6555C_SMT_EAR_VREF_EN_END    (2)


#define HI6555C_SMT_CODEC_ANA_RW40_ADDR                 ((PAGE_PMUCODEC) + (0x291))
#define    HI6555C_SMT_CODEC_ANA_REG40_BIT_START  (0)
#define    HI6555C_SMT_CODEC_ANA_REG40_BIT_END    (7)


#define HI6555C_SMT_CODEC_ANA_RO01_ADDR                 ((PAGE_PMUCODEC) + (0x292))
#define    HI6555C_SMT_CODEC_ANA_RO01_BIT_START  (0)
#define    HI6555C_SMT_CODEC_ANA_RO01_BIT_END    (7)


#define HI6555C_SMT_CODEC_ANA_RO02_ADDR                 ((PAGE_PMUCODEC) + (0x293))
#define    HI6555C_SMT_CODEC_ANA_RO02_BIT_START  (0)
#define    HI6555C_SMT_CODEC_ANA_RO02_BIT_END    (7)


#define HI6555C_SMT_CODEC_ANA_RW41_ADDR                 ((PAGE_PMUCODEC) + (0x294))


#define HI6555C_SMT_CODEC_ANA_RW42_ADDR                 ((PAGE_PMUCODEC) + (0x295))


#define HI6555C_PMU_CODEC_CLASSD_CTRL0_ADDR             ((PAGE_PMUCTRL) + (0x13B))
#define    HI6555C_PMU_CODEC_EN_CLASSD_INT_BIT  (0)
#define    HI6555C_PMU_CODEC_CLASSD_MUTE_BIT        (1)
#define    HI6555C_PMU_CODEC_CLASSD_MUTE_SEL_BIT    (2)
#define    HI6555C_PMU_CODEC_CLASSD_DRV_EN_BIT  (3)
#define    HI6555C_PMU_CODEC_CLASSD_I_OCP_BIT_START (4)
#define    HI6555C_PMU_CODEC_CLASSD_I_OCP_BIT_END   (5)
#define    HI6555C_PMU_CODEC_CLASSD_GAIN_BIT_START  (6)
#define    HI6555C_PMU_CODEC_CLASSD_GAIN_BIT_END    (7)


#define SOC_SMART_CLASSD_CTRL0_ADDR(base)             ((base) + (0x13B))
#define SOC_SMART_CLASSD_CTRL1_ADDR(base)             ((base) + (0x13C))
#define SOC_SMART_CLASSD_CTRL2_ADDR(base)             ((base) + (0x13D))

/* CRGPERIPH */
#define HI6555C_PSCTRL_RSTDIS2_ADDR    ((PAGE_PERICRG) + SOC_CRGPERIPH_PEREN3_ADDR(0))
#define HI6555C_RSTDIS2_ABB_BIT_START  (SOC_CRGPERIPH_PEREN3_sc_abb_pll_audio_en_START)


#define SOC_SMART_PMU_SOFT_RST_ADDR(base)             ((base) + (0x24E))
#define SOC_SMART_PMU_SOFT_RST_soft_rst_n_START  (0)
#define SOC_SMART_PMU_SOFT_RST_soft_rst_n_END    (7)


/* ASP CFG REG: Codec Dis-Reset and CLK EN*/
#define ASP_CFG_SOFT_RST_REG_OFFSET    (0x4)
#define ASP_CFG_SOFT_RST_REG_CODEC_BIT    (10)
#define ASP_CFG_SOFT_RST_REG_CODEC_APB_BIT    (9)
#define ASP_CODEC_SOFT_RST_VALUE   ((0x1 << ASP_CFG_SOFT_RST_REG_CODEC_BIT) | (0x1 << ASP_CFG_SOFT_RST_REG_CODEC_APB_BIT))

#define ASP_CFG_CLK_EN_REG_OFFSET    (0xC)
#define ASP_CFG_CLK_EN_REG_CODEC_BIT    (13)
#define ASP_CFG_CLK_EN_REG_CODEC_APB_BIT    (12)
#define ASP_CODEC_CLK_EN_VALUE    ((0x1 << ASP_CFG_CLK_EN_REG_CODEC_BIT) | (0x1 << ASP_CFG_CLK_EN_REG_CODEC_APB_BIT))

#define HI6555C_PB_MIN_CHANNELS (2)
#define HI6555C_PB_MAX_CHANNELS (2)
#define HI6555C_CP_MIN_CHANNELS (2)
#define HI6555C_CP_MAX_CHANNELS (2)
#define HI6555C_FORMATS (SNDRV_PCM_FMTBIT_S16_LE | SNDRV_PCM_FMTBIT_S24_LE)
#define HI6555C_RATES (SNDRV_PCM_RATE_8000  | SNDRV_PCM_RATE_16000 |\
		SNDRV_PCM_RATE_48000 | SNDRV_PCM_RATE_96000)

#define HI6555C_HS_INIT_STATUS (0)
#define HI6555C_HS_DETECTING (1<<2)
#define HI6555C_HS_WITH_MIC (1<<0)
#define HI6555C_HS_WITHOUT_MIC (1<<1)

#define IRQ_PLUG_OUT (0x1 << (HI6555C_SMT_ANA_IRQ_MASK_BIT_START + 7))
#define IRQ_PLUG_IN (0x1 << (HI6555C_SMT_ANA_IRQ_MASK_BIT_START + 6))
#define IRQ_ECO_BTN_DOWN (0x1 << (HI6555C_SMT_ANA_IRQ_MASK_BIT_START + 5))
#define IRQ_ECO_BTN_UP (0x1 << (HI6555C_SMT_ANA_IRQ_MASK_BIT_START + 4))
#define IRQ_COMP_L_BTN_DOWN (0x1 << (HI6555C_SMT_ANA_IRQ_MASK_BIT_START + 3))
#define IRQ_COMP_L_BTN_UP (0x1 << (HI6555C_SMT_ANA_IRQ_MASK_BIT_START + 2))
#define IRQ_COMP_H_BTN_DOWN (0x1 << (HI6555C_SMT_ANA_IRQ_MASK_BIT_START + 1))
#define IRQ_COMP_H_BTN_UP (0x1 << (HI6555C_SMT_ANA_IRQ_MASK_BIT_START + 0))

#define IRQ_MSK_COMP_H_BTN (IRQ_COMP_H_BTN_UP | IRQ_COMP_H_BTN_DOWN)
#define IRQ_MSK_BTN_ECO (IRQ_ECO_BTN_UP | IRQ_ECO_BTN_DOWN)
#define IRQ_MSK_BTN_NOR (IRQ_COMP_L_BTN_UP | IRQ_COMP_L_BTN_DOWN | IRQ_MSK_COMP_H_BTN)
#define IRQ_MSK_COMP (IRQ_MSK_BTN_NOR | IRQ_MSK_BTN_ECO)
#define IRQ_MSK_HS_ALL (IRQ_PLUG_OUT | IRQ_PLUG_IN | IRQ_MSK_COMP)

/* 0-earphone not pluged, 1-earphone pluged */
#define IRQ_STAT_PLUG_IN (0x1 << HI6555C_SMT_HS_DET_IRQ_BIT_START)
/* 0-normal btn event    1- no normal btn event */
#define IRQ_STAT_KEY_EVENT (0x1 << HI6555C_SMT_HS_MIC_NOR2_IRQ_BIT_START)
/* 0-eco btn event     1- no eco btn event */
#define IRQ_STAT_ECO_KEY_EVENT (0x1 << HI6555C_SMT_HS_MIC_ECO_IRQ_BIT_START)

#define JACK_RPT_MSK_BTN (SND_JACK_BTN_0 | SND_JACK_BTN_1 | SND_JACK_BTN_2)

/* 6555 codec hkadc channel is 14(0x1110) */
#define HI6555C_HKADC_CHN	14

/* catch size */
#define REG_CACHE_NUM_MAX       1024
#define REG_CACHE_FLAG_WRITE    (0x01 << 16)
#define REG_CACHE_FLAG_READ     (0x02 << 16)
#define REG_CACHE_FLAG_MASK     (0xFF << 16)

#define HI6555C_DBG_SIZE_PAGE         4096
#define HI6555C_DBG_SIZE_WIDGET       8192
#define HI6555C_DBG_SIZE_PATH         16384
/* single line max size is
time,w reg val
8(time) +3 +4(reg) +1 +8(val) +1 = 25
min size is
time,r reg
8(time) +3 +4(reg) +1 = 16
so allocate 6 pages(=24K)
*/
#define HI6555C_DBG_SIZE_CACHE        (24*REG_CACHE_NUM_MAX)

/* HI6555C REGISTER RESOURCE NUM (comply with dts) */
enum hi6555c_reg_resource {
	HI6555C_SOCCODEC = 0,
	HI6555C_PMU,
	HI6555C_PMUHKADC,
	HI6555C_PCTRL,
	HI6555C_ASPCFG,
	HI6555C_AOIOC,
	HI6555C_IOC,
	HI6555C_PERICRG,
	HI6555C_REG_CNT
};

struct hi6555c_reg_page {
	unsigned int page_tag;
	unsigned int page_reg_begin;
	unsigned int page_reg_end;
	const char  *page_name;
};

enum hi6555c_jack_states {
	HI6555C_JACK_BIT_NONE           = 0, /* unpluged */
	HI6555C_JACK_BIT_HEADSET     = 1, /* pluged with mic */
	HI6555C_JACK_BIT_HEADPHONE = 2, /* pluged with 3 pole */
	HI6555C_JACK_BIT_HEADSET_NO_MIC = 3, /* pluged without mic */
	HI6555C_JACK_BIT_PLUGING      = 4, /* pluging, not fully pluged */
	HI6555C_JACK_BIT_INVALID       = 5, /* index */
};

enum headset_voltage {/*mV*/
	HS_3_POLE_MAX_VOLTAGE = 8,
	HS_4_POLE_MIN_VOLTAGE = 1350,
	HS_4_POLE_MAX_VOLTAGE = 2565,
	HS_MAX_VOLTAGE = 2650,
};

enum btn_voltage{/*mV*/
	KEY_UP_MIN_VALUE     = 1350,
	KEY_UP_MAX_VALUE     = 2565,
	KEY_PLAY_MIN_VALUE  = 0,
	KEY_PLAY_MAX_VALUE = 50,
	KEY_BACK_MIN_VALUE  = 500,
	KEY_BACK_MAX_VALUE = 680,
	KEY_FORWARD_MIN_VALUE = 130,
	KEY_FORWARD_MAX_VALUE = 300
};

enum delay_time {
	HS_TIME_PI_DETECT       = 800, /* ms */
	HS_TIME_COMP_IRQ_TRIG   = 30,  /* ms */
	HS_TIME_COMP_IRQ_TRIG_2 = 50, /*ms*/
};

struct hi6555c_jack_data {
	struct snd_soc_jack jack;
	int report;
	struct switch_dev sdev;
	bool is_dev_registered;
};

struct hi6555c_headset_voltage {/*mV*/
	unsigned short hs_3_pole_max_voltage;
	unsigned short hs_4_pole_min_voltage;
	unsigned short hs_4_pole_max_voltage;
};

struct hi6555c_btn_voltage {/*mV*/
	unsigned short key_up_min_value;
	unsigned short key_up_max_value;
	unsigned short key_play_min_value;
	unsigned short key_play_max_value;
	unsigned short key_back_min_value;
	unsigned short key_back_max_value;
	unsigned short key_forward_min_value;
	unsigned short key_forward_max_value;
};

struct tool_priv {
	unsigned int normal_always;
	unsigned int reg;
	unsigned int value;
	int codec_soc_clk_cnt;
	int scharge_boost_cnt;
};

struct hi6555c_debug_rr_cache {
	unsigned int reg;
	unsigned int val;
	unsigned long time;
};

/* codec private data */
struct hi6555c_priv {
	struct snd_soc_codec *codec;
	struct hi6555c_jack_data  hs_jack;
	enum hi6555c_jack_states  hs_status;
	enum hi6555c_jack_states  old_hs_status;
	int pressed_btn_type;
	unsigned short adc_voltage;
	bool have_dapm;
	bool asp_pd;
	int asp_use_count;
	struct wake_lock wake_lock;
	struct clk *codec_clk;
	/* work queue for headset */
	struct workqueue_struct *hs_pi_dwq; /* headset plugin delayed work queue */
	struct delayed_work hs_pi_dw;
	struct workqueue_struct *hs_po_dwq; /* headset plugout delayed work queue */
	struct delayed_work hs_po_dw;
	struct workqueue_struct *hs_comp_l_btn_down_dwq; /* headset button down delayed work queue */
	struct delayed_work hs_comp_l_btn_down_dw;
	struct workqueue_struct *hs_comp_l_btn_up_dwq; /* headset button up delayed work queue */
	struct delayed_work hs_comp_l_btn_up_dw;
	struct workqueue_struct *hs_eco_btn_down_dwq; /* headset eco button down delayed work queue */
	struct delayed_work hs_eco_btn_down_dw;
	struct workqueue_struct *hs_eco_btn_up_dwq; /* headset eco button up delayed work queue */
	struct delayed_work hs_eco_btn_up_dw;
	struct workqueue_struct *hs_comp_h_btn_down_dwq; /* headset button down delayed work queue */
	struct delayed_work hs_comp_h_btn_down_dw;
	struct workqueue_struct *hs_comp_h_btn_up_dwq; /* headset button up delayed work queue */
	struct delayed_work hs_comp_h_btn_up_dw;
	struct workqueue_struct *hs_micbias_hkadc_dwq; /* hs_micbias_hkadc work queue */
	struct delayed_work hs_micbias_hkadc_dw;
	spinlock_t lock;
	struct mutex io_mutex;
	struct mutex ibias_mutex;
	struct mutex hkadc_mutex;
	struct mutex plug_mutex;
	unsigned int ibias_work;
	bool ibias_hkadc;
	struct mutex hs_micbias_mutex;
	unsigned int hs_micbias_work;
	bool hs_micbias_hkadc;
	struct hi6555c_headset_voltage headset_voltage;
	struct hi6555c_btn_voltage btn_voltage;
	/* gpio intr pin */
	int gpio_intr_pin;
	int gpio_irq;
	/* power */

	struct regulator    *asp_cfg_regu;
	struct regulator	*codec_peri;

	struct regulator *regulator_schg_boost3;
	bool use_battery_supply;
	/* clock */
	struct clk *codec_soc;/* periph_clken12_codec_soc */
	struct clk *codec_modem0;/* periph_clken1_digacodec */

	struct tool_priv tool_data;
	struct work_struct tool_work;
	unsigned int v_codec_reg[2]; /* virtual codec register on ddr */
#ifdef ENABLE_CODEC_DEBUG
	struct dentry *df_dir;        /* debugfs dir*/
	unsigned int rr_cache_idx;       /* write/read index to rr_cache[] */
	struct hi6555c_debug_rr_cache rr_cache[REG_CACHE_NUM_MAX];
#endif
};

extern unsigned int codec_reg_read(unsigned int reg);
extern void codec_reg_write(unsigned int reg, unsigned int value);

#endif /* __HI6555C_H__ */
