obj-y += rdr_hisi_audio_adapter.o
obj-y += rdr_hisi_audio_codec.o
obj-y += rdr_hisi_audio_soc.o

EXTRA_CFLAGS += -Idrivers/hisi/hifidsp/
EXTRA_CFLAGS += -Idrivers/hisi/hi6402dsp/
EXTRA_CFLAGS += -Idrivers/hisi/mntn/blackbox/
EXTRA_CFLAGS += -Idrivers/hisi/load_image/
