# MD5: fb398b8ac0b5116398f72b6c27624ca2
set(CFG_PRODUCT_HISILICON_VERSION hi3660) 

set(CFG_PRODUCT_NV_SPLITFILE binfilesplit "0") 

set(CFG_PRODUCT_NV_FILE_MAX_SIZE binfileLimitSize "100") 

set(CFG_PRODUCT_NV_BIN_MODEM_NUNBER bin_modem_number "1") 

set(CFG_PRODUCT_NV_XNV_MODEM_NUNBER xnv_modem_number "1") 

set(CFG_PRODUCT_NV_XNV_SUPPORT_PRODUCT_CAT xnv_support_product_cat "1") 

set(CFG_PRODUCT_NV_XNV_PDT_VERSION K3V6_UDP) 

