# MD5: 4cfd8aa716dacaf05792430e95af15e7
set(CFG_FEATURE_UE_MODE_G FEATURE_ON) 

set(CFG_FEATURE_UE_MODE_W FEATURE_ON) 

set(CFG_FEATURE_LTE FEATURE_ON) 

set(CFG_FEATURE_UE_MODE_TDS FEATURE_ON) 

set(CFG_FEATURE_PC_VOICE FEATURE_OFF) 

set(CFG_FEATURE_GCBS FEATURE_ON) 

set(CFG_FEATURE_WCBS FEATURE_ON) 

set(CFG_FEATURE_ETWS FEATURE_ON) 

set(CFG_FEATURE_AGPS FEATURE_OFF) 

set(CFG_FEATRUE_XML_PARSER FEATURE_ON) 

set(CFG_NAS_FEATURE_SMS_NVIM_SMSEXIST FEATURE_ON) 

set(CFG_NAS_FEATURE_SMS_FLASH_SMSEXIST FEATURE_ON) 

set(CFG_FEATURE_IPV6 FEATURE_ON) 

set(CFG_FEATURE_RMNET_CUSTOM FEATURE_OFF) 

set(CFG_FEATURE_VCOM_EXT FEATURE_ON) 

set(CFG_FEATURE_AT_HSIC FEATURE_OFF) 

set(CFG_FEATURE_AT_HSUART FEATURE_OFF) 

set(CFG_FEATURE_CL_INTERWORK FEATURE_OFF) 

set(CFG_FEATURE_MULTI_MODEM FEATURE_OFF) 

set(CFG_MULTI_MODEM_NUMBER 3) 

set(CFG_FEATURE_ECALL FEATURE_OFF) 

set(CFG_FEATURE_AP FEATURE_OFF) 

set(CFG_FEATURE_E5 FEATURE_OFF) 

set(CFG_FEATURE_POWER_ON_OFF FEATURE_OFF) 

set(CFG_FEATURE_RNIC FEATURE_OFF) 

set(CFG_FEATURE_SECURITY_SHELL          			 FEATURE_ON) 

set(CFG_FEATURE_WIFI FEATURE_OFF) 

set(CFG_FEATURE_HUAWEI_VP FEATURE_ON) 

set(CFG_PS_PTL_VER_PRE_R99 (-2)) 

set(CFG_PS_PTL_VER_R99 (-1)) 

set(CFG_PS_PTL_VER_R3 0) 

set(CFG_PS_PTL_VER_R4 1) 

set(CFG_PS_PTL_VER_R5 2) 

set(CFG_PS_PTL_VER_R6 3) 

set(CFG_PS_PTL_VER_R7 4) 

set(CFG_PS_PTL_VER_R8 5) 

set(CFG_PS_PTL_VER_R9 6) 

set(CFG_PS_UE_REL_VER PS_PTL_VER_R9) 

