# MD5: 75f4b5ce6a54a9c9779db67a36bac247
set(CFG_TENSILICA_BUILDS_HIFI $(ROOT_XTENSA_PATH_W)/XtDevTools/install/builds/RE-2014.5-linux) 

set(CFG_TENSILICA_TOOLS_HIFI $(ROOT_XTENSA_PATH_W)/XtDevTools/install/tools/RE-2014.5-linux) 

set(CFG_FEATURE_HIFI FEATURE_ON) 

set(CFG_FEATURE_HIFI_USE_ICC FEATURE_ON) 

set(CFG_FEATURE_MBB_MODULE_AUDIO FEATURE_OFF) 

set(CFG_FEATURE_VOICE_UP FEATURE_OFF) 

set(CFG_PLATFORM_CHIP_TYPE hi3660) 

