##############################################
#     Make file of OV13850 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/huawei_platform/camera_legacy/hi6220/ov13850_liteon_171/
#EXTRA_CFLAGS += -fno-pic 
ccflags-$(CONFIG_HI6210_CAMERA_OV13850_LITEON_171) += -DOV13850_LIT171_OTP
obj-$(CONFIG_HI6210_CAMERA_OV13850_LITEON_171) += ov13850_liteon_171.o

#################### END #####################
