#
# Generic Hardware Spinlock framework
#

obj-$(CONFIG_HWSPINLOCK)		+= hwspinlock_core.o
obj-$(CONFIG_HWSPINLOCK_OMAP)		+= omap_hwspinlock.o
obj-$(CONFIG_HSEM_U8500)		+= u8500_hsem.o
obj-$(CONFIG_HWSPINLOCK_HISI)		+= hisi_hwspinlock.o
obj-$(CONFIG_HWSPINLOCK_HISI_DEBUG) += hisi_hwspinlock_debugfs.o
