#
# Logger extend configuration
#

obj-$(CONFIG_LOG_SWITCH)	+= log_switch.o
obj-$(CONFIG_LOG_EXCEPTION)	+= log_exception.o
obj-$(CONFIG_LOG_JANK)	        += log_jank.o

obj-$(CONFIG_HUAWEI_GOLDENEYE) += goldeneye/

obj-$(CONFIG_HUAWEI_BOOT_LOG) += boot_log/

obj-$(CONFIG_PROC_LOGUSERTYPE) += log_usertype/
