obj-$(CONFIG_HISI_IOMMU) += hisi_smmu.o hisi_smmu_irq.o
obj-$(CONFIG_HISI_IOMMU_LPAE) += hisi_smmu_lpae.o
obj-$(CONFIG_HISI_IOMMU_TEST) += hisi_smmu_test.o
obj-$(CONFIG_HISI_IOMMU_TEST) += hisi_smmu_unittest.o
