# Pericom Type C Connector

obj-y += hw_typec.o
obj-$(CONFIG_DUAL_ROLE_USB_INTF)	+= class-dual-role.o
obj-$(CONFIG_HUAWEI_TYPEC_PERICOM30216) += pericom30216/
obj-$(CONFIG_HUAWEI_TYPEC_TUSB320) += tusb320/
obj-$(CONFIG_HUAWEI_TYPEC_FUSB301) += fusb301/
obj-$(CONFIG_HUAWEI_TYPEC_PTN5150H) += ptn5150h/
