ccflags-y += -Idrivers/media/huawei/camera/depthisp
ccflags-y += -Idrivers/media/huawei/camera
ccflags-y += -Idrivers/media/huawei/camera/platform
ccflags-y += -Idrivers/media/huawei/camera/pmic

obj-y += ald2.o
obj-y += depthisp.o
