# Makefile for the DSM drivers.
#
# Each configuration option enables a list of files.

obj-$(CONFIG_HUAWEI_DSM)  += dsm_core.o
#obj-$(CONFIG_HUAWEI_DSM)  += dsm_test.o
obj-$(CONFIG_HUAWEI_DSM)  += dsm_earlyboot_client/