##############################################
#     Make file of OV13850 camera sensor
##############################################


EXTRA_CFLAGS += -Idrivers/huawei/camera/ov13850/
#EXTRA_CFLAGS += -fno-pic 
ccflags-$(CONFIG_HI6210_CAMERA_OV13850) += -DOV13850_OTP
obj-$(CONFIG_HI6210_CAMERA_OV13850) += ov13850.o

#################### END #####################
