obj-y += synaptics.o
obj-y += synaptics_fw_update.o
obj-y += synaptics_fw_s3718_update.o
obj-y += synaptics_fw_debug.o
obj-y += synaptics_dsx_test_reporting.o
obj-y += synaptics_debug.o
EXTRA_CFLAGS += -Iarch/arm/mach-hisi
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
