# Makefile for the Huawei selinux dsm drivers.
#
# Each configuration option enables a list of files.

obj-$(CONFIG_HUAWEI_SELINUX_DSM)  += hwselinux_dsm.o

ccflags-y := -Isecurity/selinux -Isecurity/selinux/include
