##############################################
#     Make file of OV13850_ofilm camera sensor
##############################################


EXTRA_CFLAGS += -Idrivers/huawei/camera/ov13850_ofilm/
#EXTRA_CFLAGS += -fno-pic 
ccflags-$(CONFIG_HI6210_CAMERA_OV13850_OFILM) += -DOV13850_OFILM_OTP
obj-$(CONFIG_HI6210_CAMERA_OV13850_OFILM) += ov13850_ofilm.o

#################### END #####################
