/** ****************************************************************************

                    Huawei Technologies Sweden AB (C), 2001-2011

 ********************************************************************************
 * @author    Automatically generated by DAISY
 * @version
 * @date      2014-09-02
 * @file
 * @brief
 * The interface is used to carry voice data from MAC to the decoder.
 * It's interface used between MAC and Voice. Both MAC and Voice have more
 * than one PID, take care.
 * @copyright Huawei Technologies Sweden AB
 *******************************************************************************/
#ifndef CTTF_1X_MAC_VOICE_DECODE_PIF_H
#define CTTF_1X_MAC_VOICE_DECODE_PIF_H

/*******************************************************************************
 1. Other files included
*******************************************************************************/
#include "vos.h"
#include "CodecInterface.h"
#include "cttf_1x_voice_data_public_pif.h"

#ifdef __cplusplus
#if __cplusplus
    extern "C" {
#endif /* __cpluscplus */
#endif /* __cpluscplus */
#pragma pack(4)

/*******************************************************************************
 2. Macro definitions
*******************************************************************************/


/*******************************************************************************
 3. Enumerations declarations
*******************************************************************************/
/** ****************************************************************************
 * Name        : CTTF_1X_MAC_VOICE_DECODE_PIF_MSG_TYPE_ENUM_UINT16
 * Description :
 *******************************************************************************/
enum CTTF_1X_MAC_VOICE_DECODE_PIF_MSG_TYPE_ENUM
{
    ID_CTTF_VOICE_1X_RX_DATA_IND                            = 0x9471, /* _H2ASN_MsgChoice CTTF_VOICE_1X_RX_DATA_IND_STRU*/ /**< @sa CTTF_VOICE_1X_RX_DATA_IND_STRU */
    ID_CTTF_1X_MAC_VOICE_DECODE_PIF_MSG_TYPE_ENUM_BUTT      = 0xFFFF
};
typedef VOS_UINT16 CTTF_1X_MAC_VOICE_DECODE_PIF_MSG_TYPE_ENUM_UINT16;


/*******************************************************************************
 4. Message Header declaration
*******************************************************************************/

/*******************************************************************************
 5. Message declaration
*******************************************************************************/

/*******************************************************************************
 6. STRUCT and UNION declaration
*******************************************************************************/

/*******************************************************************************
 7. OTHER declarations
*******************************************************************************/
/** ****************************************************************************
 * Name        : CTTF_VOICE_1X_RX_DATA_IND_STRU
 * Description : 1x_MAC_Demux uses this signal to deliver received speech data
 * to voice SO. Frame_quality roots from PHY.
 * If @enCodecType is EVRC, it's SO 3 data, and EVRC-B, it's SO 68. Using
 * @enCodecType, Voice can check whether SO are the same in MAC and Voice,
 * now. If not matched, Voice should discard current voice data.
 * @ulSenderPid: It's convenient for MAC that only receiving message from one
 * PID. So @ulSenderPid is always DSP_PID_VOICE in this message.
 * @ulReceiverPid: As requirement from CTTF team, it's MSPS_PID_1X_RMAC in
 * this message.
 * @usOpId: We used it to debug. It's like swift number or running number in
 * bank. The 1st message, it's 0, the next message, it's 1, and so on. In
 * debug tool, like SDT or HiDS, we can know whether there is any message
 * lost, if @usOpId is not consecutive. It's maintained by sender--MAC,
 * receiver--Voice can ignore it in this message.
 *******************************************************************************/
typedef struct
{
    VOS_MSG_HEADER                                                           /* _H2ASN_Skip */
    CTTF_1X_MAC_VOICE_DECODE_PIF_MSG_TYPE_ENUM_UINT16       enMsgId;         /* _H2ASN_Skip */
    VOS_UINT16                                              usOpId;
    VOS_UINT16                                              enFrameQuality;
    CODEC_ENUM_UINT16                                       enCodecType;
    MACITF_VOICE_RATE_TYPE_ENUM_UINT16                      enVoiceDataRate;
    VOS_UINT16                                              ausData[CTTF_1X_MAX_VOICE_DATA_BLOCK_SIZE];
}CTTF_VOICE_1X_RX_DATA_IND_STRU;


/*******************************************************************************
 8. Global  declaration
*******************************************************************************/

/*******************************************************************************
 9. Function declarations
*******************************************************************************/
/** ****************************************************************************
 * Name        : CTTF_1x_MAC_Voice_Decode_PIF_MSG_DATA
 * Description : H2ASN top level message structure definition
 *******************************************************************************/
typedef struct
{
    CTTF_1X_MAC_VOICE_DECODE_PIF_MSG_TYPE_ENUM_UINT16       enMsgId;     /* _H2ASN_MsgChoice_Export CTTF_1X_MAC_VOICE_DECODE_PIF_MSG_TYPE_ENUM_UINT16 */
    VOS_UINT8                                               aucMsgBlock[2];

    /* _H2ASN_MsgChoice_When_Comment CTTF_1X_MAC_VOICE_DECODE_PIF_MSG_TYPE_ENUM_UINT16 */
}CTTF_1x_MAC_Voice_Decode_PIF_MSG_DATA;

/* _H2ASN_Length UINT32*/
/** ****************************************************************************
 * Name        : CTTF_1x_MAC_Voice_Decode_PIF
 * Description : H2ASN top level message structure definition
 *******************************************************************************/
typedef struct
{
    VOS_MSG_HEADER
    CTTF_1x_MAC_Voice_Decode_PIF_MSG_DATA                   stMsgData;
}CTTF_1x_MAC_Voice_Decode_PIF;


#if ((VOS_OS_VER == VOS_WIN32) || (VOS_OS_VER == VOS_NUCLEUS))
#pragma pack()
#else
#pragma pack(0)
#endif

#ifdef __cplusplus
#if __cplusplus
}
#endif /* __cpluscplus */
#endif /* __cpluscplus */

#endif
