/** ****************************************************************************

                    Huawei Technologies Sweden AB (C), 2001-2011

 ********************************************************************************
 * @author    Automatically generated by DAISY
 * @version
 * @date      2014-09-02
 * @file
 * @brief
 * The interface is used to carry voice data from the encoder to MAC. The
 * interface also provides signaling to grant different frame size to the
 * encoder. Signaling of different frame size is used for blank-and-burst and
 * dim-and-burst functionality (i.e. when higher prioritized bits (signaling)
 * should be transmitted while the voice service is active.
 * It's interface about tx voice data between Voice and MAC.
 * @copyright Huawei Technologies Sweden AB
 *******************************************************************************/
#ifndef CTTF_1X_MAC_VOICE_ENCODE_PIF_H
#define CTTF_1X_MAC_VOICE_ENCODE_PIF_H

/*******************************************************************************
 1. Other files included
*******************************************************************************/
#include "vos.h"
#include "cttf_1x_voice_data_public_pif.h"
#include "CodecInterface.h"

#ifdef __cplusplus
#if __cplusplus
    extern "C" {
#endif /* __cpluscplus */
#endif /* __cpluscplus */
#pragma pack(4)

/*******************************************************************************
 2. Macro definitions
*******************************************************************************/


/*******************************************************************************
 3. Enumerations declarations
*******************************************************************************/
/** ****************************************************************************
 * Name        : CTTF_1X_MAC_VOICE_ENCODE_PIF_MSG_TYPE_ENUM_UINT16
 * Description :
 *******************************************************************************/
enum CTTF_1X_MAC_VOICE_ENCODE_PIF_MSG_TYPE_ENUM
{
    ID_VOICE_CTTF_1X_TX_DATA_REQ                            = 0x3071, /* _H2ASN_MsgChoice VOICE_CTTF_1X_TX_DATA_REQ_STRU*/ /**< @sa VOICE_CTTF_1X_TX_DATA_REQ_STRU */
    ID_CTTF_VOICE_1X_TX_RATE_CTRL_IND                       = 0x9470, /* _H2ASN_MsgChoice CTTF_VOICE_1X_TX_RATE_CTRL_IND_STRU*/ /**< @sa CTTF_VOICE_1X_TX_RATE_CTRL_IND_STRU */
    ID_CTTF_1X_MAC_VOICE_ENCODE_PIF_MSG_TYPE_ENUM_BUTT      = 0xFFFF
};
typedef VOS_UINT16 CTTF_1X_MAC_VOICE_ENCODE_PIF_MSG_TYPE_ENUM_UINT16;

/** ****************************************************************************
 * Name        : MACITF_1X_DIM_AND_BURST_ENUM_UINT16
 * Description : To indicate whether it's dim-and-burst or not. If it's
 * Dim-And-Burst, and CodeC produces full-rate data, then CodeC will reduce
 * rate to half rate at most.
 *******************************************************************************/
enum MACITF_1X_DIM_AND_BURST_ENUM
{
    MACITF_1X_DIM_AND_BURST_OFF         = 0x0000,
    MACITF_1X_DIM_AND_BURST_ON          = 0x0001,
    MACITF_1X_DIM_AND_BURST_ENUM_BUTT   = 0x0002
};
typedef VOS_UINT16 MACITF_1X_DIM_AND_BURST_ENUM_UINT16;


/*******************************************************************************
 4. Message Header declaration
*******************************************************************************/

/*******************************************************************************
 5. Message declaration
*******************************************************************************/

/*******************************************************************************
 6. STRUCT and UNION declaration
*******************************************************************************/

/*******************************************************************************
 7. OTHER declarations
*******************************************************************************/
/** ****************************************************************************
 * Name        : CTTF_VOICE_1X_TX_RATE_CTRL_IND_STRU
 * Description : MAC uses this signal to ask voice SO to send speech data. MAC
 * only tell Voice the allowed maximum rate. The actual rate Voice produced is
 * determined by itself. But it can not beyond the @enAllowedMaxRate.
 * @enDimAndBurstFlag indicates whether it's Dim-And-Burst or not.
 * -  If Voice produces full-rate, and @enDimAndBurstFlag is on, then Voice
 *    will reduce rate to half rate at most. It's possible to reduce to lower
 *    rate, e.g. 1/4 rate or 1/8 rate.
 * -  If Voice produced rate is under full-rate, Voice will ignore
 *    @enDimAndBurstFlag.
 * -  If @enDimAndBurstFlag is off, then Voice will not reduce any rate after
 *    Voice has produced rate data.
 * @ulSenderPid: It's convenient for Voice that only receiving message for one
 * PID from MAC. So @ulSenderPid is always MSPS_PID_1X_RMAC in this message.
 * @ulReceiverPid: As requirement from Voice team, it's DSP_PID_VOICE_RT in
 * this message.
 * @usOpId: We used it to debug. It's like swift number or running number in
 * bank. The 1st message, it's 0, the next message, it's 1, and so on. In
 * debug tool, like SDT or HiDS, we can know whether there is any message
 * lost, if usOpId is not consecutive. It's maintained by sender--MAC,
 * receiver--Voice can ignore it in this message.
 *******************************************************************************/
typedef struct
{
    VOS_MSG_HEADER                                                             /* _H2ASN_Skip */
    CTTF_1X_MAC_VOICE_ENCODE_PIF_MSG_TYPE_ENUM_UINT16       enMsgId;           /* _H2ASN_Skip */
    VOS_UINT16                                              usOpId;
    MACITF_VOICE_RATE_TYPE_ENUM_UINT16                      enAllowedMaxRate;
    MACITF_1X_DIM_AND_BURST_ENUM_UINT16                     enDimAndBurstFlag;
}CTTF_VOICE_1X_TX_RATE_CTRL_IND_STRU;

/** ****************************************************************************
 * Name        : VOICE_CTTF_1X_TX_DATA_REQ_STRU
 * Description : Voice SO uses this signal to send its actual speech data to
 * MAC. The @enVoiceDataRate is determined by Voice itself, and it can not
 * beyond the allowed max rate in CTTF_VOICE_1X_TX_RATE_CTRL_IND.
 * If @enCodecType is EVRC, it's SO 3 data, and EVRC-B, it's SO 68. Using
 * @enCodecType, MAC can check whether SO are the same in MAC and Voice, now.
 * If not match, MAC should discard current voice data.
 * @ulSenderPid: It's convenient for Voice that only receiving message for one
 * PID from MAC. So @ulSenderPid is always MSPS_PID_1X_RMAC in this message.
 * @ulReceiverPid: As requirement from Voice team, it's DSP_PID_VOICE in this
 * message.
 * @usOpId: It's used to debug only. It's like swift number or running number
 * in bank. The 1st message, it's 0, the next message, it's 1, and so on. In
 * debug tool, like SDT or HiDS, we can know whether there is any message
 * lost, if usOpId is not consecutive. It's maintained by sender--Voice,
 * receiver--MAC can ignore it in this message.
 *******************************************************************************/
typedef struct
{
    VOS_MSG_HEADER                                                           /* _H2ASN_Skip */
    CTTF_1X_MAC_VOICE_ENCODE_PIF_MSG_TYPE_ENUM_UINT16       enMsgId;         /* _H2ASN_Skip */
    VOS_UINT16                                              usOpId;
    MACITF_VOICE_RATE_TYPE_ENUM_UINT16                      enVoiceDataRate;
    CODEC_ENUM_UINT16                                       enCodecType;
    VOS_UINT16                                              ausReserve[1];
    VOS_UINT16                                              ausData[CTTF_1X_MAX_VOICE_DATA_BLOCK_SIZE];
}VOICE_CTTF_1X_TX_DATA_REQ_STRU;


/*******************************************************************************
 8. Global  declaration
*******************************************************************************/

/*******************************************************************************
 9. Function declarations
*******************************************************************************/
/** ****************************************************************************
 * Name        : CTTF_1x_MAC_Voice_Encode_PIF_MSG_DATA
 * Description : H2ASN top level message structure definition
 *******************************************************************************/
typedef struct
{
    CTTF_1X_MAC_VOICE_ENCODE_PIF_MSG_TYPE_ENUM_UINT16       enMsgId;     /* _H2ASN_MsgChoice_Export CTTF_1X_MAC_VOICE_ENCODE_PIF_MSG_TYPE_ENUM_UINT16 */
    VOS_UINT8                                               aucMsgBlock[2];

    /* _H2ASN_MsgChoice_When_Comment CTTF_1X_MAC_VOICE_ENCODE_PIF_MSG_TYPE_ENUM_UINT16 */
}CTTF_1x_MAC_Voice_Encode_PIF_MSG_DATA;

/* _H2ASN_Length UINT32*/
/** ****************************************************************************
 * Name        : CTTF_1x_MAC_Voice_Encode_PIF
 * Description : H2ASN top level message structure definition
 *******************************************************************************/
typedef struct
{
    VOS_MSG_HEADER
    CTTF_1x_MAC_Voice_Encode_PIF_MSG_DATA                   stMsgData;
}CTTF_1x_MAC_Voice_Encode_PIF;


#if ((VOS_OS_VER == VOS_WIN32) || (VOS_OS_VER == VOS_NUCLEUS))
#pragma pack()
#else
#pragma pack(0)
#endif

#ifdef __cplusplus
#if __cplusplus
}
#endif /* __cpluscplus */
#endif /* __cpluscplus */

#endif
