obj-$(CONFIG_HISI_CHARGER_ARCH)		+= hisi_charger.o hisi_charging_core.o
#obj-$(CONFIG_BQ25892_CHARGER)	+= bq25892/
obj-$(CONFIG_SCHARGER_V200)	    += schargerV200/
obj-$(CONFIG_SCHARGER_V300)	    += schargerV300/

