KBUILD_CPPFLAGS += -Idrivers/hisi/modem/drv/nvim
-include $(srctree)/drivers/hisi/modem/config/product/$(OBB_PRODUCT_NAME)/config/balong_product_config.mk

obj-y			+= sc_balong.o

subdir-ccflags-y := -Werror

