
#ifndef _SHB_DMD_H
#define _SHB_DMD_H

typedef enum
{
  DSM_SHB_ERR_FIRST = 20400,
  DSM_SHB_ERR_IOM7_CFG_DATA = DSM_SHB_ERR_FIRST,
  DSM_SHB_ERR_IOM7_CMD,
  DSM_SHB_ERR_IOM7_DYNLOAD,
  DSM_SHB_ERR_IOM7_I2C_DBG,
  DSM_SHB_ERR_IOM7_IPC_TIMEOUT,
  DSM_SHB_ERR_IOM7_OTHER,
  DSM_SHB_ERR_IOM7_READ,
  DSM_SHB_ERR_IOM7_STEP,
  DSM_SHB_ERR_IOM7_WDG,
  DSM_SHB_ERR_IOM7_WRITE,
  DSM_SHB_ERR_MCU_ACCEL,//20410
  DSM_SHB_ERR_MCU_AIRPRESS,
  DSM_SHB_ERR_MCU_ALS,
  DSM_SHB_ERR_MCU_FUSION,
  DSM_SHB_ERR_MCU_GYRO,
  DSM_SHB_ERR_MCU_I2C_ERR,
  DSM_SHB_ERR_MCU_LABC,
  DSM_SHB_ERR_MCU_LIGHT,
  DSM_SHB_ERR_MCU_MAG,
  DSM_SHB_ERR_MCU_MOTION,
  DSM_SHB_ERR_MCU_OTHER,//20420
  DSM_SHB_ERR_MCU_PDR,
  DSM_SHB_ERR_MCU_PEDOMETER,
  DSM_SHB_ERR_MCU_PS,
  DSM_SHB_ERR_MCU_SYS_MAIN_INIT,
  DSM_SHB_ERR_MCU_SYS_SERVER_INIT,
  DSM_SHB_ERR_MCU_TIMER_TIMEOUT,
  DSM_SHB_ERR_MCU_ACC_PERIOD_ERROR,//20427
  DSM_SHB_ERR_LAST = 20499,
} sensorhub_dmd_type_t;

#endif
