##############################################
#     Make file of SONYIMX328 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/huawei_platform/camera_legacy/hi6220/sonyimx328_171/
#EXTRA_CFLAGS += -fno-pic 
ccflags-$(CONFIG_HI6210_CAMERA_SONYIMX328_171) += -DIMX328_171_OTP
obj-$(CONFIG_HI6210_CAMERA_SONYIMX328_171) += sonyimx328_171.o
#################### END #####################
