##############################################
#     Make file of S5K4E1GA_FOXCONN camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/huawei/camera/s5k4e1ga_foxconn/
#EXTRA_CFLAGS += -fno-pic
obj-$(CONFIG_HI6210_CAMERA_S5K4E1GA_FOXCONN) += s5k4e1ga_foxconn.o

#################### END #####################
