# hifi dsp device driver

EXTRA_CFLAGS += -I../kernel/drivers/hisi/slimbus


obj-$(CONFIG_HIFI_DSP_ONE_TRACK)	+= mlib_ringbuffer.o
obj-$(CONFIG_HIFI_DSP_ONE_TRACK)	+= mlib_static_ringbuffer.o
obj-$(CONFIG_HIFI_DSP_ONE_TRACK)	+= soundtrigger_dma_drv.o
