

obj-$(CONFIG_VIACBP82D_3RD_MODEM) += core.o power.o oem.o via_gpios.o ext_modem.o modem_packet.o modem_channels.o modem_ttys.o via_sdio.o via_spi.o 4wire_wake.o apcp_test.o rnic_txrx.o
obj-$(CONFIG_HISI_BALONG_MODEM) += rnic_adapter.o
