################################################################
## fake camera driver used to debug HAL work flow
################################################################
EXTRA_CFLAGS += -Idrivers/media/video/ovisp22/fake_capture/
hik3_fake_capture-objs := k3_fake_capture.o
obj-$(CONFIG_VIDEO_HIK3_FAKE_CAMERA) += hik3_fake_capture.o
################################################################
