ifneq ($(CONFIG_RPMSG),y)
	obj-y += fake_fw.o
	obj-y += fake_rpmsg_bus.o
	obj-y += test/
endif

#obj-$(CONFIG_HISP_FAKE_FW) += fake_fw.o
#obj-$(CONFIG_HISP_FAKE_FW) += fake_rpmsg_bus.o
#obj-$(CONFIG_HISP_FAKE_FW) += test/
