##############################################
#     Make file of SONYIMX105 camera sensor
##############################################


EXTRA_CFLAGS += -Idrivers/huawei/camera/sonyimx134/
#EXTRA_CFLAGS += -fno-pic 
##ccflags-y += -DIMX134_OTP
obj-$(CONFIG_HI6210_CAMERA_SONYIMX134) += imx134_tune.o
obj-$(CONFIG_HI6210_CAMERA_SONYIMX134) += sonyimx134.o

#################### END #####################
