##############################################
#     Make file of OV8850 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hi6620/capture/ov8850/
EXTRA_CFLAGS += -fno-pic 
obj-$(CONFIG_HI6620_CAMERA_OV8850) += ov8850.o

#################### END #####################
