# MD5: 7809c79485ff0a2fffec79ad65ec53d6
set(CFG_BALONG_OBUILD_VERSION 10) 

set(CFG_PRODUCT_CFG_CHIP_SOLUTION_BALONG YES) 

set(CFG_PRODUCT_CFG_CHIP_SOLUTION_NAME "Balong") 

set(CFG_PRODUCT_NAME							 "hi6210sft") 

set(CFG_BUILD_TYPE RELEASE) 

set(CFG_PRODUCT_VER V700R001C00B155) 

set(CFG_PRODUCT_CFG_VERSION_STR "V800R200C00B590") 

set(CFG_PRODUCT_FULL_VERSION_STR "Balong V800R200C00B590") 

set(CFG_PRODUCT_CFG_FILE_VERSION_STR "2.1.5.5") 

set(CFG_PRODUCT_CFG_NV_VERSION_STR "1.2.1") 

set(CFG_PRODUCT_CFG_BOOTLOADER_VERSION_STR "1.0.0") 

set(CFG_PRODUCT_CFG_VERSION_V 800) 

set(CFG_PRODUCT_CFG_VERSION_R 001) 

set(CFG_PRODUCT_CFG_VERSION_C 51) 

set(CFG_PRODUCT_CFG_VERSION_B 190) 

set(CFG_PRODUCT_CFG_VERSION_RELEASE YES) 

set(CFG_PRODUCT_CFG_ENABLE_SHELL_SYM   			 YES) 

set(CFG_PRODUCT_CONTROL_VERSION "121") 

set(CFG_PRODUCT_HISILICON_VERSION hi6210) 

set(CFG_PRODUCT_NV_SPLITFILE binfilesplit "1") 

set(CFG_PRODUCT_NV_FILE_MAX_SIZE binfileLimitSize "500") 

set(CFG_PRODUCT_NV_BIN_MODEM_NUNBER bin_modem_number "2") 

set(CFG_PRODUCT_NV_XNV_MODEM_NUNBER xnv_modem_number "2") 

set(CFG_PRODUCT_NV_XNV_PDT_VERSION hi6210sft) 

set(CFG_PRODUCT_NV_XNV_SUPPORT_PRODUCT_CAT xnv_support_product_cat "1") 

set(CFG_FEATURE_OBJ_CMP NO) 

set(CFG_FEATURE_OBJ_DUMP NO) 

set(CFG_FIRMWARE_DIR_NAME	    			 IDT) 

set(CFG_PRODUCT_CFG_ISO_NAME "MOBILE_CONNECT") 

set(CFG_PRODUCT_CFG_ISO_VER "UTPS21.005.18.00.03") 

set(CFG_PRODUCT_CFG_DLOAD_ID "H69DUSAVA") 

set(CFG_PRODUCT_CFG_DLOAD_NAME "H69DUSAVA") 

set(CFG_PRODUCT_CFG_DLOAD_TOOL_VER "B311") 

set(CFG_PRODUCT_CFG_DLOAD_SOFTWARE_VER "21.120.00.00.00") 

set(CFG_PRODUCT_CFG_DLOAD_CFG		 "Bin2App.cfg") 

set(CFG_PRODUCT_CFG_DLOAD_CFG_GZ		 "Bin2App.gz.cfg") 

set(CFG_PRODUCT_CFG_DLOAD_PACK_BAT "BalongV8R1_download_images.xml") 

set(CFG_PRODUCT_CFG_HARDWARE_PCB_NAME "03020QXR") 

set(CFG_PRODUCT_CFG_HARDWARE_NAME_PRIVATE "MT1B390A") 

set(CFG_PRODUCT_CFG_HARDWARE_NAME     		 "Hi6210") 

set(CFG_PKG_APP_IMG			 NO) 

set(CFG_APP_IMG_DIR		 "") 

set(CFG_DLOAD_PACK_FILELIST MakeBalongV7R1_LV) 

set(CFG_USE_USBLOADER_MERGE				 YES) 

set(CFG_USBLOADER_MERGE_BIN				 ramInit_256M_CS.bin) 

set(CFG_CHIP_BB_6210CS YES) 

set(CFG_CHIP_BB CHIP_BB_6210CS) 

set(CFG_CHIP_BB_HI6210 YES) 

set(CFG_CHIP_MODEM_ARM_ARCH CORTEX_A7) 

set(CFG_CHIP_PMU_6451ES0 YES) 

set(CFG_CHIP_RFIC_6361V100 YES) 

set(CFG_BOARD_SFT YES) 

set(CFG_BOARD SFT) 

set(CFG_PLATFORM_CHIP_TYPE hi6210) 

set(CFG_PRODUCT_CFG_MULTIMODE_GUL YES) 

set(CFG_CHIPSET_PATH modem/platform/hi6210sft) 

set(CFG_OS_LINUX_PRODUCT_NAME hisi_hi6210sft_defconfig) 

set(CFG_OS_LINUX_PRODUCT_NAME_HI6210OEM hisi_hi6210oem_defconfig) 

set(CFG_PRODUCT_CFG_VXWORKS_PRJ prj_ccore_vxworks_interpeak) 

set(CFG_GU_NV_PATH modem/config/nvim/data/gu/bin_dsda) 

set(CFG_GU_NV_XML_FLAG YES) 

set(CFG_GU_NV_XML_PATH modem/config/nvim/data/gu/hi6210) 

set(CFG_GU_XNV_PATH modem/config/nvim/data/gu/v8r1/sft) 

set(CFG_LNV_PRO_NAME hi6210sft) 

set(CFG_XTENSA_CORE				 Balong_V8R1_BBE16) 

set(CFG_XTENSA_SYSTEM			 $(ROOT_XTENSA_PATH_W)/XtDevTools/install/builds/RD-2012.5-linux/Balong_V8R1_BBE16/config) 

set(CFG_TENSILICA_BUILDS	 $(ROOT_XTENSA_PATH_W)/XtDevTools/install/builds/RD-2012.5-linux) 

set(CFG_TENSILICA_TOOLS	 $(ROOT_XTENSA_PATH_W)/XtDevTools/install/tools/RD-2012.5-linux) 

set(CFG_TENSILICA_BUILDS_HIFI $(ROOT_XTENSA_PATH_W)/XtDevTools/install/builds/RD-2012.5-linux) 

set(CFG_TENSILICA_TOOLS_HIFI $(ROOT_XTENSA_PATH_W)/XtDevTools/install/tools/RD-2012.5-linux	) 

set(LPHY_LD_MAP_UNI_PATH modem/phy/lt/Tensilica_LSP/BBE16_V810_LSP/fulllsp) 

set(LPHY_LD_MAP_PUB_PATH modem/phy/lt/Tensilica_LSP/BBE16_V810_LSP/mainlsp) 

set(LPHY_LD_MAP_LTE_PATH modem/phy/lt/Tensilica_LSP/BBE16_V810_LSP/overlaplsp) 

set(LPHY_LD_MAP_TDS_PATH modem/phy/lt/Tensilica_LSP/BBE16_V810_LSP/overlaplsp) 

set(LPHY_LD_SDR_LIB_FILE BBE16_V8R1_O2) 

set(LPHY_XTENSA_RULES cc_tensilica4.0.5_rules.mk) 

set(CFG_LPHY_UNI_DTCM_BASE	 0xff280000) 

set(CFG_LPHY_UNI_ITCM_BASE	 0xff200000) 

set(CFG_LPHY_PUB_DTCM_BASE		 0xff280000) 

set(CFG_LPHY_PUB_ITCM_BASE		 0xff200000) 

set(CFG_LPHY_PRV_DTCM_BASE		 0xff2c3000) 

set(CFG_LPHY_PRV_ITCM_BASE		 0xff23b800) 

set(CFG_LPHY_UNI_DTCM_SIZE		 0x70000) 

set(CFG_LPHY_UNI_ITCM_SIZE		 0x70000) 

set(CFG_LPHY_PUB_DTCM_SIZE		 0x43000) 

set(CFG_LPHY_PUB_ITCM_SIZE		 0x3b800) 

set(CFG_LPHY_PRV_DTCM_SIZE		 0x2d000) 

set(CFG_LPHY_PRV_ITCM_SIZE		 0x34800) 

set(CFG_LPHY_LTE_DTCM_SIZE		 0x2d000) 

set(CFG_LPHY_LTE_ITCM_SIZE		 0x34800) 

set(CFG_LPHY_TDS_DTCM_SIZE		 0x2d000) 

set(CFG_LPHY_TDS_ITCM_SIZE		 0x34800) 

set(CFG_LPHY_ALL_IMAG_SIZE		 0x1a3000) 

set(CFG_LPHY_TOTAL_IMG_SIZE ((LPHY_PUB_DTCM_SIZE)+(LPHY_PUB_ITCM_SIZE)+(LPHY_LTE_DTCM_SIZE)*2+(LPHY_LTE_ITCM_SIZE)*2+(LPHY_TDS_DTCM_SIZE)+(LPHY_TDS_ITCM_SIZE))) 

set(CFG_TL_PHY_LALG_PATH    	 include/phy) 

set(CFG_TL_PHY_ASIC_V810 YES) 

set(CFG_TL_PHY_6930         	 YES) 

set(CFG_TL_PHY_FEATURE_LTE_LCS NO) 

set(CFG_GU_PRODUCT_VERSION VERSION_V8R1) 

set(PRODUCT_CFG_PRODUCT_VERSION VERSION_V8R1) 

set(CFG_RAT_GU 0) 

set(CFG_RAT_GUL 1) 

set(CFG_VERSION_V9R1 1) 

set(CFG_RAT_MODE RAT_GUL) 

set(CFG_PLATFORM_HISI_BALONG hi6210sft) 

set(CFG_PLATFORM hi6210sft) 

set(CFG_TTF_SKB_EXP NO) 

set(CFG_DX_SEC_IMG YES) 

set(CFG_FEATURE_KERNEL_LINUX_3_10 YES) 

set(CFG_GU_FEATURE_CONFIG_PATH modem/config/product/hi6210sft/include) 

set(CFG_MCU_INCLUDE YES) 

set(CFG_HIPSE_INCLUDE YES) 

set(CFG_HIFI_INCLUDE YES) 

set(CFG_HIFI_LINK_DIR_NAME			 hifi_ld_SFT) 

set(CFG_XTENSA_CORE_HIFI Balong_V8R1_HiFi) 

set(CFG_ZSP_DSP_CHIP_BB_TYPE		 4) 

set(CFG_ZSP_DSP_PRODUCT_FORM		 1) 

set(CFG_FEATURE_BOARD_STUB_BJ_E5776S NO) 

set(CFG_FEATURE_BOARD_STUB_BJ_UDP YES) 

set(CFG_BSP_ASIC_DIR_NAME v7r1) 

set(CFG_PRODUCT_CFG_ENABLE_BUILD_VARS YES) 

set(CFG_PRODUCT_CFG_PRODUCT_TYPE_HI6920CS_UDP YES) 

set(CFG_FEATURE_WIFI_ON NO) 

set(CFG_FEATURE_NCM_ON YES) 

set(CFG_FEATURE_ECM_OFF YES) 

set(CFG_FEATURE_BSP_SOFTTIMER			 YES) 

set(CFG_FEATURE_BSP_I2C					 YES) 

set(CFG_FEATURE_BSP_EFUSE				 YES) 

set(CFG_FEATURE_BSP_PWRCTRL				 YES) 

set(CFG_FEATURE_BSP_HKADC				 YES) 

set(CFG_FEATURE_BSP_SSDMA				 NO) 

set(CFG_FEATURE_BSP_POWER_DRX			 NO) 

set(CFG_FEATURE_BSP_LCD					 YES) 

set(CFG_FEATURE_BSP_CHG					 YES) 

set(CFG_FEATURE_BSP_SHELL				 YES) 

set(CFG_FEATURE_BSP_LANSWITCH			 YES) 

set(CFG_FEATURE_BSP_WM8990				 YES) 

set(CFG_FEATURE_BSP_HIFI				 YES) 

set(CFG_CONFIG_HI3650_TLBBP_DS YES) 

set(CFG_FEATURE_BSP_TDS YES) 

set(CFG_TDS_PHY_COMPONENTS tds_dsp_ddr_data.bin tds_tensilica_app.bin) 

set(CFG_ENABLE_SHELL_SYM				 YES) 

set(CFG_RTOSCK_CCORE_LINK_LD_SCRIPT	 ld_rtosck_link.ld) 

set(CFG_BOOTROM_INCLUDE NO) 

set(CFG_ACORE_CHECK_LIBS		 boot.img system.img vmlinux kernel isp.bin  nvme.img ptable.img ramdisk.img ramdisk-recovery.img recovery.img userdata.img cache.img dump.img fastboot1.img fastboot2.img mnvm1.img mnvm2.img  modemlog.img dt.img) 

set(CFG_CCORE_CHECK_LIBS		 balong_mcore.elf balong_mcore.bin  guhifi_mcore.bin  dsp.img) 

set(CFG_CCORE_CHECK_SEPRARTE_LIBS balong_mcore.elf guhifi_mcore.bin) 

set(CFG_CCORE_CHECK_MCU_LIBS mcuimage.bin) 

set(ENV_PRODUCT_CFG_CORE_TYPE_MODEM YES; NO; YES; NO) 

set(ENV_PRODUCT_CFG_OS_TYPE_LINUX NO; YES; NO; NO) 

set(ENV_PRODUCT_CFG_OS_TYPE_VXWORKS YES; NO; YES; NO) 

set(ENV_PRODUCT_CFG_IMAGE_TYPE_VXWORKS YES; NO; NO; NO) 

set(ENV_PRODUCT_CFG_IMAGE_TYPE_linux NO; YES; NO; NO) 

set(ENV_PRODUCT_CFG_IMAGE_NAME "VXWORKS"; "linux"; "BOOTROM"; "BOOTLOADER") 

set(ENV_PRODUCT_CFG_BUILD_SEPARATE NO;  NO;  NO;  NO) 

set(CFG_PRODUCT_CFG_BUILD_SEPARATE					 NO) 

set(ENV_PRODUCT_CFG_ETH_PHY_GMII YES; NO;  NO;  NO) 

set(ENV_PRODUCT_CFG_DEV_USE_GMAC YES; NO;  NO;  NO) 

set(ENV_PRODUCT_CFG_DEV_USE_LANSWITCH YES; NO;  NO;  NO) 

set(ENV_PRODUCT_CFG_DEV_USE_SDIO NO;  YES; NO;  NO) 

set(ENV_PRODUCT_CFG_DEV_USE_JUSB NO;  YES; YES; NO) 

set(ENV_PRODUCT_CFG_DEV_USE_ACM NO;  YES; YES; NO) 

set(ENV_PRODUCT_CFG_DEV_USE_NCM NO;  YES;  NO; NO) 

set(ENV_PRODUCT_CFG_DEV_USE_MASS NO;  YES;  NO; NO) 

set(ENV_PRODUCT_CFG_DEV_USE_DRX YES; NO;  NO;  NO) 

set(ENV_PRODUCT_CFG_ENABLE_TEST_CODE NO;  NO;  NO;  NO) 

set(CFG_PRODUCT_CFG_ENABLE_TEST_CODE				 NO) 

set(CFG_PTABLE_TRANSITION	 NO) 

set(ENV_PRODUCT_CFG_PTABLE_TRANSITION NO;  NO;  NO;  NO) 

set(CFG_PRODUCT_CFG_PTABLE_STUB_DLOAD_ID "H69DUSAVA") 

set(CFG_PRODUCT_CFG_PTABLE_STUB_DLOAD_NAME "H69DUSAVA") 

set(CFG_PRODUCT_CFG_PTABLE_STUB_DLOAD_VER "71.080.10.00.00") 

set(CFG_PRODUCT_CFG_MCORE_RAM_LOW_ADDR 0x00004000) 

set(CFG_PRODUCT_CFG_MCORE_RAM_HIGH_ADDR 	 0x04FFA000) 

set(ENV_PRODUCT_CFG_DEV_USE_DDR1 NO ;  NO ;  NO ;  YES) 

set(ENV_PRODUCT_CFG_DEV_USE_ABBIN YES;  NO ;  NO ;  NO) 

set(ENV_VERSION_E5_HW_TEST NO;  NO;  NO;  NO) 

set(CFG_FEATURE_ON 1) 

set(CFG_FEATURE_OFF 0) 

set(CFG_MEMORY_SIZE_32M 1) 

set(CFG_MEMORY_SIZE_64M 2) 

set(CFG_MEMORY_SIZE_128M 3) 

set(CFG_MEMORY_SIZE_256M 4) 

set(CFG_MEMORY_SIZE_512M 5) 

set(CFG_PS_PTL_VER_DANAMIC 20) 

set(CFG_PS_PTL_VER_PRE_R99 (-2)) 

set(CFG_PS_PTL_VER_R99 (-1)) 

set(CFG_PS_PTL_VER_R3 0) 

set(CFG_PS_PTL_VER_R4 1) 

set(CFG_PS_PTL_VER_R5 2) 

set(CFG_PS_PTL_VER_R6 3) 

set(CFG_PS_PTL_VER_R7 4) 

set(CFG_PS_PTL_VER_R8 5) 

set(CFG_PS_PTL_VER_R9 6) 

set(CFG_PS_UE_REL_VER PS_PTL_VER_R9) 

set(CFG_FEATURE_UE_MODE_G FEATURE_ON) 

set(CFG_FEATURE_UE_MODE_W FEATURE_ON) 

set(CFG_FEATURE_GCBS FEATURE_ON) 

set(CFG_FEATURE_WCBS FEATURE_ON) 

set(CFG_FEATURE_AP FEATURE_OFF) 

set(CFG_FEATURE_PTABLE_UDP FEATURE_ON) 

set(CFG_FEATURE_STICK FEATURE_OFF) 

set(CFG_FEATURE_E5 FEATURE_OFF) 

set(CFG_FEATURE_E5_UDP FEATURE_OFF) 

set(CFG_FEATURE_HILINK FEATURE_OFF) 

set(CFG_FEATURE_SEC_BOOT FEATURE_OFF) 

set(CFG_FEATURE_LTE FEATURE_ON) 

set(CFG_FEATURE_CSD FEATURE_OFF) 

set(CFG_FEATURE_IPV6 FEATURE_ON) 

set(CFG_FEATURE_PPP FEATURE_ON) 

set(CFG_FEATURE_HARDWARE_HDLC_FUNC FEATURE_OFF) 

set(CFG_FEATURE_HARDWARE_HDLC_ON_CCPU FEATURE_OFF) 

set(CFG_FEATURE_UPDATEONLINE FEATURE_OFF) 

set(CFG_FEATURE_WIFI FEATURE_OFF) 

set(CFG_FEATURE_HIFI FEATURE_OFF) 

set(CFG_FEATURE_HIFI_USE_ICC FEATURE_OFF) 

set(CFG_FEATURE_MBB_MODULE_AUDIO FEATURE_OFF) 

set(CFG_FEATURE_SDIO FEATURE_OFF) 

set(CFG_FEATURE_KEYBOARD FEATURE_OFF) 

set(CFG_FEATURE_CHARGE FEATURE_OFF) 

set(CFG_FEATURE_ICC_DEBUG FEATURE_ON) 

set(CFG_FEATURE_POWER_ON_OFF FEATURE_OFF) 

set(CFG_FEATURE_OLED FEATURE_OFF) 

set(CFG_FEATURE_TFT FEATURE_OFF) 

set(CFG_FEATURE_MMI_TEST FEATURE_OFF) 

set(CFG_FEATURE_DL_E_CELL_FACH FEATURE_ON) 

set(CFG_FEATURE_DC_MIMO FEATURE_OFF) 

set(CFG_IPWEBS_FEATURE_E5 FEATURE_OFF) 

set(CFG_IPWEBS_FEATURE_WIRELESS_DONGLE FEATURE_OFF) 

set(CFG_IPWEBS_FEATURE_LIGHTNING_CARD FEATURE_OFF) 

set(CFG_FEATURE_WEBNAS FEATURE_OFF) 

set(CFG_FEATURE_WIRELESS_DONGLE FEATURE_OFF) 

set(CFG_FEATURE_PMU_PROTECT FEATURE_OFF) 

set(CFG_FEATURE_MEMORY_SIZE MEMORY_SIZE_64M) 

set(CFG_FEATURE_ECM_RNDIS FEATURE_OFF) 

set(CFG_FEATURE_RNIC FEATURE_OFF) 

set(CFG_FEATURE_NFEXT FEATURE_ON) 

set(CFG_FEATURE_UL_E_CELL_FACH FEATURE_OFF) 

set(CFG_FEATURE_DC_UPA FEATURE_OFF) 

set(CFG_FEATURE_BREATH_LIGHT FEATURE_OFF) 

set(CFG_FEATURE_LEDSTATUS FEATURE_OFF) 

set(CFG_FEATURE_E5_LED FEATURE_OFF) 

set(CFG_FEATURE_RTC FEATURE_OFF) 

set(CFG_FEATURE_SMALL_MAILBOX FEATURE_OFF) 

set(CFG_FEATURE_TEMP_DSP_CORE_POWER_DOWN FEATURE_OFF) 

set(CFG_FEATURE_RECONFIG FEATURE_ON) 

set(CFG_FEATURE_HWENCRY_REWORK FEATURE_OFF) 

set(CFG_FEATURE_MMU_BIG FEATURE_OFF) 

set(CFG_FEATURE_MMU_MEDIUM FEATURE_ON) 

set(CFG_FEATURE_MMU_SMALL FEATURE_OFF) 

set(CFG_FEATURE_TTFMEM_CACHE FEATURE_OFF) 

set(CFG_FEATURE_SDUPDATE FEATURE_OFF) 

set(CFG_FEATURE_SECURITY_SHELL FEATURE_ON) 

set(CFG_FEATURE_EPAD FEATURE_OFF) 

set(CFG_FEATURE_HSIC_SLAVE FEATURE_OFF) 

set(CFG_FEATURE_MANUFACTURE_LOG FEATURE_OFF) 

set(CFG_FEATURE_MEM_MONITOR FEATURE_ON) 

set(CFG_FEATURE_DRV_REPLAY_DUMP FEATURE_OFF) 

set(CFG_FEATURE_POWER_DRV FEATURE_OFF) 

set(CFG_FEATURE_SIM_NOTIFY FEATURE_OFF) 

set(CFG_FEATURE_HW_CODEC FEATURE_OFF) 

set(CFG_FEATURE_SKB_EXP FEATURE_OFF) 

set(CFG_FEATURE_MULTI_FS_PARTITION FEATURE_ON) 

set(CFG_FEATURE_MULTI_MODEM FEATURE_ON) 

set(CFG_MULTI_MODEM_NUMBER 2) 

set(CFG_FEATURE_VCOM_EXT FEATURE_ON) 

set(CFG_FEATURE_MERGE_OM_CHAN						 FEATURE_ON) 

set(CFG_FEATURE_SOCP_CHANNEL_REDUCE FEATURE_OFF) 

set(CFG_FEATURE_S_SKU_M_OPERATORS FEATURE_OFF) 

set(CFG_FEATURE_BROWSER_NV_FILE_IMEI_PROTECT FEATURE_OFF) 

set(CFG_FEATURE_COMPRESS_WRITE_LOG_FILE FEATURE_OFF) 

set(CFG_FEATURE_POWER_TIMER FEATURE_ON) 

set(CFG_FEATURE_UE_MODE_TDS FEATURE_ON) 

set(CFG_FEATURE_ETWS FEATURE_ON) 

set(CFG_FEATURE_AGPS FEATURE_ON) 

set(CFG_FEATRUE_XML_PARSER FEATURE_ON) 

set(CFG_FEATURE_RNDIS				 FEATURE_OFF) 

set(CFG_FEATURE_PTM FEATURE_ON) 

set(CFG_FEATURE_UE_UICC_MULTI_APP_SUPPORT FEATURE_ON) 

set(CFG_FEATURE_VSIM FEATURE_OFF) 

set(CFG_FEATURE_VOS_REDUCE_MEM_CFG FEATURE_OFF) 

set(CFG_FEATURE_DELAY_MODEM_INIT FEATURE_ON) 

set(CFG_FEATURE_GUBBP_HANDSHAKE FEATURE_ON) 

set(CFG_FEATURE_SOCP_SYNC_ENABLE FEATURE_ON) 

set(CFG_FEATURE_BBP_MASTER FEATURE_ON) 

set(CFG_BBP_MASTER_INT_MODE		 		 FEATURE_OFF) 

set(CFG_FEATURE_BBP_MASTER_CHAN_EXTEND		 FEATURE_OFF) 

set(CFG_FEATURE_BBP_MASTER_CHAN_U2              	 FEATURE_OFF) 

set(CFG_FEATURE_LPHY_RFIC_HI6362 FEATURE_OFF) 

set(CFG_FEATURE_LTE_4RX FEATURE_OFF) 

set(CFG_FEATURE_GUDRX_NEWVERSION FEATURE_OFF) 

set(CFG_FEATURE_OM_BBPLOG FEATURE_OFF) 

set(CFG_FEATURE_RTC_TIMER_DBG FEATURE_ON) 

set(CFG_NAS_FEATURE_SMS_NVIM_SMSEXIST FEATURE_ON) 

set(CFG_NAS_FEATURE_SMS_FLASH_SMSEXIST FEATURE_ON) 

set(CFG_FEATURE_IMS FEATURE_OFF) 

set(CFG_FEATURE_ECALL FEATURE_OFF) 

set(CFG_FEATURE_VISP_VPP FEATURE_ON) 

set(CFG_FEATURE_AT_HSIC FEATURE_OFF) 

set(CFG_FEATURE_AT_HSUART FEATURE_OFF) 

set(CFG_FEATURE_HUAWEI_VP FEATURE_ON) 

set(CFG_FEATURE_BASTET FEATURE_OFF) 

set(CFG_FEATURE_RMNET_CUSTOM FEATURE_OFF) 

set(CFG_GAS_PTL_VER_PRE_R99 (PS_PTL_VER_PRE_R99)) 

set(CFG_GAS_PTL_VER_R99 (PS_PTL_VER_R99)) 

set(CFG_GAS_PTL_VER_R3 (PS_PTL_VER_R3)) 

set(CFG_GAS_PTL_VER_R4 (PS_PTL_VER_R4)) 

set(CFG_GAS_PTL_VER_R5 (PS_PTL_VER_R5)) 

set(CFG_GAS_PTL_VER_R6 (PS_PTL_VER_R6)) 

set(CFG_GAS_PTL_VER_R7 (PS_PTL_VER_R7)) 

set(CFG_GAS_PTL_VER_R8 (PS_PTL_VER_R8)) 

set(CFG_GAS_PTL_VER_R9 (PS_PTL_VER_R9)) 

set(CFG_GAS_UE_REL_VER (GAS_PTL_VER_R9)) 

set(CFG_FEATURE_BBPMST_FREQUENCY_REDUCE FEATURE_OFF) 

set(CFG_TTF_CF_FEATURE FEATURE_OFF) 

set(CFG_FEATURE_TTF_MEM_DEBUG FEATURE_ON) 

set(CFG_FEATURE_TCP_ACK_IN_FRONT FEATURE_ON) 

set(CFG_FEATURE_CST_ASYN_OR_NOT_TRANS FEATURE_OFF) 

set(CFG_FEATURE_EDMAC FEATURE_OFF) 

set(CFG_FEATURE_ACPU_STAT FEATURE_OFF) 

set(CFG_FEATURE_ACPU_FC_POINT_REG FEATURE_ON) 

set(CFG_FEATURE_XNV_SUPPORT_PRODUCT_CAT FEATURE_ON) 

set(CFG_SC_CTRL_MOD_6620_FPGA 1) 

set(CFG_SC_CTRL_MOD_6620_SFT 2) 

set(CFG_SC_CTRL_MOD_6758_FPGA 3) 

set(CFG_SC_CTRL_MOD_6758_SFT 4) 

set(CFG_SC_CTRL_MOD_6930_FPGA 5) 

set(CFG_SC_CTRL_MOD_6930_SFT 6) 

set(CFG_SC_CTRL_MOD_3630_UDP 7) 

set(CFG_SC_CTRL_MOD_6210_FPGA 8) 

set(CFG_SC_CTRL_MOD_6210_SFT 9) 

set(CFG_SC_CTRL_MOD_P532 10) 

set(CFG_SC_CTRL_MOD_6950_SFT 11) 

set(CFG_SC_CTRL_MOD_3650_SFT 12) 

set(CFG_SC_CTRL_MOD_6250_SFT 13) 

set(CFG_SC_CTRL_MOD_6932_SFT 14) 

set(CFG_SC_CTRL_MOD (SC_CTRL_MOD_6210_SFT)) 

set(CFG_FEATURE_TLPHY_SINGLE_XO								 YES) 

set(CFG_FEATURE_TEMP_MULTI_MODE_LP                	 FEATURE_ON) 

set(CFG_FEATURE_HARQ_OUT                          	 FEATURE_ON) 

set(CFG_FEATURE_MULTI_RFIC_MEAS			 FEATURE_ON) 

set(CFG_FEATURE_DC_DPA				 FEATURE_ON) 

set(CFG_FEATURE_EXTERNAL_32K_CLK			 FEATURE_OFF) 

set(CFG_FEATURE_RFIC_RESET_GPIO_ON			 FEATURE_OFF) 

set(CFG_FEATURE_ANT_SHARE				 FEATURE_ON) 

set(CFG_FEATURE_TUNER				 FEATURE_OFF) 

set(CFG_FEATURE_UPHY_SIO_WPLL_ELUSION_ON		 FEATURE_OFF) 

set(CFG_FEATURE_SOCP_ON_DEMAND			 FEATURE_OFF) 

set(CFG_FEATURE_VIRTUAL_BAND			 FEATURE_ON) 

set(CFG_FEATURE_MODE_FEM_CHAN_EXT FEATURE_ON) 

set(CFG_CONFIG_IPF_ADQ_LEN 							 2) 

set(CFG_IPF_V200 1) 

set(CFG_IPF_V300 2) 

set(CFG_FEATURE_IPF_VERSION IPF_V200) 

set(CFG_FEATURE_HANDSET_SECURITY_BOOT	 FEATURE_OFF) 

set(CFG_FEATURE_PHONE     			 FEATURE_OFF) 

set(CFG_FEATURE_PHOTOFRAME			 FEATURE_OFF) 

set(CFG_FEATURE_DSP_LOAD			 FEATURE_ON) 

set(CFG_FEATURE_VOICE_UP FEATURE_OFF) 

set(CFG_FEATURE_PMU_SMARTSTAR FEATURE_ON) 

set(CFG_FEATURE_SRAM_400K FEATURE_OFF) 

set(CFG_FEATURE_DSDS FEATURE_ON) 

set(CFG_FEATURE_TAS FEATURE_OFF) 

set(CFG_FEATURE_SOCP_ON_DEMAND			 FEATURE_OFF) 

set(CFG_FEATURE_SAMPLE_LTE_CHAN			 FEATURE_ON) 

set(CFG_FEATURE_BSP_LCH_OM FEATURE_OFF) 

set(CFG_FEATURE_CL_INTERWORK FEATURE_OFF) 

set(CFG_FEATURE_HISOCKET FEATURE_OFF) 

set(CFG_FEATURE_CL_INTERWORK FEATURE_ON) 

set(CFG_FEATURE_MULTI_CHANNEL		 FEATURE_ON) 

set(CFG_FEATURE_DFS_SYNC FEATURE_OFF) 

set(CFG_FEATURE_GU_DSP_SPLIT FEATURE_ON) 

set(CFG_FEATURE_MULTI_CHANNEL		 FEATURE_ON) 

set(CFG_FEATURE_CIPHER_OPTIMIZE FEATURE_ON) 

set(CFG_FEATURE_DCX0_TLHPA_WRITE_PHY_NV FEATURE_ON) 

set(CFG_FEATURE_VERSION_V8 FEATURE_ON) 

set(CFG_FEATURE_LTE_R11 FEATURE_OFF) 

set(CFG_FEATURE_LTE_MBMS FEATURE_OFF) 

set(CFG_FEATURE_LTE_NAS_R11 FEATURE_OFF) 

set(CFG_FEATURE_LTE_CDMA_R11 FEATURE_OFF) 

set(CFG_FEATURE_LPP FEATURE_OFF) 

set(CFG_PREFER_MODEM_CONFIG hi6220) 

set(CFG_FEATURE_BALONG_CL FEATURE_OFF) 

set(CFG_FEATURE_UE_MODE_CDMA FEATURE_ON) 

set(CFG_FEATURE_CHINA_TELECOM_VOICE_ENCRYPT FEATURE_ON) 

set(CFG_FEATURE_CHINA_TELECOM_VOICE_ENCRYPT_TEST_MODE FEATURE_ON) 

set(CFG_MCORE_CDMA_COMPONENTS cphy_ccore.o  cttf_ccore.o cas_ccore.o cpscomm_ccore.o cencodix_ccore.o cnas_ccore.o csdr_mbx_ccore.o) 

set(CFG_FEATURE_TDS_WCDMA_DYNAMIC_LOAD FEATURE_OFF) 

set(CFG_FEATURE_CSG FEATURE_OFF) 

set(CFG_FEATURE_CSS_CLOUD_MEMORY_IMPROVE FEATURE_OFF) 

