ccflags-y += -Idrivers/media/huawei/camera/extisp
ccflags-y += -Idrivers/media/huawei/camera
ccflags-y += -Idrivers/media/huawei/camera/platform
ccflags-y += -Idrivers/media/huawei/camera/pmic

obj-y += altek6045.o
###obj-y += extisp_node.o
obj-y += extisp.o
