#
# Makefile for the Linux kernel device drivers.
#
# 15 Sep 2000, Christoph Hellwig <hch@infradead.org>
# Rewritten to use lists instead of if-statements.
#

obj-$(CONFIG_MEDIA_VIDEO_MNTN)    += mntn/
obj-$(CONFIG_MEDIA_VIDEO_HARDEN)  += videoharden/
obj-$(CONFIG_MEDIA_VIDEO_CONFIG)  += videoconfig/

