/*************************************************************************/ /*!
@File           /home/jenkins/builds/workspace/PKG_PVRVIDEO_REL_6.1.0/D5500_VXE384/img/vdec/regdefs/pvdec/include/interface/deva_fw_msg.h
@Title          
@Copyright      Copyright (c) Imagination Technologies Ltd. All Rights Reserved
@Description    This file contains the DEVA_FW_MSG_H Definitions.
@License        Strictly Confidential.
*/ /**************************************************************************/

#if !defined (__DEVA_FW_MSG_H__)
#define __DEVA_FW_MSG_H__

#ifdef __cplusplus
extern "C" {
#endif


#define FW_DEVA_GENMSG_SIZE		(8)

// FW_DEVA_GENMSG     MSG_ID
#define FW_DEVA_GENMSG_MSG_ID_START_BIT		16
#define FW_DEVA_GENMSG_MSG_ID_END_BIT		31
#define FW_DEVA_GENMSG_MSG_ID_ALIGNMENT		(2)
#define FW_DEVA_GENMSG_MSG_ID_TYPE		IMG_UINT16
#define FW_DEVA_GENMSG_MSG_ID_MASK		(0xFFFF)
#define FW_DEVA_GENMSG_MSG_ID_LSBMASK		(0xFFFF)
#define FW_DEVA_GENMSG_MSG_ID_OFFSET		(0x0002)
#define FW_DEVA_GENMSG_MSG_ID_SHIFT		(0)
#define FW_DEVA_GENMSG_MSG_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_GENMSG_MSG_ID_TRUSTED		(IMG_FALSE)

// FW_DEVA_GENMSG     MSG_TYPE
#define FW_DEVA_GENMSG_MSG_TYPE_START_BIT		8
#define FW_DEVA_GENMSG_MSG_TYPE_END_BIT		15
#define FW_DEVA_GENMSG_MSG_TYPE_ALIGNMENT		(1)
#define FW_DEVA_GENMSG_MSG_TYPE_TYPE		IMG_UINT8
#define FW_DEVA_GENMSG_MSG_TYPE_MASK		(0xFF)
#define FW_DEVA_GENMSG_MSG_TYPE_LSBMASK		(0xFF)
#define FW_DEVA_GENMSG_MSG_TYPE_OFFSET		(0x0001)
#define FW_DEVA_GENMSG_MSG_TYPE_SHIFT		(0)
#define FW_DEVA_GENMSG_MSG_TYPE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_GENMSG_MSG_TYPE_TRUSTED		(IMG_FALSE)

// FW_DEVA_GENMSG     BATCH_START
#define FW_DEVA_GENMSG_BATCH_START_START_BIT		7
#define FW_DEVA_GENMSG_BATCH_START_END_BIT		7
#define FW_DEVA_GENMSG_BATCH_START_ALIGNMENT		(1)
#define FW_DEVA_GENMSG_BATCH_START_TYPE		IMG_UINT8
#define FW_DEVA_GENMSG_BATCH_START_MASK		(0x80)
#define FW_DEVA_GENMSG_BATCH_START_LSBMASK		(0x01)
#define FW_DEVA_GENMSG_BATCH_START_OFFSET		(0x0000)
#define FW_DEVA_GENMSG_BATCH_START_SHIFT		(7)
#define FW_DEVA_GENMSG_BATCH_START_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_GENMSG_BATCH_START_TRUSTED		(IMG_FALSE)

// FW_DEVA_GENMSG     MSG_SIZE
#define FW_DEVA_GENMSG_MSG_SIZE_START_BIT		0
#define FW_DEVA_GENMSG_MSG_SIZE_END_BIT		6
#define FW_DEVA_GENMSG_MSG_SIZE_ALIGNMENT		(1)
#define FW_DEVA_GENMSG_MSG_SIZE_TYPE		IMG_UINT8
#define FW_DEVA_GENMSG_MSG_SIZE_MASK		(0x7F)
#define FW_DEVA_GENMSG_MSG_SIZE_LSBMASK		(0x7F)
#define FW_DEVA_GENMSG_MSG_SIZE_OFFSET		(0x0000)
#define FW_DEVA_GENMSG_MSG_SIZE_SHIFT		(0)
#define FW_DEVA_GENMSG_MSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_GENMSG_MSG_SIZE_TRUSTED		(IMG_FALSE)

// FW_DEVA_GENMSG     TRANS_ID
#define FW_DEVA_GENMSG_TRANS_ID_START_BIT		0
#define FW_DEVA_GENMSG_TRANS_ID_END_BIT		31
#define FW_DEVA_GENMSG_TRANS_ID_ALIGNMENT		(4)
#define FW_DEVA_GENMSG_TRANS_ID_TYPE		IMG_UINT32
#define FW_DEVA_GENMSG_TRANS_ID_MASK		(0xFFFFFFFF)
#define FW_DEVA_GENMSG_TRANS_ID_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_GENMSG_TRANS_ID_OFFSET		(0x0004)
#define FW_DEVA_GENMSG_TRANS_ID_SHIFT		(0)
#define FW_DEVA_GENMSG_TRANS_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_GENMSG_TRANS_ID_TRUSTED		(IMG_FALSE)

#define FW_DEVA_DECODE_SIZE		(32)

// FW_DEVA_DECODE     MSG_ID
#define FW_DEVA_DECODE_MSG_ID_START_BIT		16
#define FW_DEVA_DECODE_MSG_ID_END_BIT		31
#define FW_DEVA_DECODE_MSG_ID_ALIGNMENT		(2)
#define FW_DEVA_DECODE_MSG_ID_TYPE		IMG_UINT16
#define FW_DEVA_DECODE_MSG_ID_MASK		(0xFFFF)
#define FW_DEVA_DECODE_MSG_ID_LSBMASK		(0xFFFF)
#define FW_DEVA_DECODE_MSG_ID_OFFSET		(0x0002)
#define FW_DEVA_DECODE_MSG_ID_SHIFT		(0)
#define FW_DEVA_DECODE_MSG_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DECODE_MSG_ID_TRUSTED		(IMG_FALSE)

// FW_DEVA_DECODE     MSG_TYPE
#define FW_DEVA_DECODE_MSG_TYPE_START_BIT		8
#define FW_DEVA_DECODE_MSG_TYPE_END_BIT		15
#define FW_DEVA_DECODE_MSG_TYPE_ALIGNMENT		(1)
#define FW_DEVA_DECODE_MSG_TYPE_TYPE		IMG_UINT8
#define FW_DEVA_DECODE_MSG_TYPE_MASK		(0xFF)
#define FW_DEVA_DECODE_MSG_TYPE_LSBMASK		(0xFF)
#define FW_DEVA_DECODE_MSG_TYPE_OFFSET		(0x0001)
#define FW_DEVA_DECODE_MSG_TYPE_SHIFT		(0)
#define FW_DEVA_DECODE_MSG_TYPE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DECODE_MSG_TYPE_TRUSTED		(IMG_FALSE)

// FW_DEVA_DECODE     BATCH_START
#define FW_DEVA_DECODE_BATCH_START_START_BIT		7
#define FW_DEVA_DECODE_BATCH_START_END_BIT		7
#define FW_DEVA_DECODE_BATCH_START_ALIGNMENT		(1)
#define FW_DEVA_DECODE_BATCH_START_TYPE		IMG_UINT8
#define FW_DEVA_DECODE_BATCH_START_MASK		(0x80)
#define FW_DEVA_DECODE_BATCH_START_LSBMASK		(0x01)
#define FW_DEVA_DECODE_BATCH_START_OFFSET		(0x0000)
#define FW_DEVA_DECODE_BATCH_START_SHIFT		(7)
#define FW_DEVA_DECODE_BATCH_START_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DECODE_BATCH_START_TRUSTED		(IMG_FALSE)

// FW_DEVA_DECODE     MSG_SIZE
#define FW_DEVA_DECODE_MSG_SIZE_START_BIT		0
#define FW_DEVA_DECODE_MSG_SIZE_END_BIT		6
#define FW_DEVA_DECODE_MSG_SIZE_ALIGNMENT		(1)
#define FW_DEVA_DECODE_MSG_SIZE_TYPE		IMG_UINT8
#define FW_DEVA_DECODE_MSG_SIZE_MASK		(0x7F)
#define FW_DEVA_DECODE_MSG_SIZE_LSBMASK		(0x7F)
#define FW_DEVA_DECODE_MSG_SIZE_OFFSET		(0x0000)
#define FW_DEVA_DECODE_MSG_SIZE_SHIFT		(0)
#define FW_DEVA_DECODE_MSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DECODE_MSG_SIZE_TRUSTED		(IMG_FALSE)

// FW_DEVA_DECODE     TRANS_ID
#define FW_DEVA_DECODE_TRANS_ID_START_BIT		0
#define FW_DEVA_DECODE_TRANS_ID_END_BIT		31
#define FW_DEVA_DECODE_TRANS_ID_ALIGNMENT		(4)
#define FW_DEVA_DECODE_TRANS_ID_TYPE		IMG_UINT32
#define FW_DEVA_DECODE_TRANS_ID_MASK		(0xFFFFFFFF)
#define FW_DEVA_DECODE_TRANS_ID_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_DECODE_TRANS_ID_OFFSET		(0x0004)
#define FW_DEVA_DECODE_TRANS_ID_SHIFT		(0)
#define FW_DEVA_DECODE_TRANS_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DECODE_TRANS_ID_TRUSTED		(IMG_FALSE)

// FW_DEVA_DECODE     FLAGS
#define FW_DEVA_DECODE_FLAGS_START_BIT		0
#define FW_DEVA_DECODE_FLAGS_END_BIT		15
#define FW_DEVA_DECODE_FLAGS_ALIGNMENT		(2)
#define FW_DEVA_DECODE_FLAGS_TYPE		IMG_UINT16
#define FW_DEVA_DECODE_FLAGS_MASK		(0xFFFF)
#define FW_DEVA_DECODE_FLAGS_LSBMASK		(0xFFFF)
#define FW_DEVA_DECODE_FLAGS_OFFSET		(0x0008)
#define FW_DEVA_DECODE_FLAGS_SHIFT		(0)
#define FW_DEVA_DECODE_FLAGS_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DECODE_FLAGS_TRUSTED		(IMG_FALSE)

// FW_DEVA_DECODE     BUFFER_SIZE
#define FW_DEVA_DECODE_BUFFER_SIZE_START_BIT		16
#define FW_DEVA_DECODE_BUFFER_SIZE_END_BIT		31
#define FW_DEVA_DECODE_BUFFER_SIZE_ALIGNMENT		(2)
#define FW_DEVA_DECODE_BUFFER_SIZE_TYPE		IMG_UINT16
#define FW_DEVA_DECODE_BUFFER_SIZE_MASK		(0xFFFF)
#define FW_DEVA_DECODE_BUFFER_SIZE_LSBMASK		(0xFFFF)
#define FW_DEVA_DECODE_BUFFER_SIZE_OFFSET		(0x000A)
#define FW_DEVA_DECODE_BUFFER_SIZE_SHIFT		(0)
#define FW_DEVA_DECODE_BUFFER_SIZE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DECODE_BUFFER_SIZE_TRUSTED		(IMG_FALSE)

// FW_DEVA_DECODE     CTRL_ALLOC_ADDR
#define FW_DEVA_DECODE_CTRL_ALLOC_ADDR_START_BIT		0
#define FW_DEVA_DECODE_CTRL_ALLOC_ADDR_END_BIT		31
#define FW_DEVA_DECODE_CTRL_ALLOC_ADDR_ALIGNMENT		(4)
#define FW_DEVA_DECODE_CTRL_ALLOC_ADDR_TYPE		IMG_UINT32
#define FW_DEVA_DECODE_CTRL_ALLOC_ADDR_MASK		(0xFFFFFFFF)
#define FW_DEVA_DECODE_CTRL_ALLOC_ADDR_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_DECODE_CTRL_ALLOC_ADDR_OFFSET		(0x000C)
#define FW_DEVA_DECODE_CTRL_ALLOC_ADDR_SHIFT		(0)
#define FW_DEVA_DECODE_CTRL_ALLOC_ADDR_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DECODE_CTRL_ALLOC_ADDR_TRUSTED		(IMG_FALSE)

// FW_DEVA_DECODE     MMUPTD
#define FW_DEVA_DECODE_MMUPTD_START_BIT		0
#define FW_DEVA_DECODE_MMUPTD_END_BIT		31
#define FW_DEVA_DECODE_MMUPTD_ALIGNMENT		(4)
#define FW_DEVA_DECODE_MMUPTD_TYPE		IMG_UINT32
#define FW_DEVA_DECODE_MMUPTD_MASK		(0xFFFFFFFF)
#define FW_DEVA_DECODE_MMUPTD_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_DECODE_MMUPTD_OFFSET		(0x0010)
#define FW_DEVA_DECODE_MMUPTD_SHIFT		(0)
#define FW_DEVA_DECODE_MMUPTD_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DECODE_MMUPTD_TRUSTED		(IMG_FALSE)

// FW_DEVA_DECODE     OPERATING_MODE
#define FW_DEVA_DECODE_OPERATING_MODE_START_BIT		0
#define FW_DEVA_DECODE_OPERATING_MODE_END_BIT		31
#define FW_DEVA_DECODE_OPERATING_MODE_ALIGNMENT		(4)
#define FW_DEVA_DECODE_OPERATING_MODE_TYPE		IMG_UINT32
#define FW_DEVA_DECODE_OPERATING_MODE_MASK		(0xFFFFFFFF)
#define FW_DEVA_DECODE_OPERATING_MODE_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_DECODE_OPERATING_MODE_OFFSET		(0x0014)
#define FW_DEVA_DECODE_OPERATING_MODE_SHIFT		(0)
#define FW_DEVA_DECODE_OPERATING_MODE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DECODE_OPERATING_MODE_TRUSTED		(IMG_FALSE)

// FW_DEVA_DECODE     STREAMID
#define FW_DEVA_DECODE_STREAMID_START_BIT		24
#define FW_DEVA_DECODE_STREAMID_END_BIT		31
#define FW_DEVA_DECODE_STREAMID_ALIGNMENT		(1)
#define FW_DEVA_DECODE_STREAMID_TYPE		IMG_UINT8
#define FW_DEVA_DECODE_STREAMID_MASK		(0xFF)
#define FW_DEVA_DECODE_STREAMID_LSBMASK		(0xFF)
#define FW_DEVA_DECODE_STREAMID_OFFSET		(0x001B)
#define FW_DEVA_DECODE_STREAMID_SHIFT		(0)
#define FW_DEVA_DECODE_STREAMID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DECODE_STREAMID_TRUSTED		(IMG_FALSE)

// FW_DEVA_DECODE     VDEC_FLAGS
#define FW_DEVA_DECODE_VDEC_FLAGS_START_BIT		16
#define FW_DEVA_DECODE_VDEC_FLAGS_END_BIT		23
#define FW_DEVA_DECODE_VDEC_FLAGS_ALIGNMENT		(1)
#define FW_DEVA_DECODE_VDEC_FLAGS_TYPE		IMG_UINT8
#define FW_DEVA_DECODE_VDEC_FLAGS_MASK		(0xFF)
#define FW_DEVA_DECODE_VDEC_FLAGS_LSBMASK		(0xFF)
#define FW_DEVA_DECODE_VDEC_FLAGS_OFFSET		(0x001A)
#define FW_DEVA_DECODE_VDEC_FLAGS_SHIFT		(0)
#define FW_DEVA_DECODE_VDEC_FLAGS_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DECODE_VDEC_FLAGS_TRUSTED		(IMG_FALSE)

// FW_DEVA_DECODE     PIPE
#define FW_DEVA_DECODE_PIPE_START_BIT		12
#define FW_DEVA_DECODE_PIPE_END_BIT		15
#define FW_DEVA_DECODE_PIPE_ALIGNMENT		(1)
#define FW_DEVA_DECODE_PIPE_TYPE		IMG_UINT8
#define FW_DEVA_DECODE_PIPE_MASK		(0xF0)
#define FW_DEVA_DECODE_PIPE_LSBMASK		(0x0F)
#define FW_DEVA_DECODE_PIPE_OFFSET		(0x0019)
#define FW_DEVA_DECODE_PIPE_SHIFT		(4)
#define FW_DEVA_DECODE_PIPE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DECODE_PIPE_TRUSTED		(IMG_FALSE)

// FW_DEVA_DECODE     EXT_STATE_BUFFER
#define FW_DEVA_DECODE_EXT_STATE_BUFFER_START_BIT		0
#define FW_DEVA_DECODE_EXT_STATE_BUFFER_END_BIT		31
#define FW_DEVA_DECODE_EXT_STATE_BUFFER_ALIGNMENT		(4)
#define FW_DEVA_DECODE_EXT_STATE_BUFFER_TYPE		IMG_UINT32
#define FW_DEVA_DECODE_EXT_STATE_BUFFER_MASK		(0xFFFFFFFF)
#define FW_DEVA_DECODE_EXT_STATE_BUFFER_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_DECODE_EXT_STATE_BUFFER_OFFSET		(0x001C)
#define FW_DEVA_DECODE_EXT_STATE_BUFFER_SHIFT		(0)
#define FW_DEVA_DECODE_EXT_STATE_BUFFER_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DECODE_EXT_STATE_BUFFER_TRUSTED		(IMG_FALSE)

// FW_DEVA_DECODE     TILE_CFG
#define FW_DEVA_DECODE_TILE_CFG_START_BIT		0
#define FW_DEVA_DECODE_TILE_CFG_END_BIT		31
#define FW_DEVA_DECODE_TILE_CFG_ALIGNMENT		(4)
#define FW_DEVA_DECODE_TILE_CFG_TYPE		IMG_UINT32
#define FW_DEVA_DECODE_TILE_CFG_MASK		(0xFFFFFFFF)
#define FW_DEVA_DECODE_TILE_CFG_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_DECODE_TILE_CFG_OFFSET		(0x0018)
#define FW_DEVA_DECODE_TILE_CFG_SHIFT		(0)
#define FW_DEVA_DECODE_TILE_CFG_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DECODE_TILE_CFG_TRUSTED		(IMG_FALSE)

#define FW_DEVA_ENDFRAME_SIZE		(28)

// FW_DEVA_ENDFRAME     MSG_ID
#define FW_DEVA_ENDFRAME_MSG_ID_START_BIT		16
#define FW_DEVA_ENDFRAME_MSG_ID_END_BIT		31
#define FW_DEVA_ENDFRAME_MSG_ID_ALIGNMENT		(2)
#define FW_DEVA_ENDFRAME_MSG_ID_TYPE		IMG_UINT16
#define FW_DEVA_ENDFRAME_MSG_ID_MASK		(0xFFFF)
#define FW_DEVA_ENDFRAME_MSG_ID_LSBMASK		(0xFFFF)
#define FW_DEVA_ENDFRAME_MSG_ID_OFFSET		(0x0002)
#define FW_DEVA_ENDFRAME_MSG_ID_SHIFT		(0)
#define FW_DEVA_ENDFRAME_MSG_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_ENDFRAME_MSG_ID_TRUSTED		(IMG_FALSE)

// FW_DEVA_ENDFRAME     MSG_TYPE
#define FW_DEVA_ENDFRAME_MSG_TYPE_START_BIT		8
#define FW_DEVA_ENDFRAME_MSG_TYPE_END_BIT		15
#define FW_DEVA_ENDFRAME_MSG_TYPE_ALIGNMENT		(1)
#define FW_DEVA_ENDFRAME_MSG_TYPE_TYPE		IMG_UINT8
#define FW_DEVA_ENDFRAME_MSG_TYPE_MASK		(0xFF)
#define FW_DEVA_ENDFRAME_MSG_TYPE_LSBMASK		(0xFF)
#define FW_DEVA_ENDFRAME_MSG_TYPE_OFFSET		(0x0001)
#define FW_DEVA_ENDFRAME_MSG_TYPE_SHIFT		(0)
#define FW_DEVA_ENDFRAME_MSG_TYPE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_ENDFRAME_MSG_TYPE_TRUSTED		(IMG_FALSE)

// FW_DEVA_ENDFRAME     BATCH_START
#define FW_DEVA_ENDFRAME_BATCH_START_START_BIT		7
#define FW_DEVA_ENDFRAME_BATCH_START_END_BIT		7
#define FW_DEVA_ENDFRAME_BATCH_START_ALIGNMENT		(1)
#define FW_DEVA_ENDFRAME_BATCH_START_TYPE		IMG_UINT8
#define FW_DEVA_ENDFRAME_BATCH_START_MASK		(0x80)
#define FW_DEVA_ENDFRAME_BATCH_START_LSBMASK		(0x01)
#define FW_DEVA_ENDFRAME_BATCH_START_OFFSET		(0x0000)
#define FW_DEVA_ENDFRAME_BATCH_START_SHIFT		(7)
#define FW_DEVA_ENDFRAME_BATCH_START_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_ENDFRAME_BATCH_START_TRUSTED		(IMG_FALSE)

// FW_DEVA_ENDFRAME     MSG_SIZE
#define FW_DEVA_ENDFRAME_MSG_SIZE_START_BIT		0
#define FW_DEVA_ENDFRAME_MSG_SIZE_END_BIT		6
#define FW_DEVA_ENDFRAME_MSG_SIZE_ALIGNMENT		(1)
#define FW_DEVA_ENDFRAME_MSG_SIZE_TYPE		IMG_UINT8
#define FW_DEVA_ENDFRAME_MSG_SIZE_MASK		(0x7F)
#define FW_DEVA_ENDFRAME_MSG_SIZE_LSBMASK		(0x7F)
#define FW_DEVA_ENDFRAME_MSG_SIZE_OFFSET		(0x0000)
#define FW_DEVA_ENDFRAME_MSG_SIZE_SHIFT		(0)
#define FW_DEVA_ENDFRAME_MSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_ENDFRAME_MSG_SIZE_TRUSTED		(IMG_FALSE)

// FW_DEVA_ENDFRAME     TRANS_ID
#define FW_DEVA_ENDFRAME_TRANS_ID_START_BIT		0
#define FW_DEVA_ENDFRAME_TRANS_ID_END_BIT		31
#define FW_DEVA_ENDFRAME_TRANS_ID_ALIGNMENT		(4)
#define FW_DEVA_ENDFRAME_TRANS_ID_TYPE		IMG_UINT32
#define FW_DEVA_ENDFRAME_TRANS_ID_MASK		(0xFFFFFFFF)
#define FW_DEVA_ENDFRAME_TRANS_ID_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_ENDFRAME_TRANS_ID_OFFSET		(0x0004)
#define FW_DEVA_ENDFRAME_TRANS_ID_SHIFT		(0)
#define FW_DEVA_ENDFRAME_TRANS_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_ENDFRAME_TRANS_ID_TRUSTED		(IMG_FALSE)

// FW_DEVA_ENDFRAME     FLAGS
#define FW_DEVA_ENDFRAME_FLAGS_START_BIT		0
#define FW_DEVA_ENDFRAME_FLAGS_END_BIT		15
#define FW_DEVA_ENDFRAME_FLAGS_ALIGNMENT		(2)
#define FW_DEVA_ENDFRAME_FLAGS_TYPE		IMG_UINT16
#define FW_DEVA_ENDFRAME_FLAGS_MASK		(0xFFFF)
#define FW_DEVA_ENDFRAME_FLAGS_LSBMASK		(0xFFFF)
#define FW_DEVA_ENDFRAME_FLAGS_OFFSET		(0x0008)
#define FW_DEVA_ENDFRAME_FLAGS_SHIFT		(0)
#define FW_DEVA_ENDFRAME_FLAGS_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_ENDFRAME_FLAGS_TRUSTED		(IMG_FALSE)

// FW_DEVA_ENDFRAME     BUFFER_SIZE
#define FW_DEVA_ENDFRAME_BUFFER_SIZE_START_BIT		16
#define FW_DEVA_ENDFRAME_BUFFER_SIZE_END_BIT		31
#define FW_DEVA_ENDFRAME_BUFFER_SIZE_ALIGNMENT		(2)
#define FW_DEVA_ENDFRAME_BUFFER_SIZE_TYPE		IMG_UINT16
#define FW_DEVA_ENDFRAME_BUFFER_SIZE_MASK		(0xFFFF)
#define FW_DEVA_ENDFRAME_BUFFER_SIZE_LSBMASK		(0xFFFF)
#define FW_DEVA_ENDFRAME_BUFFER_SIZE_OFFSET		(0x000A)
#define FW_DEVA_ENDFRAME_BUFFER_SIZE_SHIFT		(0)
#define FW_DEVA_ENDFRAME_BUFFER_SIZE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_ENDFRAME_BUFFER_SIZE_TRUSTED		(IMG_FALSE)

// FW_DEVA_ENDFRAME     BUFFER_ADDR
#define FW_DEVA_ENDFRAME_BUFFER_ADDR_START_BIT		0
#define FW_DEVA_ENDFRAME_BUFFER_ADDR_END_BIT		31
#define FW_DEVA_ENDFRAME_BUFFER_ADDR_ALIGNMENT		(4)
#define FW_DEVA_ENDFRAME_BUFFER_ADDR_TYPE		IMG_UINT32
#define FW_DEVA_ENDFRAME_BUFFER_ADDR_MASK		(0xFFFFFFFF)
#define FW_DEVA_ENDFRAME_BUFFER_ADDR_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_ENDFRAME_BUFFER_ADDR_OFFSET		(0x000C)
#define FW_DEVA_ENDFRAME_BUFFER_ADDR_SHIFT		(0)
#define FW_DEVA_ENDFRAME_BUFFER_ADDR_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_ENDFRAME_BUFFER_ADDR_TRUSTED		(IMG_FALSE)

// FW_DEVA_ENDFRAME     MMUPTD
#define FW_DEVA_ENDFRAME_MMUPTD_START_BIT		8
#define FW_DEVA_ENDFRAME_MMUPTD_END_BIT		31
#define FW_DEVA_ENDFRAME_MMUPTD_ALIGNMENT		(4)
#define FW_DEVA_ENDFRAME_MMUPTD_TYPE		IMG_UINT32
#define FW_DEVA_ENDFRAME_MMUPTD_MASK		(0xFFFFFF00)
#define FW_DEVA_ENDFRAME_MMUPTD_LSBMASK		(0x00FFFFFF)
#define FW_DEVA_ENDFRAME_MMUPTD_OFFSET		(0x0010)
#define FW_DEVA_ENDFRAME_MMUPTD_SHIFT		(8)
#define FW_DEVA_ENDFRAME_MMUPTD_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_ENDFRAME_MMUPTD_TRUSTED		(IMG_FALSE)

// FW_DEVA_ENDFRAME     STREAMID
#define FW_DEVA_ENDFRAME_STREAMID_START_BIT		0
#define FW_DEVA_ENDFRAME_STREAMID_END_BIT		7
#define FW_DEVA_ENDFRAME_STREAMID_ALIGNMENT		(1)
#define FW_DEVA_ENDFRAME_STREAMID_TYPE		IMG_UINT8
#define FW_DEVA_ENDFRAME_STREAMID_MASK		(0xFF)
#define FW_DEVA_ENDFRAME_STREAMID_LSBMASK		(0xFF)
#define FW_DEVA_ENDFRAME_STREAMID_OFFSET		(0x0010)
#define FW_DEVA_ENDFRAME_STREAMID_SHIFT		(0)
#define FW_DEVA_ENDFRAME_STREAMID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_ENDFRAME_STREAMID_TRUSTED		(IMG_FALSE)

// FW_DEVA_ENDFRAME     OPERATING_MODE
#define FW_DEVA_ENDFRAME_OPERATING_MODE_START_BIT		0
#define FW_DEVA_ENDFRAME_OPERATING_MODE_END_BIT		31
#define FW_DEVA_ENDFRAME_OPERATING_MODE_ALIGNMENT		(4)
#define FW_DEVA_ENDFRAME_OPERATING_MODE_TYPE		IMG_UINT32
#define FW_DEVA_ENDFRAME_OPERATING_MODE_MASK		(0xFFFFFFFF)
#define FW_DEVA_ENDFRAME_OPERATING_MODE_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_ENDFRAME_OPERATING_MODE_OFFSET		(0x0014)
#define FW_DEVA_ENDFRAME_OPERATING_MODE_SHIFT		(0)
#define FW_DEVA_ENDFRAME_OPERATING_MODE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_ENDFRAME_OPERATING_MODE_TRUSTED		(IMG_FALSE)

// FW_DEVA_ENDFRAME     EXT_STATE_BUFFER
#define FW_DEVA_ENDFRAME_EXT_STATE_BUFFER_START_BIT		0
#define FW_DEVA_ENDFRAME_EXT_STATE_BUFFER_END_BIT		31
#define FW_DEVA_ENDFRAME_EXT_STATE_BUFFER_ALIGNMENT		(4)
#define FW_DEVA_ENDFRAME_EXT_STATE_BUFFER_TYPE		IMG_UINT32
#define FW_DEVA_ENDFRAME_EXT_STATE_BUFFER_MASK		(0xFFFFFFFF)
#define FW_DEVA_ENDFRAME_EXT_STATE_BUFFER_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_ENDFRAME_EXT_STATE_BUFFER_OFFSET		(0x0018)
#define FW_DEVA_ENDFRAME_EXT_STATE_BUFFER_SHIFT		(0)
#define FW_DEVA_ENDFRAME_EXT_STATE_BUFFER_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_ENDFRAME_EXT_STATE_BUFFER_TRUSTED		(IMG_FALSE)

// FW_DEVA_ENDFRAME     TILE_CFG
#define FW_DEVA_ENDFRAME_TILE_CFG_START_BIT		0
#define FW_DEVA_ENDFRAME_TILE_CFG_END_BIT		31
#define FW_DEVA_ENDFRAME_TILE_CFG_ALIGNMENT		(4)
#define FW_DEVA_ENDFRAME_TILE_CFG_TYPE		IMG_UINT32
#define FW_DEVA_ENDFRAME_TILE_CFG_MASK		(0xFFFFFFFF)
#define FW_DEVA_ENDFRAME_TILE_CFG_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_ENDFRAME_TILE_CFG_OFFSET		(0x0018)
#define FW_DEVA_ENDFRAME_TILE_CFG_SHIFT		(0)
#define FW_DEVA_ENDFRAME_TILE_CFG_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_ENDFRAME_TILE_CFG_TRUSTED		(IMG_FALSE)

#define FW_DEVA_INIT_SIZE		(28)

// FW_DEVA_INIT     MSG_ID
#define FW_DEVA_INIT_MSG_ID_START_BIT		16
#define FW_DEVA_INIT_MSG_ID_END_BIT		31
#define FW_DEVA_INIT_MSG_ID_ALIGNMENT		(2)
#define FW_DEVA_INIT_MSG_ID_TYPE		IMG_UINT16
#define FW_DEVA_INIT_MSG_ID_MASK		(0xFFFF)
#define FW_DEVA_INIT_MSG_ID_LSBMASK		(0xFFFF)
#define FW_DEVA_INIT_MSG_ID_OFFSET		(0x0002)
#define FW_DEVA_INIT_MSG_ID_SHIFT		(0)
#define FW_DEVA_INIT_MSG_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_INIT_MSG_ID_TRUSTED		(IMG_FALSE)

// FW_DEVA_INIT     MSG_TYPE
#define FW_DEVA_INIT_MSG_TYPE_START_BIT		8
#define FW_DEVA_INIT_MSG_TYPE_END_BIT		15
#define FW_DEVA_INIT_MSG_TYPE_ALIGNMENT		(1)
#define FW_DEVA_INIT_MSG_TYPE_TYPE		IMG_UINT8
#define FW_DEVA_INIT_MSG_TYPE_MASK		(0xFF)
#define FW_DEVA_INIT_MSG_TYPE_LSBMASK		(0xFF)
#define FW_DEVA_INIT_MSG_TYPE_OFFSET		(0x0001)
#define FW_DEVA_INIT_MSG_TYPE_SHIFT		(0)
#define FW_DEVA_INIT_MSG_TYPE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_INIT_MSG_TYPE_TRUSTED		(IMG_FALSE)

// FW_DEVA_INIT     BATCH_START
#define FW_DEVA_INIT_BATCH_START_START_BIT		7
#define FW_DEVA_INIT_BATCH_START_END_BIT		7
#define FW_DEVA_INIT_BATCH_START_ALIGNMENT		(1)
#define FW_DEVA_INIT_BATCH_START_TYPE		IMG_UINT8
#define FW_DEVA_INIT_BATCH_START_MASK		(0x80)
#define FW_DEVA_INIT_BATCH_START_LSBMASK		(0x01)
#define FW_DEVA_INIT_BATCH_START_OFFSET		(0x0000)
#define FW_DEVA_INIT_BATCH_START_SHIFT		(7)
#define FW_DEVA_INIT_BATCH_START_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_INIT_BATCH_START_TRUSTED		(IMG_FALSE)

// FW_DEVA_INIT     MSG_SIZE
#define FW_DEVA_INIT_MSG_SIZE_START_BIT		0
#define FW_DEVA_INIT_MSG_SIZE_END_BIT		6
#define FW_DEVA_INIT_MSG_SIZE_ALIGNMENT		(1)
#define FW_DEVA_INIT_MSG_SIZE_TYPE		IMG_UINT8
#define FW_DEVA_INIT_MSG_SIZE_MASK		(0x7F)
#define FW_DEVA_INIT_MSG_SIZE_LSBMASK		(0x7F)
#define FW_DEVA_INIT_MSG_SIZE_OFFSET		(0x0000)
#define FW_DEVA_INIT_MSG_SIZE_SHIFT		(0)
#define FW_DEVA_INIT_MSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_INIT_MSG_SIZE_TRUSTED		(IMG_FALSE)

// FW_DEVA_INIT     TRANS_ID
#define FW_DEVA_INIT_TRANS_ID_START_BIT		0
#define FW_DEVA_INIT_TRANS_ID_END_BIT		31
#define FW_DEVA_INIT_TRANS_ID_ALIGNMENT		(4)
#define FW_DEVA_INIT_TRANS_ID_TYPE		IMG_UINT32
#define FW_DEVA_INIT_TRANS_ID_MASK		(0xFFFFFFFF)
#define FW_DEVA_INIT_TRANS_ID_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_INIT_TRANS_ID_OFFSET		(0x0004)
#define FW_DEVA_INIT_TRANS_ID_SHIFT		(0)
#define FW_DEVA_INIT_TRANS_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_INIT_TRANS_ID_TRUSTED		(IMG_FALSE)

// FW_DEVA_INIT     RENDEC_ADDR0
#define FW_DEVA_INIT_RENDEC_ADDR0_START_BIT		0
#define FW_DEVA_INIT_RENDEC_ADDR0_END_BIT		31
#define FW_DEVA_INIT_RENDEC_ADDR0_ALIGNMENT		(4)
#define FW_DEVA_INIT_RENDEC_ADDR0_TYPE		IMG_UINT32
#define FW_DEVA_INIT_RENDEC_ADDR0_MASK		(0xFFFFFFFF)
#define FW_DEVA_INIT_RENDEC_ADDR0_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_INIT_RENDEC_ADDR0_OFFSET		(0x0008)
#define FW_DEVA_INIT_RENDEC_ADDR0_SHIFT		(0)
#define FW_DEVA_INIT_RENDEC_ADDR0_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_INIT_RENDEC_ADDR0_TRUSTED		(IMG_FALSE)

// FW_DEVA_INIT     RESERVED
#define FW_DEVA_INIT_RESERVED_START_BIT		16
#define FW_DEVA_INIT_RESERVED_END_BIT		31
#define FW_DEVA_INIT_RESERVED_ALIGNMENT		(2)
#define FW_DEVA_INIT_RESERVED_TYPE		IMG_UINT16
#define FW_DEVA_INIT_RESERVED_MASK		(0xFFFF)
#define FW_DEVA_INIT_RESERVED_LSBMASK		(0xFFFF)
#define FW_DEVA_INIT_RESERVED_OFFSET		(0x000E)
#define FW_DEVA_INIT_RESERVED_SHIFT		(0)
#define FW_DEVA_INIT_RESERVED_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_INIT_RESERVED_TRUSTED		(IMG_FALSE)

// FW_DEVA_INIT     RENDEC_SIZE0
#define FW_DEVA_INIT_RENDEC_SIZE0_START_BIT		0
#define FW_DEVA_INIT_RENDEC_SIZE0_END_BIT		15
#define FW_DEVA_INIT_RENDEC_SIZE0_ALIGNMENT		(2)
#define FW_DEVA_INIT_RENDEC_SIZE0_TYPE		IMG_UINT16
#define FW_DEVA_INIT_RENDEC_SIZE0_MASK		(0xFFFF)
#define FW_DEVA_INIT_RENDEC_SIZE0_LSBMASK		(0xFFFF)
#define FW_DEVA_INIT_RENDEC_SIZE0_OFFSET		(0x000C)
#define FW_DEVA_INIT_RENDEC_SIZE0_SHIFT		(0)
#define FW_DEVA_INIT_RENDEC_SIZE0_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_INIT_RENDEC_SIZE0_TRUSTED		(IMG_FALSE)

// FW_DEVA_INIT     HEVC_MAX_H_FOR_PIPE_WAIT
#define FW_DEVA_INIT_HEVC_MAX_H_FOR_PIPE_WAIT_START_BIT		16
#define FW_DEVA_INIT_HEVC_MAX_H_FOR_PIPE_WAIT_END_BIT		31
#define FW_DEVA_INIT_HEVC_MAX_H_FOR_PIPE_WAIT_ALIGNMENT		(2)
#define FW_DEVA_INIT_HEVC_MAX_H_FOR_PIPE_WAIT_TYPE		IMG_UINT16
#define FW_DEVA_INIT_HEVC_MAX_H_FOR_PIPE_WAIT_MASK		(0xFFFF)
#define FW_DEVA_INIT_HEVC_MAX_H_FOR_PIPE_WAIT_LSBMASK		(0xFFFF)
#define FW_DEVA_INIT_HEVC_MAX_H_FOR_PIPE_WAIT_OFFSET		(0x0012)
#define FW_DEVA_INIT_HEVC_MAX_H_FOR_PIPE_WAIT_SHIFT		(0)
#define FW_DEVA_INIT_HEVC_MAX_H_FOR_PIPE_WAIT_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_INIT_HEVC_MAX_H_FOR_PIPE_WAIT_TRUSTED		(IMG_FALSE)

// FW_DEVA_INIT     HEVC_MIN_H_FOR_DUAL_PIPE
#define FW_DEVA_INIT_HEVC_MIN_H_FOR_DUAL_PIPE_START_BIT		0
#define FW_DEVA_INIT_HEVC_MIN_H_FOR_DUAL_PIPE_END_BIT		15
#define FW_DEVA_INIT_HEVC_MIN_H_FOR_DUAL_PIPE_ALIGNMENT		(2)
#define FW_DEVA_INIT_HEVC_MIN_H_FOR_DUAL_PIPE_TYPE		IMG_UINT16
#define FW_DEVA_INIT_HEVC_MIN_H_FOR_DUAL_PIPE_MASK		(0xFFFF)
#define FW_DEVA_INIT_HEVC_MIN_H_FOR_DUAL_PIPE_LSBMASK		(0xFFFF)
#define FW_DEVA_INIT_HEVC_MIN_H_FOR_DUAL_PIPE_OFFSET		(0x0010)
#define FW_DEVA_INIT_HEVC_MIN_H_FOR_DUAL_PIPE_SHIFT		(0)
#define FW_DEVA_INIT_HEVC_MIN_H_FOR_DUAL_PIPE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_INIT_HEVC_MIN_H_FOR_DUAL_PIPE_TRUSTED		(IMG_FALSE)

// FW_DEVA_INIT     HW_SIG_SELECT
#define FW_DEVA_INIT_HW_SIG_SELECT_START_BIT		0
#define FW_DEVA_INIT_HW_SIG_SELECT_END_BIT		31
#define FW_DEVA_INIT_HW_SIG_SELECT_ALIGNMENT		(4)
#define FW_DEVA_INIT_HW_SIG_SELECT_TYPE		IMG_UINT32
#define FW_DEVA_INIT_HW_SIG_SELECT_MASK		(0xFFFFFFFF)
#define FW_DEVA_INIT_HW_SIG_SELECT_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_INIT_HW_SIG_SELECT_OFFSET		(0x0014)
#define FW_DEVA_INIT_HW_SIG_SELECT_SHIFT		(0)
#define FW_DEVA_INIT_HW_SIG_SELECT_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_INIT_HW_SIG_SELECT_TRUSTED		(IMG_FALSE)

// FW_DEVA_INIT     SPARE
#define FW_DEVA_INIT_SPARE_START_BIT		16
#define FW_DEVA_INIT_SPARE_END_BIT		31
#define FW_DEVA_INIT_SPARE_ALIGNMENT		(2)
#define FW_DEVA_INIT_SPARE_TYPE		IMG_UINT16
#define FW_DEVA_INIT_SPARE_MASK		(0xFFFF)
#define FW_DEVA_INIT_SPARE_LSBMASK		(0xFFFF)
#define FW_DEVA_INIT_SPARE_OFFSET		(0x001A)
#define FW_DEVA_INIT_SPARE_SHIFT		(0)
#define FW_DEVA_INIT_SPARE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_INIT_SPARE_TRUSTED		(IMG_FALSE)

// FW_DEVA_INIT     DBG_RENDEC_DELAY
#define FW_DEVA_INIT_DBG_RENDEC_DELAY_START_BIT		12
#define FW_DEVA_INIT_DBG_RENDEC_DELAY_END_BIT		15
#define FW_DEVA_INIT_DBG_RENDEC_DELAY_ALIGNMENT		(1)
#define FW_DEVA_INIT_DBG_RENDEC_DELAY_TYPE		IMG_UINT8
#define FW_DEVA_INIT_DBG_RENDEC_DELAY_MASK		(0xF0)
#define FW_DEVA_INIT_DBG_RENDEC_DELAY_LSBMASK		(0x0F)
#define FW_DEVA_INIT_DBG_RENDEC_DELAY_OFFSET		(0x0019)
#define FW_DEVA_INIT_DBG_RENDEC_DELAY_SHIFT		(4)
#define FW_DEVA_INIT_DBG_RENDEC_DELAY_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_INIT_DBG_RENDEC_DELAY_TRUSTED		(IMG_FALSE)

// FW_DEVA_INIT     DBG_BE_DELAY
#define FW_DEVA_INIT_DBG_BE_DELAY_START_BIT		8
#define FW_DEVA_INIT_DBG_BE_DELAY_END_BIT		11
#define FW_DEVA_INIT_DBG_BE_DELAY_ALIGNMENT		(1)
#define FW_DEVA_INIT_DBG_BE_DELAY_TYPE		IMG_UINT8
#define FW_DEVA_INIT_DBG_BE_DELAY_MASK		(0x0F)
#define FW_DEVA_INIT_DBG_BE_DELAY_LSBMASK		(0x0F)
#define FW_DEVA_INIT_DBG_BE_DELAY_OFFSET		(0x0019)
#define FW_DEVA_INIT_DBG_BE_DELAY_SHIFT		(0)
#define FW_DEVA_INIT_DBG_BE_DELAY_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_INIT_DBG_BE_DELAY_TRUSTED		(IMG_FALSE)

// FW_DEVA_INIT     DBG_EP_DELAY
#define FW_DEVA_INIT_DBG_EP_DELAY_START_BIT		4
#define FW_DEVA_INIT_DBG_EP_DELAY_END_BIT		7
#define FW_DEVA_INIT_DBG_EP_DELAY_ALIGNMENT		(1)
#define FW_DEVA_INIT_DBG_EP_DELAY_TYPE		IMG_UINT8
#define FW_DEVA_INIT_DBG_EP_DELAY_MASK		(0xF0)
#define FW_DEVA_INIT_DBG_EP_DELAY_LSBMASK		(0x0F)
#define FW_DEVA_INIT_DBG_EP_DELAY_OFFSET		(0x0018)
#define FW_DEVA_INIT_DBG_EP_DELAY_SHIFT		(4)
#define FW_DEVA_INIT_DBG_EP_DELAY_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_INIT_DBG_EP_DELAY_TRUSTED		(IMG_FALSE)

// FW_DEVA_INIT     DBG_FE_DELAY
#define FW_DEVA_INIT_DBG_FE_DELAY_START_BIT		0
#define FW_DEVA_INIT_DBG_FE_DELAY_END_BIT		3
#define FW_DEVA_INIT_DBG_FE_DELAY_ALIGNMENT		(1)
#define FW_DEVA_INIT_DBG_FE_DELAY_TYPE		IMG_UINT8
#define FW_DEVA_INIT_DBG_FE_DELAY_MASK		(0x0F)
#define FW_DEVA_INIT_DBG_FE_DELAY_LSBMASK		(0x0F)
#define FW_DEVA_INIT_DBG_FE_DELAY_OFFSET		(0x0018)
#define FW_DEVA_INIT_DBG_FE_DELAY_SHIFT		(0)
#define FW_DEVA_INIT_DBG_FE_DELAY_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_INIT_DBG_FE_DELAY_TRUSTED		(IMG_FALSE)

#define FW_DEVA_DEBLOCK_SIZE		(56)

// FW_DEVA_DEBLOCK     MSG_ID
#define FW_DEVA_DEBLOCK_MSG_ID_START_BIT		16
#define FW_DEVA_DEBLOCK_MSG_ID_END_BIT		31
#define FW_DEVA_DEBLOCK_MSG_ID_ALIGNMENT		(2)
#define FW_DEVA_DEBLOCK_MSG_ID_TYPE		IMG_UINT16
#define FW_DEVA_DEBLOCK_MSG_ID_MASK		(0xFFFF)
#define FW_DEVA_DEBLOCK_MSG_ID_LSBMASK		(0xFFFF)
#define FW_DEVA_DEBLOCK_MSG_ID_OFFSET		(0x0002)
#define FW_DEVA_DEBLOCK_MSG_ID_SHIFT		(0)
#define FW_DEVA_DEBLOCK_MSG_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_MSG_ID_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     MSG_TYPE
#define FW_DEVA_DEBLOCK_MSG_TYPE_START_BIT		8
#define FW_DEVA_DEBLOCK_MSG_TYPE_END_BIT		15
#define FW_DEVA_DEBLOCK_MSG_TYPE_ALIGNMENT		(1)
#define FW_DEVA_DEBLOCK_MSG_TYPE_TYPE		IMG_UINT8
#define FW_DEVA_DEBLOCK_MSG_TYPE_MASK		(0xFF)
#define FW_DEVA_DEBLOCK_MSG_TYPE_LSBMASK		(0xFF)
#define FW_DEVA_DEBLOCK_MSG_TYPE_OFFSET		(0x0001)
#define FW_DEVA_DEBLOCK_MSG_TYPE_SHIFT		(0)
#define FW_DEVA_DEBLOCK_MSG_TYPE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_MSG_TYPE_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     BATCH_START
#define FW_DEVA_DEBLOCK_BATCH_START_START_BIT		7
#define FW_DEVA_DEBLOCK_BATCH_START_END_BIT		7
#define FW_DEVA_DEBLOCK_BATCH_START_ALIGNMENT		(1)
#define FW_DEVA_DEBLOCK_BATCH_START_TYPE		IMG_UINT8
#define FW_DEVA_DEBLOCK_BATCH_START_MASK		(0x80)
#define FW_DEVA_DEBLOCK_BATCH_START_LSBMASK		(0x01)
#define FW_DEVA_DEBLOCK_BATCH_START_OFFSET		(0x0000)
#define FW_DEVA_DEBLOCK_BATCH_START_SHIFT		(7)
#define FW_DEVA_DEBLOCK_BATCH_START_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_BATCH_START_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     MSG_SIZE
#define FW_DEVA_DEBLOCK_MSG_SIZE_START_BIT		0
#define FW_DEVA_DEBLOCK_MSG_SIZE_END_BIT		6
#define FW_DEVA_DEBLOCK_MSG_SIZE_ALIGNMENT		(1)
#define FW_DEVA_DEBLOCK_MSG_SIZE_TYPE		IMG_UINT8
#define FW_DEVA_DEBLOCK_MSG_SIZE_MASK		(0x7F)
#define FW_DEVA_DEBLOCK_MSG_SIZE_LSBMASK		(0x7F)
#define FW_DEVA_DEBLOCK_MSG_SIZE_OFFSET		(0x0000)
#define FW_DEVA_DEBLOCK_MSG_SIZE_SHIFT		(0)
#define FW_DEVA_DEBLOCK_MSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_MSG_SIZE_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     TRANS_ID
#define FW_DEVA_DEBLOCK_TRANS_ID_START_BIT		0
#define FW_DEVA_DEBLOCK_TRANS_ID_END_BIT		31
#define FW_DEVA_DEBLOCK_TRANS_ID_ALIGNMENT		(4)
#define FW_DEVA_DEBLOCK_TRANS_ID_TYPE		IMG_UINT32
#define FW_DEVA_DEBLOCK_TRANS_ID_MASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_TRANS_ID_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_TRANS_ID_OFFSET		(0x0004)
#define FW_DEVA_DEBLOCK_TRANS_ID_SHIFT		(0)
#define FW_DEVA_DEBLOCK_TRANS_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_TRANS_ID_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     RESERVED
#define FW_DEVA_DEBLOCK_RESERVED_START_BIT		18
#define FW_DEVA_DEBLOCK_RESERVED_END_BIT		31
#define FW_DEVA_DEBLOCK_RESERVED_ALIGNMENT		(2)
#define FW_DEVA_DEBLOCK_RESERVED_TYPE		IMG_UINT16
#define FW_DEVA_DEBLOCK_RESERVED_MASK		(0xFFFC)
#define FW_DEVA_DEBLOCK_RESERVED_LSBMASK		(0x3FFF)
#define FW_DEVA_DEBLOCK_RESERVED_OFFSET		(0x000A)
#define FW_DEVA_DEBLOCK_RESERVED_SHIFT		(2)
#define FW_DEVA_DEBLOCK_RESERVED_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_RESERVED_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     SLICE_FIELD_TYPE
#define FW_DEVA_DEBLOCK_SLICE_FIELD_TYPE_START_BIT		16
#define FW_DEVA_DEBLOCK_SLICE_FIELD_TYPE_END_BIT		17
#define FW_DEVA_DEBLOCK_SLICE_FIELD_TYPE_ALIGNMENT		(1)
#define FW_DEVA_DEBLOCK_SLICE_FIELD_TYPE_TYPE		IMG_UINT8
#define FW_DEVA_DEBLOCK_SLICE_FIELD_TYPE_MASK		(0x03)
#define FW_DEVA_DEBLOCK_SLICE_FIELD_TYPE_LSBMASK		(0x03)
#define FW_DEVA_DEBLOCK_SLICE_FIELD_TYPE_OFFSET		(0x000A)
#define FW_DEVA_DEBLOCK_SLICE_FIELD_TYPE_SHIFT		(0)
#define FW_DEVA_DEBLOCK_SLICE_FIELD_TYPE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_SLICE_FIELD_TYPE_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     FLAGS
#define FW_DEVA_DEBLOCK_FLAGS_START_BIT		0
#define FW_DEVA_DEBLOCK_FLAGS_END_BIT		15
#define FW_DEVA_DEBLOCK_FLAGS_ALIGNMENT		(2)
#define FW_DEVA_DEBLOCK_FLAGS_TYPE		IMG_UINT16
#define FW_DEVA_DEBLOCK_FLAGS_MASK		(0xFFFF)
#define FW_DEVA_DEBLOCK_FLAGS_LSBMASK		(0xFFFF)
#define FW_DEVA_DEBLOCK_FLAGS_OFFSET		(0x0008)
#define FW_DEVA_DEBLOCK_FLAGS_SHIFT		(0)
#define FW_DEVA_DEBLOCK_FLAGS_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_FLAGS_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     OPERATING_MODE
#define FW_DEVA_DEBLOCK_OPERATING_MODE_START_BIT		0
#define FW_DEVA_DEBLOCK_OPERATING_MODE_END_BIT		31
#define FW_DEVA_DEBLOCK_OPERATING_MODE_ALIGNMENT		(4)
#define FW_DEVA_DEBLOCK_OPERATING_MODE_TYPE		IMG_UINT32
#define FW_DEVA_DEBLOCK_OPERATING_MODE_MASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_OPERATING_MODE_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_OPERATING_MODE_OFFSET		(0x000C)
#define FW_DEVA_DEBLOCK_OPERATING_MODE_SHIFT		(0)
#define FW_DEVA_DEBLOCK_OPERATING_MODE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_OPERATING_MODE_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     MMUPTD
#define FW_DEVA_DEBLOCK_MMUPTD_START_BIT		8
#define FW_DEVA_DEBLOCK_MMUPTD_END_BIT		31
#define FW_DEVA_DEBLOCK_MMUPTD_ALIGNMENT		(4)
#define FW_DEVA_DEBLOCK_MMUPTD_TYPE		IMG_UINT32
#define FW_DEVA_DEBLOCK_MMUPTD_MASK		(0xFFFFFF00)
#define FW_DEVA_DEBLOCK_MMUPTD_LSBMASK		(0x00FFFFFF)
#define FW_DEVA_DEBLOCK_MMUPTD_OFFSET		(0x0010)
#define FW_DEVA_DEBLOCK_MMUPTD_SHIFT		(8)
#define FW_DEVA_DEBLOCK_MMUPTD_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_MMUPTD_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     STREAMID
#define FW_DEVA_DEBLOCK_STREAMID_START_BIT		0
#define FW_DEVA_DEBLOCK_STREAMID_END_BIT		7
#define FW_DEVA_DEBLOCK_STREAMID_ALIGNMENT		(1)
#define FW_DEVA_DEBLOCK_STREAMID_TYPE		IMG_UINT8
#define FW_DEVA_DEBLOCK_STREAMID_MASK		(0xFF)
#define FW_DEVA_DEBLOCK_STREAMID_LSBMASK		(0xFF)
#define FW_DEVA_DEBLOCK_STREAMID_OFFSET		(0x0010)
#define FW_DEVA_DEBLOCK_STREAMID_SHIFT		(0)
#define FW_DEVA_DEBLOCK_STREAMID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_STREAMID_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     RESB
#define FW_DEVA_DEBLOCK_RESB_START_BIT		24
#define FW_DEVA_DEBLOCK_RESB_END_BIT		31
#define FW_DEVA_DEBLOCK_RESB_ALIGNMENT		(1)
#define FW_DEVA_DEBLOCK_RESB_TYPE		IMG_UINT8
#define FW_DEVA_DEBLOCK_RESB_MASK		(0xFF)
#define FW_DEVA_DEBLOCK_RESB_LSBMASK		(0xFF)
#define FW_DEVA_DEBLOCK_RESB_OFFSET		(0x0017)
#define FW_DEVA_DEBLOCK_RESB_SHIFT		(0)
#define FW_DEVA_DEBLOCK_RESB_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_RESB_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     PIC_WIDTH_MBS
#define FW_DEVA_DEBLOCK_PIC_WIDTH_MBS_START_BIT		16
#define FW_DEVA_DEBLOCK_PIC_WIDTH_MBS_END_BIT		23
#define FW_DEVA_DEBLOCK_PIC_WIDTH_MBS_ALIGNMENT		(1)
#define FW_DEVA_DEBLOCK_PIC_WIDTH_MBS_TYPE		IMG_UINT8
#define FW_DEVA_DEBLOCK_PIC_WIDTH_MBS_MASK		(0xFF)
#define FW_DEVA_DEBLOCK_PIC_WIDTH_MBS_LSBMASK		(0xFF)
#define FW_DEVA_DEBLOCK_PIC_WIDTH_MBS_OFFSET		(0x0016)
#define FW_DEVA_DEBLOCK_PIC_WIDTH_MBS_SHIFT		(0)
#define FW_DEVA_DEBLOCK_PIC_WIDTH_MBS_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_PIC_WIDTH_MBS_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     RESA
#define FW_DEVA_DEBLOCK_RESA_START_BIT		8
#define FW_DEVA_DEBLOCK_RESA_END_BIT		15
#define FW_DEVA_DEBLOCK_RESA_ALIGNMENT		(1)
#define FW_DEVA_DEBLOCK_RESA_TYPE		IMG_UINT8
#define FW_DEVA_DEBLOCK_RESA_MASK		(0xFF)
#define FW_DEVA_DEBLOCK_RESA_LSBMASK		(0xFF)
#define FW_DEVA_DEBLOCK_RESA_OFFSET		(0x0015)
#define FW_DEVA_DEBLOCK_RESA_SHIFT		(0)
#define FW_DEVA_DEBLOCK_RESA_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_RESA_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     FRAME_HEIGHT_MBS
#define FW_DEVA_DEBLOCK_FRAME_HEIGHT_MBS_START_BIT		0
#define FW_DEVA_DEBLOCK_FRAME_HEIGHT_MBS_END_BIT		7
#define FW_DEVA_DEBLOCK_FRAME_HEIGHT_MBS_ALIGNMENT		(1)
#define FW_DEVA_DEBLOCK_FRAME_HEIGHT_MBS_TYPE		IMG_UINT8
#define FW_DEVA_DEBLOCK_FRAME_HEIGHT_MBS_MASK		(0xFF)
#define FW_DEVA_DEBLOCK_FRAME_HEIGHT_MBS_LSBMASK		(0xFF)
#define FW_DEVA_DEBLOCK_FRAME_HEIGHT_MBS_OFFSET		(0x0014)
#define FW_DEVA_DEBLOCK_FRAME_HEIGHT_MBS_SHIFT		(0)
#define FW_DEVA_DEBLOCK_FRAME_HEIGHT_MBS_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_FRAME_HEIGHT_MBS_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     ADDRESS_A0
#define FW_DEVA_DEBLOCK_ADDRESS_A0_START_BIT		0
#define FW_DEVA_DEBLOCK_ADDRESS_A0_END_BIT		31
#define FW_DEVA_DEBLOCK_ADDRESS_A0_ALIGNMENT		(4)
#define FW_DEVA_DEBLOCK_ADDRESS_A0_TYPE		IMG_UINT32
#define FW_DEVA_DEBLOCK_ADDRESS_A0_MASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_ADDRESS_A0_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_ADDRESS_A0_OFFSET		(0x0018)
#define FW_DEVA_DEBLOCK_ADDRESS_A0_SHIFT		(0)
#define FW_DEVA_DEBLOCK_ADDRESS_A0_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_ADDRESS_A0_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     ADDRESS_A1
#define FW_DEVA_DEBLOCK_ADDRESS_A1_START_BIT		0
#define FW_DEVA_DEBLOCK_ADDRESS_A1_END_BIT		31
#define FW_DEVA_DEBLOCK_ADDRESS_A1_ALIGNMENT		(4)
#define FW_DEVA_DEBLOCK_ADDRESS_A1_TYPE		IMG_UINT32
#define FW_DEVA_DEBLOCK_ADDRESS_A1_MASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_ADDRESS_A1_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_ADDRESS_A1_OFFSET		(0x001C)
#define FW_DEVA_DEBLOCK_ADDRESS_A1_SHIFT		(0)
#define FW_DEVA_DEBLOCK_ADDRESS_A1_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_ADDRESS_A1_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     MB_PARAM_ADDRESS
#define FW_DEVA_DEBLOCK_MB_PARAM_ADDRESS_START_BIT		0
#define FW_DEVA_DEBLOCK_MB_PARAM_ADDRESS_END_BIT		31
#define FW_DEVA_DEBLOCK_MB_PARAM_ADDRESS_ALIGNMENT		(4)
#define FW_DEVA_DEBLOCK_MB_PARAM_ADDRESS_TYPE		IMG_UINT32
#define FW_DEVA_DEBLOCK_MB_PARAM_ADDRESS_MASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_MB_PARAM_ADDRESS_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_MB_PARAM_ADDRESS_OFFSET		(0x0020)
#define FW_DEVA_DEBLOCK_MB_PARAM_ADDRESS_SHIFT		(0)
#define FW_DEVA_DEBLOCK_MB_PARAM_ADDRESS_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_MB_PARAM_ADDRESS_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     EXTSTRIDE_A
#define FW_DEVA_DEBLOCK_EXTSTRIDE_A_START_BIT		0
#define FW_DEVA_DEBLOCK_EXTSTRIDE_A_END_BIT		31
#define FW_DEVA_DEBLOCK_EXTSTRIDE_A_ALIGNMENT		(4)
#define FW_DEVA_DEBLOCK_EXTSTRIDE_A_TYPE		IMG_UINT32
#define FW_DEVA_DEBLOCK_EXTSTRIDE_A_MASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_EXTSTRIDE_A_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_EXTSTRIDE_A_OFFSET		(0x0024)
#define FW_DEVA_DEBLOCK_EXTSTRIDE_A_SHIFT		(0)
#define FW_DEVA_DEBLOCK_EXTSTRIDE_A_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_EXTSTRIDE_A_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     ADDRESS_B0
#define FW_DEVA_DEBLOCK_ADDRESS_B0_START_BIT		0
#define FW_DEVA_DEBLOCK_ADDRESS_B0_END_BIT		31
#define FW_DEVA_DEBLOCK_ADDRESS_B0_ALIGNMENT		(4)
#define FW_DEVA_DEBLOCK_ADDRESS_B0_TYPE		IMG_UINT32
#define FW_DEVA_DEBLOCK_ADDRESS_B0_MASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_ADDRESS_B0_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_ADDRESS_B0_OFFSET		(0x0028)
#define FW_DEVA_DEBLOCK_ADDRESS_B0_SHIFT		(0)
#define FW_DEVA_DEBLOCK_ADDRESS_B0_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_ADDRESS_B0_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     ADDRESS_B1
#define FW_DEVA_DEBLOCK_ADDRESS_B1_START_BIT		0
#define FW_DEVA_DEBLOCK_ADDRESS_B1_END_BIT		31
#define FW_DEVA_DEBLOCK_ADDRESS_B1_ALIGNMENT		(4)
#define FW_DEVA_DEBLOCK_ADDRESS_B1_TYPE		IMG_UINT32
#define FW_DEVA_DEBLOCK_ADDRESS_B1_MASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_ADDRESS_B1_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_ADDRESS_B1_OFFSET		(0x002C)
#define FW_DEVA_DEBLOCK_ADDRESS_B1_SHIFT		(0)
#define FW_DEVA_DEBLOCK_ADDRESS_B1_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_ADDRESS_B1_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     ALTOUTPUTFLAGS_B
#define FW_DEVA_DEBLOCK_ALTOUTPUTFLAGS_B_START_BIT		0
#define FW_DEVA_DEBLOCK_ALTOUTPUTFLAGS_B_END_BIT		31
#define FW_DEVA_DEBLOCK_ALTOUTPUTFLAGS_B_ALIGNMENT		(4)
#define FW_DEVA_DEBLOCK_ALTOUTPUTFLAGS_B_TYPE		IMG_UINT32
#define FW_DEVA_DEBLOCK_ALTOUTPUTFLAGS_B_MASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_ALTOUTPUTFLAGS_B_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_ALTOUTPUTFLAGS_B_OFFSET		(0x0030)
#define FW_DEVA_DEBLOCK_ALTOUTPUTFLAGS_B_SHIFT		(0)
#define FW_DEVA_DEBLOCK_ALTOUTPUTFLAGS_B_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_ALTOUTPUTFLAGS_B_TRUSTED		(IMG_FALSE)

// FW_DEVA_DEBLOCK     EXT_STATE_BUFFER
#define FW_DEVA_DEBLOCK_EXT_STATE_BUFFER_START_BIT		0
#define FW_DEVA_DEBLOCK_EXT_STATE_BUFFER_END_BIT		31
#define FW_DEVA_DEBLOCK_EXT_STATE_BUFFER_ALIGNMENT		(4)
#define FW_DEVA_DEBLOCK_EXT_STATE_BUFFER_TYPE		IMG_UINT32
#define FW_DEVA_DEBLOCK_EXT_STATE_BUFFER_MASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_EXT_STATE_BUFFER_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_DEBLOCK_EXT_STATE_BUFFER_OFFSET		(0x0034)
#define FW_DEVA_DEBLOCK_EXT_STATE_BUFFER_SHIFT		(0)
#define FW_DEVA_DEBLOCK_EXT_STATE_BUFFER_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_DEBLOCK_EXT_STATE_BUFFER_TRUSTED		(IMG_FALSE)

#define FW_DEVA_COMPLETED_SIZE		(20)

// FW_DEVA_COMPLETED     MSG_ID
#define FW_DEVA_COMPLETED_MSG_ID_START_BIT		16
#define FW_DEVA_COMPLETED_MSG_ID_END_BIT		31
#define FW_DEVA_COMPLETED_MSG_ID_ALIGNMENT		(2)
#define FW_DEVA_COMPLETED_MSG_ID_TYPE		IMG_UINT16
#define FW_DEVA_COMPLETED_MSG_ID_MASK		(0xFFFF)
#define FW_DEVA_COMPLETED_MSG_ID_LSBMASK		(0xFFFF)
#define FW_DEVA_COMPLETED_MSG_ID_OFFSET		(0x0002)
#define FW_DEVA_COMPLETED_MSG_ID_SHIFT		(0)
#define FW_DEVA_COMPLETED_MSG_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_COMPLETED_MSG_ID_TRUSTED		(IMG_FALSE)

// FW_DEVA_COMPLETED     MSG_TYPE
#define FW_DEVA_COMPLETED_MSG_TYPE_START_BIT		8
#define FW_DEVA_COMPLETED_MSG_TYPE_END_BIT		15
#define FW_DEVA_COMPLETED_MSG_TYPE_ALIGNMENT		(1)
#define FW_DEVA_COMPLETED_MSG_TYPE_TYPE		IMG_UINT8
#define FW_DEVA_COMPLETED_MSG_TYPE_MASK		(0xFF)
#define FW_DEVA_COMPLETED_MSG_TYPE_LSBMASK		(0xFF)
#define FW_DEVA_COMPLETED_MSG_TYPE_OFFSET		(0x0001)
#define FW_DEVA_COMPLETED_MSG_TYPE_SHIFT		(0)
#define FW_DEVA_COMPLETED_MSG_TYPE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_COMPLETED_MSG_TYPE_TRUSTED		(IMG_FALSE)

// FW_DEVA_COMPLETED     MSG_SIZE
#define FW_DEVA_COMPLETED_MSG_SIZE_START_BIT		0
#define FW_DEVA_COMPLETED_MSG_SIZE_END_BIT		7
#define FW_DEVA_COMPLETED_MSG_SIZE_ALIGNMENT		(1)
#define FW_DEVA_COMPLETED_MSG_SIZE_TYPE		IMG_UINT8
#define FW_DEVA_COMPLETED_MSG_SIZE_MASK		(0xFF)
#define FW_DEVA_COMPLETED_MSG_SIZE_LSBMASK		(0xFF)
#define FW_DEVA_COMPLETED_MSG_SIZE_OFFSET		(0x0000)
#define FW_DEVA_COMPLETED_MSG_SIZE_SHIFT		(0)
#define FW_DEVA_COMPLETED_MSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_COMPLETED_MSG_SIZE_TRUSTED		(IMG_FALSE)

// FW_DEVA_COMPLETED     TRANS_ID
#define FW_DEVA_COMPLETED_TRANS_ID_START_BIT		0
#define FW_DEVA_COMPLETED_TRANS_ID_END_BIT		31
#define FW_DEVA_COMPLETED_TRANS_ID_ALIGNMENT		(4)
#define FW_DEVA_COMPLETED_TRANS_ID_TYPE		IMG_UINT32
#define FW_DEVA_COMPLETED_TRANS_ID_MASK		(0xFFFFFFFF)
#define FW_DEVA_COMPLETED_TRANS_ID_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_COMPLETED_TRANS_ID_OFFSET		(0x0004)
#define FW_DEVA_COMPLETED_TRANS_ID_SHIFT		(0)
#define FW_DEVA_COMPLETED_TRANS_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_COMPLETED_TRANS_ID_TRUSTED		(IMG_FALSE)

// FW_DEVA_COMPLETED     STATUS_FLAGS
#define FW_DEVA_COMPLETED_STATUS_FLAGS_START_BIT		16
#define FW_DEVA_COMPLETED_STATUS_FLAGS_END_BIT		31
#define FW_DEVA_COMPLETED_STATUS_FLAGS_ALIGNMENT		(2)
#define FW_DEVA_COMPLETED_STATUS_FLAGS_TYPE		IMG_UINT16
#define FW_DEVA_COMPLETED_STATUS_FLAGS_MASK		(0xFFFF)
#define FW_DEVA_COMPLETED_STATUS_FLAGS_LSBMASK		(0xFFFF)
#define FW_DEVA_COMPLETED_STATUS_FLAGS_OFFSET		(0x000A)
#define FW_DEVA_COMPLETED_STATUS_FLAGS_SHIFT		(0)
#define FW_DEVA_COMPLETED_STATUS_FLAGS_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_COMPLETED_STATUS_FLAGS_TRUSTED		(IMG_FALSE)

// FW_DEVA_COMPLETED     ERROR_FLAGS
#define FW_DEVA_COMPLETED_ERROR_FLAGS_START_BIT		0
#define FW_DEVA_COMPLETED_ERROR_FLAGS_END_BIT		15
#define FW_DEVA_COMPLETED_ERROR_FLAGS_ALIGNMENT		(2)
#define FW_DEVA_COMPLETED_ERROR_FLAGS_TYPE		IMG_UINT16
#define FW_DEVA_COMPLETED_ERROR_FLAGS_MASK		(0xFFFF)
#define FW_DEVA_COMPLETED_ERROR_FLAGS_LSBMASK		(0xFFFF)
#define FW_DEVA_COMPLETED_ERROR_FLAGS_OFFSET		(0x0008)
#define FW_DEVA_COMPLETED_ERROR_FLAGS_SHIFT		(0)
#define FW_DEVA_COMPLETED_ERROR_FLAGS_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_COMPLETED_ERROR_FLAGS_TRUSTED		(IMG_FALSE)

// FW_DEVA_COMPLETED     FLAGS
#define FW_DEVA_COMPLETED_FLAGS_START_BIT		0
#define FW_DEVA_COMPLETED_FLAGS_END_BIT		31
#define FW_DEVA_COMPLETED_FLAGS_ALIGNMENT		(4)
#define FW_DEVA_COMPLETED_FLAGS_TYPE		IMG_UINT32
#define FW_DEVA_COMPLETED_FLAGS_MASK		(0xFFFFFFFF)
#define FW_DEVA_COMPLETED_FLAGS_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_COMPLETED_FLAGS_OFFSET		(0x0008)
#define FW_DEVA_COMPLETED_FLAGS_SHIFT		(0)
#define FW_DEVA_COMPLETED_FLAGS_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_COMPLETED_FLAGS_TRUSTED		(IMG_FALSE)

// FW_DEVA_COMPLETED     STARTMB
#define FW_DEVA_COMPLETED_STARTMB_START_BIT		16
#define FW_DEVA_COMPLETED_STARTMB_END_BIT		31
#define FW_DEVA_COMPLETED_STARTMB_ALIGNMENT		(2)
#define FW_DEVA_COMPLETED_STARTMB_TYPE		IMG_UINT16
#define FW_DEVA_COMPLETED_STARTMB_MASK		(0xFFFF)
#define FW_DEVA_COMPLETED_STARTMB_LSBMASK		(0xFFFF)
#define FW_DEVA_COMPLETED_STARTMB_OFFSET		(0x000E)
#define FW_DEVA_COMPLETED_STARTMB_SHIFT		(0)
#define FW_DEVA_COMPLETED_STARTMB_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_COMPLETED_STARTMB_TRUSTED		(IMG_FALSE)

// FW_DEVA_COMPLETED     LASTMB
#define FW_DEVA_COMPLETED_LASTMB_START_BIT		0
#define FW_DEVA_COMPLETED_LASTMB_END_BIT		15
#define FW_DEVA_COMPLETED_LASTMB_ALIGNMENT		(2)
#define FW_DEVA_COMPLETED_LASTMB_TYPE		IMG_UINT16
#define FW_DEVA_COMPLETED_LASTMB_MASK		(0xFFFF)
#define FW_DEVA_COMPLETED_LASTMB_LSBMASK		(0xFFFF)
#define FW_DEVA_COMPLETED_LASTMB_OFFSET		(0x000C)
#define FW_DEVA_COMPLETED_LASTMB_SHIFT		(0)
#define FW_DEVA_COMPLETED_LASTMB_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_COMPLETED_LASTMB_TRUSTED		(IMG_FALSE)

// FW_DEVA_COMPLETED     VDEBCR
#define FW_DEVA_COMPLETED_VDEBCR_START_BIT		0
#define FW_DEVA_COMPLETED_VDEBCR_END_BIT		31
#define FW_DEVA_COMPLETED_VDEBCR_ALIGNMENT		(4)
#define FW_DEVA_COMPLETED_VDEBCR_TYPE		IMG_UINT32
#define FW_DEVA_COMPLETED_VDEBCR_MASK		(0xFFFFFFFF)
#define FW_DEVA_COMPLETED_VDEBCR_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_COMPLETED_VDEBCR_OFFSET		(0x0010)
#define FW_DEVA_COMPLETED_VDEBCR_SHIFT		(0)
#define FW_DEVA_COMPLETED_VDEBCR_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_COMPLETED_VDEBCR_TRUSTED		(IMG_FALSE)

#define FW_DEVA_PANIC_SIZE		(12)

// FW_DEVA_PANIC     MSG_ID
#define FW_DEVA_PANIC_MSG_ID_START_BIT		16
#define FW_DEVA_PANIC_MSG_ID_END_BIT		31
#define FW_DEVA_PANIC_MSG_ID_ALIGNMENT		(2)
#define FW_DEVA_PANIC_MSG_ID_TYPE		IMG_UINT16
#define FW_DEVA_PANIC_MSG_ID_MASK		(0xFFFF)
#define FW_DEVA_PANIC_MSG_ID_LSBMASK		(0xFFFF)
#define FW_DEVA_PANIC_MSG_ID_OFFSET		(0x0002)
#define FW_DEVA_PANIC_MSG_ID_SHIFT		(0)
#define FW_DEVA_PANIC_MSG_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_PANIC_MSG_ID_TRUSTED		(IMG_FALSE)

// FW_DEVA_PANIC     MSG_TYPE
#define FW_DEVA_PANIC_MSG_TYPE_START_BIT		8
#define FW_DEVA_PANIC_MSG_TYPE_END_BIT		15
#define FW_DEVA_PANIC_MSG_TYPE_ALIGNMENT		(1)
#define FW_DEVA_PANIC_MSG_TYPE_TYPE		IMG_UINT8
#define FW_DEVA_PANIC_MSG_TYPE_MASK		(0xFF)
#define FW_DEVA_PANIC_MSG_TYPE_LSBMASK		(0xFF)
#define FW_DEVA_PANIC_MSG_TYPE_OFFSET		(0x0001)
#define FW_DEVA_PANIC_MSG_TYPE_SHIFT		(0)
#define FW_DEVA_PANIC_MSG_TYPE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_PANIC_MSG_TYPE_TRUSTED		(IMG_FALSE)

// FW_DEVA_PANIC     MSG_SIZE
#define FW_DEVA_PANIC_MSG_SIZE_START_BIT		0
#define FW_DEVA_PANIC_MSG_SIZE_END_BIT		7
#define FW_DEVA_PANIC_MSG_SIZE_ALIGNMENT		(1)
#define FW_DEVA_PANIC_MSG_SIZE_TYPE		IMG_UINT8
#define FW_DEVA_PANIC_MSG_SIZE_MASK		(0xFF)
#define FW_DEVA_PANIC_MSG_SIZE_LSBMASK		(0xFF)
#define FW_DEVA_PANIC_MSG_SIZE_OFFSET		(0x0000)
#define FW_DEVA_PANIC_MSG_SIZE_SHIFT		(0)
#define FW_DEVA_PANIC_MSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_PANIC_MSG_SIZE_TRUSTED		(IMG_FALSE)

// FW_DEVA_PANIC     TRANS_ID
#define FW_DEVA_PANIC_TRANS_ID_START_BIT		0
#define FW_DEVA_PANIC_TRANS_ID_END_BIT		31
#define FW_DEVA_PANIC_TRANS_ID_ALIGNMENT		(4)
#define FW_DEVA_PANIC_TRANS_ID_TYPE		IMG_UINT32
#define FW_DEVA_PANIC_TRANS_ID_MASK		(0xFFFFFFFF)
#define FW_DEVA_PANIC_TRANS_ID_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_PANIC_TRANS_ID_OFFSET		(0x0004)
#define FW_DEVA_PANIC_TRANS_ID_SHIFT		(0)
#define FW_DEVA_PANIC_TRANS_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_PANIC_TRANS_ID_TRUSTED		(IMG_FALSE)

// FW_DEVA_PANIC     ERROR_INT
#define FW_DEVA_PANIC_ERROR_INT_START_BIT		0
#define FW_DEVA_PANIC_ERROR_INT_END_BIT		31
#define FW_DEVA_PANIC_ERROR_INT_ALIGNMENT		(4)
#define FW_DEVA_PANIC_ERROR_INT_TYPE		IMG_UINT32
#define FW_DEVA_PANIC_ERROR_INT_MASK		(0xFFFFFFFF)
#define FW_DEVA_PANIC_ERROR_INT_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_PANIC_ERROR_INT_OFFSET		(0x0008)
#define FW_DEVA_PANIC_ERROR_INT_SHIFT		(0)
#define FW_DEVA_PANIC_ERROR_INT_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_PANIC_ERROR_INT_TRUSTED		(IMG_FALSE)

#define FW_DEVA_CONTIGUITY_WARNING_SIZE		(12)

// FW_DEVA_CONTIGUITY_WARNING     MSG_ID
#define FW_DEVA_CONTIGUITY_WARNING_MSG_ID_START_BIT		16
#define FW_DEVA_CONTIGUITY_WARNING_MSG_ID_END_BIT		31
#define FW_DEVA_CONTIGUITY_WARNING_MSG_ID_ALIGNMENT		(2)
#define FW_DEVA_CONTIGUITY_WARNING_MSG_ID_TYPE		IMG_UINT16
#define FW_DEVA_CONTIGUITY_WARNING_MSG_ID_MASK		(0xFFFF)
#define FW_DEVA_CONTIGUITY_WARNING_MSG_ID_LSBMASK		(0xFFFF)
#define FW_DEVA_CONTIGUITY_WARNING_MSG_ID_OFFSET		(0x0002)
#define FW_DEVA_CONTIGUITY_WARNING_MSG_ID_SHIFT		(0)
#define FW_DEVA_CONTIGUITY_WARNING_MSG_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_CONTIGUITY_WARNING_MSG_ID_TRUSTED		(IMG_FALSE)

// FW_DEVA_CONTIGUITY_WARNING     MSG_TYPE
#define FW_DEVA_CONTIGUITY_WARNING_MSG_TYPE_START_BIT		8
#define FW_DEVA_CONTIGUITY_WARNING_MSG_TYPE_END_BIT		15
#define FW_DEVA_CONTIGUITY_WARNING_MSG_TYPE_ALIGNMENT		(1)
#define FW_DEVA_CONTIGUITY_WARNING_MSG_TYPE_TYPE		IMG_UINT8
#define FW_DEVA_CONTIGUITY_WARNING_MSG_TYPE_MASK		(0xFF)
#define FW_DEVA_CONTIGUITY_WARNING_MSG_TYPE_LSBMASK		(0xFF)
#define FW_DEVA_CONTIGUITY_WARNING_MSG_TYPE_OFFSET		(0x0001)
#define FW_DEVA_CONTIGUITY_WARNING_MSG_TYPE_SHIFT		(0)
#define FW_DEVA_CONTIGUITY_WARNING_MSG_TYPE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_CONTIGUITY_WARNING_MSG_TYPE_TRUSTED		(IMG_FALSE)

// FW_DEVA_CONTIGUITY_WARNING     MSG_SIZE
#define FW_DEVA_CONTIGUITY_WARNING_MSG_SIZE_START_BIT		0
#define FW_DEVA_CONTIGUITY_WARNING_MSG_SIZE_END_BIT		7
#define FW_DEVA_CONTIGUITY_WARNING_MSG_SIZE_ALIGNMENT		(1)
#define FW_DEVA_CONTIGUITY_WARNING_MSG_SIZE_TYPE		IMG_UINT8
#define FW_DEVA_CONTIGUITY_WARNING_MSG_SIZE_MASK		(0xFF)
#define FW_DEVA_CONTIGUITY_WARNING_MSG_SIZE_LSBMASK		(0xFF)
#define FW_DEVA_CONTIGUITY_WARNING_MSG_SIZE_OFFSET		(0x0000)
#define FW_DEVA_CONTIGUITY_WARNING_MSG_SIZE_SHIFT		(0)
#define FW_DEVA_CONTIGUITY_WARNING_MSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_CONTIGUITY_WARNING_MSG_SIZE_TRUSTED		(IMG_FALSE)

// FW_DEVA_CONTIGUITY_WARNING     TRANS_ID
#define FW_DEVA_CONTIGUITY_WARNING_TRANS_ID_START_BIT		0
#define FW_DEVA_CONTIGUITY_WARNING_TRANS_ID_END_BIT		31
#define FW_DEVA_CONTIGUITY_WARNING_TRANS_ID_ALIGNMENT		(4)
#define FW_DEVA_CONTIGUITY_WARNING_TRANS_ID_TYPE		IMG_UINT32
#define FW_DEVA_CONTIGUITY_WARNING_TRANS_ID_MASK		(0xFFFFFFFF)
#define FW_DEVA_CONTIGUITY_WARNING_TRANS_ID_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_CONTIGUITY_WARNING_TRANS_ID_OFFSET		(0x0004)
#define FW_DEVA_CONTIGUITY_WARNING_TRANS_ID_SHIFT		(0)
#define FW_DEVA_CONTIGUITY_WARNING_TRANS_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_CONTIGUITY_WARNING_TRANS_ID_TRUSTED		(IMG_FALSE)

// FW_DEVA_CONTIGUITY_WARNING     END_MB_NUM
#define FW_DEVA_CONTIGUITY_WARNING_END_MB_NUM_START_BIT		0
#define FW_DEVA_CONTIGUITY_WARNING_END_MB_NUM_END_BIT		15
#define FW_DEVA_CONTIGUITY_WARNING_END_MB_NUM_ALIGNMENT		(2)
#define FW_DEVA_CONTIGUITY_WARNING_END_MB_NUM_TYPE		IMG_UINT16
#define FW_DEVA_CONTIGUITY_WARNING_END_MB_NUM_MASK		(0xFFFF)
#define FW_DEVA_CONTIGUITY_WARNING_END_MB_NUM_LSBMASK		(0xFFFF)
#define FW_DEVA_CONTIGUITY_WARNING_END_MB_NUM_OFFSET		(0x0008)
#define FW_DEVA_CONTIGUITY_WARNING_END_MB_NUM_SHIFT		(0)
#define FW_DEVA_CONTIGUITY_WARNING_END_MB_NUM_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_CONTIGUITY_WARNING_END_MB_NUM_TRUSTED		(IMG_FALSE)

// FW_DEVA_CONTIGUITY_WARNING     BEGIN_MB_NUM
#define FW_DEVA_CONTIGUITY_WARNING_BEGIN_MB_NUM_START_BIT		16
#define FW_DEVA_CONTIGUITY_WARNING_BEGIN_MB_NUM_END_BIT		31
#define FW_DEVA_CONTIGUITY_WARNING_BEGIN_MB_NUM_ALIGNMENT		(2)
#define FW_DEVA_CONTIGUITY_WARNING_BEGIN_MB_NUM_TYPE		IMG_UINT16
#define FW_DEVA_CONTIGUITY_WARNING_BEGIN_MB_NUM_MASK		(0xFFFF)
#define FW_DEVA_CONTIGUITY_WARNING_BEGIN_MB_NUM_LSBMASK		(0xFFFF)
#define FW_DEVA_CONTIGUITY_WARNING_BEGIN_MB_NUM_OFFSET		(0x000A)
#define FW_DEVA_CONTIGUITY_WARNING_BEGIN_MB_NUM_SHIFT		(0)
#define FW_DEVA_CONTIGUITY_WARNING_BEGIN_MB_NUM_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_CONTIGUITY_WARNING_BEGIN_MB_NUM_TRUSTED		(IMG_FALSE)

#define FW_DEVA_SIGNATURES_SIZE		(16)

// FW_DEVA_SIGNATURES     MSG_ID
#define FW_DEVA_SIGNATURES_MSG_ID_START_BIT		16
#define FW_DEVA_SIGNATURES_MSG_ID_END_BIT		31
#define FW_DEVA_SIGNATURES_MSG_ID_ALIGNMENT		(2)
#define FW_DEVA_SIGNATURES_MSG_ID_TYPE		IMG_UINT16
#define FW_DEVA_SIGNATURES_MSG_ID_MASK		(0xFFFF)
#define FW_DEVA_SIGNATURES_MSG_ID_LSBMASK		(0xFFFF)
#define FW_DEVA_SIGNATURES_MSG_ID_OFFSET		(0x0002)
#define FW_DEVA_SIGNATURES_MSG_ID_SHIFT		(0)
#define FW_DEVA_SIGNATURES_MSG_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_SIGNATURES_MSG_ID_TRUSTED		(IMG_FALSE)

// FW_DEVA_SIGNATURES     MSG_TYPE
#define FW_DEVA_SIGNATURES_MSG_TYPE_START_BIT		8
#define FW_DEVA_SIGNATURES_MSG_TYPE_END_BIT		15
#define FW_DEVA_SIGNATURES_MSG_TYPE_ALIGNMENT		(1)
#define FW_DEVA_SIGNATURES_MSG_TYPE_TYPE		IMG_UINT8
#define FW_DEVA_SIGNATURES_MSG_TYPE_MASK		(0xFF)
#define FW_DEVA_SIGNATURES_MSG_TYPE_LSBMASK		(0xFF)
#define FW_DEVA_SIGNATURES_MSG_TYPE_OFFSET		(0x0001)
#define FW_DEVA_SIGNATURES_MSG_TYPE_SHIFT		(0)
#define FW_DEVA_SIGNATURES_MSG_TYPE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_SIGNATURES_MSG_TYPE_TRUSTED		(IMG_FALSE)

// FW_DEVA_SIGNATURES     BATCH_START
#define FW_DEVA_SIGNATURES_BATCH_START_START_BIT		7
#define FW_DEVA_SIGNATURES_BATCH_START_END_BIT		7
#define FW_DEVA_SIGNATURES_BATCH_START_ALIGNMENT		(1)
#define FW_DEVA_SIGNATURES_BATCH_START_TYPE		IMG_UINT8
#define FW_DEVA_SIGNATURES_BATCH_START_MASK		(0x80)
#define FW_DEVA_SIGNATURES_BATCH_START_LSBMASK		(0x01)
#define FW_DEVA_SIGNATURES_BATCH_START_OFFSET		(0x0000)
#define FW_DEVA_SIGNATURES_BATCH_START_SHIFT		(7)
#define FW_DEVA_SIGNATURES_BATCH_START_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_SIGNATURES_BATCH_START_TRUSTED		(IMG_FALSE)

// FW_DEVA_SIGNATURES     MSG_SIZE
#define FW_DEVA_SIGNATURES_MSG_SIZE_START_BIT		0
#define FW_DEVA_SIGNATURES_MSG_SIZE_END_BIT		6
#define FW_DEVA_SIGNATURES_MSG_SIZE_ALIGNMENT		(1)
#define FW_DEVA_SIGNATURES_MSG_SIZE_TYPE		IMG_UINT8
#define FW_DEVA_SIGNATURES_MSG_SIZE_MASK		(0x7F)
#define FW_DEVA_SIGNATURES_MSG_SIZE_LSBMASK		(0x7F)
#define FW_DEVA_SIGNATURES_MSG_SIZE_OFFSET		(0x0000)
#define FW_DEVA_SIGNATURES_MSG_SIZE_SHIFT		(0)
#define FW_DEVA_SIGNATURES_MSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_SIGNATURES_MSG_SIZE_TRUSTED		(IMG_FALSE)

// FW_DEVA_SIGNATURES     TRANS_ID
#define FW_DEVA_SIGNATURES_TRANS_ID_START_BIT		0
#define FW_DEVA_SIGNATURES_TRANS_ID_END_BIT		31
#define FW_DEVA_SIGNATURES_TRANS_ID_ALIGNMENT		(4)
#define FW_DEVA_SIGNATURES_TRANS_ID_TYPE		IMG_UINT32
#define FW_DEVA_SIGNATURES_TRANS_ID_MASK		(0xFFFFFFFF)
#define FW_DEVA_SIGNATURES_TRANS_ID_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_SIGNATURES_TRANS_ID_OFFSET		(0x0004)
#define FW_DEVA_SIGNATURES_TRANS_ID_SHIFT		(0)
#define FW_DEVA_SIGNATURES_TRANS_ID_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_SIGNATURES_TRANS_ID_TRUSTED		(IMG_FALSE)

// FW_DEVA_SIGNATURES     SIGNATURE_SELECT
#define FW_DEVA_SIGNATURES_SIGNATURE_SELECT_START_BIT		0
#define FW_DEVA_SIGNATURES_SIGNATURE_SELECT_END_BIT		31
#define FW_DEVA_SIGNATURES_SIGNATURE_SELECT_ALIGNMENT		(4)
#define FW_DEVA_SIGNATURES_SIGNATURE_SELECT_TYPE		IMG_UINT32
#define FW_DEVA_SIGNATURES_SIGNATURE_SELECT_MASK		(0xFFFFFFFF)
#define FW_DEVA_SIGNATURES_SIGNATURE_SELECT_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_SIGNATURES_SIGNATURE_SELECT_OFFSET		(0x0008)
#define FW_DEVA_SIGNATURES_SIGNATURE_SELECT_SHIFT		(0)
#define FW_DEVA_SIGNATURES_SIGNATURE_SELECT_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_SIGNATURES_SIGNATURE_SELECT_TRUSTED		(IMG_FALSE)

// FW_DEVA_SIGNATURES     SIGNATURES
#define FW_DEVA_SIGNATURES_SIGNATURES_START_BIT		0
#define FW_DEVA_SIGNATURES_SIGNATURES_END_BIT		31
#define FW_DEVA_SIGNATURES_SIGNATURES_ALIGNMENT		(4)
#define FW_DEVA_SIGNATURES_SIGNATURES_TYPE		IMG_UINT32
#define FW_DEVA_SIGNATURES_SIGNATURES_MASK		(0xFFFFFFFF)
#define FW_DEVA_SIGNATURES_SIGNATURES_LSBMASK		(0xFFFFFFFF)
#define FW_DEVA_SIGNATURES_SIGNATURES_OFFSET		(0x000C)
#define FW_DEVA_SIGNATURES_SIGNATURES_SHIFT		(0)
#define FW_DEVA_SIGNATURES_SIGNATURES_SIGNED_FIELD	IMG_FALSE
#define FW_DEVA_SIGNATURES_SIGNATURES_TRUSTED		(IMG_FALSE)



#ifdef __cplusplus
}
#endif

#endif /* __DEVA_FW_MSG_H__ */
