EXTRA_CFLAGS   += -Idrivers/hisi/ipc_hi6xxx/
EXTRA_CFLAGS   += -I../../../../vendor/hisi/ap/platform/hi3650/
EXTRA_CFLAGS   += -Idrivers/hisi/mntn/blackbox/platform_lpm3
obj-$(CONFIG_HISILICON_PLATFORM_TELE_MNTN)	+= drv_tele_mntn_common.o drv_tele_mntn_gut.o drv_tele_mntn_node.o
