# MD5: 11d5a20a694108f0c223bc9e04b370f1
set(CFG_TENSILICA_BUILDS_HIFI $(ROOT_XTENSA_PATH_W)/XtDevTools/install/builds/RE-2014.5-linux) 

set(CFG_TENSILICA_TOOLS_HIFI $(ROOT_XTENSA_PATH_W)/XtDevTools/install/tools/RE-2014.5-linux) 

set(CFG_FEATURE_HIFI FEATURE_ON) 

set(CFG_FEATURE_HIFI_USE_ICC FEATURE_ON) 

set(CFG_FEATURE_MBB_MODULE_AUDIO FEATURE_OFF) 

set(CFG_FEATURE_VOICE_UP FEATURE_OFF) 

set(CFG_FEATURE_DTMF FEATURE_ON) 

