# MD5: c4edbe7b9b0d3bb6199027e5b31d8af2
set(CFG_PRODUCT_CONTROL_VERSION "121") 

set(CFG_PRODUCT_HISILICON_VERSION hi6932) 

set(CFG_PRODUCT_NV_SPLITFILE binfilesplit "0") 

set(CFG_PRODUCT_NV_FILE_MAX_SIZE binfileLimitSize "100") 

set(CFG_PRODUCT_NV_BIN_MODEM_NUNBER bin_modem_number "1") 

set(CFG_PRODUCT_NV_XNV_MODEM_NUNBER xnv_modem_number "1") 

set(CFG_PRODUCT_NV_XNV_PDT_VERSION hi6932_udp) 

