# MD5: 6077281abcec0828679759108e25203f
set(CFG_FEATURE_ACPU_FC_POINT_REG FEATURE_OFF) 

set(CFG_FEATURE_ACPU_STAT FEATURE_OFF) 

set(CFG_FEATURE_BBPMST_FREQUENCY_REDUCE FEATURE_ON) 

set(CFG_FEATURE_CSD FEATURE_OFF) 

set(CFG_FEATURE_CST_ASYN_OR_NOT_TRANS FEATURE_OFF) 

set(CFG_FEATURE_HARDWARE_HDLC_FUNC FEATURE_OFF) 

set(CFG_FEATURE_HISOCKET				 FEATURE_OFF) 

set(CFG_FEATURE_MMU_MEDIUM FEATURE_ON) 

set(CFG_FEATURE_MMU_SMALL FEATURE_OFF) 

set(CFG_FEATURE_NFEXT FEATURE_OFF) 

set(CFG_FEATURE_PPP FEATURE_OFF) 

set(CFG_FEATURE_SMALL_MAILBOX FEATURE_OFF) 

set(CFG_FEATURE_TCP_ACK_IN_FRONT FEATURE_ON) 

set(CFG_FEATURE_TTF_MEM_DEBUG FEATURE_ON) 

set(CFG_FEATURE_VISP_VPP				 FEATURE_ON) 

set(CFG_SC_CTRL_MOD_6620_FPGA 1) 

set(CFG_SC_CTRL_MOD_6620_SFT 2) 

set(CFG_SC_CTRL_MOD_6758_FPGA 3) 

set(CFG_SC_CTRL_MOD_6758_SFT 4) 

set(CFG_SC_CTRL_MOD_6930_FPGA 5) 

set(CFG_SC_CTRL_MOD_6930_SFT 6) 

set(CFG_SC_CTRL_MOD_3630_UDP 7) 

set(CFG_SC_CTRL_MOD_6210_FPGA 8) 

set(CFG_SC_CTRL_MOD_6210_SFT 9) 

set(CFG_SC_CTRL_MOD_P532 10) 

set(CFG_SC_CTRL_MOD_6950_SFT 11) 

set(CFG_SC_CTRL_MOD_3650_SFT 12) 

set(CFG_SC_CTRL_MOD (SC_CTRL_MOD_P532)) 

set(CFG_TTF_CF_FEATURE FEATURE_OFF) 

set(CFG_FEATURE_DSDS FEATURE_OFF) 

set(CFG_GAS_PTL_VER_PRE_R99 (PS_PTL_VER_PRE_R99)) 

set(CFG_GAS_PTL_VER_R99 (PS_PTL_VER_R99)) 

set(CFG_GAS_PTL_VER_R3 (PS_PTL_VER_R3)) 

set(CFG_GAS_PTL_VER_R4 (PS_PTL_VER_R4)) 

set(CFG_GAS_PTL_VER_R5 (PS_PTL_VER_R5)) 

set(CFG_GAS_PTL_VER_R6 (PS_PTL_VER_R6)) 

set(CFG_GAS_PTL_VER_R7 (PS_PTL_VER_R7)) 

set(CFG_GAS_PTL_VER_R8 (PS_PTL_VER_R8)) 

set(CFG_GAS_PTL_VER_R9 (PS_PTL_VER_R9)) 

set(CFG_GAS_UE_REL_VER (GAS_PTL_VER_R9)) 

set(CFG_FEATURE_DC_MIMO FEATURE_OFF) 

set(CFG_FEATURE_DC_UPA FEATURE_OFF) 

set(CFG_FEATURE_DL_E_CELL_FACH FEATURE_ON) 

set(CFG_FEATURE_UL_E_CELL_FACH FEATURE_ON) 

set(CFG_FEATURE_HARDWARE_HDLC_ON_CCPU FEATURE_OFF) 

set(CFG_FEATURE_BASTET FEATURE_OFF) 

