# MD5: 751e206763761094ef9967cce754e207
set(CFG_ZSP_DSP_CHIP_BB_TYPE		 11) 

set(CFG_ZSP_DSP_PRODUCT_FORM		 4) 

set(CFG_BOARD FPGA) 

set(CFG_FEATURE_TEMP_DSP_CORE_POWER_DOWN FEATURE_OFF) 

set(CFG_FEATURE_TUNER				 FEATURE_ON) 

set(CFG_FEATURE_TEMP_MULTI_MODE_LP FEATURE_ON) 

set(CFG_FEATURE_SRAM_400K FEATURE_OFF) 

set(CFG_FEATURE_EXTERNAL_32K_CLK		 FEATURE_ON) 

set(CFG_FEATURE_SOCP_ON_DEMAND			 FEATURE_OFF) 

set(CFG_FEATURE_GU_DSP_SPLIT FEATURE_ON) 

set(CFG_FEATURE_DC_DPA			 FEATURE_ON) 

set(CFG_FEATURE_HARQ_OUT FEATURE_OFF) 

set(CFG_FEATURE_MULTI_RFIC_MEAS			 FEATURE_ON) 

set(CFG_FEATURE_RFIC_RESET_GPIO_ON		 FEATURE_OFF) 

set(CFG_FEATURE_UPHY_SIO_WPLL_ELUSION_ON FEATURE_OFF) 

set(CFG_FEATURE_VIRTUAL_BAND			 FEATURE_OFF) 

set(CFG_FEATURE_ANT_SHARE				 FEATURE_OFF) 

set(CFG_CPHY_PUB_DTCM_BASE	 0x49400000) 

set(CFG_CPHY_PUB_ITCM_BASE	 0x49500000) 

set(CFG_CPHY_PRV_DTCM_BASE	 0x49480000) 

set(CFG_CPHY_PRV_ITCM_BASE	 0x49580000) 

set(CFG_CPHY_PUB_DTCM_SIZE		 0x80000) 

set(CFG_CPHY_PUB_ITCM_SIZE		 0x80000) 

set(CFG_CPHY_PRV_DTCM_SIZE		 0x80000) 

set(CFG_CPHY_PRV_ITCM_SIZE		 0x80000) 

set(CFG_XTENSA_CORE_X_CACHE p532_bbe16_cache) 

