##############################################
#     Make file of SONYIMX328 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/huawei/camera/sonyimx328/
#EXTRA_CFLAGS += -fno-pic 
ccflags-$(CONFIG_HI6210_CAMERA_SONYIMX328) += -DSONYIMX328_OTP
obj-$(CONFIG_HI6210_CAMERA_SONYIMX328) += sonyimx328.o
#################### END #####################
