/*
 * hi3630_asp_cfg.h -- HI3630 ASP CFG DRIVER
 *
 * Copyright (c) 2013 Hisilicon Technologies CO., Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef __HI3630_CFG_H__
#define __HI3630_CFG_H__

/******************************************************************************/
/*                      HI3630 asp_cfg                         */
/******************************************************************************/
#define HI3630_CFG_R_RST_CTRLEN_REG        (0x0)
#define HI3630_CFG_R_RST_CTRLDIS_REG       (0x4)
#define HI3630_CFG_R_RST_CTRLSTAT_REG      (0x8)
#define HI3630_CFG_R_GATE_EN_REG           (0xC)
#define HI3630_CFG_R_GATE_DIS_REG          (0x10)
#define HI3630_CFG_R_GATE_CLKEN_REG        (0x14)
#define HI3630_CFG_R_GATE_CLKSTAT_REG      (0x18)
#define HI3630_CFG_R_GATE_CLKDIV_EN_REG    (0x1C)
#define HI3630_CFG_R_CLK1_DIV_REG          (0x20)
#define HI3630_CFG_R_CLK2_DIV_REG          (0x24)
#define HI3630_CFG_R_CLK3_DIV_REG          (0x28)
#define HI3630_CFG_R_CLK4_DIV_REG          (0x2C)
#define HI3630_CFG_R_CLK5_DIV_REG          (0x30)
#define HI3630_CFG_R_CLK6_DIV_REG          (0x34)
#define HI3630_CFG_R_CLK_SEL_REG           (0x38)
#define HI3630_CFG_R_DSP_NMI_REG           (0x3C)
#define HI3630_CFG_R_DSP_PRID_REG          (0x40)
#define HI3630_CFG_R_DSP_RUNSTALL_REG      (0x44)
#define HI3630_CFG_R_DSP_STATVECTORSEL_REG  (0x48)
#define HI3630_CFG_R_DSP_OCDHALTONRESET_REG  (0x4C)
#define HI3630_CFG_R_DSP_STATUS_REG     	(0x50)
#define HI3630_CFG_R_DMAC_SEL_REG          (0x54)
#define HI3630_CFG_R_BUS_PRIORITY_REG      (0x58)
#define HI3630_CFG_R_CG_EN_REG             (0x5C)
#define HI3630_CFG_R_OCRAM_RET_REG         (0x60)
//#define HI3630_CFG_R_DLOCK_BP_REG          (0x64)
#define HI3630_CFG_R_INTR_NS_INI_REG       (0x64)
#define HI3630_CFG_R_INTR_NS_EN_REG        (0x68)
#define HI3630_CFG_R_INTR_NS_MASK_REG      (0x6c)
#define HI3630_CFG_R_DBG_SET_AHB2AXI_REG   (0x70)
#define HI3630_CFG_R_DBG_STATUS_AHB2AXI_REG (0x74)
#define HI3630_CFG_R_DLOCK_BP_REG          (0x78)
#define HI3630_CFG_R_TZ_SECURE_N_REG       (0x100)
#define HI3630_CFG_R_OCRAM_R0SIZE_REG      (0x104)
#define HI3630_CFG_R_SIO_LOOP_SECURE_N_REG (0x108)
#define HI3630_CFG_R_INTR_S_INI_REG        (0x10C)
#define HI3630_CFG_R_INTR_S_EN_REG         (0x110)
#define HI3630_CFG_R_INTR_S_MASK_REG       (0x114)
#define HI3630_CFG_R_DSP_REMAPPING_EN_REG  (0x118)
#define HI3630_CFG_R_DSP_REMAPPING_REG     (0x11c)
#define HI3630_CFG_R_SLIMBUS_ID            (0x01b8)
#define HI3630_CFG_R_SLIM_DAT_FMT_CFG      (0x1bc)
#define HI3630_CFG_R_SLIM_DAT_CHNL_CFG     (0x1c0)
//******************************************************************************
//REG FIELD
//******************************************************************************
#define ASP_CFG_R_GATE_EN_GT_SLIMBUSHCLK_BIT         16
#define ASP_CFG_R_GATE_EN_GT_SLIMBUS_BASE_CLK_BIT    17
#define ASP_CFG_R_GT_SIOBCLK_DIV_BIT                 2 
#define ASP_CFG_DAT_FMT_CFG_0                        1
#define ASP_CFG_DMAC_HCLK1_CG_EN                     11
#define ASP_CFG_DMAC_HCLK1_CG_EN_WRITE_EN            26
#define ASP_CFG_DMAC_HCLK0_CG_EN                     10
#define ASP_CFG_DMAC_HCLK0_CG_EN_WRITE_EN            25
#define ASP_CFG_SLIM_DAT_CHNL_CFG_EN_BIT                 0

#define ASP_CFG_RST_TIMER1_N_LEN    1
#define ASP_CFG_RST_TIMER1_N_OFFSET 18
#define ASP_CFG_RST_TIMER0_N_LEN    1
#define ASP_CFG_RST_TIMER0_N_OFFSET 17
#define ASP_CFG_RST_GPIO_N_LEN    1
#define ASP_CFG_RST_GPIO_N_OFFSET 16
#define ASP_CFG_RST_ASP_H2X_N_LEN    1
#define ASP_CFG_RST_ASP_H2X_N_OFFSET 15
#define ASP_CFG_RST_SLIMBUS_N_LEN    1
#define ASP_CFG_RST_SLIMBUS_N_OFFSET 14
#define ASP_CFG_RST_SLIMBUS_BASE_N_LEN    1
#define ASP_CFG_RST_SLIMBUS_BASE_N_OFFSET 13
#define ASP_CFG_RST_WATCHDOG_N_LEN    1
#define ASP_CFG_RST_WATCHDOG_N_OFFSET 12
#define ASP_CFG_RST_OCRAM_N_LEN    1
#define ASP_CFG_RST_OCRAM_N_OFFSET 11
#define ASP_CFG_RST_SRC_DOWN_N_LEN    1
#define ASP_CFG_RST_SRC_DOWN_N_OFFSET 10
#define ASP_CFG_RST_SRC_UP_N_LEN    1
#define ASP_CFG_RST_SRC_UP_N_OFFSET 9
#define ASP_CFG_RST_DMAC_N_LEN    1
#define ASP_CFG_RST_DMAC_N_OFFSET 8
#define ASP_CFG_RST_ASP_HDMI_N_LEN    1
#define ASP_CFG_RST_ASP_HDMI_N_OFFSET 7
#define ASP_CFG_RST_IPC_N_LEN    1
#define ASP_CFG_RST_IPC_N_OFFSET 6
#define ASP_CFG_RST_DSP_DEBUG_N_LEN    1
#define ASP_CFG_RST_DSP_DEBUG_N_OFFSET 5
#define ASP_CFG_RST_DSP_N_LEN    1
#define ASP_CFG_RST_DSP_N_OFFSET 4
#define ASP_CFG_RST_SIO_MODEM_N_LEN    1
#define ASP_CFG_RST_SIO_MODEM_N_OFFSET 3
#define ASP_CFG_RST_SIO_BT_N_LEN    1
#define ASP_CFG_RST_SIO_BT_N_OFFSET 2
#define ASP_CFG_RST_SIO_VOICE_N_LEN    1
#define ASP_CFG_RST_SIO_VOICE_N_OFFSET 1
#define ASP_CFG_RST_SIO_AUDIO_N_LEN    1
#define ASP_CFG_RST_SIO_AUDIO_N_OFFSET 0

#define ASP_CFG_RST_TIMER1_N_LEN    1
#define ASP_CFG_RST_TIMER1_N_OFFSET 18
#define ASP_CFG_RST_TIMER0_N_LEN    1
#define ASP_CFG_RST_TIMER0_N_OFFSET 17
#define ASP_CFG_RST_GPIO_N_LEN    1
#define ASP_CFG_RST_GPIO_N_OFFSET 16
#define ASP_CFG_RST_ASP_H2X_N_LEN    1
#define ASP_CFG_RST_ASP_H2X_N_OFFSET 15
#define ASP_CFG_RST_SLIMBUS_N_LEN    1
#define ASP_CFG_RST_SLIMBUS_N_OFFSET 14
#define ASP_CFG_RST_SLIMBUS_BASE_N_LEN    1
#define ASP_CFG_RST_SLIMBUS_BASE_N_OFFSET 13
#define ASP_CFG_RST_WATCHDOG_N_LEN    1
#define ASP_CFG_RST_WATCHDOG_N_OFFSET 12
#define ASP_CFG_RST_OCRAM_N_LEN    1
#define ASP_CFG_RST_OCRAM_N_OFFSET 11
#define ASP_CFG_RST_SRC_DOWM_N_LEN    1
#define ASP_CFG_RST_SRC_DOWM_N_OFFSET 10
#define ASP_CFG_RST_SRC_UP_N_LEN    1
#define ASP_CFG_RST_SRC_UP_N_OFFSET 9
#define ASP_CFG_RST_DMAC_N_LEN    1
#define ASP_CFG_RST_DMAC_N_OFFSET 8
#define ASP_CFG_RST_ASP_HDMI_N_LEN    1
#define ASP_CFG_RST_ASP_HDMI_N_OFFSET 7
#define ASP_CFG_RST_IPC_N_LEN    1
#define ASP_CFG_RST_IPC_N_OFFSET 6
#define ASP_CFG_RST_DSP_DEBUG_N_LEN    1
#define ASP_CFG_RST_DSP_DEBUG_N_OFFSET 5
#define ASP_CFG_RST_DSP_N_LEN    1
#define ASP_CFG_RST_DSP_N_OFFSET 4
#define ASP_CFG_RST_SIO_MODEM_LEN    1
#define ASP_CFG_RST_SIO_MODEM_OFFSET 3
#define ASP_CFG_RST_SIO_BT_LEN    1
#define ASP_CFG_RST_SIO_BT_OFFSET 2
#define ASP_CFG_RST_SIO_VOICE_LEN    1
#define ASP_CFG_RST_SIO_VOICE_OFFSET 1
#define ASP_CFG_RST_SIO_AUDIO_LEN    1
#define ASP_CFG_RST_SIO_AUDIO_OFFSET 0

#define ASP_CFG_RST_TIMER1_N_LEN    1
#define ASP_CFG_RST_TIMER1_N_OFFSET 18
#define ASP_CFG_RST_TIMER0_N_LEN    1
#define ASP_CFG_RST_TIMER0_N_OFFSET 17
#define ASP_CFG_RST_GPIO_N_LEN    1
#define ASP_CFG_RST_GPIO_N_OFFSET 16
#define ASP_CFG_RST_ASP_H2X_N_LEN    1
#define ASP_CFG_RST_ASP_H2X_N_OFFSET 15
#define ASP_CFG_RST_SLIMBUS_N_LEN    1
#define ASP_CFG_RST_SLIMBUS_N_OFFSET 14
#define ASP_CFG_RST_SLIMBUS_BASE_N_LEN    1
#define ASP_CFG_RST_SLIMBUS_BASE_N_OFFSET 13
#define ASP_CFG_RST_WATCHDOG_N_LEN    1
#define ASP_CFG_RST_WATCHDOG_N_OFFSET 12
#define ASP_CFG_RST_OCRAM_N_LEN    1
#define ASP_CFG_RST_OCRAM_N_OFFSET 11
#define ASP_CFG_RST_SRC_DOWM_N_LEN    1
#define ASP_CFG_RST_SRC_DOWM_N_OFFSET 10
#define ASP_CFG_RST_SRC_UP_N_LEN    1
#define ASP_CFG_RST_SRC_UP_N_OFFSET 9
#define ASP_CFG_RST_DMAC_N_LEN    1
#define ASP_CFG_RST_DMAC_N_OFFSET 8
#define ASP_CFG_RST_ASP_HDMI_N_LEN    1
#define ASP_CFG_RST_ASP_HDMI_N_OFFSET 7
#define ASP_CFG_RST_IPC_N_LEN    1
#define ASP_CFG_RST_IPC_N_OFFSET 6
#define ASP_CFG_RST_DSP_DEBUG_N_LEN    1
#define ASP_CFG_RST_DSP_DEBUG_N_OFFSET 5
#define ASP_CFG_RST_DSP_N_LEN    1
#define ASP_CFG_RST_DSP_N_OFFSET 4
#define ASP_CFG_RST_SIO_MODEM_LEN    1
#define ASP_CFG_RST_SIO_MODEM_OFFSET 3
#define ASP_CFG_RST_SIO_BT_LEN    1
#define ASP_CFG_RST_SIO_BT_OFFSET 2
#define ASP_CFG_RST_SIO_VOICE_LEN    1
#define ASP_CFG_RST_SIO_VOICE_OFFSET 1
#define ASP_CFG_RST_SIO_AUDIO_LEN    1
#define ASP_CFG_RST_SIO_AUDIO_OFFSET 0

#define ASP_CFG_GT_TIMER1HCLK_LEN    1
#define ASP_CFG_GT_TIMER1HCLK_OFFSET 23
#define ASP_CFG_GT_TIMER0HCLK_LEN    1
#define ASP_CFG_GT_TIMER0HCLK_OFFSET 22
#define ASP_CFG_GT_GPIOHCLK_LEN    1
#define ASP_CFG_GT_GPIOHCLK_OFFSET 21
#define ASP_CFG_GT_HDMIBCLK_LEN    1
#define ASP_CFG_GT_HDMIBCLK_OFFSET 20
#define ASP_CFG_GT_SPDIFCLK_LEN    1
#define ASP_CFG_GT_SPDIFCLK_OFFSET 19
#define ASP_CFG_GT_HDMIMCLK_LEN    1
#define ASP_CFG_GT_HDMIMCLK_OFFSET 18
#define ASP_CFG_GT_SLIMBUS_BASE_CLK_LEN    1
#define ASP_CFG_GT_SLIMBUS_BASE_CLK_OFFSET 17
#define ASP_CFG_GT_SLIMBUSHCLK_LEN    1
#define ASP_CFG_GT_SLIMBUSHCLK_OFFSET 16
#define ASP_CFG_GT_WDHCLK_LEN    1
#define ASP_CFG_GT_WDHCLK_OFFSET 15
#define ASP_CFG_GT_OCRAMHCLK_LEN    1
#define ASP_CFG_GT_OCRAMHCLK_OFFSET 14
#define ASP_CFG_GT_SRCDOWNHCLK_LEN    1
#define ASP_CFG_GT_SRCDOWNHCLK_OFFSET 13
#define ASP_CFG_GT_SRCUPHCLK_LEN    1
#define ASP_CFG_GT_SRCUPHCLK_OFFSET 12
#define ASP_CFG_GT_DMACHCLK_LEN    1
#define ASP_CFG_GT_DMACHCLK_OFFSET 11
#define ASP_CFG_GT_HDMIHCLK_LEN    1
#define ASP_CFG_GT_HDMIHCLK_OFFSET 10
#define ASP_CFG_GT_IPCHCLK_LEN    1
#define ASP_CFG_GT_IPCHCLK_OFFSET 9
#define ASP_CFG_GT_SIOMODEM_LEN    1
#define ASP_CFG_GT_SIOMODEM_OFFSET 8
#define ASP_CFG_GT_MODEMBCLK_OUT_LEN    1
#define ASP_CFG_GT_MODEMBCLK_OUT_OFFSET 7
#define ASP_CFG_GT_SIOBT_LEN    1
#define ASP_CFG_GT_SIOBT_OFFSET 6
#define ASP_CFG_GT_BTBCLK_OUT_LEN    1
#define ASP_CFG_GT_BTBCLK_OUT_OFFSET 5
#define ASP_CFG_GT_SIOVOICE_LEN    1
#define ASP_CFG_GT_SIOVOICE_OFFSET 4
#define ASP_CFG_GT_VOICEBCLK_OUT_LEN    1
#define ASP_CFG_GT_VOICEBCLK_OUT_OFFSET 3
#define ASP_CFG_GT_SIOAUDIO_LEN    1
#define ASP_CFG_GT_SIOAUDIO_OFFSET 2
#define ASP_CFG_GT_AUDIOBCLK_OUT_LEN    1
#define ASP_CFG_GT_AUDIOBCLK_OUT_OFFSET 1
#define ASP_CFG_GT_HIFIDSPCLK_LEN    1
#define ASP_CFG_GT_HIFIDSPCLK_OFFSET 0

#define ASP_CFG_GT_TIMER1HCLK_LEN    1
#define ASP_CFG_GT_TIMER1HCLK_OFFSET 23
#define ASP_CFG_GT_TIMER0HCLK_LEN    1
#define ASP_CFG_GT_TIMER0HCLK_OFFSET 22
#define ASP_CFG_GT_GPIOHCLK_LEN    1
#define ASP_CFG_GT_GPIOHCLK_OFFSET 21
#define ASP_CFG_GT_HDMIBCLK_LEN    1
#define ASP_CFG_GT_HDMIBCLK_OFFSET 20
#define ASP_CFG_GT_SPDIFCLK_LEN    1
#define ASP_CFG_GT_SPDIFCLK_OFFSET 19
#define ASP_CFG_GT_HDMIMCLK_LEN    1
#define ASP_CFG_GT_HDMIMCLK_OFFSET 18
#define ASP_CFG_GT_SLIMBUS_BASE_CLK_LEN    1
#define ASP_CFG_GT_SLIMBUS_BASE_CLK_OFFSET 17
#define ASP_CFG_GT_SLIMBUSHCLK_LEN    1
#define ASP_CFG_GT_SLIMBUSHCLK_OFFSET 16
#define ASP_CFG_GT_WDHCLK_LEN    1
#define ASP_CFG_GT_WDHCLK_OFFSET 15
#define ASP_CFG_GT_OCRAMHCLK_LEN    1
#define ASP_CFG_GT_OCRAMHCLK_OFFSET 14
#define ASP_CFG_GT_SRCDOWNHCLK_LEN    1
#define ASP_CFG_GT_SRCDOWNHCLK_OFFSET 13
#define ASP_CFG_GT_SRCUPHCLK_LEN    1
#define ASP_CFG_GT_SRCUPHCLK_OFFSET 12
#define ASP_CFG_GT_DMACHCLK_LEN    1
#define ASP_CFG_GT_DMACHCLK_OFFSET 11
#define ASP_CFG_GT_HDMIHCLK_LEN    1
#define ASP_CFG_GT_HDMIHCLK_OFFSET 10
#define ASP_CFG_GT_IPCHCLK_LEN    1
#define ASP_CFG_GT_IPCHCLK_OFFSET 9
#define ASP_CFG_GT_SIOMODEM_LEN    1
#define ASP_CFG_GT_SIOMODEM_OFFSET 8
#define ASP_CFG_GT_MODEMBCLK_OUT_LEN    1
#define ASP_CFG_GT_MODEMBCLK_OUT_OFFSET 7
#define ASP_CFG_GT_SIOBT_LEN    1
#define ASP_CFG_GT_SIOBT_OFFSET 6
#define ASP_CFG_GT_BTBCLK_OUT_LEN    1
#define ASP_CFG_GT_BTBCLK_OUT_OFFSET 5
#define ASP_CFG_GT_SIOVOICE_LEN    1
#define ASP_CFG_GT_SIOVOICE_OFFSET 4
#define ASP_CFG_GT_VOICEBCLK_OUT_LEN    1
#define ASP_CFG_GT_VOICEBCLK_OUT_OFFSET 3
#define ASP_CFG_GT_SIOAUDIO_LEN    1
#define ASP_CFG_GT_SIOAUDIO_OFFSET 2
#define ASP_CFG_GT_AUDIOBCLK_OUT_LEN    1
#define ASP_CFG_GT_AUDIOBCLK_OUT_OFFSET 1
#define ASP_CFG_GT_HIFIDSPCLK_LEN    1
#define ASP_CFG_GT_HIFIDSPCLK_OFFSET 0

#define ASP_CFG_GT_TIMER1HCLK_LEN    1
#define ASP_CFG_GT_TIMER1HCLK_OFFSET 23
#define ASP_CFG_GT_TIMER0HCLK_LEN    1
#define ASP_CFG_GT_TIMER0HCLK_OFFSET 22
#define ASP_CFG_GT_GPIOHCLK_LEN    1
#define ASP_CFG_GT_GPIOHCLK_OFFSET 21
#define ASP_CFG_GT_HDMIBCLK_LEN    1
#define ASP_CFG_GT_HDMIBCLK_OFFSET 20
#define ASP_CFG_GT_SPDIFCLK_LEN    1
#define ASP_CFG_GT_SPDIFCLK_OFFSET 19
#define ASP_CFG_GT_HDMIMCLK_LEN    1
#define ASP_CFG_GT_HDMIMCLK_OFFSET 18
#define ASP_CFG_GT_SLIMBUS_BASE_CLK_LEN    1
#define ASP_CFG_GT_SLIMBUS_BASE_CLK_OFFSET 17
#define ASP_CFG_GT_SLIMBUSHCLK_LEN    1
#define ASP_CFG_GT_SLIMBUSHCLK_OFFSET 16
#define ASP_CFG_GT_WDHCLK_LEN    1
#define ASP_CFG_GT_WDHCLK_OFFSET 15
#define ASP_CFG_GT_OCRAMHCLK_LEN    1
#define ASP_CFG_GT_OCRAMHCLK_OFFSET 14
#define ASP_CFG_GT_SRCDOWNHCLK_LEN    1
#define ASP_CFG_GT_SRCDOWNHCLK_OFFSET 13
#define ASP_CFG_GT_SRCUPHCLK_LEN    1
#define ASP_CFG_GT_SRCUPHCLK_OFFSET 12
#define ASP_CFG_GT_DMACHCLK_LEN    1
#define ASP_CFG_GT_DMACHCLK_OFFSET 11
#define ASP_CFG_GT_HDMIHCLK_LEN    1
#define ASP_CFG_GT_HDMIHCLK_OFFSET 10
#define ASP_CFG_GT_IPCHCLK_LEN    1
#define ASP_CFG_GT_IPCHCLK_OFFSET 9
#define ASP_CFG_GT_SIOMODEM_LEN    1
#define ASP_CFG_GT_SIOMODEM_OFFSET 8
#define ASP_CFG_GT_MODEMBCLK_OUT_LEN    1
#define ASP_CFG_GT_MODEMBCLK_OUT_OFFSET 7
#define ASP_CFG_GT_SIOBT_LEN    1
#define ASP_CFG_GT_SIOBT_OFFSET 6
#define ASP_CFG_GT_BTBCLK_OUT_LEN    1
#define ASP_CFG_GT_BTBCLK_OUT_OFFSET 5
#define ASP_CFG_GT_SIOVOICE_LEN    1
#define ASP_CFG_GT_SIOVOICE_OFFSET 4
#define ASP_CFG_GT_VOICEBCLK_OUT_LEN    1
#define ASP_CFG_GT_VOICEBCLK_OUT_OFFSET 3
#define ASP_CFG_GT_SIOAUDIO_LEN    1
#define ASP_CFG_GT_SIOAUDIO_OFFSET 2
#define ASP_CFG_GT_AUDIOBCLK_OUT_LEN    1
#define ASP_CFG_GT_AUDIOBCLK_OUT_OFFSET 1
#define ASP_CFG_GT_HIFIDSPCLK_LEN    1
#define ASP_CFG_GT_HIFIDSPCLK_OFFSET 0

#define ASP_CFG_ST_TIMER1HCLK_LEN    1
#define ASP_CFG_ST_TIMER1HCLK_OFFSET 29
#define ASP_CFG_ST_TIMER0HCLK_LEN    1
#define ASP_CFG_ST_TIMER0HCLK_OFFSET 28
#define ASP_CFG_ST_GPIOHCLK_LEN    1
#define ASP_CFG_ST_GPIOHCLK_OFFSET 27
#define ASP_CFG_ST_MODEMHCLK_LEN    1
#define ASP_CFG_ST_MODEMHCLK_OFFSET 26
#define ASP_CFG_ST_BTHCLK_LEN    1
#define ASP_CFG_ST_BTHCLK_OFFSET 25
#define ASP_CFG_ST_VOICEHCLK_LEN    1
#define ASP_CFG_ST_VOICEHCLK_OFFSET 24
#define ASP_CFG_ST_AUDIOHCLK_LEN    1
#define ASP_CFG_ST_AUDIOHCLK_OFFSET 23
#define ASP_CFG_ST_ASP_H2X_LEN    1
#define ASP_CFG_ST_ASP_H2X_OFFSET 22
#define ASP_CFG_ST_HDMIREF_LEN    1
#define ASP_CFG_ST_HDMIREF_OFFSET 21
#define ASP_CFG_ST_SPDIFCLK_LEN    1
#define ASP_CFG_ST_SPDIFCLK_OFFSET 20
#define ASP_CFG_ST_HDMIMCLK_LEN    1
#define ASP_CFG_ST_HDMIMCLK_OFFSET 19
#define ASP_CFG_ST_SLIMBUS_BASE_CLK_LEN    1
#define ASP_CFG_ST_SLIMBUS_BASE_CLK_OFFSET 18
#define ASP_CFG_ST_SLIMBUSHCLK_LEN    1
#define ASP_CFG_ST_SLIMBUSHCLK_OFFSET 17
#define ASP_CFG_ST_WDHCLK_LEN    1
#define ASP_CFG_ST_WDHCLK_OFFSET 16
#define ASP_CFG_ST_OCRAMHCLK_LEN    1
#define ASP_CFG_ST_OCRAMHCLK_OFFSET 15
#define ASP_CFG_ST_SRCDOWNHCLK_LEN    1
#define ASP_CFG_ST_SRCDOWNHCLK_OFFSET 14
#define ASP_CFG_ST_SRCUPHCLK_LEN    1
#define ASP_CFG_ST_SRCUPHCLK_OFFSET 13
#define ASP_CFG_ST_DMACHCLK1_LEN    1
#define ASP_CFG_ST_DMACHCLK1_OFFSET 12
#define ASP_CFG_ST_DMACHCLK0_LEN    1
#define ASP_CFG_ST_DMACHCLK0_OFFSET 11
#define ASP_CFG_ST_HDMIHCLK_LEN    1
#define ASP_CFG_ST_HDMIHCLK_OFFSET 10
#define ASP_CFG_ST_IPCHCLK_LEN    1
#define ASP_CFG_ST_IPCHCLK_OFFSET 9
#define ASP_CFG_ST_MODEMBCLK_LEN    1
#define ASP_CFG_ST_MODEMBCLK_OFFSET 8
#define ASP_CFG_ST_MODEMBCLK_OUT_LEN    1
#define ASP_CFG_ST_MODEMBCLK_OUT_OFFSET 7
#define ASP_CFG_ST_BTBCLK_LEN    1
#define ASP_CFG_ST_BTBCLK_OFFSET 6
#define ASP_CFG_ST_BTBCLK_OUT_LEN    1
#define ASP_CFG_ST_BTBCLK_OUT_OFFSET 5
#define ASP_CFG_ST_VOICEBCLK_LEN    1
#define ASP_CFG_ST_VOICEBCLK_OFFSET 4
#define ASP_CFG_ST_VOICEBCLK_OUT_LEN    1
#define ASP_CFG_ST_VOICEBCLK_OUT_OFFSET 3
#define ASP_CFG_ST_AUDIOBCLK_LEN    1
#define ASP_CFG_ST_AUDIOBCLK_OFFSET 2
#define ASP_CFG_ST_AUDIOBCLK_OUT_LEN    1
#define ASP_CFG_ST_AUDIOBCLK_OUT_OFFSET 1
#define ASP_CFG_ST_HIFIDSPCLK_LEN    1
#define ASP_CFG_ST_HIFIDSPCLK_OFFSET 0

#define ASP_CFG_GT_SIO_MODEM_BCLK_DIV_LEN    1
#define ASP_CFG_GT_SIO_MODEM_BCLK_DIV_OFFSET 6
#define ASP_CFG_GT_SIO_BT_BCLK_DIV_LEN    1
#define ASP_CFG_GT_SIO_BT_BCLK_DIV_OFFSET 5
#define ASP_CFG_GT_SIO_VOICE_BCLK_DIV_LEN    1
#define ASP_CFG_GT_SIO_VOICE_BCLK_DIV_OFFSET 4
#define ASP_CFG_GT_SIO_AUDIO_BCLK_DIV_LEN    1
#define ASP_CFG_GT_SIO_AUDIO_BCLK_DIV_OFFSET 3
#define ASP_CFG_GT_SIOBCLK_DIV_LEN    1
#define ASP_CFG_GT_SIOBCLK_DIV_OFFSET 2
#define ASP_CFG_GT_HDMIREF_DIV_LEN    1
#define ASP_CFG_GT_HDMIREF_DIV_OFFSET 1
#define ASP_CFG_GT_HDMIMCLK_DIV_LEN    1
#define ASP_CFG_GT_HDMIMCLK_DIV_OFFSET 0

#define ASP_CFG_DIV_SIOBCLK_LEN    27
#define ASP_CFG_DIV_SIOBCLK_OFFSET 0
#define ASP_CFG_DIV_HDMIMCLK_LEN    27
#define ASP_CFG_DIV_HDMIMCLK_OFFSET 0
#define ASP_CFG_WRITE_EN_LEN    16
#define ASP_CFG_WRITE_EN_OFFSET 16
#define ASP_CFG_DIV_SIO_VOICE_BCLK_LEN    8
#define ASP_CFG_DIV_SIO_VOICE_BCLK_OFFSET 8
#define ASP_CFG_DIV_SIO_AUDIO_BCLK_LEN    8
#define ASP_CFG_DIV_SIO_AUDIO_BCLK_OFFSET 0
#define ASP_CFG_WRITE_EN_LEN    16
#define ASP_CFG_WRITE_EN_OFFSET 16
#define ASP_CFG_DIV_SIO_MODEM_BCLK_LEN    8
#define ASP_CFG_DIV_SIO_MODEM_BCLK_OFFSET 8
#define ASP_CFG_DIV_SIO_BT_BCLK_LEN    8
#define ASP_CFG_DIV_SIO_BT_BCLK_OFFSET 0
#define ASP_CFG_WRITE_EN_LEN    16
#define ASP_CFG_WRITE_EN_OFFSET 16
#define ASP_CFG_DIV_SIO_VOICE_ADWS_LEN    8
#define ASP_CFG_DIV_SIO_VOICE_ADWS_OFFSET 8
#define ASP_CFG_DIV_SIO_AUDIO_ADWS_LEN    8
#define ASP_CFG_DIV_SIO_AUDIO_ADWS_OFFSET 0
#define ASP_CFG_WRITE_EN_LEN    16
#define ASP_CFG_WRITE_EN_OFFSET 16
#define ASP_CFG_DIV_SIO_MODEM_ADWS_LEN    8
#define ASP_CFG_DIV_SIO_MODEM_ADWS_OFFSET 8
#define ASP_CFG_DIV_SIO_BT_ADWS_LEN    8
#define ASP_CFG_DIV_SIO_BT_ADWS_OFFSET 0
#define ASP_CFG_WRITE_EN_LEN    16
#define ASP_CFG_WRITE_EN_OFFSET 16
#define ASP_CFG_HIFI_SLEEP_MODE_LEN    1
#define ASP_CFG_HIFI_SLEEP_MODE_OFFSET 13
#define ASP_CFG_HIFI_PLL_CTRL_LEN    1
#define ASP_CFG_HIFI_PLL_CTRL_OFFSET 12
#define ASP_CFG_TIMER1_2_CLKEN_SEL_LEN    1
#define ASP_CFG_TIMER1_2_CLKEN_SEL_OFFSET 11
#define ASP_CFG_TIMER1_1_CLKEN_SEL_LEN    1
#define ASP_CFG_TIMER1_1_CLKEN_SEL_OFFSET 10
#define ASP_CFG_TIMER0_2_CLKEN_SEL_LEN    1
#define ASP_CFG_TIMER0_2_CLKEN_SEL_OFFSET 9
#define ASP_CFG_TIMER0_1_CLKEN_SEL_LEN    1
#define ASP_CFG_TIMER0_1_CLKEN_SEL_OFFSET 8
#define ASP_CFG_WATCHDOG_CLKEN_SEL_LEN    1
#define ASP_CFG_WATCHDOG_CLKEN_SEL_OFFSET 7
#define ASP_CFG_SLIMBUS_BASE_CLK_SEL_LEN    2
#define ASP_CFG_SLIMBUS_BASE_CLK_SEL_OFFSET 5
#define ASP_CFG_SIOBCLK_SEL_LEN    1
#define ASP_CFG_SIOBCLK_SEL_OFFSET 4
#define ASP_CFG_SIO_MODEM_SLAVE_EN_LEN    1
#define ASP_CFG_SIO_MODEM_SLAVE_EN_OFFSET 3
#define ASP_CFG_SIO_BT_SLAVE_EN_LEN    1
#define ASP_CFG_SIO_BT_SLAVE_EN_OFFSET 2
#define ASP_CFG_SIO_VOICE_SLAVE_EN_LEN    1
#define ASP_CFG_SIO_VOICE_SLAVE_EN_OFFSET 1
#define ASP_CFG_SIO_AUDIO_SLAVE_EN_LEN    1
#define ASP_CFG_SIO_AUDIO_SLAVE_EN_OFFSET 0

#define ASP_CFG_R_DSP_NMI_LEN    16
#define ASP_CFG_R_DSP_NMI_OFFSET 0
#define ASP_CFG_DSP_PRID_LEN    16
#define ASP_CFG_DSP_PRID_OFFSET 0
#define ASP_CFG_DSP_RUNSTALL_LEN    1
#define ASP_CFG_DSP_RUNSTALL_OFFSET 0
#define ASP_CFG_DSP_STATVECTORSEL_LEN    1
#define ASP_CFG_DSP_STATVECTORSEL_OFFSET 0
#define ASP_CFG_DSP_OCDHALTONRESET_LEN    1
#define ASP_CFG_DSP_OCDHALTONRESET_OFFSET 0
#define ASP_CFG_DSP_ADDR_REMAPPING_CFG_LEN    32
#define ASP_CFG_DSP_ADDR_REMAPPING_CFG_OFFSET 0
#define ASP_CFG_WRITE_EN_LEN    16
#define ASP_CFG_WRITE_EN_OFFSET 16
#define ASP_CFG_SRC_DOWN_DMAC_SEL_LEN    2
#define ASP_CFG_SRC_DOWN_DMAC_SEL_OFFSET 8
#define ASP_CFG_SRC_UP_DMAC_SEL_LEN    1
#define ASP_CFG_SRC_UP_DMAC_SEL_OFFSET 7
#define ASP_CFG_SLIMBUS3_DMAC_SEL_LEN    1
#define ASP_CFG_SLIMBUS3_DMAC_SEL_OFFSET 6
#define ASP_CFG_SLIMBUS2_DMAC_SEL_LEN    1
#define ASP_CFG_SLIMBUS2_DMAC_SEL_OFFSET 5
#define ASP_CFG_SLIMBUS1_DMAC_SEL_LEN    1
#define ASP_CFG_SLIMBUS1_DMAC_SEL_OFFSET 4
#define ASP_CFG_SLIMBUS0_DMAC_SEL_LEN    1
#define ASP_CFG_SLIMBUS0_DMAC_SEL_OFFSET 3
#define ASP_CFG_SIO_BT_DMAC_SEL_LEN    1
#define ASP_CFG_SIO_BT_DMAC_SEL_OFFSET 2
#define ASP_CFG_SIO_VOICE_DMAC_SEL_LEN    1
#define ASP_CFG_SIO_VOICE_DMAC_SEL_OFFSET 1
#define ASP_CFG_SRC_AUDIO_DMAC_SEL_LEN    1
#define ASP_CFG_SRC_AUDIO_DMAC_SEL_OFFSET 0
#define ASP_CFG_X2H_PRIORITY_LEN    2
#define ASP_CFG_X2H_PRIORITY_OFFSET 26
#define ASP_CFG_OCRAM_PRIORITY_LEN    2
#define ASP_CFG_OCRAM_PRIORITY_OFFSET 24
#define ASP_CFG_DSP_SLV_PRIORITY_LEN    2
#define ASP_CFG_DSP_SLV_PRIORITY_OFFSET 22
#define ASP_CFG_ASP_MST_PRIORITY_LEN    2
#define ASP_CFG_ASP_MST_PRIORITY_OFFSET 20
#define ASP_CFG_AHB2AXI_PRIORITY_LEN    2
#define ASP_CFG_AHB2AXI_PRIORITY_OFFSET 18
#define ASP_CFG_DMAC_PRIORITY_LEN    2
#define ASP_CFG_DMAC_PRIORITY_OFFSET 16
#define ASP_CFG_DSP_MST_PRIORITY_LEN    2
#define ASP_CFG_DSP_MST_PRIORITY_OFFSET 14
#define ASP_CFG_ASP_SLV_PRIORITY_LEN    2
#define ASP_CFG_ASP_SLV_PRIORITY_OFFSET 12
#define ASP_CFG_AHB2AXI_AW_QOS_LEN    2
#define ASP_CFG_AHB2AXI_AW_QOS_OFFSET 10
#define ASP_CFG_AHB2AXI_AR_QOS_LEN    2
#define ASP_CFG_AHB2AXI_AR_QOS_OFFSET 8
#define ASP_CFG_DMA_AW_QOS_LEN    2
#define ASP_CFG_DMA_AW_QOS_OFFSET 6
#define ASP_CFG_DMA_AR_QOS_LEN    2
#define ASP_CFG_DMA_AR_QOS_OFFSET 4
#define ASP_CFG_DSP_AW_QOS_LEN    2
#define ASP_CFG_DSP_AW_QOS_OFFSET 2
#define ASP_CFG_DSP_AR_QOS_LEN    2
#define ASP_CFG_DSP_AR_QOS_OFFSET 0
#define ASP_CFG_DMAC_HCLK1_CG_EN_LEN    1
#define ASP_CFG_DMAC_HCLK1_CG_EN_OFFSET 11
#define ASP_CFG_DMAC_HCLK0_CG_EN_LEN    1
#define ASP_CFG_DMAC_HCLK0_CG_EN_OFFSET 10
#define ASP_CFG_SLIMBUS_HCLK_CG_EN_LEN    1
#define ASP_CFG_SLIMBUS_HCLK_CG_EN_OFFSET 9
#define ASP_CFG_DW_AXI_M1_CG_EN_LEN    1
#define ASP_CFG_DW_AXI_M1_CG_EN_OFFSET 8
#define ASP_CFG_DW_AXI_M2_CG_EN_LEN    1
#define ASP_CFG_DW_AXI_M2_CG_EN_OFFSET 7
#define ASP_CFG_DW_AXI_M3_CG_EN_LEN    1
#define ASP_CFG_DW_AXI_M3_CG_EN_OFFSET 6
#define ASP_CFG_DW_AXI_M4_CG_EN_LEN    1
#define ASP_CFG_DW_AXI_M4_CG_EN_OFFSET 5
#define ASP_CFG_DW_AXI_S1_CG_EN_LEN    1
#define ASP_CFG_DW_AXI_S1_CG_EN_OFFSET 4
#define ASP_CFG_DW_AXI_S2_CG_EN_LEN    1
#define ASP_CFG_DW_AXI_S2_CG_EN_OFFSET 3
#define ASP_CFG_DW_AXI_S3_CG_EN_LEN    1
#define ASP_CFG_DW_AXI_S3_CG_EN_OFFSET 2
#define ASP_CFG_DW_AXI_S4_CG_EN_LEN    1
#define ASP_CFG_DW_AXI_S4_CG_EN_OFFSET 1
#define ASP_CFG_DW_AXI_S0_CG_EN_LEN    1
#define ASP_CFG_DW_AXI_S0_CG_EN_OFFSET 0
#define ASP_CFG_WRITE_EN_LEN    16
#define ASP_CFG_WRITE_EN_OFFSET 16
#define ASP_CFG_OCRAM_PGEN_LEN    4
#define ASP_CFG_OCRAM_PGEN_OFFSET 8
#define ASP_CFG_OCRAM_RET2N_LEN    4
#define ASP_CFG_OCRAM_RET2N_OFFSET 4
#define ASP_CFG_OCRAM_RET1N_LEN    4
#define ASP_CFG_OCRAM_RET1N_OFFSET 0
#define ASP_CFG_WRITE_EN_LEN    16
#define ASP_CFG_WRITE_EN_OFFSET 16
#define ASP_CFG_DLOCK_BP_TIMER1_LEN    1
#define ASP_CFG_DLOCK_BP_TIMER1_OFFSET 15
#define ASP_CFG_DLOCK_BP_TIMER0_LEN    1
#define ASP_CFG_DLOCK_BP_TIMER0_OFFSET 14
#define ASP_CFG_DLOCK_BP_GPIO_LEN    1
#define ASP_CFG_DLOCK_BP_GPIO_OFFSET 13
#define ASP_CFG_DLOCK_BP_CFG_LEN    1
#define ASP_CFG_DLOCK_BP_CFG_OFFSET 12
#define ASP_CFG_DLOCK_BP_WATCHDOG_LEN    1
#define ASP_CFG_DLOCK_BP_WATCHDOG_OFFSET 11
#define ASP_CFG_DLOCK_BP_IPC_LEN    1
#define ASP_CFG_DLOCK_BP_IPC_OFFSET 10
#define ASP_CFG_DLOCK_BP_EDMAC_LEN    1
#define ASP_CFG_DLOCK_BP_EDMAC_OFFSET 9
#define ASP_CFG_DLOCK_BP_SLIMBUS_LEN    1
#define ASP_CFG_DLOCK_BP_SLIMBUS_OFFSET 8
#define ASP_CFG_DLOCK_BP_SIOMODEM_LEN    1
#define ASP_CFG_DLOCK_BP_SIOMODEM_OFFSET 7
#define ASP_CFG_DLOCK_BP_SIOBT_LEN    1
#define ASP_CFG_DLOCK_BP_SIOBT_OFFSET 6
#define ASP_CFG_DLOCK_BP_SIOVOICE_LEN    1
#define ASP_CFG_DLOCK_BP_SIOVOICE_OFFSET 5
#define ASP_CFG_DLOCK_BP_SIOAUDIO_LEN    1
#define ASP_CFG_DLOCK_BP_SIOAUDIO_OFFSET 4
#define ASP_CFG_DLOCK_BP_ASPHDMI_LEN    1
#define ASP_CFG_DLOCK_BP_ASPHDMI_OFFSET 3
#define ASP_CFG_DLOCK_BP_H2P_LEN    1
#define ASP_CFG_DLOCK_BP_H2P_OFFSET 2
#define ASP_CFG_DLOCK_BP_SRCDOWN_LEN    1
#define ASP_CFG_DLOCK_BP_SRCDOWN_OFFSET 1
#define ASP_CFG_DLOCK_BP_SRCUP_LEN    1
#define ASP_CFG_DLOCK_BP_SRCUP_OFFSET 0
#define ASP_CFG_SLIMBUS_INTR_LEN    1
#define ASP_CFG_SLIMBUS_INTR_OFFSET 3
#define ASP_CFG_SRC_DOWN_INTR_LEN    1
#define ASP_CFG_SRC_DOWN_INTR_OFFSET 2
#define ASP_CFG_SRC_UP_INTR_LEN    1
#define ASP_CFG_SRC_UP_INTR_OFFSET 1
#define ASP_CFG_ASP_HDMI_INT_LEN    1
#define ASP_CFG_ASP_HDMI_INT_OFFSET 0
#define ASP_CFG_SLIMBUS_INTR_EN_LEN    1
#define ASP_CFG_SLIMBUS_INTR_EN_OFFSET 3
#define ASP_CFG_SRC_DOWN_INTR_EN_LEN    1
#define ASP_CFG_SRC_DOWN_INTR_EN_OFFSET 2
#define ASP_CFG_SRC_UP_INTR_EN_LEN    1
#define ASP_CFG_SRC_UP_INTR_EN_OFFSET 1
#define ASP_CFG_ASP_HDMI_INT_EN_LEN    1
#define ASP_CFG_ASP_HDMI_INT_EN_OFFSET 0
#define ASP_CFG_SLIMBUS_INTR_MASK_LEN    1
#define ASP_CFG_SLIMBUS_INTR_MASK_OFFSET 3
#define ASP_CFG_SRC_DOWN_INTR_MASK_LEN    1
#define ASP_CFG_SRC_DOWN_INTR_MASK_OFFSET 2
#define ASP_CFG_SRC_UP_INTR_MASK_LEN    1
#define ASP_CFG_SRC_UP_INTR_MASK_OFFSET 1
#define ASP_CFG_ASP_HDMI_INT_MASK_LEN    1
#define ASP_CFG_ASP_HDMI_INT_MASK_OFFSET 0
#define ASP_CFG_DBG_STAT_CLR_LEN    1
#define ASP_CFG_DBG_STAT_CLR_OFFSET 26
#define ASP_CFG_DBG_H2X_SEL_LEN    1
#define ASP_CFG_DBG_H2X_SEL_OFFSET 25
#define ASP_CFG_DBG_INCR_SPEN_LEN    1
#define ASP_CFG_DBG_INCR_SPEN_OFFSET 24
#define ASP_CFG_DBG_PORT_SEL_LEN    4
#define ASP_CFG_DBG_PORT_SEL_OFFSET 20
#define ASP_CFG_DBG_WR_OUTSTD_LEN    4
#define ASP_CFG_DBG_WR_OUTSTD_OFFSET 16
#define ASP_CFG_DBG_RD_OUTSTD_LEN    4
#define ASP_CFG_DBG_RD_OUTSTD_OFFSET 12
#define ASP_CFG_DBG_WFQ_WEIGHT_PORT0_LEN    4
#define ASP_CFG_DBG_WFQ_WEIGHT_PORT0_OFFSET 8
#define ASP_CFG_DBG_WFQ_WEIGHT_PORT1_LEN    4
#define ASP_CFG_DBG_WFQ_WEIGHT_PORT1_OFFSET 4
#define ASP_CFG_DBG_WFQ_WEIGHT_PORT2_LEN    4
#define ASP_CFG_DBG_WFQ_WEIGHT_PORT2_OFFSET 0
#define ASP_CFG_DBG_STATUS_LEN    32
#define ASP_CFG_DBG_STATUS_OFFSET 0
#define ASP_CFG_DSP_MST_SECURE_N_LEN    1
#define ASP_CFG_DSP_MST_SECURE_N_OFFSET 15
#define ASP_CFG_TZ_SECURE_TIMER1_N_LEN    1
#define ASP_CFG_TZ_SECURE_TIMER1_N_OFFSET 14
#define ASP_CFG_TZ_SECURE_TIMER0_N_LEN    1
#define ASP_CFG_TZ_SECURE_TIMER0_N_OFFSET 13
#define ASP_CFG_TZ_SECURE_GPIO_N_LEN    1
#define ASP_CFG_TZ_SECURE_GPIO_N_OFFSET 12
#define ASP_CFG_TZ_SECURE_DSP_N_LEN    1
#define ASP_CFG_TZ_SECURE_DSP_N_OFFSET 11
#define ASP_CFG_TZ_SECURE_WATCHDOG_N_LEN    1
#define ASP_CFG_TZ_SECURE_WATCHDOG_N_OFFSET 10
#define ASP_CFG_TZ_SECURE_IPC_N_LEN    1
#define ASP_CFG_TZ_SECURE_IPC_N_OFFSET 9
#define ASP_CFG_TZ_SECURE_EDAMC_N_LEN    1
#define ASP_CFG_TZ_SECURE_EDAMC_N_OFFSET 8
#define ASP_CFG_TZ_SECURE_SLIMBUS_N_LEN    1
#define ASP_CFG_TZ_SECURE_SLIMBUS_N_OFFSET 7
#define ASP_CFG_TZ_SECURE_SIOMODEM_N_LEN    1
#define ASP_CFG_TZ_SECURE_SIOMODEM_N_OFFSET 6
#define ASP_CFG_TZ_SECURE_SIOBT_N_LEN    1
#define ASP_CFG_TZ_SECURE_SIOBT_N_OFFSET 5
#define ASP_CFG_TZ_SECURE_SIOVOICE_N_LEN    1
#define ASP_CFG_TZ_SECURE_SIOVOICE_N_OFFSET 4
#define ASP_CFG_TZ_SECURE_SIOAUDIO_N_LEN    1
#define ASP_CFG_TZ_SECURE_SIOAUDIO_N_OFFSET 3
#define ASP_CFG_TZ_SECURE_ASPHDMI_N_LEN    1
#define ASP_CFG_TZ_SECURE_ASPHDMI_N_OFFSET 2
#define ASP_CFG_TZ_SECURE_SRCDOWN_N_LEN    1
#define ASP_CFG_TZ_SECURE_SRCDOWN_N_OFFSET 1
#define ASP_CFG_TZ_SECURE_SRCUP_N_LEN    1
#define ASP_CFG_TZ_SECURE_SRCUP_N_OFFSET 0
#define ASP_CFG_OCRAM_R0SIZE_LEN    10
#define ASP_CFG_OCRAM_R0SIZE_OFFSET 0
#define ASP_CFG_SIO_MODEM_LOOP_SECURE_N_LEN    1
#define ASP_CFG_SIO_MODEM_LOOP_SECURE_N_OFFSET 3
#define ASP_CFG_SIO_BT_LOOP_SECURE_N_LEN    1
#define ASP_CFG_SIO_BT_LOOP_SECURE_N_OFFSET 2
#define ASP_CFG_SIO_VOICE_LOOP_SECURE_N_LEN    1
#define ASP_CFG_SIO_VOICE_LOOP_SECURE_N_OFFSET 1
#define ASP_CFG_SIO_AUDIO_LOOP_SECURE_N_LEN    1
#define ASP_CFG_SIO_AUDIO_LOOP_SECURE_N_OFFSET 0
#define ASP_CFG_SRC_DOWN_INTR_SECURE_LEN    1
#define ASP_CFG_SRC_DOWN_INTR_SECURE_OFFSET 2
#define ASP_CFG_SRC_UP_INTR_SECURE_LEN    1
#define ASP_CFG_SRC_UP_INTR_SECURE_OFFSET 1
#define ASP_CFG_ASP_HDMI_INT_SECURE_LEN    1
#define ASP_CFG_ASP_HDMI_INT_SECURE_OFFSET 0
#define ASP_CFG_SRC_DOWN_INTR_SECURE_EN_LEN    1
#define ASP_CFG_SRC_DOWN_INTR_SECURE_EN_OFFSET 2
#define ASP_CFG_SRC_UP_INTR_SECURE_EN_LEN    1
#define ASP_CFG_SRC_UP_INTR_SECURE_EN_OFFSET 1
#define ASP_CFG_ASP_HDMI_INT_SECURE_EN_LEN    1
#define ASP_CFG_ASP_HDMI_INT_SECURE_EN_OFFSET 0
#define ASP_CFG_SRC_DOWN_INTR_SECURE_MASK_LEN    1
#define ASP_CFG_SRC_DOWN_INTR_SECURE_MASK_OFFSET 2
#define ASP_CFG_SRC_UP_INTR_SECURE_MASK_LEN    1
#define ASP_CFG_SRC_UP_INTR_SECURE_MASK_OFFSET 1
#define ASP_CFG_ASP_HDMI_INT_SECURE_MASK_LEN    1
#define ASP_CFG_ASP_HDMI_INT_SECURE_MASK_OFFSET 0
#define ASP_CFG_DSP_ADDR_REMAPPING_EN_LEN    32
#define ASP_CFG_DSP_ADDR_REMAPPING_EN_OFFSET 0


#define BASE_ADDR_SIO_AUDIO                   0xe804e800
#define BASE_ADDR_SIO_VOICE                   0xE804EC00

#define HI3630_SIO_I2S_LEFT_XD_REG            0x4C
#define HI3630_SIO_I2S_RIGHT_XD_REG           0x50
#define HI3630_SIO_I2S_LEFT_RD_REG            0x54
#define HI3630_SIO_I2S_RIGHT_RD_REG           0x58

#define HI3630_SIO_I2S_RX_CHN_REG               0xa0
#define HI3630_SIO_I2S_TX_CHN_REG               0xc0

#define HI3630_SRCUP_SIO_FIXED_ADDR \
			(BASE_ADDR_SIO_AUDIO + HI3630_SIO_I2S_TX_CHN_REG)
#define HI3630_SRCDOWN_SIO_FIXED_ADDR \
			(BASE_ADDR_SIO_VOICE + HI3630_SIO_I2S_TX_CHN_REG)

#define SRCUP_BASE_ADDR			(0xe8054000 - 0xe804e000)
#define SRCUP_EN_REG			(SRCUP_BASE_ADDR + 0x98)
#define SRCUP_LEFT_FIX_ADDR_REG		(SRCUP_BASE_ADDR + 0x8c)
#define SRCUP_RIGHT_FIX_ADDR_REG	(SRCUP_BASE_ADDR + 0x90)

#define SRCUP_ENABLE		1
#define SRCUP_DISABLE		0

#define SRCDOWN_BASE_ADDR		(0xe8051000 - 0xe804e000)
#define SRCDOWN_EN_REG			(SRCDOWN_BASE_ADDR + 0x60)
#define SRCDOWN_LEFT_FIX_ADDR_REG	(SRCDOWN_BASE_ADDR + 0x54)
#define SRCDOWN_RIGHT_FIX_ADDR_REG	(SRCDOWN_BASE_ADDR + 0x58)

#define SRCDOWN_ENABLE		1
#define SRCDOWN_DISABLE		0

#define RST_ASP_H2X_BIT		(1 << ASP_CFG_RST_ASP_H2X_N_OFFSET)
#define RST_SIO_AUDIO_BIT	(1 << ASP_CFG_RST_SIO_AUDIO_N_OFFSET)
#define RST_SIO_VOICE_BIT	(1 << ASP_CFG_RST_SIO_VOICE_N_OFFSET)
#define RST_SIO_BT_BIT		(1 << ASP_CFG_RST_SIO_BT_N_OFFSET)
#define RST_SIO_MODEM_BIT	(1 << ASP_CFG_RST_SIO_MODEM_N_OFFSET)
#define RST_ASP_HDMI_BIT	(1 << ASP_CFG_RST_ASP_HDMI_N_OFFSET)
#define RST_SRCUP_BIT		(1 << ASP_CFG_RST_SRC_UP_N_OFFSET)
#define RST_SRCDOWN_BIT		(1 << ASP_CFG_RST_SRC_DOWN_N_OFFSET)
#define RST_DMAC_BIT		(1 << ASP_CFG_RST_DMAC_N_OFFSET)
#define RST_SLIMBUS_BIT     (1 << ASP_CFG_RST_SLIMBUS_N_OFFSET)
#define RST_SLIMBUS_BASE_BIT  (1 << ASP_CFG_RST_SLIMBUS_BASE_N_OFFSET)

#define ASP_CFG_SIO_AUDIO_BIT 		(1 << ASP_CFG_SIO_AUDIO_SLAVE_EN_OFFSET)
#define ASP_CFG_SIO_AUDIO_SLAVE_BIT 	(ASP_CFG_SIO_AUDIO_BIT << 16 | ASP_CFG_SIO_AUDIO_BIT)
#define ASP_CFG_SIO_AUDIO_MASTER_BIT 	(ASP_CFG_SIO_AUDIO_BIT << 16)

#define ASP_CFG_SIO_VOICE_BIT 		(1 << ASP_CFG_SIO_VOICE_SLAVE_EN_OFFSET)
#define ASP_CFG_SIO_VOICE_SLAVE_BIT 	(ASP_CFG_SIO_VOICE_BIT << 16 | ASP_CFG_SIO_VOICE_BIT)
#define ASP_CFG_SIO_VOICE_MASTER_BIT 	(ASP_CFG_SIO_VOICE_BIT << 16)

#define ASP_CFG_SIO_BT_BIT 		(1 << ASP_CFG_SIO_BT_SLAVE_EN_OFFSET)
#define ASP_CFG_SIO_BT_SLAVE_BIT 	(ASP_CFG_SIO_BT_BIT << 16 | ASP_CFG_SIO_BT_BIT)
#define ASP_CFG_SIO_BT_MASTER_BIT 	(ASP_CFG_SIO_BT_BIT << 16)

#define ASP_CFG_SIO_MODEM_BIT 		(1 << ASP_CFG_SIO_MODEM_SLAVE_EN_OFFSET)
#define ASP_CFG_SIO_MODEM_SLAVE_BIT 	(ASP_CFG_SIO_MODEM_BIT << 16 | ASP_CFG_SIO_MODEM_BIT)
#define ASP_CFG_SIO_MODEM_MASTER_BIT 	(ASP_CFG_SIO_MODEM_BIT << 16)

#define ASP_CFG_SIOBCLK_SEL_BIT		(1 << ASP_CFG_SIOBCLK_SEL_OFFSET)
#define ASP_CFG_SIOBCLK_360M_BIT	(ASP_CFG_SIOBCLK_SEL_BIT << 16 | ASP_CFG_SIOBCLK_SEL_BIT)

#define CLK_SIO_AUDIO_BIT 		(1 << ASP_CFG_GT_SIOAUDIO_OFFSET)
#define CLK_SIO_AUDIO_BCLK_BIT 		(1 << ASP_CFG_GT_AUDIOBCLK_OUT_OFFSET)

#define CLK_SIO_VOICE_BIT 		(1 << ASP_CFG_GT_SIOVOICE_OFFSET)
#define CLK_SIO_VOICE_BCLK_BIT 		(1 << ASP_CFG_GT_VOICEBCLK_OUT_OFFSET)

#define CLK_SIO_BT_BIT 			(1 << ASP_CFG_GT_SIOBT_OFFSET)
#define CLK_SIO_BT_BCLK_BIT 		(1 << ASP_CFG_GT_BTBCLK_OUT_OFFSET)

#define CLK_SIO_MODEM_BIT 		(1 << ASP_CFG_GT_SIOMODEM_OFFSET)
#define CLK_SIO_MODEM_BCLK_BIT  	(1 << ASP_CFG_GT_MODEMBCLK_OUT_OFFSET)

#define CLK_DMAC_HCLK_BIT  		(1 << ASP_CFG_GT_DMACHCLK_OFFSET)
#define CLK_SRCUP_HCLK_BIT  		(1 << ASP_CFG_GT_SRCUPHCLK_OFFSET)
#define CLK_SRCDOWN_HCLK_BIT  		(1 << ASP_CFG_GT_SRCDOWNHCLK_OFFSET)

#define CLK_HDMI_HCLK_BIT  		(1 << ASP_CFG_GT_HDMIHCLK_OFFSET)
#define CLK_HDMI_MCLK_BIT  		(1 << ASP_CFG_GT_HDMIMCLK_OFFSET)
#define CLK_HDMI_BCLK_BIT  		(1 << ASP_CFG_GT_HDMIBCLK_OFFSET)
#define CLK_SLIMBUSH_BIT            (1 << ASP_CFG_GT_SLIMBUSHCLK_OFFSET)
#define CLK_SLIMBUS_BASE_BIT        (1 << ASP_CFG_GT_SLIMBUS_BASE_CLK_OFFSET)

/* 24.576 M*/
#define FRAC_DIV_VALUE		0x8BCF65
#define AUDIO_DIV_WRITE_EN	0x00FF0000
#define VOICE_DIV_WRITE_EN	0xFF000000
#define BT_DIV_WRITE_EN 	0x00FF0000
#define MODEM_DIV_WRITE_EN 	0xFF000000

/*
 * AUDIO CLOCK
 *
 * BCLK 3.072M --DIV = 0x7
 * FS 48K --DIV = 0x3f
 *
 * BCLK 6.144M --DIV = 0x3
 * FS 96K --DIV = 0x3f
*/
#define AUDIO_BCLK_DIV_VALUE 	(AUDIO_DIV_WRITE_EN | 0x7 << ASP_CFG_DIV_SIO_AUDIO_BCLK_OFFSET)
#define AUDIO_FS_DIV_VALUE 	(AUDIO_DIV_WRITE_EN | 0x3f << ASP_CFG_DIV_SIO_AUDIO_ADWS_OFFSET)

/*
 * VOICE CLOCK I2S 16bit
 *
 * BCLK 1.024M --DIV = 0x17
 * FS 16K --DIV = 0x3f
 *
 * BCLK 2.048M --DIV = 0xb
 * FS 32K --DIV = 0x3f
 *
 * VOICE CLOCK PCM 16bit
 *
 * BCLK 0.512M --DIV = 0x2f
 * FS 32K --DIV = 0xf
*/
#define VOICE_BCLK_DIV_VALUE	(VOICE_DIV_WRITE_EN | 0xb << ASP_CFG_DIV_SIO_VOICE_BCLK_OFFSET)
#define VOICE_FS_DIV_VALUE	(VOICE_DIV_WRITE_EN | 0x3f << ASP_CFG_DIV_SIO_VOICE_ADWS_OFFSET)

/*
 * BT CLOCK
 *
 * BCLK 1.024M --DIV = 0x17
 * FS 16K --DIV = 0x3f
 *
 * BCLK 2.048M --DIV = 0xb
 * FS 32K --DIV = 0x3f
*/
#define BT_BCLK_DIV_VALUE	(BT_DIV_WRITE_EN | 0xb << ASP_CFG_DIV_SIO_BT_BCLK_OFFSET)
#define BT_FS_DIV_VALUE 	(BT_DIV_WRITE_EN | 0x3f << ASP_CFG_DIV_SIO_BT_ADWS_OFFSET)

/*
 * MODEM CLOCK
 *
 * BCLK 1.024M --DIV = 0x17
 * FS 16K --DIV = 0x3f
 *
 * BCLK 2.048M --DIV = 0xb
 * FS 32K --DIV = 0x3f
*/
#define MODEM_BCLK_DIV_VALUE 	(MODEM_DIV_WRITE_EN | 0xb << ASP_CFG_DIV_SIO_MODEM_BCLK_OFFSET)
#define MODEM_FS_DIV_VALUE 	(MODEM_DIV_WRITE_EN | 0x3f << ASP_CFG_DIV_SIO_MODEM_ADWS_OFFSET)

#endif