ccflags-y += -Idrivers/media/huawei/camera/sensor
ccflags-y += -Idrivers/media/huawei/camera
ccflags-y += -Idrivers/media/huawei/camera/csi
ccflags-y += -Idrivers/media/huawei/camera/platform

obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX214) += imx214.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX214) += imx219.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_OV8856) += ov8856.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_OV13850) += ov13850.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_HI843) += hi843.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_T4KA3) += t4ka3.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_AR1335) += ar1335.o
