# hisilicon ivp

obj-$(CONFIG_IVP_SMMU)      += ivp_smmu.o
obj-$(CONFIG_IVP_SMMU_TEST) += ivp_smmu_test.o
obj-$(CONFIG_HISI_IVP) += ivp_ipc.o
obj-$(CONFIG_HISI_IVP) += ivp_core.o
obj-$(CONFIG_HISI_IVP) += ivp_mntn.o
