##############################################
#     Make file of S5K4E1GA_SUNNY camera sensor
##############################################

#EXTRA_CFLAGS += -fno-pic
ccflags-$(CONFIG_HI6210_CAMERA_S5K4E1GA_SUNNY) += -DS5K4E1GA_USE_OTP
obj-$(CONFIG_HI6210_CAMERA_S5K4E1GA_SUNNY) += s5k4e1ga_sunny.o
#################### END #####################
