##############################################
#     Make file of OV8830 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hi6620/capture/ov8830/
EXTRA_CFLAGS += -fno-pic 
obj-$(CONFIG_HI6620_CAMERA_OV8830) += ov8830.o
#obj-m += ov8830.o

#################### END #####################
