#
# Makefile for hisilicon camera vcm driver
#
EXTRA_CFLAGS += -Idrivers/media/huawei/camera/sensor/vcm
EXTRA_CFLAGS += -Idrivers/media/huawei/camera/
EXTRA_CFLAGS += -Idrivers/media/huawei/cci/
EXTRA_CFLAGS += -fno-pic

obj-y += hwvcm.o
obj-y += dw9714.o
obj-y += ad5816.o
obj-y += ad5823.o
