#include "mach/clock.h"
#include "mach/clock_map_oem.h"
#include "mach/clock_info_oem.h"

/**********************************************************************************************************
#define MICRO_CLK(_clk, _clkname, _state, _rate, _min_rate, _max_rate, _parent, \
		  _friends, _sel_parents, _enable_reg, _enable_bit, _clksel_reg, _clksel_mask, \
		  _clksel_set_valid, _clkdiv_reg, _clkdiv_mask, _clkdiv_set_valid) \
static struct clk _clk = { \
	.name = _clkname, \
	.refcnt = 0, \
	.state = _state, \
	.rate = _rate, \
	.min_rate = _min_rate, \
	.max_rate = _max_rate, \
	.parent = &_parent, \
	.friends = &_friends, \
	.ops = &clk_ops, \
	.sel_parents = _sel_parents, \
	.enable_reg = (void __iomem	*)_enable_reg, \
	.enable_bit = _enable_bit, \
	.clksel_reg = (void __iomem	*)_clksel_reg, \
	.clksel_mask = _clksel_mask, \
	.clksel_set_valid = _clksel_set_valid, \
	.clkdiv_reg = (void __iomem	*)_clkdiv_reg, \
	.clkdiv_mask = _clkdiv_mask, \
	.clkdiv_set_valid = _clkdiv_set_valid, \
	.set = false, \
};
**********************************************************************************************************/

/* system clocks */
MACRO_CLK(clkin_sys, CLKIN_SYS, ON, CLKIN_SYS_RATE, CLKIN_SYS_MIN_RATE, CLKIN_SYS_MAX_RATE, NULL, NULL, NULL, NULL, 0, NULL, 0, -1, NULL, 0, -1)
MACRO_CLK(clk_ref, CLK_REF, ON, CLK_REF_RATE, CLK_REF_MIN_RATE, CLK_REF_MAX_RATE, NULL, NULL, NULL, NULL, 0, NULL, 0, -1, NULL, 0, -1)
MACRO_CLK(clk_ref32k, CLK_REF32K, ON, CLK_REF32K_RATE, CLK_REF32K_MIN_RATE, CLK_REF32K_MAX_RATE, NULL, NULL, NULL, NULL, 0, NULL, 0, -1, NULL, 0, -1)
MACRO_CLK(clk_dsppll, CLK_DSPPLL, ON, CLK_DSPPLL_RATE, CLK_DSPPLL_MIN_RATE, CLK_DSPPLL_MAX_RATE, NULL, NULL, NULL, NULL, 0, NULL, 0, -1, NULL, 0, -1)
PLL_CLK(clk_gpll0, CLK_GPLL0, OFF, CLK_GPLL0_RATE, CLK_GPLL0_MIN_RATE, CLK_GPLL0_MAX_RATE, CLK_GPLL0_ENABLE_REG_ADDR, CLK_GPLL0_ENABLE_BIT_OFFSET)
PLL_CLK(clk_gpll1, CLK_GPLL1, OFF, CLK_GPLL1_RATE, CLK_GPLL1_MIN_RATE, CLK_GPLL1_MAX_RATE, NULL, NULL)
PLL_CLK(clk_peripll, CLK_PERIPLL, OFF, CLK_PERIPLL_RATE, CLK_PERIPLL_MIN_RATE, CLK_PERIPLL_MAX_RATE, NULL, 0)
PLL_CLK(clk_hdmipll, CLK_HDMIPLL, OFF, CLK_HDMIPLL_RATE, CLK_HDMIPLL_MIN_RATE, CLK_HDMIPLL_MAX_RATE, CLK_HDMIPLL_ENABLE_REG_ADDR, CLK_HDMIPLL_ENABLE_BIT_OFFSET)
MACRO_CLK(clk_ddrpll, CLK_DDRPLL, ON, CLK_DDRPLL_RATE, CLK_DDRPLL_MIN_RATE, CLK_DDRPLL_MAX_RATE, NULL, NULL, NULL, NULL, 0, NULL, 0, -1, NULL, 0, -1)
MACRO_CLK(clk_300m_src, CLK_300M_SRC, ON, CLK_300M_SRC_RATE, CLK_300M_SRC_MIN_RATE, CLK_300M_SRC_MAX_RATE, &clk_dsppll, NULL, NULL, NULL, 0, NULL, 0, -1, NULL, 0, -1)
MACRO_CLK(clk_100m_src, CLK_100M_SRC, ON, CLK_100M_SRC_RATE, CLK_100M_SRC_MIN_RATE, CLK_100M_SRC_MAX_RATE, &clk_300m_src, NULL, NULL, NULL, 0, NULL, 0, -1, NULL, 0, -1)
MACRO_CLK(clk_bus_src, CLK_BUS_SRC, ON, CLK_BUS_SRC_RATE, CLK_BUS_SRC_MIN_RATE, CLK_BUS_SRC_MAX_RATE, &clk_300m_src, NULL, NULL, NULL, 0, NULL, 0, -1, NULL, 0, -1)

/* PMU clocks */
PMU_CLK(clk_pmu32kb, CLK_PMU32KB, OFF, CLK_PMU32KB_RATE, CLK_PMU32KB_MIN_RATE, CLK_PMU32KB_MAX_RATE, CLK_PMU32KB_ENABLE_REG_ADDR, CLK_PMU32KB_ENABLE_BIT_OFFSET)
PMU_CLK(clk_pmu32kc, CLK_PMU32KC, OFF, CLK_PMU32KC_RATE, CLK_PMU32KC_MIN_RATE, CLK_PMU32KC_MAX_RATE, CLK_PMU32KC_ENABLE_REG_ADDR, CLK_PMU32KC_ENABLE_BIT_OFFSET)

/* 27M & 90K */
struct clksel clksels_27m_gated[] = {
	{.sel_parent = &clk_hdmipll, .sel_val = 0,
	.parent_min = CLK_HDMIPLL_RATE/CLK_27M_GATED_DIV_MAX, .parent_max = CLK_DSPPLL_RATE},
	{.sel_parent = &clk_peripll, .sel_val = 1,
	.parent_min = CLK_PERIPLL_RATE/CLK_27M_GATED_DIV_MAX, .parent_max = CLK_PERIPLL_RATE},
	{.sel_parent = NULL},
};	
MACRO_CLK(clk_27m_gated, CLK_27M_GATED, OFF, CLK_27M_GATED_RATE,CLK_27M_GATED_MIN_RATE, CLK_27M_GATED_MAX_RATE, &clk_hdmipll, NULL, \
		clksels_27m_gated, CLK_27M_GATED_ENABLE_REG_ADDR, CLK_27M_GATED_ENABLE_BIT_OFFSET, CLK_27M_GATED_CLKSEL_REG_ADDR, CLK_27M_GATED_CLKSEL_MASK, \
		CLK_27M_GATED_CLKSEL_SET_VALID, NULL, 0, -1)

MACRO_CLK(clk_27m, CLK_27M, OFF, CLK_27M_RATE, CLK_27M_MIN_RATE, CLK_27M_MAX_RATE, &clk_27m_gated, NULL, \
		NULL, CLK_27M_ENABLE_REG_ADDR, CLK_27M_ENABLE_BIT_OFFSET, NULL, 0, -1, CLK_27M_CLKDIV_REG_ADDR, CLK_27M_CLKDIV_MASK, CLK_27M_CLKDIV_SET_VALID)
MACRO_CLK(clk_90k, CLK_90K, OFF, CLK_90K_RATE, CLK_90K_MIN_RATE, CLK_90K_MAX_RATE, &clk_27m, NULL, \
		NULL, CLK_90K_ENABLE_REG_ADDR, CLK_90K_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
		
/* todo delete */
MACRO_CLK(clk_axi_video_bus, CLK_AXI_VIDEO_BUS, OFF, CLK_AXI_VIDEO_BUS_RATE, CLK_AXI_VIDEO_BUS_MIN_RATE, CLK_AXI_VIDEO_BUS_MAX_RATE, NULL, NULL, NULL, NULL, 0, NULL, 0, -1, NULL, 0, -1)
MACRO_CLK(clk_axi_img_bus, CLK_AXI_IMG_BUS, OFF, CLK_AXI_IMG_BUS_RATE, CLK_AXI_IMG_BUS_MIN_RATE, CLK_AXI_IMG_BUS_MAX_RATE, NULL, NULL,	NULL, NULL, 0, NULL, 0, -1, NULL, 0, -1)

/* edc0 module */
MACRO_CLK(clk_dsppll_edc0_core_gated, CLK_DSPPLL_EDC0_CORE_GATED, OFF, CLK_DSPPLL_EDC0_CORE_GATED_RATE, CLK_DSPPLL_EDC0_CORE_GATED_MIN_RATE, CLK_DSPPLL_EDC0_CORE_GATED_MAX_RATE, &clk_dsppll, NULL, \
		NULL, CLK_DSPPLL_EDC0_CORE_GATED_ENABLE_REG_ADDR, CLK_DSPPLL_EDC0_CORE_GATED_ENABLE_BIT_OFFSET, CLK_DSPPLL_EDC0_CORE_GATED_CLKSEL_REG_ADDR, CLK_DSPPLL_EDC0_CORE_GATED_CLKSEL_MASK, \
		CLK_DSPPLL_EDC0_CORE_GATED_CLKSEL_SET_VALID, CLK_DSPPLL_EDC0_CORE_GATED_CLKDIV_REG_ADDR, CLK_DSPPLL_EDC0_CORE_GATED_CLKDIV_MASK, CLK_DSPPLL_EDC0_CORE_GATED_CLKDIV_SET_VALID)

MACRO_CLK(clk_edc0_core, CLK_EDC0_CORE, OFF, CLK_EDC0_CORE_RATE, CLK_EDC0_CORE_MIN_RATE, CLK_EDC0_CORE_MAX_RATE, &clk_dsppll_edc0_core_gated, NULL, \
		NULL, CLK_EDC0_CORE_ENABLE_REG_ADDR, CLK_EDC0_CORE_ENABLE_BIT_OFFSET, CLK_EDC0_CORE_CLKSEL_REG_ADDR, CLK_EDC0_CORE_CLKSEL_MASK, \
		CLK_EDC0_CORE_CLKSEL_SET_VALID, CLK_EDC0_CORE_CLKDIV_REG_ADDR, CLK_EDC0_CORE_CLKDIV_MASK, CLK_EDC0_CORE_CLKDIV_SET_VALID)

struct clksel clksels_mux_edc0_pix_gated[] = {
	{.sel_parent = &clk_dsppll, .sel_val = 0,
	.parent_min = CLK_DSPPLL_RATE/CLK_MUX_EDC0_PIX_GATED_DIV_MAX, .parent_max = CLK_DSPPLL_RATE},
	{.sel_parent = &clk_peripll, .sel_val = 1,
	.parent_min = CLK_PERIPLL_RATE/CLK_MUX_EDC0_PIX_GATED_DIV_MAX, .parent_max = CLK_PERIPLL_RATE},
	{.sel_parent = NULL},
};	
MACRO_CLK(clk_mux_edc0_pix_gated, CLK_MUX_EDC0_PIX_GATED, OFF, CLK_MUX_EDC0_PIX_GATED_RATE, CLK_MUX_EDC0_PIX_GATED_MIN_RATE, CLK_MUX_EDC0_PIX_GATED_MAX_RATE, &clk_dsppll, NULL, \
		clksels_mux_edc0_pix_gated, CLK_MUX_EDC0_PIX_GATED_ENABLE_REG_ADDR, CLK_MUX_EDC0_PIX_GATED_ENABLE_BIT_OFFSET, CLK_MUX_EDC0_PIX_GATED_CLKSEL_REG_ADDR, CLK_MUX_EDC0_PIX_GATED_CLKSEL_MASK, \
		CLK_MUX_EDC0_PIX_GATED_CLKSEL_SET_VALID, CLK_MUX_EDC0_PIX_GATED_CLKDIV_REG_ADDR, CLK_MUX_EDC0_PIX_GATED_CLKDIV_MASK, CLK_MUX_EDC0_PIX_GATED_CLKDIV_SET_VALID)

MACRO_CLK(clk_edc0_pix_ldi, CLK_EDC0_PIX_LDI, OFF, CLK_EDC0_PIX_LDI_RATE, CLK_EDC0_PIX_LDI_MIN_RATE, CLK_EDC0_PIX_LDI_MAX_RATE, &clk_mux_edc0_pix_gated, NULL, \
		NULL, CLK_EDC0_PIX_LDI_ENABLE_REG_ADDR, CLK_EDC0_PIX_LDI_ENABLE_BIT_OFFSET, CLK_EDC0_PIX_LDI_CLKSEL_REG_ADDR, CLK_EDC0_PIX_LDI_CLKSEL_MASK, \
		CLK_EDC0_PIX_LDI_CLKSEL_SET_VALID, CLK_EDC0_PIX_LDI_CLKDIV_REG_ADDR, CLK_EDC0_PIX_LDI_CLKDIV_MASK, CLK_EDC0_PIX_LDI_CLKDIV_SET_VALID)
		
MACRO_CLK(clk_aclk_edc0, CLK_ACLK_EDC0, OFF, CLK_ACLK_EDC0_RATE, CLK_ACLK_EDC0_MIN_RATE, CLK_ACLK_EDC0_MAX_RATE, NULL, NULL, \
		NULL, CLK_ACLK_EDC0_ENABLE_REG_ADDR, CLK_ACLK_EDC0_ENABLE_BIT_OFFSET, CLK_ACLK_EDC0_CLKSEL_REG_ADDR, CLK_ACLK_EDC0_CLKSEL_MASK, \
		CLK_ACLK_EDC0_CLKSEL_SET_VALID, CLK_ACLK_EDC0_CLKDIV_REG_ADDR, CLK_ACLK_EDC0_CLKDIV_MASK, CLK_ACLK_EDC0_CLKDIV_SET_VALID)
		
MACRO_CLK(clk_edc0_cfg_clk, CLK_EDC0_CFG_CLK, OFF, CLK_EDC0_CFG_CLK_RATE, CLK_EDC0_CFG_CLK_MIN_RATE, CLK_EDC0_CFG_CLK_MAX_RATE, NULL, NULL, \
		NULL, CLK_EDC0_CFG_CLK_ENABLE_REG_ADDR, CLK_EDC0_CFG_CLK_ENABLE_BIT_OFFSET, CLK_EDC0_CFG_CLK_CLKSEL_REG_ADDR, CLK_EDC0_CFG_CLK_CLKSEL_MASK, \
		CLK_EDC0_CFG_CLK_CLKSEL_SET_VALID, CLK_EDC0_CFG_CLK_CLKDIV_REG_ADDR, CLK_EDC0_CFG_CLK_CLKDIV_MASK, CLK_EDC0_CFG_CLK_CLKDIV_SET_VALID)

MACRO_CLK(clk_dsio_cfg_clk, CLK_DSIO_CFG_CLK, OFF, CLK_DSIO_CFG_CLK_RATE, CLK_DSIO_CFG_CLK_MIN_RATE, CLK_DSIO_CFG_CLK_MAX_RATE, NULL, NULL, \
		NULL, CLK_DSIO_CFG_CLK_ENABLE_REG_ADDR, CLK_DSIO_CFG_CLK_ENABLE_BIT_OFFSET, CLK_DSIO_CFG_CLK_CLKSEL_REG_ADDR, CLK_DSIO_CFG_CLK_CLKSEL_MASK, \
		CLK_DSIO_CFG_CLK_CLKSEL_SET_VALID, CLK_DSIO_CFG_CLK_CLKDIV_REG_ADDR, CLK_DSIO_CFG_CLK_CLKDIV_MASK, CLK_DSIO_CFG_CLK_CLKDIV_SET_VALID)

/* edc1 */
MACRO_CLK(clk_edc1_core, CLK_EDC1_CORE, OFF, CLK_EDC1_CORE_RATE, CLK_EDC1_CORE_MIN_RATE, CLK_EDC1_CORE_MAX_RATE, &clk_hdmipll, NULL, \
		NULL, CLK_EDC1_CORE_ENABLE_REG_ADDR, CLK_EDC1_CORE_ENABLE_BIT_OFFSET, CLK_EDC1_CORE_CLKSEL_REG_ADDR, CLK_EDC1_CORE_CLKSEL_MASK, \
		CLK_EDC1_CORE_CLKSEL_SET_VALID, CLK_EDC1_CORE_CLKDIV_REG_ADDR, CLK_EDC1_CORE_CLKDIV_MASK, CLK_EDC1_CORE_CLKDIV_SET_VALID)

MACRO_CLK(clk_edc1_pix_ldi, CLK_EDC1_PIX_LDI, OFF, CLK_EDC1_PIX_LDI_RATE, CLK_EDC1_PIX_LDI_MIN_RATE, CLK_EDC1_PIX_LDI_MAX_RATE, &clk_hdmipll, NULL, \
		NULL, CLK_EDC1_PIX_LDI_ENABLE_REG_ADDR, CLK_EDC1_PIX_LDI_ENABLE_BIT_OFFSET, CLK_EDC1_PIX_LDI_CLKSEL_REG_ADDR, CLK_EDC1_PIX_LDI_CLKSEL_MASK, \
		CLK_EDC1_PIX_LDI_CLKSEL_SET_VALID, CLK_EDC1_PIX_LDI_CLKDIV_REG_ADDR, CLK_EDC1_PIX_LDI_CLKDIV_MASK, CLK_EDC1_PIX_LDI_CLKDIV_SET_VALID)
		
MACRO_CLK(clk_edc1_axi, CLK_EDC1_AXI, OFF, CLK_EDC1_AXI_RATE, CLK_EDC1_AXI_MIN_RATE, CLK_EDC1_AXI_MAX_RATE, NULL, NULL, \
		NULL, CLK_EDC1_AXI_ENABLE_REG_ADDR, CLK_EDC1_AXI_ENABLE_BIT_OFFSET, CLK_EDC1_AXI_CLKSEL_REG_ADDR, CLK_EDC1_AXI_CLKSEL_MASK, \
		CLK_EDC1_AXI_CLKSEL_SET_VALID, CLK_EDC1_AXI_CLKDIV_REG_ADDR, CLK_EDC1_AXI_CLKDIV_MASK, CLK_EDC1_AXI_CLKDIV_SET_VALID)
		
MACRO_CLK(clk_edc1_cfg_clk, CLK_EDC1_CFG_CLK, OFF, CLK_EDC1_CFG_CLK_RATE, CLK_EDC1_CFG_CLK_MIN_RATE, CLK_EDC1_CFG_CLK_MAX_RATE, NULL, NULL, \
		NULL, CLK_EDC1_CFG_CLK_ENABLE_REG_ADDR, CLK_EDC1_CFG_CLK_ENABLE_BIT_OFFSET, CLK_EDC1_CFG_CLK_CLKSEL_REG_ADDR, CLK_EDC1_CFG_CLK_CLKSEL_MASK, \
		CLK_EDC1_CFG_CLK_CLKSEL_SET_VALID, CLK_EDC1_CFG_CLK_CLKDIV_REG_ADDR, CLK_EDC1_CFG_CLK_CLKDIV_MASK, CLK_EDC1_CFG_CLK_CLKDIV_SET_VALID)
		
MACRO_CLK(clk_hdmi_slave, CLK_HDMI_SLAVE, OFF, CLK_HDMI_SLAVE_RATE, CLK_HDMI_SLAVE_MIN_RATE, CLK_HDMI_SLAVE_MAX_RATE, &clk_100m_src, NULL, \
		NULL, CLK_HDMI_SLAVE_ENABLE_REG_ADDR, CLK_HDMI_SLAVE_ENABLE_BIT_OFFSET, CLK_HDMI_SLAVE_CLKSEL_REG_ADDR, CLK_HDMI_SLAVE_CLKSEL_MASK, \
		CLK_HDMI_SLAVE_CLKSEL_SET_VALID, CLK_HDMI_SLAVE_CLKDIV_REG_ADDR, CLK_HDMI_SLAVE_CLKDIV_MASK, CLK_HDMI_SLAVE_CLKDIV_SET_VALID)


		
/* asp module */
MACRO_CLK(clk_hdmi_sck, CLK_HDMI_SCK, OFF, CLK_HDMI_SCK_RATE, CLK_HDMI_SCK_MIN_RATE, CLK_HDMI_SCK_MAX_RATE, &clk_hdmipll, NULL, \
		NULL, CLK_HDMI_SCK_ENABLE_REG_ADDR, CLK_HDMI_SCK_ENABLE_BIT_OFFSET, CLK_HDMI_SCK_CLKSEL_REG_ADDR, CLK_HDMI_SCK_CLKSEL_MASK, \
		CLK_HDMI_SCK_CLKSEL_SET_VALID, CLK_HDMI_SCK_CLKDIV_REG_ADDR, CLK_HDMI_SCK_CLKDIV_MASK, CLK_HDMI_SCK_CLKDIV_SET_VALID)
		
MACRO_CLK(clk_mclk_hdmi, CLK_MCLK_HDMI, OFF, CLK_MCLK_HDMI_RATE, CLK_MCLK_HDMI_MIN_RATE, CLK_MCLK_HDMI_MAX_RATE, &clk_hdmipll, NULL, \
		NULL, CLK_MCLK_HDMI_ENABLE_REG_ADDR, CLK_MCLK_HDMI_ENABLE_BIT_OFFSET, CLK_MCLK_HDMI_CLKSEL_REG_ADDR, CLK_MCLK_HDMI_CLKSEL_MASK, \
		CLK_MCLK_HDMI_CLKSEL_SET_VALID, CLK_MCLK_HDMI_CLKDIV_REG_ADDR, CLK_MCLK_HDMI_CLKDIV_MASK, CLK_MCLK_HDMI_CLKDIV_SET_VALID)		
MACRO_CLK(clk_asp_hdmi_adws, CLK_ASP_HDMI_ADWS, OFF, CLK_ASP_HDMI_ADWS_RATE, CLK_ASP_HDMI_ADWS_MIN_RATE, CLK_ASP_HDMI_ADWS_MAX_RATE, &clk_hdmipll, NULL, \
		NULL, CLK_ASP_HDMI_ADWS_ENABLE_REG_ADDR, CLK_ASP_HDMI_ADWS_ENABLE_BIT_OFFSET, CLK_ASP_HDMI_ADWS_CLKSEL_REG_ADDR, CLK_ASP_HDMI_ADWS_CLKSEL_MASK, \
		CLK_ASP_HDMI_ADWS_CLKSEL_SET_VALID, CLK_ASP_HDMI_ADWS_CLKDIV_REG_ADDR, CLK_ASP_HDMI_ADWS_CLKDIV_MASK, CLK_ASP_HDMI_ADWS_CLKDIV_SET_VALID)
		
MACRO_CLK(clk_asp_hdmi_bclk, CLK_ASP_HDMI_BCLK, OFF, CLK_ASP_HDMI_BCLK_RATE, CLK_ASP_HDMI_BCLK_MIN_RATE, CLK_ASP_HDMI_BCLK_MAX_RATE, &clk_hdmipll, NULL, \
		NULL, CLK_ASP_HDMI_BCLK_ENABLE_REG_ADDR, CLK_ASP_HDMI_BCLK_ENABLE_BIT_OFFSET, CLK_ASP_HDMI_BCLK_CLKSEL_REG_ADDR, CLK_ASP_HDMI_BCLK_CLKSEL_MASK, \
		CLK_ASP_HDMI_BCLK_CLKSEL_SET_VALID, CLK_ASP_HDMI_BCLK_CLKDIV_REG_ADDR, CLK_ASP_HDMI_BCLK_CLKDIV_MASK, CLK_ASP_HDMI_BCLK_CLKDIV_SET_VALID)

MACRO_CLK(clk_asp_hdmi_ref, CLK_ASP_HDMI_REF, OFF, CLK_ASP_HDMI_REF_RATE, CLK_ASP_HDMI_REF_MIN_RATE, CLK_ASP_HDMI_REF_MAX_RATE, NULL, NULL, \
		NULL, CLK_ASP_HDMI_REF_ENABLE_REG_ADDR, CLK_ASP_HDMI_REF_ENABLE_BIT_OFFSET, CLK_ASP_HDMI_REF_CLKSEL_REG_ADDR, CLK_ASP_HDMI_REF_CLKSEL_MASK, \
		CLK_ASP_HDMI_REF_CLKSEL_SET_VALID, CLK_ASP_HDMI_REF_CLKDIV_REG_ADDR, CLK_ASP_HDMI_REF_CLKDIV_MASK, CLK_ASP_HDMI_REF_CLKDIV_SET_VALID)
		
MACRO_CLK(clk_asp_spdif_ref, CLK_ASP_SPDIF_REF, OFF, CLK_ASP_SPDIF_REF_RATE, CLK_ASP_SPDIF_REF_MIN_RATE, CLK_ASP_SPDIF_REF_MAX_RATE, &clk_hdmipll, NULL, \
		NULL, CLK_ASP_SPDIF_REF_ENABLE_REG_ADDR, CLK_ASP_SPDIF_REF_ENABLE_BIT_OFFSET, CLK_ASP_SPDIF_REF_CLKSEL_REG_ADDR, CLK_ASP_SPDIF_REF_CLKSEL_MASK, \
		CLK_ASP_SPDIF_REF_CLKSEL_SET_VALID, CLK_ASP_SPDIF_REF_CLKDIV_REG_ADDR, CLK_ASP_SPDIF_REF_CLKDIV_MASK, CLK_ASP_SPDIF_REF_CLKDIV_SET_VALID)

MACRO_CLK(clk_asp_cfg, CLK_ASP_CFG, OFF, CLK_ASP_CFG_RATE, CLK_ASP_CFG_MIN_RATE, CLK_ASP_CFG_MAX_RATE, NULL, NULL, \
		NULL, CLK_ASP_CFG_ENABLE_REG_ADDR, CLK_ASP_CFG_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)



/* g2d module */
MACRO_CLK(clk_dsppll_g2dcore_gated, CLK_DSPPLL_G2DCORE_GATED, OFF, CLK_DSPPLL_G2DCORE_GATED_RATE, CLK_DSPPLL_G2DCORE_GATED_MIN_RATE, CLK_DSPPLL_G2DCORE_GATED_MAX_RATE, &clk_dsppll, NULL, \
		NULL, CLK_DSPPLL_G2DCORE_GATED_ENABLE_REG_ADDR, CLK_DSPPLL_G2DCORE_GATED_ENABLE_BIT_OFFSET, CLK_DSPPLL_G2DCORE_GATED_CLKSEL_REG_ADDR, CLK_DSPPLL_G2DCORE_GATED_CLKSEL_MASK, \
		CLK_DSPPLL_G2DCORE_GATED_CLKSEL_SET_VALID, CLK_DSPPLL_G2DCORE_GATED_CLKDIV_REG_ADDR, CLK_DSPPLL_G2DCORE_GATED_CLKDIV_MASK, CLK_DSPPLL_G2DCORE_GATED_CLKDIV_SET_VALID)
		
MACRO_CLK(clk_5g2d_core_clk, CLK_5G2D_CORE_CLK, OFF, CLK_5G2D_CORE_CLK_RATE, CLK_5G2D_CORE_CLK_MIN_RATE, CLK_5G2D_CORE_CLK_MAX_RATE, &clk_dsppll_g2dcore_gated, NULL, \
		NULL, CLK_5G2D_CORE_CLK_ENABLE_REG_ADDR, CLK_5G2D_CORE_CLK_ENABLE_BIT_OFFSET, CLK_5G2D_CORE_CLK_CLKSEL_REG_ADDR, CLK_5G2D_CORE_CLK_CLKSEL_MASK, \
		CLK_5G2D_CORE_CLK_CLKSEL_SET_VALID, CLK_5G2D_CORE_CLK_CLKDIV_REG_ADDR, CLK_5G2D_CORE_CLK_CLKDIV_MASK, CLK_5G2D_CORE_CLK_CLKDIV_SET_VALID)
		
MACRO_CLK(clk_4g2d_axi_clkhb, CLK_4G2D_AXI_CLKHB, OFF, CLK_4G2D_AXI_CLKHB_RATE, CLK_4G2D_AXI_CLKHB_MIN_RATE, CLK_4G2D_AXI_CLKHB_MAX_RATE, NULL, NULL, \
		NULL, CLK_4G2D_AXI_CLKHB_ENABLE_REG_ADDR, CLK_4G2D_AXI_CLKHB_ENABLE_BIT_OFFSET, CLK_4G2D_AXI_CLKHB_CLKSEL_REG_ADDR, CLK_4G2D_AXI_CLKHB_CLKSEL_MASK, \
		CLK_4G2D_AXI_CLKHB_CLKSEL_SET_VALID, CLK_4G2D_AXI_CLKHB_CLKDIV_REG_ADDR, CLK_4G2D_AXI_CLKHB_CLKDIV_MASK, CLK_4G2D_AXI_CLKHB_CLKDIV_SET_VALID)

MACRO_CLK(clk_3g2d_cfg_clk, CLK_3G2D_CFG_CLK, OFF, CLK_3G2D_CFG_CLK_RATE, CLK_3G2D_CFG_CLK_MIN_RATE, CLK_3G2D_CFG_CLK_MAX_RATE, NULL, NULL, \
		NULL, CLK_3G2D_CFG_CLK_ENABLE_REG_ADDR, CLK_3G2D_CFG_CLK_ENABLE_BIT_OFFSET, CLK_3G2D_CFG_CLK_CLKSEL_REG_ADDR, CLK_3G2D_CFG_CLK_CLKSEL_MASK, \
		CLK_3G2D_CFG_CLK_CLKSEL_SET_VALID, CLK_3G2D_CFG_CLK_CLKDIV_REG_ADDR, CLK_3G2D_CFG_CLK_CLKDIV_MASK, CLK_3G2D_CFG_CLK_CLKDIV_SET_VALID)

/* mali module */	
MACRO_CLK(clk_p2p_mali_brg_s, CLK_P2P_MALI_BRG_S, OFF, CLK_P2P_MALI_BRG_S_RATE, CLK_P2P_MALI_BRG_S_MIN_RATE, CLK_P2P_MALI_BRG_S_MAX_RATE, NULL, NULL, \
		NULL, CLK_P2P_MALI_BRG_S_ENABLE_REG_ADDR, CLK_P2P_MALI_BRG_S_ENABLE_BIT_OFFSET, CLK_P2P_MALI_BRG_S_CLKSEL_REG_ADDR, CLK_P2P_MALI_BRG_S_CLKSEL_MASK, \
		CLK_P2P_MALI_BRG_S_CLKSEL_SET_VALID, CLK_P2P_MALI_BRG_S_CLKDIV_REG_ADDR, CLK_P2P_MALI_BRG_S_CLKDIV_MASK, CLK_P2P_MALI_BRG_S_CLKDIV_SET_VALID)
struct clksel clksels_mali[] = {
	{.sel_parent = &clk_gpll0, .sel_val = 0,
	 .parent_min = CLK_GPLL0_RATE/CLK_MALI_DIV_MAX, .parent_max = CLK_GPLL0_RATE},
	{.sel_parent = &clk_gpll1, .sel_val = 1,
	 .parent_min = CLK_GPLL1_RATE/CLK_MALI_DIV_MAX, .parent_max = CLK_GPLL1_RATE},
	{.sel_parent = NULL},
};
MACRO_CLK(clk_mali, CLK_MALI, OFF, CLK_MALI_RATE, CLK_MALI_MIN_RATE, CLK_MALI_MAX_RATE, &clk_gpll0, NULL, \
		NULL, CLK_MALI_ENABLE_REG_ADDR, CLK_MALI_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
MACRO_CLK(clk_x2x_mali_brg_s, CLK_X2X_MALI_BRG_S, OFF, CLK_X2X_MALI_BRG_S_RATE, CLK_X2X_MALI_BRG_S_MIN_RATE, CLK_X2X_MALI_BRG_S_MAX_RATE, NULL, NULL, \
		NULL, CLK_X2X_MALI_BRG_S_ENABLE_REG_ADDR, CLK_X2X_MALI_BRG_S_ENABLE_BIT_OFFSET, CLK_X2X_MALI_BRG_S_CLKSEL_REG_ADDR, CLK_X2X_MALI_BRG_S_CLKSEL_MASK, \
		CLK_X2X_MALI_BRG_S_CLKSEL_SET_VALID, CLK_X2X_MALI_BRG_S_CLKDIV_REG_ADDR, CLK_X2X_MALI_BRG_S_CLKDIV_MASK, CLK_X2X_MALI_BRG_S_CLKDIV_SET_VALID)
		
MACRO_CLK(clk_x2x_mali_brg_m, CLK_X2X_MALI_BRG_M, OFF, CLK_X2X_MALI_BRG_M_RATE, CLK_X2X_MALI_BRG_M_MIN_RATE, CLK_X2X_MALI_BRG_M_MAX_RATE, NULL, NULL, \
		NULL, CLK_X2X_MALI_BRG_M_ENABLE_REG_ADDR, CLK_X2X_MALI_BRG_M_ENABLE_BIT_OFFSET, CLK_X2X_MALI_BRG_M_CLKSEL_REG_ADDR, CLK_X2X_MALI_BRG_M_CLKSEL_MASK, \
		CLK_X2X_MALI_BRG_M_CLKSEL_SET_VALID, CLK_X2X_MALI_BRG_M_CLKDIV_REG_ADDR, CLK_X2X_MALI_BRG_M_CLKDIV_MASK, CLK_X2X_MALI_BRG_M_CLKDIV_SET_VALID)

MACRO_CLK(clk_axi_mali_bus, CLK_AXI_MALI_BUS, OFF, CLK_AXI_MALI_BUS_RATE, CLK_AXI_MALI_BUS_MIN_RATE, CLK_AXI_MALI_BUS_MAX_RATE, NULL, NULL, \
		NULL, CLK_AXI_MALI_BUS_ENABLE_REG_ADDR, CLK_AXI_MALI_BUS_ENABLE_BIT_OFFSET, CLK_AXI_MALI_BUS_CLKSEL_REG_ADDR, CLK_AXI_MALI_BUS_CLKSEL_MASK, \
		CLK_AXI_MALI_BUS_CLKSEL_SET_VALID, CLK_AXI_MALI_BUS_CLKDIV_REG_ADDR, CLK_AXI_MALI_BUS_CLKDIV_MASK, CLK_AXI_MALI_BUS_CLKDIV_SET_VALID)

/* isp module */
static struct clksel clksels_isp[] = {
	{.sel_parent = &clk_peripll, .sel_val = 0x00, 
	.parent_min = CLK_PERIPLL_RATE/CLK_ISP_DIV_MAX, .parent_max = CLK_PERIPLL_RATE},
	{.sel_parent = &clk_dsppll, .sel_val = 0x01, 
	.parent_min = CLK_DSPPLL_RATE/CLK_ISP_DIV_MAX, .parent_max = CLK_DSPPLL_RATE},
	{.sel_parent = NULL},
};
MACRO_CLK(clk_peripll_isp_gated, CLK_PERIPLL_ISP_GATED, OFF, CLK_PERIPLL_ISP_GATED_RATE, CLK_PERIPLL_ISP_GATED_MIN_RATE, CLK_PERIPLL_ISP_GATED_MAX_RATE, &clk_peripll, NULL, \
		clksels_isp, CLK_PERIPLL_ISP_GATED_ENABLE_REG_ADDR, CLK_PERIPLL_ISP_GATED_ENABLE_BIT_OFFSET, CLK_PERIPLL_ISP_GATED_CLKSEL_REG_ADDR, CLK_PERIPLL_ISP_GATED_CLKSEL_MASK, \
		CLK_PERIPLL_ISP_GATED_CLKSEL_SET_VALID, CLK_PERIPLL_ISP_GATED_CLKDIV_REG_ADDR, CLK_PERIPLL_ISP_GATED_CLKDIV_MASK, CLK_PERIPLL_ISP_GATED_CLKDIV_SET_VALID)
MACRO_CLK(clk_isp, CLK_ISP, OFF, CLK_ISP_RATE, CLK_ISP_MIN_RATE, CLK_ISP_MAX_RATE, &clk_peripll_isp_gated, NULL, \
		NULL, CLK_ISP_ENABLE_REG_ADDR, CLK_ISP_ENABLE_BIT_OFFSET, CLK_ISP_CLKSEL_REG_ADDR, CLK_ISP_CLKSEL_MASK, \
		CLK_ISP_CLKSEL_SET_VALID, CLK_ISP_CLKDIV_REG_ADDR, CLK_ISP_CLKDIV_MASK, CLK_ISP_CLKDIV_SET_VALID)	
MACRO_CLK(clk_peripll_isp_ref_gated, CLK_PERIPLL_ISP_REF_GATED, OFF, CLK_PERIPLL_ISP_REF_GATED_RATE, CLK_PERIPLL_ISP_REF_GATED_MIN_RATE, CLK_PERIPLL_ISP_REF_GATED_MAX_RATE, &clk_peripll, NULL, \
		NULL, CLK_PERIPLL_ISP_REF_GATED_ENABLE_REG_ADDR, CLK_PERIPLL_ISP_REF_GATED_ENABLE_BIT_OFFSET, CLK_PERIPLL_ISP_REF_GATED_CLKSEL_REG_ADDR, CLK_PERIPLL_ISP_REF_GATED_CLKSEL_MASK, \
		CLK_PERIPLL_ISP_REF_GATED_CLKSEL_SET_VALID, CLK_PERIPLL_ISP_REF_GATED_CLKDIV_REG_ADDR, CLK_PERIPLL_ISP_REF_GATED_CLKDIV_MASK, CLK_PERIPLL_ISP_REF_GATED_CLKDIV_SET_VALID)
MACRO_CLK(clk_isp_ref, CLK_ISP_REF, OFF, CLK_ISP_REF_RATE, CLK_ISP_REF_MIN_RATE, CLK_ISP_REF_MAX_RATE, &clk_peripll_isp_ref_gated, NULL, \
		NULL, CLK_ISP_REF_ENABLE_REG_ADDR, CLK_ISP_REF_ENABLE_BIT_OFFSET, CLK_ISP_REF_CLKSEL_REG_ADDR, CLK_ISP_REF_CLKSEL_MASK, \
		CLK_ISP_REF_CLKSEL_SET_VALID, CLK_ISP_REF_CLKDIV_REG_ADDR, CLK_ISP_REF_CLKDIV_MASK, CLK_ISP_REF_CLKDIV_SET_VALID)
MACRO_CLK(clk_isp_cfg_clk, CLK_ISP_CFG_CLK, OFF, CLK_ISP_CFG_CLK_RATE, CLK_ISP_CFG_CLK_MIN_RATE, CLK_ISP_CFG_CLK_MAX_RATE, &clk_bus_src, NULL, \
		NULL, CLK_ISP_CFG_CLK_ENABLE_REG_ADDR, CLK_ISP_CFG_CLK_ENABLE_BIT_OFFSET, CLK_ISP_CFG_CLK_CLKSEL_REG_ADDR, CLK_ISP_CFG_CLK_CLKSEL_MASK, \
		CLK_ISP_CFG_CLK_CLKSEL_SET_VALID, CLK_ISP_CFG_CLK_CLKDIV_REG_ADDR, CLK_ISP_CFG_CLK_CLKDIV_MASK, CLK_ISP_CFG_CLK_CLKDIV_SET_VALID)
MACRO_CLK(clk_isp_axi, CLK_ISP_AXI, OFF, CLK_ISP_AXI_RATE, CLK_ISP_AXI_MIN_RATE, CLK_ISP_AXI_MAX_RATE, NULL, NULL, \
		NULL, CLK_ISP_AXI_ENABLE_REG_ADDR, CLK_ISP_AXI_ENABLE_BIT_OFFSET, CLK_ISP_AXI_CLKSEL_REG_ADDR, CLK_ISP_AXI_CLKSEL_MASK, \
		CLK_ISP_AXI_CLKSEL_SET_VALID, CLK_ISP_AXI_CLKDIV_REG_ADDR, CLK_ISP_AXI_CLKDIV_MASK, CLK_ISP_AXI_CLKDIV_SET_VALID)
MACRO_CLK(clk_csi_apb_mux, CLK_CSI_APB_MUX, OFF, CLK_CSI_APB_MUX_RATE, CLK_CSI_APB_MUX_MIN_RATE, CLK_CSI_APB_MUX_MAX_RATE, &clk_bus_src, NULL, \
		NULL, CLK_CSI_APB_MUX_ENABLE_REG_ADDR, CLK_CSI_APB_MUX_ENABLE_BIT_OFFSET, CLK_CSI_APB_MUX_CLKSEL_REG_ADDR, CLK_CSI_APB_MUX_CLKSEL_MASK, \
		CLK_CSI_APB_MUX_CLKSEL_SET_VALID, CLK_CSI_APB_MUX_CLKDIV_REG_ADDR, CLK_CSI_APB_MUX_CLKDIV_MASK, CLK_CSI_APB_MUX_CLKDIV_SET_VALID)
MACRO_CLK(clk_csio_cfg, CLK_CSIO_CFG, OFF, CLK_CSIO_CFG_RATE, CLK_CSIO_CFG_MIN_RATE, CLK_CSIO_CFG_MAX_RATE, &clk_bus_src, NULL, \
		NULL, CLK_CSIO_CFG_ENABLE_REG_ADDR, CLK_CSIO_CFG_ENABLE_BIT_OFFSET, CLK_CSIO_CFG_CLKSEL_REG_ADDR, CLK_CSIO_CFG_CLKSEL_MASK, \
		CLK_CSIO_CFG_CLKSEL_SET_VALID, CLK_CSIO_CFG_CLKDIV_REG_ADDR, CLK_CSIO_CFG_CLKDIV_MASK, CLK_CSIO_CFG_CLKDIV_SET_VALID)
MACRO_CLK(csi2_cfg_clk, CSI2_CFG_CLK, OFF, CSI2_CFG_CLK_RATE, CSI2_CFG_CLK_MIN_RATE, CSI2_CFG_CLK_MAX_RATE, &clk_bus_src, NULL, \
		NULL, CSI2_CFG_CLK_ENABLE_REG_ADDR, CSI2_CFG_CLK_ENABLE_BIT_OFFSET, CSI2_CFG_CLK_CLKSEL_REG_ADDR, CSI2_CFG_CLK_CLKSEL_MASK, \
		CSI2_CFG_CLK_CLKSEL_SET_VALID, CSI2_CFG_CLK_CLKDIV_REG_ADDR, CSI2_CFG_CLK_CLKDIV_MASK, CSI2_CFG_CLK_CLKDIV_SET_VALID)

/* dphy module  */	
MACRO_CLK(clk_dphy0_ref, CLK_DPHY0_REF, OFF, CLK_DPHY0_REF_RATE, CLK_DPHY0_REF_MIN_RATE, CLK_DPHY0_REF_MAX_RATE, &clk_ref, NULL, \
		NULL, CLK_DPHY0_REF_ENABLE_REG_ADDR, CLK_DPHY0_REF_ENABLE_BIT_OFFSET, CLK_DPHY0_REF_CLKSEL_REG_ADDR, CLK_DPHY0_REF_CLKSEL_MASK, \
		CLK_DPHY0_REF_CLKSEL_SET_VALID, CLK_DPHY0_REF_CLKDIV_REG_ADDR, CLK_DPHY0_REF_CLKDIV_MASK, CLK_DPHY0_REF_CLKDIV_SET_VALID)
MACRO_CLK(clk_dphy0_cfg, CLK_DPHY0_CFG, OFF, CLK_DPHY0_CFG_RATE, CLK_DPHY0_CFG_MIN_RATE, CLK_DPHY0_CFG_MAX_RATE, &clk_ref, NULL, \
		NULL, CLK_DPHY0_CFG_ENABLE_REG_ADDR, CLK_DPHY0_CFG_ENABLE_BIT_OFFSET, CLK_DPHY0_CFG_CLKSEL_REG_ADDR, CLK_DPHY0_CFG_CLKSEL_MASK, \
		CLK_DPHY0_CFG_CLKSEL_SET_VALID, CLK_DPHY0_CFG_CLKDIV_REG_ADDR, CLK_DPHY0_CFG_CLKDIV_MASK, CLK_DPHY0_CFG_CLKDIV_SET_VALID)
MACRO_CLK(clk_dphy1_cfg, CLK_DPHY1_CFG, OFF, CLK_DPHY1_CFG_RATE, CLK_DPHY1_CFG_MIN_RATE, CLK_DPHY1_CFG_MAX_RATE, &clk_ref, NULL, \
		NULL, CLK_DPHY1_CFG_ENABLE_REG_ADDR, CLK_DPHY1_CFG_ENABLE_BIT_OFFSET, CLK_DPHY1_CFG_CLKSEL_REG_ADDR, CLK_DPHY1_CFG_CLKSEL_MASK, \
		CLK_DPHY1_CFG_CLKSEL_SET_VALID, CLK_DPHY1_CFG_CLKDIV_REG_ADDR, CLK_DPHY1_CFG_CLKDIV_MASK, CLK_DPHY1_CFG_CLKDIV_SET_VALID)
MACRO_CLK(clk_dphy2_cfg, CLK_DPHY2_CFG, OFF, CLK_DPHY2_CFG_RATE, CLK_DPHY2_CFG_MIN_RATE, CLK_DPHY2_CFG_MAX_RATE, &clk_ref, NULL, \
		NULL, CLK_DPHY2_CFG_ENABLE_REG_ADDR, CLK_DPHY2_CFG_ENABLE_BIT_OFFSET, CLK_DPHY2_CFG_CLKSEL_REG_ADDR, CLK_DPHY2_CFG_CLKSEL_MASK, \
		CLK_DPHY2_CFG_CLKSEL_SET_VALID, CLK_DPHY2_CFG_CLKDIV_REG_ADDR, CLK_DPHY2_CFG_CLKDIV_MASK, CLK_DPHY2_CFG_CLKDIV_SET_VALID)

/* venc module */
MACRO_CLK(clk_peripll_venc_gated, CLK_PERIPLL_VENC_GATED, OFF, CLK_PERIPLL_VENC_GATED_RATE, CLK_PERIPLL_VENC_GATED_MIN_RATE, CLK_PERIPLL_VENC_GATED_MAX_RATE, &clk_peripll, NULL, \
		NULL, CLK_PERIPLL_VENC_GATED_ENABLE_REG_ADDR, CLK_PERIPLL_VENC_GATED_ENABLE_BIT_OFFSET, CLK_PERIPLL_VENC_GATED_CLKSEL_REG_ADDR, CLK_PERIPLL_VENC_GATED_CLKSEL_MASK, \
		CLK_PERIPLL_VENC_GATED_CLKSEL_SET_VALID, CLK_PERIPLL_VENC_GATED_CLKDIV_REG_ADDR, CLK_PERIPLL_VENC_GATED_CLKDIV_MASK, CLK_PERIPLL_VENC_GATED_CLKDIV_SET_VALID)
MACRO_CLK(clk_0venc_slave_clk, CLK_0VENC_SLAVE_CLK, OFF, CLK_0VENC_SLAVE_CLK_RATE, CLK_0VENC_SLAVE_CLK_MIN_RATE, CLK_0VENC_SLAVE_CLK_MAX_RATE, &clk_peripll_venc_gated, NULL, \
		NULL, CLK_0VENC_SLAVE_CLK_ENABLE_REG_ADDR, CLK_0VENC_SLAVE_CLK_ENABLE_BIT_OFFSET, CLK_0VENC_SLAVE_CLK_CLKSEL_REG_ADDR, CLK_0VENC_SLAVE_CLK_CLKSEL_MASK, \
		CLK_0VENC_SLAVE_CLK_CLKSEL_SET_VALID, CLK_0VENC_SLAVE_CLK_CLKDIV_REG_ADDR, CLK_0VENC_SLAVE_CLK_CLKDIV_MASK, CLK_0VENC_SLAVE_CLK_CLKDIV_SET_VALID)	
MACRO_CLK(clk_x2x_venc_brg_s, CLK_X2X_VENC_BRG_S, OFF, CLK_X2X_VENC_BRG_S_RATE, CLK_X2X_VENC_BRG_S_MIN_RATE, CLK_X2X_VENC_BRG_S_MAX_RATE, NULL, NULL, \
		NULL, CLK_X2X_VENC_BRG_S_ENABLE_REG_ADDR, CLK_X2X_VENC_BRG_S_ENABLE_BIT_OFFSET, CLK_X2X_VENC_BRG_S_CLKSEL_REG_ADDR, CLK_X2X_VENC_BRG_S_CLKSEL_MASK, \
		CLK_X2X_VENC_BRG_S_CLKSEL_SET_VALID, CLK_X2X_VENC_BRG_S_CLKDIV_REG_ADDR, CLK_X2X_VENC_BRG_S_CLKDIV_MASK, CLK_X2X_VENC_BRG_S_CLKDIV_SET_VALID)
MACRO_CLK(clk_p2p_venc_brg_s, CLK_P2P_VENC_BRG_S, OFF, CLK_P2P_VENC_BRG_S_RATE, CLK_P2P_VENC_BRG_S_MIN_RATE, CLK_P2P_VENC_BRG_S_MAX_RATE, NULL, NULL, \
		NULL, CLK_P2P_VENC_BRG_S_ENABLE_REG_ADDR, CLK_P2P_VENC_BRG_S_ENABLE_BIT_OFFSET, CLK_P2P_VENC_BRG_S_CLKSEL_REG_ADDR, CLK_P2P_VENC_BRG_S_CLKSEL_MASK, \
		CLK_P2P_VENC_BRG_S_CLKSEL_SET_VALID, CLK_P2P_VENC_BRG_S_CLKDIV_REG_ADDR, CLK_P2P_VENC_BRG_S_CLKDIV_MASK, CLK_P2P_VENC_BRG_S_CLKDIV_SET_VALID)
		
/* vdec module */
MACRO_CLK(clk_peripll_vdec_gated, CLK_PERIPLL_VDEC_GATED, OFF, CLK_PERIPLL_VDEC_GATED_RATE, CLK_PERIPLL_VDEC_GATED_MIN_RATE, CLK_PERIPLL_VDEC_GATED_MAX_RATE, &clk_peripll, NULL, \
		NULL, CLK_PERIPLL_VDEC_GATED_ENABLE_REG_ADDR, CLK_PERIPLL_VDEC_GATED_ENABLE_BIT_OFFSET, CLK_PERIPLL_VDEC_GATED_CLKSEL_REG_ADDR, CLK_PERIPLL_VDEC_GATED_CLKSEL_MASK, \
		CLK_PERIPLL_VDEC_GATED_CLKSEL_SET_VALID, CLK_PERIPLL_VDEC_GATED_CLKDIV_REG_ADDR, CLK_PERIPLL_VDEC_GATED_CLKDIV_MASK, CLK_PERIPLL_VDEC_GATED_CLKDIV_SET_VALID)

MACRO_CLK(clk_1vdec_slave_clk, CLK_1VDEC_SLAVE_CLK, OFF, CLK_1VDEC_SLAVE_CLK_RATE, CLK_1VDEC_SLAVE_CLK_MIN_RATE, CLK_1VDEC_SLAVE_CLK_MAX_RATE, &clk_peripll_vdec_gated, NULL, \
		NULL, CLK_1VDEC_SLAVE_CLK_ENABLE_REG_ADDR, CLK_1VDEC_SLAVE_CLK_ENABLE_BIT_OFFSET, CLK_1VDEC_SLAVE_CLK_CLKSEL_REG_ADDR, CLK_1VDEC_SLAVE_CLK_CLKSEL_MASK, \
		CLK_1VDEC_SLAVE_CLK_CLKSEL_SET_VALID, CLK_1VDEC_SLAVE_CLK_CLKDIV_REG_ADDR, CLK_1VDEC_SLAVE_CLK_CLKDIV_MASK, CLK_1VDEC_SLAVE_CLK_CLKDIV_SET_VALID)

MACRO_CLK(clk_x2x_vdec_brg_s, CLK_X2X_VDEC_BRG_S, OFF, CLK_X2X_VDEC_BRG_S_RATE, CLK_X2X_VDEC_BRG_S_MIN_RATE, CLK_X2X_VDEC_BRG_S_MAX_RATE, NULL, NULL, \
		NULL, CLK_X2X_VDEC_BRG_S_ENABLE_REG_ADDR, CLK_X2X_VDEC_BRG_S_ENABLE_BIT_OFFSET, CLK_X2X_VDEC_BRG_S_CLKSEL_REG_ADDR, CLK_X2X_VDEC_BRG_S_CLKSEL_MASK, \
		CLK_X2X_VDEC_BRG_S_CLKSEL_SET_VALID, CLK_X2X_VDEC_BRG_S_CLKDIV_REG_ADDR, CLK_X2X_VDEC_BRG_S_CLKDIV_MASK, CLK_X2X_VDEC_BRG_S_CLKDIV_SET_VALID)

MACRO_CLK(clk_p2p_vdec_brg_s, CLK_P2P_VDEC_BRG_S, OFF, CLK_P2P_VDEC_BRG_S_RATE, CLK_P2P_VDEC_BRG_S_MIN_RATE, CLK_P2P_VDEC_BRG_S_MAX_RATE, NULL, NULL, \
		NULL, CLK_P2P_VDEC_BRG_S_ENABLE_REG_ADDR, CLK_P2P_VDEC_BRG_S_ENABLE_BIT_OFFSET, CLK_P2P_VDEC_BRG_S_CLKSEL_REG_ADDR, CLK_P2P_VDEC_BRG_S_CLKSEL_MASK, \
		CLK_P2P_VDEC_BRG_S_CLKSEL_SET_VALID, CLK_P2P_VDEC_BRG_S_CLKDIV_REG_ADDR, CLK_P2P_VDEC_BRG_S_CLKDIV_MASK, CLK_P2P_VDEC_BRG_S_CLKDIV_SET_VALID)
		
/* vpp module */
MACRO_CLK(clk_peripll_vpp_gated, CLK_PERIPLL_VPP_GATED, OFF, CLK_PERIPLL_VPP_GATED_RATE, CLK_PERIPLL_VPP_GATED_MIN_RATE, CLK_PERIPLL_VPP_GATED_MAX_RATE, &clk_peripll, NULL, \
		NULL, CLK_PERIPLL_VPP_GATED_ENABLE_REG_ADDR, CLK_PERIPLL_VPP_GATED_ENABLE_BIT_OFFSET, CLK_PERIPLL_VPP_GATED_CLKSEL_REG_ADDR, CLK_PERIPLL_VPP_GATED_CLKSEL_MASK, \
		CLK_PERIPLL_VPP_GATED_CLKSEL_SET_VALID, CLK_PERIPLL_VPP_GATED_CLKDIV_REG_ADDR, CLK_PERIPLL_VPP_GATED_CLKDIV_MASK, CLK_PERIPLL_VPP_GATED_CLKDIV_SET_VALID)

MACRO_CLK(clk_2vpp_slave_clk, CLK_2VPP_SLAVE_CLK, OFF, CLK_2VPP_SLAVE_CLK_RATE, CLK_2VPP_SLAVE_CLK_MIN_RATE, CLK_2VPP_SLAVE_CLK_MAX_RATE, &clk_peripll_vpp_gated, NULL, \
		NULL, CLK_2VPP_SLAVE_CLK_ENABLE_REG_ADDR, CLK_2VPP_SLAVE_CLK_ENABLE_BIT_OFFSET, CLK_2VPP_SLAVE_CLK_CLKSEL_REG_ADDR, CLK_2VPP_SLAVE_CLK_CLKSEL_MASK, \
		CLK_2VPP_SLAVE_CLK_CLKSEL_SET_VALID, CLK_2VPP_SLAVE_CLK_CLKDIV_REG_ADDR, CLK_2VPP_SLAVE_CLK_CLKDIV_MASK, CLK_2VPP_SLAVE_CLK_CLKDIV_SET_VALID)		

MACRO_CLK(clk_x2x_vpp_brg_s, CLK_X2X_VPP_BRG_S, OFF, CLK_X2X_VPP_BRG_S_RATE, CLK_X2X_VPP_BRG_S_MIN_RATE, CLK_X2X_VPP_BRG_S_MAX_RATE, NULL, NULL, \
		NULL, CLK_X2X_VPP_BRG_S_ENABLE_REG_ADDR, CLK_X2X_VPP_BRG_S_ENABLE_BIT_OFFSET, CLK_X2X_VPP_BRG_S_CLKSEL_REG_ADDR, CLK_X2X_VPP_BRG_S_CLKSEL_MASK, \
		CLK_X2X_VPP_BRG_S_CLKSEL_SET_VALID, CLK_X2X_VPP_BRG_S_CLKDIV_REG_ADDR, CLK_X2X_VPP_BRG_S_CLKDIV_MASK, CLK_X2X_VPP_BRG_S_CLKDIV_SET_VALID)

MACRO_CLK(clk_p2p_vpp_brg_s, CLK_P2P_VPP_BRG_S, OFF, CLK_P2P_VPP_BRG_S_RATE, CLK_P2P_VPP_BRG_S_MIN_RATE, CLK_P2P_VPP_BRG_S_MAX_RATE, NULL, NULL, \
		NULL, CLK_P2P_VPP_BRG_S_ENABLE_REG_ADDR, CLK_P2P_VPP_BRG_S_ENABLE_BIT_OFFSET, CLK_P2P_VPP_BRG_S_CLKSEL_REG_ADDR, CLK_P2P_VPP_BRG_S_CLKSEL_MASK, \
		CLK_P2P_VPP_BRG_S_CLKSEL_SET_VALID, CLK_P2P_VPP_BRG_S_CLKDIV_REG_ADDR, CLK_P2P_VPP_BRG_S_CLKDIV_MASK, CLK_P2P_VPP_BRG_S_CLKDIV_SET_VALID)
		
/* uart module */
MACRO_CLK(pclk_uart0, PCLK_UART0, ON, PCLK_UART0_RATE, PCLK_UART0_MIN_RATE, PCLK_UART0_MAX_RATE, &clkin_sys, NULL, \
		NULL, PCLK_UART0_ENABLE_REG_ADDR, PCLK_UART0_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clk *clkfr_uart0[] = {
	&pclk_uart0,
	NULL,
};			
MACRO_CLK(clk_uart0, CLK_UART0, OFF, CLK_UART0_RATE, CLK_UART0_MIN_RATE, CLK_UART0_MAX_RATE, &clk_ref, clkfr_uart0, \
		NULL, CLK_UART0_ENABLE_REG_ADDR, CLK_UART0_ENABLE_BIT_OFFSET, CLK_UART0_CLKSEL_REG_ADDR, CLK_UART0_CLKSEL_MASK, \
		CLK_UART0_CLKSEL_SET_VALID, CLK_UART0_CLKDIV_REG_ADDR, CLK_UART0_CLKDIV_MASK, CLK_UART0_CLKDIV_SET_VALID)

static struct clksel clksels_uart1[] = {
	{.sel_parent = &clk_ref, .sel_val = 0x00, 
	.parent_min = CLK_REF_RATE/CLK_UART1_DIV_MAX, .parent_max = CLK_REF_RATE},
	{.sel_parent = &clkin_sys, .sel_val = 0x01, 
	.parent_min = CLKIN_SYS_RATE/CLK_UART1_DIV_MAX, .parent_max = CLKIN_SYS_RATE},
	{.sel_parent = NULL},
};
MACRO_CLK(pclk_uart1, PCLK_UART1, OFF, PCLK_UART1_RATE, PCLK_UART1_MIN_RATE, PCLK_UART1_MAX_RATE, &clkin_sys, NULL, \
		NULL, PCLK_UART1_ENABLE_REG_ADDR, PCLK_UART1_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clk *clkfr_uart1[] = {
	&pclk_uart1,
	NULL,
};		
MACRO_CLK(clk_uart1, CLK_UART1, OFF, CLK_UART1_RATE, CLK_UART1_MIN_RATE, CLK_UART1_MAX_RATE, &clk_ref, clkfr_uart1, \
		clksels_uart1, CLK_UART1_ENABLE_REG_ADDR, CLK_UART1_ENABLE_BIT_OFFSET, CLK_UART1_CLKSEL_REG_ADDR, CLK_UART1_CLKSEL_MASK, \
		CLK_UART1_CLKSEL_SET_VALID, CLK_UART1_CLKDIV_REG_ADDR, CLK_UART1_CLKDIV_MASK, CLK_UART1_CLKDIV_SET_VALID)

static struct clksel clksels_uart2[] = {
	{.sel_parent = &clk_ref, .sel_val = 0x00, 
	.parent_min = CLK_REF_RATE/CLK_UART2_DIV_MAX, .parent_max = CLK_REF_RATE},
	{.sel_parent = &clkin_sys, .sel_val = 0x01, 
	.parent_min = CLKIN_SYS_RATE/CLK_UART2_DIV_MAX, .parent_max = CLKIN_SYS_RATE},
	{.sel_parent = NULL},
};
MACRO_CLK(pclk_uart2, PCLK_UART2, OFF, PCLK_UART2_RATE, PCLK_UART2_MIN_RATE, PCLK_UART2_MAX_RATE, &clkin_sys, NULL, \
		NULL, PCLK_UART2_ENABLE_REG_ADDR, PCLK_UART2_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clk *clkfr_uart2[] = {
	&pclk_uart2,
	NULL,
};		
MACRO_CLK(clk_uart2, CLK_UART2, OFF, CLK_UART2_RATE, CLK_UART2_MIN_RATE, CLK_UART2_MAX_RATE, &clk_ref, clkfr_uart2, \
		clksels_uart2, CLK_UART2_ENABLE_REG_ADDR, CLK_UART2_ENABLE_BIT_OFFSET, CLK_UART2_CLKSEL_REG_ADDR, CLK_UART2_CLKSEL_MASK, \
		CLK_UART2_CLKSEL_SET_VALID, CLK_UART2_CLKDIV_REG_ADDR, CLK_UART2_CLKDIV_MASK, CLK_UART2_CLKDIV_SET_VALID)
		
static struct clksel clksels_uart3[] = {
	{.sel_parent = &clk_ref, .sel_val = 0x00, 
	.parent_min = CLK_REF_RATE/CLK_UART3_DIV_MAX, .parent_max = CLK_REF_RATE},
	{.sel_parent = &clkin_sys, .sel_val = 0x01, 
	.parent_min = CLKIN_SYS_RATE/CLK_UART3_DIV_MAX, .parent_max = CLKIN_SYS_RATE},
	{.sel_parent = NULL},
};
MACRO_CLK(pclk_uart3, PCLK_UART3, OFF, PCLK_UART3_RATE, PCLK_UART3_MIN_RATE, PCLK_UART3_MAX_RATE, &clkin_sys, NULL, \
		NULL, PCLK_UART3_ENABLE_REG_ADDR, PCLK_UART3_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clk *clkfr_uart3[] = {
	&pclk_uart3,
	NULL,
};				
MACRO_CLK(clk_uart3, CLK_UART3, OFF, CLK_UART3_RATE, CLK_UART3_MIN_RATE, CLK_UART3_MAX_RATE, &clk_ref, clkfr_uart3, \
		clksels_uart3, CLK_UART3_ENABLE_REG_ADDR, CLK_UART3_ENABLE_BIT_OFFSET, CLK_UART3_CLKSEL_REG_ADDR, CLK_UART3_CLKSEL_MASK, \
		CLK_UART3_CLKSEL_SET_VALID, CLK_UART3_CLKDIV_REG_ADDR, CLK_UART3_CLKDIV_MASK, CLK_UART3_CLKDIV_SET_VALID)
		
static struct clksel clksels_uart4[] = {
	{.sel_parent = &clk_ref, .sel_val = 0x00, 
	.parent_min = CLK_REF_RATE/CLK_UART4_DIV_MAX, .parent_max = CLK_REF_RATE},
	{.sel_parent = &clkin_sys, .sel_val = 0x01, 
	.parent_min = CLKIN_SYS_RATE/CLK_UART4_DIV_MAX, .parent_max = CLKIN_SYS_RATE},
	{.sel_parent = NULL},
};
MACRO_CLK(pclk_uart4, PCLK_UART4, OFF, PCLK_UART4_RATE, PCLK_UART4_MIN_RATE, PCLK_UART4_MAX_RATE, &clkin_sys, NULL, \
		NULL, PCLK_UART4_ENABLE_REG_ADDR, PCLK_UART4_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clk *clkfr_uart4[] = {
	&pclk_uart4,
	NULL,
};				
MACRO_CLK(clk_uart4, CLK_UART4, OFF, CLK_UART4_RATE, CLK_UART4_MIN_RATE, CLK_UART4_MAX_RATE, &clk_ref, clkfr_uart4, \
		clksels_uart4, CLK_UART4_ENABLE_REG_ADDR, CLK_UART4_ENABLE_BIT_OFFSET, CLK_UART4_CLKSEL_REG_ADDR, CLK_UART4_CLKSEL_MASK, \
		CLK_UART4_CLKSEL_SET_VALID, CLK_UART4_CLKDIV_REG_ADDR, CLK_UART4_CLKDIV_MASK, CLK_UART4_CLKDIV_SET_VALID)
static struct clksel clksels_uart5[] = {
	{.sel_parent = &clk_ref, .sel_val = 0x00, 
	.parent_min = CLK_REF_RATE/CLK_UART5_DIV_MAX, .parent_max = CLK_REF_RATE},
	{.sel_parent = &clkin_sys, .sel_val = 0x01, 
	.parent_min = CLKIN_SYS_RATE/CLK_UART5_DIV_MAX, .parent_max = CLKIN_SYS_RATE},
	{.sel_parent = NULL},
};
#if 0
MACRO_CLK(pclk_uart5, PCLK_UART5, OFF, PCLK_UART5_RATE, PCLK_UART5_MIN_RATE, PCLK_UART5_MAX_RATE, &clkin_sys, NULL, \
		NULL, PCLK_UART5_ENABLE_REG_ADDR, PCLK_UART5_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)	
static struct clk *clkfr_uart5[] = {
	&pclk_uart5,
	NULL,
};		
MACRO_CLK(clk_uart5, CLK_UART5, OFF, CLK_UART5_RATE, CLK_UART5_MIN_RATE, CLK_UART5_MAX_RATE, &clk_ref, clkfr_uart5, \
		clksels_uart5, CLK_UART5_ENABLE_REG_ADDR, CLK_UART5_ENABLE_BIT_OFFSET, CLK_UART5_CLKSEL_REG_ADDR, CLK_UART5_CLKSEL_MASK, \
		CLK_UART5_CLKSEL_SET_VALID, CLK_UART5_CLKDIV_REG_ADDR, CLK_UART5_CLKDIV_MASK, CLK_UART5_CLKDIV_SET_VALID)

static struct clksel clksels_uart6[] = {
	{.sel_parent = &clk_ref, .sel_val = 0x00, 
	.parent_min = CLK_REF_RATE/CLK_UART6_DIV_MAX, .parent_max = CLK_REF_RATE},
	{.sel_parent = &clkin_sys, .sel_val = 0x01, 
	.parent_min = CLKIN_SYS_RATE/CLK_UART6_DIV_MAX, .parent_max = CLKIN_SYS_RATE},
	{.sel_parent = NULL},
};
MACRO_CLK(pclk_uart6, PCLK_UART6, OFF, PCLK_UART6_RATE, PCLK_UART6_MIN_RATE, PCLK_UART6_MAX_RATE, &clkin_sys, NULL, \
		NULL, PCLK_UART6_ENABLE_REG_ADDR, PCLK_UART6_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)	
static struct clk *clkfr_uart6[] = {
	&pclk_uart6,
	NULL,
};			
MACRO_CLK(clk_uart6, CLK_UART6, OFF, CLK_UART6_RATE, CLK_UART6_MIN_RATE, CLK_UART6_MAX_RATE, &clk_ref, clkfr_uart6, \
		clksels_uart6, CLK_UART6_ENABLE_REG_ADDR, CLK_UART6_ENABLE_BIT_OFFSET, CLK_UART6_CLKSEL_REG_ADDR, CLK_UART6_CLKSEL_MASK, \
		CLK_UART6_CLKSEL_SET_VALID, CLK_UART6_CLKDIV_REG_ADDR, CLK_UART6_CLKDIV_MASK, CLK_UART6_CLKDIV_SET_VALID)


#endif
/* mmc module */
MACRO_CLK(hclk_mmc0, HCLK_MMC0, OFF, HCLK_MMC0_RATE, HCLK_MMC0_MIN_RATE, HCLK_MMC0_MAX_RATE, &clkin_sys, NULL, \
		NULL, HCLK_MMC0_ENABLE_REG_ADDR, HCLK_MMC0_ENABLE_BIT_OFFSET,  NULL, 0, -1, NULL, 0, -1)
MACRO_CLK(clk_dsppll_mmc0_gated, CLK_DSPPLL_MMC0_GATED, OFF, CLK_DSPPLL_MMC0_GATED_RATE, CLK_DSPPLL_MMC0_GATED_MIN_RATE, CLK_DSPPLL_MMC0_GATED_MAX_RATE, &clk_dsppll, NULL, \
		NULL, CLK_DSPPLL_MMC0_GATED_ENABLE_REG_ADDR, CLK_DSPPLL_MMC0_GATED_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clk *clkfr_mmc0low[] = {
	&hclk_mmc0,
      &clk_dsppll_mmc0_gated,  
	NULL,
};			
MACRO_CLK(clk_mmc0high, CLK_MMC0HIGH, OFF, CLK_MMC0HIGH_RATE, CLK_MMC0HIGH_MIN_RATE, CLK_MMC0HIGH_MAX_RATE, &clk_dsppll, NULL, \
		NULL, CLK_MMC0HIGH_ENABLE_REG_ADDR, CLK_MMC0HIGH_ENABLE_BIT_OFFSET, NULL, 0, -1, \
		CLK_MMC0HIGH_CLKDIV_REG_ADDR, CLK_MMC0HIGH_CLKDIV_MASK, CLK_MMC0HIGH_CLKDIV_SET_VALID)
MACRO_CLK(clk_mmc0low, CLK_MMC0LOW, OFF, CLK_MMC0LOW_RATE, CLK_MMC0LOW_MIN_RATE, CLK_MMC0LOW_MAX_RATE, &clk_mmc0high, clkfr_mmc0low, \
		NULL, CLK_MMC0LOW_ENABLE_REG_ADDR, CLK_MMC0LOW_ENABLE_BIT_OFFSET, CLK_MMC0LOW_CLKSEL_REG_ADDR, CLK_MMC0LOW_CLKSEL_MASK, \
		CLK_MMC0LOW_CLKSEL_SET_VALID, CLK_MMC0LOW_CLKDIV_REG_ADDR, CLK_MMC0LOW_CLKDIV_MASK, CLK_MMC0LOW_CLKDIV_SET_VALID)
MACRO_CLK(hclk_mmc1, HCLK_MMC1, OFF, HCLK_MMC1_RATE, HCLK_MMC1_MIN_RATE, HCLK_MMC1_MAX_RATE, &clkin_sys, NULL, \
		NULL, HCLK_MMC1_ENABLE_REG_ADDR, HCLK_MMC1_ENABLE_BIT_OFFSET,  NULL, 0, -1, NULL, 0, -1)
MACRO_CLK(clk_dsppll_mmc1_gated, CLK_DSPPLL_MMC1_GATED, OFF, CLK_DSPPLL_MMC1_GATED_RATE, CLK_DSPPLL_MMC1_GATED_MIN_RATE, CLK_DSPPLL_MMC1_GATED_MAX_RATE, &clk_dsppll, NULL, \
		NULL, CLK_DSPPLL_MMC1_GATED_ENABLE_REG_ADDR, CLK_DSPPLL_MMC1_GATED_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)	
static struct clk *clkfr_mmc1low[] = {
	&hclk_mmc1,
      &clk_dsppll_mmc1_gated,  
	NULL,
};		
MACRO_CLK(clk_mmc1high, CLK_MMC1HIGH, OFF, CLK_MMC1HIGH_RATE, CLK_MMC1HIGH_MIN_RATE, CLK_MMC1HIGH_MAX_RATE, &clk_dsppll, NULL, \
		NULL, CLK_MMC1HIGH_ENABLE_REG_ADDR, CLK_MMC1HIGH_ENABLE_BIT_OFFSET, NULL, 0, -1, \
		CLK_MMC1HIGH_CLKDIV_REG_ADDR, CLK_MMC1HIGH_CLKDIV_MASK, CLK_MMC1HIGH_CLKDIV_SET_VALID)
MACRO_CLK(clk_mmc1low, CLK_MMC1LOW, OFF, CLK_MMC1LOW_RATE, CLK_MMC1LOW_MIN_RATE, CLK_MMC1LOW_MAX_RATE, &clk_mmc1high, clkfr_mmc1low, \
		NULL, CLK_MMC1LOW_ENABLE_REG_ADDR, CLK_MMC1LOW_ENABLE_BIT_OFFSET, CLK_MMC1LOW_CLKSEL_REG_ADDR, CLK_MMC1LOW_CLKSEL_MASK, \
		CLK_MMC1LOW_CLKSEL_SET_VALID, CLK_MMC1LOW_CLKDIV_REG_ADDR, CLK_MMC1LOW_CLKDIV_MASK, CLK_MMC1LOW_CLKDIV_SET_VALID)
MACRO_CLK(hclk_mmc2, HCLK_MMC2, OFF, HCLK_MMC2_RATE, HCLK_MMC2_MIN_RATE, HCLK_MMC2_MAX_RATE, &clkin_sys, NULL, \
		NULL, HCLK_MMC2_ENABLE_REG_ADDR, HCLK_MMC2_ENABLE_BIT_OFFSET,  NULL, 0, -1, NULL, 0, -1)
MACRO_CLK(clk_dsppll_mmc2_gated, CLK_DSPPLL_MMC2_GATED, OFF, CLK_DSPPLL_MMC2_GATED_RATE, CLK_DSPPLL_MMC2_GATED_MIN_RATE, CLK_DSPPLL_MMC2_GATED_MAX_RATE, &clk_dsppll, NULL, \
		NULL, CLK_DSPPLL_MMC2_GATED_ENABLE_REG_ADDR, CLK_DSPPLL_MMC2_GATED_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)	
static struct clk *clkfr_mmc2low[] = {
	&hclk_mmc2,
      &clk_dsppll_mmc2_gated,  
	NULL,
};		
MACRO_CLK(clk_mmc2high, CLK_MMC2HIGH, OFF, CLK_MMC2HIGH_RATE, CLK_MMC2HIGH_MIN_RATE, CLK_MMC2HIGH_MAX_RATE, &clk_dsppll, NULL, \
		NULL, CLK_MMC2HIGH_ENABLE_REG_ADDR, CLK_MMC2HIGH_ENABLE_BIT_OFFSET, NULL, 0, -1, \
		CLK_MMC2HIGH_CLKDIV_REG_ADDR, CLK_MMC2HIGH_CLKDIV_MASK, CLK_MMC2HIGH_CLKDIV_SET_VALID)
MACRO_CLK(clk_mmc2low, CLK_MMC2LOW, OFF, CLK_MMC2LOW_RATE, CLK_MMC2LOW_MIN_RATE, CLK_MMC2LOW_MAX_RATE, &clk_mmc2high, clkfr_mmc2low, \
		NULL, CLK_MMC2LOW_ENABLE_REG_ADDR, CLK_MMC2LOW_ENABLE_BIT_OFFSET, CLK_MMC2LOW_CLKSEL_REG_ADDR, CLK_MMC2LOW_CLKSEL_MASK, \
		CLK_MMC2LOW_CLKSEL_SET_VALID, CLK_MMC2LOW_CLKDIV_REG_ADDR, CLK_MMC2LOW_CLKDIV_MASK, CLK_MMC2LOW_CLKDIV_SET_VALID)

/* i2c module */
MACRO_CLK(pclk_i2c0, PCLK_I2C0, OFF, PCLK_I2C0_RATE, PCLK_I2C0_MIN_RATE, PCLK_I2C0_MAX_RATE, &clkin_sys, NULL, \
		NULL, PCLK_I2C0_ENABLE_REG_ADDR, PCLK_I2C0_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)	
static struct clk *clkfr_i2c0[] = {
	&pclk_i2c0,
	NULL,
};			
MACRO_CLK(clk_i2c0, CLK_I2C0, OFF, CLK_I2C0_RATE, CLK_I2C0_MIN_RATE, CLK_I2C0_MAX_RATE, &clkin_sys, clkfr_i2c0, \
		NULL, CLK_I2C0_ENABLE_REG_ADDR, CLK_I2C0_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)		
MACRO_CLK(pclk_i2c1, PCLK_I2C1, OFF, PCLK_I2C1_RATE, PCLK_I2C1_MIN_RATE, PCLK_I2C1_MAX_RATE, &clkin_sys, NULL, \
		NULL, PCLK_I2C1_ENABLE_REG_ADDR, PCLK_I2C1_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clk *clkfr_i2c1[] = {
	&pclk_i2c1,
	NULL,
};				
MACRO_CLK(clk_i2c1, CLK_I2C1, OFF, CLK_I2C1_RATE, CLK_I2C1_MIN_RATE, CLK_I2C1_MAX_RATE, &clkin_sys, clkfr_i2c1, \
		NULL, CLK_I2C1_ENABLE_REG_ADDR, CLK_I2C1_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)					
MACRO_CLK(pclk_i2c2, PCLK_I2C2, OFF, PCLK_I2C2_RATE, PCLK_I2C2_MIN_RATE, PCLK_I2C2_MAX_RATE, &clkin_sys, NULL, \
		NULL, PCLK_I2C2_ENABLE_REG_ADDR, PCLK_I2C2_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clk *clkfr_i2c2[] = {
	&pclk_i2c2,
	NULL,
};				
MACRO_CLK(clk_i2c2, CLK_I2C2, OFF, CLK_I2C2_RATE, CLK_I2C2_MIN_RATE, CLK_I2C2_MAX_RATE, &clkin_sys, clkfr_i2c2, \
		NULL, CLK_I2C2_ENABLE_REG_ADDR, CLK_I2C2_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)			
MACRO_CLK(pclk_i2c3, PCLK_I2C3, OFF, PCLK_I2C3_RATE, PCLK_I2C3_MIN_RATE, PCLK_I2C3_MAX_RATE, &clkin_sys, NULL, \
		NULL, PCLK_I2C3_ENABLE_REG_ADDR, PCLK_I2C3_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clk *clkfr_i2c3[] = {
	&pclk_i2c3,
	NULL,
};				
MACRO_CLK(clk_i2c3, CLK_I2C3, OFF, CLK_I2C3_RATE, CLK_I2C3_MIN_RATE, CLK_I2C3_MAX_RATE, &clkin_sys, clkfr_i2c3, \
		NULL, CLK_I2C3_ENABLE_REG_ADDR, CLK_I2C3_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)	
MACRO_CLK(pclk_i2c4, PCLK_I2C4, OFF, PCLK_I2C4_RATE, PCLK_I2C4_MIN_RATE, PCLK_I2C4_MAX_RATE, &clkin_sys, NULL, \
		NULL,PCLK_I2C4_ENABLE_REG_ADDR, PCLK_I2C4_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clk *clkfr_i2c4[] = {
	&pclk_i2c4,
	NULL,
};				
MACRO_CLK(clk_i2c4, CLK_I2C4, OFF, CLK_I2C4_RATE, CLK_I2C4_MIN_RATE, CLK_I2C4_MAX_RATE, &clkin_sys, clkfr_i2c4, \
		NULL, CLK_I2C4_ENABLE_REG_ADDR, CLK_I2C4_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)	
MACRO_CLK(pclk_i2c5, PCLK_I2C5, OFF, PCLK_I2C5_RATE, PCLK_I2C5_MIN_RATE, PCLK_I2C5_MAX_RATE, &clkin_sys, NULL, \
		NULL, PCLK_I2C5_ENABLE_REG_ADDR, PCLK_I2C5_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clk *clkfr_i2c5[] = {
	&pclk_i2c5,
	NULL,
};				
MACRO_CLK(clk_i2c5, CLK_I2C5, OFF, CLK_I2C5_RATE, CLK_I2C5_MIN_RATE, CLK_I2C5_MAX_RATE, &clkin_sys, clkfr_i2c5, \
		NULL, CLK_I2C5_ENABLE_REG_ADDR, CLK_I2C5_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)			
	

/* pwm module */
static struct clksel clksels_pwm0[] = {
	{.sel_parent = &clk_ref, .sel_val = 0x00, 
	.parent_min = CLK_REF_MIN_RATE/CLK_PWM0_DIV_MAX, .parent_max = CLK_REF_MAX_RATE},
	{.sel_parent = &clk_ref32k, .sel_val = 0x01, 
	.parent_min = CLK_REF32K_MIN_RATE/CLK_PWM0_DIV_MAX, .parent_max = CLK_REF32K_MAX_RATE},
	{.sel_parent = NULL},
};	
MACRO_CLK(pclk_pwm0, PCLK_PWM0, OFF, PCLK_PWM0_RATE, PCLK_PWM0_MIN_RATE, PCLK_PWM0_MAX_RATE, &clk_bus_src, NULL, \
		NULL, PCLK_PWM0_ENABLE_REG_ADDR, PCLK_PWM0_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clk *clkfr_pwm0[] = {
	&pclk_pwm0,
	NULL,
};			
MACRO_CLK(clk_pwm0, CLK_PWM0, OFF, CLK_PWM0_RATE, CLK_PWM0_MIN_RATE, CLK_PWM0_MAX_RATE, &clkin_sys, clkfr_pwm0, \
		clksels_pwm0, CLK_PWM0_ENABLE_REG_ADDR, CLK_PWM0_ENABLE_BIT_OFFSET, CLK_PWM0_CLKSEL_REG_ADDR, CLK_PWM0_CLKSEL_MASK, \
		CLK_PWM0_CLKSEL_SET_VALID, CLK_PWM0_CLKDIV_REG_ADDR, CLK_PWM0_CLKDIV_MASK, CLK_PWM0_CLKDIV_SET_VALID)		

static struct clksel clksels_pwm1[] = {
	{.sel_parent = &clk_ref, .sel_val = 0x00, 
	.parent_min = CLK_REF_MIN_RATE/CLK_PWM1_DIV_MAX, .parent_max = CLK_REF_MAX_RATE},
	{.sel_parent = &clk_ref32k, .sel_val = 0x01, 
	.parent_min = CLK_REF32K_MIN_RATE/CLK_PWM1_DIV_MAX, .parent_max = CLK_REF32K_MAX_RATE},
	{.sel_parent = NULL},
};
MACRO_CLK(pclk_pwm1, PCLK_PWM1, OFF, PCLK_PWM1_RATE, PCLK_PWM1_MIN_RATE, PCLK_PWM1_MAX_RATE, &clk_bus_src, NULL, \
		NULL, PCLK_PWM1_ENABLE_REG_ADDR, PCLK_PWM1_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clk *clkfr_pwm1[] = {
	&pclk_pwm1,
	NULL,
};			
MACRO_CLK(clk_pwm1, CLK_PWM1, OFF, CLK_PWM1_RATE, CLK_PWM1_MIN_RATE, CLK_PWM1_MAX_RATE, &clkin_sys, clkfr_pwm1, \
		clksels_pwm1, CLK_PWM1_ENABLE_REG_ADDR, CLK_PWM1_ENABLE_BIT_OFFSET, CLK_PWM1_CLKSEL_REG_ADDR, CLK_PWM1_CLKSEL_MASK, \
		CLK_PWM1_CLKSEL_SET_VALID, CLK_PWM1_CLKDIV_REG_ADDR, CLK_PWM1_CLKDIV_MASK, CLK_PWM1_CLKDIV_SET_VALID)	


/* spi module */
MACRO_CLK(pclk_spi0, PCLK_SPI0, OFF, PCLK_SPI0_RATE, PCLK_SPI0_MIN_RATE, PCLK_SPI0_MAX_RATE, &clkin_sys, NULL, \
		NULL, PCLK_SPI0_ENABLE_REG_ADDR, PCLK_SPI0_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)	
MACRO_CLK(pclk_spi1, PCLK_SPI1, OFF, PCLK_SPI1_RATE, PCLK_SPI1_MIN_RATE, PCLK_SPI1_MAX_RATE, &clkin_sys, NULL, \
		NULL, PCLK_SPI1_ENABLE_REG_ADDR, PCLK_SPI1_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clk *clkfr_spi0[] = {
	&pclk_spi0,
	NULL,
};		
MACRO_CLK(clk_spi0, CLK_SPI0, OFF, CLK_SPI0_RATE, CLK_SPI0_MIN_RATE, CLK_SPI0_MAX_RATE, &clkin_sys, clkfr_spi0, \
		NULL, CLK_SPI0_ENABLE_REG_ADDR, CLK_SPI0_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)	
static struct clk *clkfr_spi1[] = {
	&pclk_spi1,
	NULL,
};		
MACRO_CLK(clk_spi1, CLK_SPI1, OFF, CLK_SPI1_RATE, CLK_SPI1_MIN_RATE, CLK_SPI1_MAX_RATE, &clkin_sys, clkfr_spi1, \
		NULL, CLK_SPI1_ENABLE_REG_ADDR, CLK_SPI1_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)


/* usb module */
MACRO_CLK(hclk_usbotg_on, HCLK_USBOTG_ON, OFF, HCLK_USBOTG_ON_RATE, HCLK_USBOTG_ON_MIN_RATE, HCLK_USBOTG_ON_MAX_RATE, NULL, NULL, \
        NULL, HCLK_USBOTG_ON_ENABLE_REG_ADDR, HCLK_USBOTG_ON_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
MACRO_CLK(hclk_usbotg_off, HCLK_USBOTG_OFF, OFF, HCLK_USBOTG_OFF_RATE, HCLK_USBOTG_OFF_MIN_RATE, HCLK_USBOTG_OFF_MAX_RATE, NULL, NULL, \
        NULL, HCLK_USBOTG_OFF_ENABLE_REG_ADDR, HCLK_USBOTG_OFF_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clk *clkfr_usbotg_off[] = {
	&hclk_usbotg_on,
      &hclk_usbotg_off,
	NULL,
};   
MACRO_CLK(clk_usbotg_off, CLK_USBOTG_OFF, OFF, CLK_USBOTG_OFF_RATE, CLK_USBOTG_OFF_MIN_RATE, CLK_USBOTG_OFF_MAX_RATE, NULL, clkfr_usbotg_off, \
        NULL, CLK_USBOTG_OFF_ENABLE_REG_ADDR, CLK_USBOTG_OFF_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
MACRO_CLK(clk_picophy, CLK_PICOPHY, OFF, CLK_PICOPHY_RATE, CLK_PICOPHY_MIN_RATE, CLK_PICOPHY_MAX_RATE, NULL, NULL, \
        NULL, CLK_PICOPHY_ENABLE_REG_ADDR, CLK_PICOPHY_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
MACRO_CLK(clk_picophy_test, CLK_PICOPHY_TEST, OFF, CLK_PICOPHY_TEST_RATE, CLK_PICOPHY_TEST_MIN_RATE, CLK_PICOPHY_TEST_MAX_RATE, NULL, NULL, \
        NULL, CLK_PICOPHY_TEST_ENABLE_REG_ADDR, CLK_PICOPHY_TEST_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)

/* nandc module */
MACRO_CLK(hclk_nandc, HCLK_NANDC, OFF, HCLK_NANDC_RATE, HCLK_NANDC_MIN_RATE, HCLK_NANDC_MAX_RATE, NULL, NULL, \
        NULL, HCLK_NANDC_ENABLE_REG_ADDR, HCLK_NANDC_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)

/* ap dma module */
MACRO_CLK(clk_ap_dmac_axi0, CLK_AP_DMAC_AXI0, OFF, CLK_AP_DMAC_AXI0_RATE, CLK_AP_DMAC_AXI0_MIN_RATE, CLK_AP_DMAC_AXI0_MAX_RATE, NULL, NULL, \
        NULL, CLK_AP_DMAC_AXI0_ENABLE_REG_ADDR, CLK_AP_DMAC_AXI0_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
MACRO_CLK(clk_ap_dmac_axi1, CLK_AP_DMAC_AXI1, OFF, CLK_AP_DMAC_AXI1_RATE, CLK_AP_DMAC_AXI1_MIN_RATE, CLK_AP_DMAC_AXI1_MAX_RATE, NULL, NULL, \
        NULL, CLK_AP_DMAC_AXI1_ENABLE_REG_ADDR, CLK_AP_DMAC_AXI1_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)

/* rtc module */
MACRO_CLK(clk_rtc, CLK_RTC, OFF, CLK_RTC_RATE, CLK_RTC_MIN_RATE, CLK_RTC_MAX_RATE, NULL, NULL, \
        NULL, CLK_RTC_ENABLE_REG_ADDR, CLK_RTC_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)

/* watchdog module */
MACRO_CLK(pclk_watchdog0, PCLK_WATCHDOG0, OFF, PCLK_WATCHDOG0_RATE, PCLK_WATCHDOG0_MIN_RATE, PCLK_WATCHDOG0_MAX_RATE, NULL, NULL, \
        NULL, PCLK_WATCHDOG0_ENABLE_REG_ADDR, PCLK_WATCHDOG0_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clk *clkfr_watchdog0[] = {
	&pclk_watchdog0,
	NULL,
};                
MACRO_CLK(clk_watchdog0, CLK_WATCHDOG0, OFF, CLK_WATCHDOG0_RATE, CLK_WATCHDOG0_MIN_RATE, CLK_WATCHDOG0_MAX_RATE, NULL, clkfr_watchdog0, \
        NULL, CLK_WATCHDOG0_ENABLE_REG_ADDR, CLK_WATCHDOG0_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)


/* TS module */
MACRO_CLK(hclk_ts, HCLK_TS, OFF, HCLK_TS_RATE, HCLK_TS_MIN_RATE, HCLK_TS_MAX_RATE, NULL, NULL, \
        NULL, HCLK_TS_ENABLE_REG_ADDR, HCLK_TS_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clk *clkfr_ts[] = {
	&hclk_ts,
	NULL,
};        
MACRO_CLK(clk_ts, CLK_TS, OFF, CLK_TS_RATE, CLK_TS_MIN_RATE, CLK_TS_MAX_RATE, NULL, clkfr_ts, \
        NULL, CLK_TS_ENABLE_REG_ADDR, CLK_TS_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)


/* GPS module */
MACRO_CLK(clk_gps, CLK_GPS, OFF, CLK_GPS_RATE, CLK_GPS_MIN_RATE, CLK_GPS_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPS_ENABLE_REG_ADDR, CLK_GPS_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
        
/* Tsensor module */
MACRO_CLK(clk_tsensor0, CLK_TSENSOR0, OFF, CLK_TSENSOR0_RATE, CLK_TSENSOR0_MIN_RATE, CLK_TSENSOR0_MAX_RATE, NULL, NULL, \
        NULL, CLK_TSENSOR0_ENABLE_REG_ADDR, CLK_TSENSOR0_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
MACRO_CLK(clk_tsensor1, CLK_TSENSOR1, OFF, CLK_TSENSOR1_RATE, CLK_TSENSOR1_MIN_RATE, CLK_TSENSOR1_MAX_RATE, NULL, NULL, \
        NULL, CLK_TSENSOR1_ENABLE_REG_ADDR, CLK_TSENSOR1_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)

/* timer 0~8 */
MACRO_CLK(pclk_timer0, PCLK_TIMER0, OFF, PCLK_TIMER0_RATE, PCLK_TIMER0_MIN_RATE, PCLK_TIMER0_MAX_RATE, NULL, NULL, \
        NULL, PCLK_TIMER0_ENABLE_REG_ADDR, PCLK_TIMER0_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clksel clksels_timer0[] = {
	{.sel_parent = &clkin_sys, .sel_val = 0x00, 
	.parent_min = CLKIN_SYS_MIN_RATE, .parent_max = CLKIN_SYS_MAX_RATE},
	{.sel_parent = &clk_ref, .sel_val = 0x01, 
	.parent_min = CLK_REF_MIN_RATE, .parent_max = CLK_REF_MAX_RATE},
	{.sel_parent = &clk_ref32k, .sel_val = 0x03, 
	.parent_min = CLK_REF32K_MIN_RATE, .parent_max = CLK_REF32K_MAX_RATE},
	{.sel_parent = NULL},
};
static struct clk *clkfr_timer0[] = {
	&pclk_timer0,
	NULL,
};
MACRO_CLK(clk_timer0, CLK_TIMER0, OFF, CLK_TIMER0_RATE, CLK_TIMER0_MIN_RATE, CLK_TIMER0_MAX_RATE, &clkin_sys, clkfr_timer0, \
        clksels_timer0, CLK_TIMER0_ENABLE_REG_ADDR, CLK_TIMER0_ENABLE_BIT_OFFSET, CLK_TIMER0_CLKSEL_REG_ADDR, CLK_TIMER0_CLKSEL_MASK, \
		CLK_TIMER0_CLKSEL_SET_VALID, NULL, 0, -1)
		
MACRO_CLK(pclk_timer1, PCLK_TIMER1, OFF, PCLK_TIMER1_RATE, PCLK_TIMER1_MIN_RATE, PCLK_TIMER1_MAX_RATE, NULL, NULL, \
        NULL, PCLK_TIMER1_ENABLE_REG_ADDR, PCLK_TIMER1_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clksel clksels_timer1[] = {
	{.sel_parent = &clkin_sys, .sel_val = 0x00, 
	.parent_min = CLKIN_SYS_MIN_RATE, .parent_max = CLKIN_SYS_MAX_RATE},
	{.sel_parent = &clk_ref, .sel_val = 0x01, 
	.parent_min = CLK_REF_MIN_RATE, .parent_max = CLK_REF_MAX_RATE},
	{.sel_parent = &clk_ref32k, .sel_val = 0x03, 
	.parent_min = CLK_REF32K_MIN_RATE, .parent_max = CLK_REF32K_MAX_RATE},
	{.sel_parent = NULL},
};
static struct clk *clkfr_timer1[] = {
	&pclk_timer1,
	NULL,
};
MACRO_CLK(clk_timer1, CLK_TIMER1, OFF, CLK_TIMER1_RATE, CLK_TIMER1_MIN_RATE, CLK_TIMER1_MAX_RATE, &clkin_sys, clkfr_timer1, \
        clksels_timer1, CLK_TIMER1_ENABLE_REG_ADDR, CLK_TIMER1_ENABLE_BIT_OFFSET, CLK_TIMER1_CLKSEL_REG_ADDR, CLK_TIMER1_CLKSEL_MASK, \
		CLK_TIMER1_CLKSEL_SET_VALID, NULL, 0, -1)
MACRO_CLK(pclk_timer2, PCLK_TIMER2, OFF, PCLK_TIMER2_RATE, PCLK_TIMER2_MIN_RATE, PCLK_TIMER2_MAX_RATE, NULL, NULL, \
        NULL, PCLK_TIMER2_ENABLE_REG_ADDR, PCLK_TIMER2_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clksel clksels_timer2[] = {
	{.sel_parent = &clkin_sys, .sel_val = 0x00, 
	.parent_min = CLKIN_SYS_MIN_RATE, .parent_max = CLKIN_SYS_MAX_RATE},
	{.sel_parent = &clk_ref, .sel_val = 0x01, 
	.parent_min = CLK_REF_MIN_RATE, .parent_max = CLK_REF_MAX_RATE},
	{.sel_parent = &clk_ref32k, .sel_val = 0x03, 
	.parent_min = CLK_REF32K_MIN_RATE, .parent_max = CLK_REF32K_MAX_RATE},
	{.sel_parent = NULL},
};
static struct clk *clkfr_timer2[] = {
	&pclk_timer2,
	NULL,
};
MACRO_CLK(clk_timer2, CLK_TIMER2, OFF, CLK_TIMER2_RATE, CLK_TIMER2_MIN_RATE, CLK_TIMER2_MAX_RATE, &clkin_sys, clkfr_timer2, \
        clksels_timer2, CLK_TIMER2_ENABLE_REG_ADDR, CLK_TIMER2_ENABLE_BIT_OFFSET, CLK_TIMER2_CLKSEL_REG_ADDR, CLK_TIMER2_CLKSEL_MASK, \
		CLK_TIMER2_CLKSEL_SET_VALID,  NULL, 0, -1)
MACRO_CLK(pclk_timer3, PCLK_TIMER3, OFF, PCLK_TIMER3_RATE, PCLK_TIMER3_MIN_RATE, PCLK_TIMER3_MAX_RATE, NULL, NULL, \
        NULL, PCLK_TIMER3_ENABLE_REG_ADDR, PCLK_TIMER3_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clksel clksels_timer3[] = {
	{.sel_parent = &clkin_sys, .sel_val = 0x00, 
	.parent_min = CLKIN_SYS_MIN_RATE, .parent_max = CLKIN_SYS_MAX_RATE},
	{.sel_parent = &clk_ref, .sel_val = 0x01, 
	.parent_min = CLK_REF_MIN_RATE, .parent_max = CLK_REF_MAX_RATE},
	{.sel_parent = &clk_ref32k, .sel_val = 0x03, 
	.parent_min = CLK_REF32K_MIN_RATE, .parent_max = CLK_REF32K_MAX_RATE},
	{.sel_parent = NULL},
};
static struct clk *clkfr_timer3[] = {
	&pclk_timer3,
	NULL,
};
MACRO_CLK(clk_timer3, CLK_TIMER3, OFF, CLK_TIMER3_RATE, CLK_TIMER3_MIN_RATE, CLK_TIMER3_MAX_RATE, &clkin_sys, clkfr_timer3, \
        clksels_timer3, CLK_TIMER3_ENABLE_REG_ADDR, CLK_TIMER3_ENABLE_BIT_OFFSET, CLK_TIMER3_CLKSEL_REG_ADDR, CLK_TIMER3_CLKSEL_MASK, \
		CLK_TIMER3_CLKSEL_SET_VALID, NULL, 0, -1)
MACRO_CLK(pclk_timer4, PCLK_TIMER4, OFF, PCLK_TIMER4_RATE, PCLK_TIMER4_MIN_RATE, PCLK_TIMER4_MAX_RATE, NULL, NULL, \
        NULL, PCLK_TIMER4_ENABLE_REG_ADDR, PCLK_TIMER4_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clksel clksels_timer4[] = {
	{.sel_parent = &clkin_sys, .sel_val = 0x00, 
	.parent_min = CLKIN_SYS_MIN_RATE, .parent_max = CLKIN_SYS_MAX_RATE},
	{.sel_parent = &clk_ref, .sel_val = 0x01, 
	.parent_min = CLK_REF_MIN_RATE, .parent_max = CLK_REF_MAX_RATE},
	{.sel_parent = &clk_ref32k, .sel_val = 0x03, 
	.parent_min = CLK_REF32K_MIN_RATE, .parent_max = CLK_REF32K_MAX_RATE},
	{.sel_parent = NULL},
};
static struct clk *clkfr_timer4[] = {
	&pclk_timer4,
	NULL,
};
MACRO_CLK(clk_timer4, CLK_TIMER4, OFF, CLK_TIMER4_RATE, CLK_TIMER4_MIN_RATE, CLK_TIMER4_MAX_RATE, &clkin_sys, clkfr_timer4, \
        clksels_timer4, CLK_TIMER4_ENABLE_REG_ADDR, CLK_TIMER4_ENABLE_BIT_OFFSET, CLK_TIMER4_CLKSEL_REG_ADDR, CLK_TIMER4_CLKSEL_MASK, \
		CLK_TIMER4_CLKSEL_SET_VALID, NULL, 0, -1)
MACRO_CLK(pclk_timer5, PCLK_TIMER5, OFF, PCLK_TIMER5_RATE, PCLK_TIMER5_MIN_RATE, PCLK_TIMER5_MAX_RATE, NULL, NULL, \
        NULL, PCLK_TIMER5_ENABLE_REG_ADDR, PCLK_TIMER5_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clksel clksels_timer5[] = {
	{.sel_parent = &clkin_sys, .sel_val = 0x00, 
	.parent_min = CLKIN_SYS_MIN_RATE, .parent_max = CLKIN_SYS_MAX_RATE},
	{.sel_parent = &clk_ref, .sel_val = 0x01, 
	.parent_min = CLK_REF_MIN_RATE, .parent_max = CLK_REF_MAX_RATE},
	{.sel_parent = &clk_ref32k, .sel_val = 0x03, 
	.parent_min = CLK_REF32K_MIN_RATE, .parent_max = CLK_REF32K_MAX_RATE},
	{.sel_parent = NULL},
};
static struct clk *clkfr_timer5[] = {
	&pclk_timer5,
	NULL,
};
MACRO_CLK(clk_timer5, CLK_TIMER5, OFF, CLK_TIMER5_RATE, CLK_TIMER5_MIN_RATE, CLK_TIMER5_MAX_RATE, &clkin_sys, clkfr_timer5, \
        clksels_timer5, CLK_TIMER5_ENABLE_REG_ADDR, CLK_TIMER5_ENABLE_BIT_OFFSET, CLK_TIMER5_CLKSEL_REG_ADDR, CLK_TIMER5_CLKSEL_MASK, \
		CLK_TIMER5_CLKSEL_SET_VALID, NULL, 0, -1)
MACRO_CLK(pclk_timer6, PCLK_TIMER6, OFF, PCLK_TIMER6_RATE, PCLK_TIMER6_MIN_RATE, PCLK_TIMER6_MAX_RATE, NULL, NULL, \
        NULL, PCLK_TIMER6_ENABLE_REG_ADDR, PCLK_TIMER6_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clksel clksels_timer6[] = {
	{.sel_parent = &clkin_sys, .sel_val = 0x00, 
	.parent_min = CLKIN_SYS_MIN_RATE, .parent_max = CLKIN_SYS_MAX_RATE},
	{.sel_parent = &clk_ref, .sel_val = 0x01, 
	.parent_min = CLK_REF_MIN_RATE, .parent_max = CLK_REF_MAX_RATE},
	{.sel_parent = &clk_ref32k, .sel_val = 0x03, 
	.parent_min = CLK_REF32K_MIN_RATE, .parent_max = CLK_REF32K_MAX_RATE},
	{.sel_parent = NULL},
};
static struct clk *clkfr_timer6[] = {
	&pclk_timer6,
	NULL,
};
MACRO_CLK(clk_timer6, CLK_TIMER6, OFF, CLK_TIMER6_RATE, CLK_TIMER6_MIN_RATE, CLK_TIMER6_MAX_RATE, &clkin_sys, clkfr_timer6, \
        clksels_timer6, CLK_TIMER6_ENABLE_REG_ADDR, CLK_TIMER6_ENABLE_BIT_OFFSET, CLK_TIMER6_CLKSEL_REG_ADDR, CLK_TIMER6_CLKSEL_MASK, \
		CLK_TIMER6_CLKSEL_SET_VALID, NULL, 0, -1)
MACRO_CLK(pclk_timer7, PCLK_TIMER7, OFF, PCLK_TIMER7_RATE, PCLK_TIMER7_MIN_RATE, PCLK_TIMER7_MAX_RATE, NULL, NULL, \
        NULL, PCLK_TIMER7_ENABLE_REG_ADDR, PCLK_TIMER7_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clksel clksels_timer7[] = {
	{.sel_parent = &clkin_sys, .sel_val = 0x00, 
	.parent_min = CLKIN_SYS_MIN_RATE, .parent_max = CLKIN_SYS_MAX_RATE},
	{.sel_parent = &clk_ref, .sel_val = 0x01, 
	.parent_min = CLK_REF_MIN_RATE, .parent_max = CLK_REF_MAX_RATE},
	{.sel_parent = &clk_ref32k, .sel_val = 0x03, 
	.parent_min = CLK_REF32K_MIN_RATE, .parent_max = CLK_REF32K_MAX_RATE},
	{.sel_parent = NULL},
};
static struct clk *clkfr_timer7[] = {
	&pclk_timer7,
	NULL,
};
MACRO_CLK(clk_timer7, CLK_TIMER7, OFF, CLK_TIMER7_RATE, CLK_TIMER7_MIN_RATE, CLK_TIMER7_MAX_RATE, &clkin_sys, clkfr_timer7, \
        clksels_timer7, CLK_TIMER7_ENABLE_REG_ADDR, CLK_TIMER7_ENABLE_BIT_OFFSET, CLK_TIMER7_CLKSEL_REG_ADDR, CLK_TIMER7_CLKSEL_MASK, \
		CLK_TIMER7_CLKSEL_SET_VALID, NULL, 0, -1)

MACRO_CLK(pclk_timer8, PCLK_TIMER8, OFF, PCLK_TIMER8_RATE, PCLK_TIMER8_MIN_RATE, PCLK_TIMER8_MAX_RATE, NULL, NULL, \
        NULL, PCLK_TIMER8_ENABLE_REG_ADDR, PCLK_TIMER8_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)
static struct clksel clksels_timer8[] = {
	{.sel_parent = &clkin_sys, .sel_val = 0x00, 
	.parent_min = CLKIN_SYS_MIN_RATE, .parent_max = CLKIN_SYS_MAX_RATE},
	{.sel_parent = &clk_ref, .sel_val = 0x01, 
	.parent_min = CLK_REF_MIN_RATE, .parent_max = CLK_REF_MAX_RATE},
	{.sel_parent = &clk_ref32k, .sel_val = 0x03, 
	.parent_min = CLK_REF32K_MIN_RATE, .parent_max = CLK_REF32K_MAX_RATE},
	{.sel_parent = NULL},
};
static struct clk *clkfr_timer8[] = {
	&pclk_timer8,
	NULL,
};
MACRO_CLK(clk_timer8, CLK_TIMER8, OFF, CLK_TIMER8_RATE, CLK_TIMER8_MIN_RATE, CLK_TIMER8_MAX_RATE, &clkin_sys, clkfr_timer8, \
        clksels_timer8, CLK_TIMER8_ENABLE_REG_ADDR, CLK_TIMER8_ENABLE_BIT_OFFSET, CLK_TIMER8_CLKSEL_REG_ADDR, CLK_TIMER8_CLKSEL_MASK, \
		CLK_TIMER8_CLKSEL_SET_VALID, NULL, 0, -1)

MACRO_CLK(clk_pmussi, CLK_PMUSSI, OFF, CLK_PMUSSI_RATE, CLK_PMUSSI_MIN_RATE, CLK_PMUSSI_MAX_RATE, NULL, NULL, \
        NULL, CLK_PMUSSI_ENABLE_REG_ADDR, CLK_PMUSSI_ENABLE_BIT_OFFSET, NULL, 0, -1, NULL, 0, -1)


MACRO_CLK(clk_gpio0, CLK_GPIO0, OFF, CLK_GPIO0_RATE, CLK_GPIO0_MIN_RATE, CLK_GPIO0_MAX_RATE, NULL, NULL, \
               NULL, CLK_GPIO0_ENABLE_REG_ADDR, CLK_GPIO0_ENABLE_BIT_OFFSET, CLK_GPIO0_CLKSEL_REG_ADDR, CLK_GPIO0_CLKSEL_MASK, \
               CLK_GPIO0_CLKSEL_SET_VALID, CLK_GPIO0_CLKDIV_REG_ADDR, CLK_GPIO0_CLKDIV_MASK, CLK_GPIO0_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio1, CLK_GPIO1, OFF, CLK_GPIO1_RATE, CLK_GPIO1_MIN_RATE, CLK_GPIO1_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO1_ENABLE_REG_ADDR, CLK_GPIO1_ENABLE_BIT_OFFSET, CLK_GPIO1_CLKSEL_REG_ADDR, CLK_GPIO1_CLKSEL_MASK, \
        CLK_GPIO1_CLKSEL_SET_VALID, CLK_GPIO1_CLKDIV_REG_ADDR, CLK_GPIO1_CLKDIV_MASK, CLK_GPIO1_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio2, CLK_GPIO2, OFF, CLK_GPIO2_RATE, CLK_GPIO2_MIN_RATE, CLK_GPIO2_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO2_ENABLE_REG_ADDR, CLK_GPIO2_ENABLE_BIT_OFFSET, CLK_GPIO2_CLKSEL_REG_ADDR, CLK_GPIO2_CLKSEL_MASK, \
        CLK_GPIO2_CLKSEL_SET_VALID, CLK_GPIO2_CLKDIV_REG_ADDR, CLK_GPIO2_CLKDIV_MASK, CLK_GPIO2_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio3, CLK_GPIO3, OFF, CLK_GPIO3_RATE, CLK_GPIO3_MIN_RATE, CLK_GPIO3_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO3_ENABLE_REG_ADDR, CLK_GPIO3_ENABLE_BIT_OFFSET, CLK_GPIO3_CLKSEL_REG_ADDR, CLK_GPIO3_CLKSEL_MASK, \
        CLK_GPIO3_CLKSEL_SET_VALID, CLK_GPIO3_CLKDIV_REG_ADDR, CLK_GPIO3_CLKDIV_MASK, CLK_GPIO3_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio4, CLK_GPIO4, OFF, CLK_GPIO4_RATE, CLK_GPIO4_MIN_RATE, CLK_GPIO4_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO4_ENABLE_REG_ADDR, CLK_GPIO4_ENABLE_BIT_OFFSET, CLK_GPIO4_CLKSEL_REG_ADDR, CLK_GPIO4_CLKSEL_MASK, \
        CLK_GPIO4_CLKSEL_SET_VALID, CLK_GPIO4_CLKDIV_REG_ADDR, CLK_GPIO4_CLKDIV_MASK, CLK_GPIO4_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio5, CLK_GPIO5, OFF, CLK_GPIO5_RATE, CLK_GPIO5_MIN_RATE, CLK_GPIO5_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO5_ENABLE_REG_ADDR, CLK_GPIO5_ENABLE_BIT_OFFSET, CLK_GPIO5_CLKSEL_REG_ADDR, CLK_GPIO5_CLKSEL_MASK, \
        CLK_GPIO5_CLKSEL_SET_VALID, CLK_GPIO5_CLKDIV_REG_ADDR, CLK_GPIO5_CLKDIV_MASK, CLK_GPIO5_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio6, CLK_GPIO6, OFF, CLK_GPIO6_RATE, CLK_GPIO6_MIN_RATE, CLK_GPIO6_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO6_ENABLE_REG_ADDR, CLK_GPIO6_ENABLE_BIT_OFFSET, CLK_GPIO6_CLKSEL_REG_ADDR, CLK_GPIO6_CLKSEL_MASK, \
        CLK_GPIO6_CLKSEL_SET_VALID, CLK_GPIO6_CLKDIV_REG_ADDR, CLK_GPIO6_CLKDIV_MASK, CLK_GPIO6_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio7, CLK_GPIO7, OFF, CLK_GPIO7_RATE, CLK_GPIO7_MIN_RATE, CLK_GPIO7_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO7_ENABLE_REG_ADDR, CLK_GPIO7_ENABLE_BIT_OFFSET, CLK_GPIO7_CLKSEL_REG_ADDR, CLK_GPIO7_CLKSEL_MASK, \
        CLK_GPIO7_CLKSEL_SET_VALID, CLK_GPIO7_CLKDIV_REG_ADDR, CLK_GPIO7_CLKDIV_MASK, CLK_GPIO7_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio8, CLK_GPIO8, OFF, CLK_GPIO8_RATE, CLK_GPIO8_MIN_RATE, CLK_GPIO8_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO8_ENABLE_REG_ADDR, CLK_GPIO8_ENABLE_BIT_OFFSET, CLK_GPIO8_CLKSEL_REG_ADDR, CLK_GPIO8_CLKSEL_MASK, \
        CLK_GPIO8_CLKSEL_SET_VALID, CLK_GPIO8_CLKDIV_REG_ADDR, CLK_GPIO8_CLKDIV_MASK, CLK_GPIO8_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio9, CLK_GPIO9, OFF, CLK_GPIO9_RATE, CLK_GPIO9_MIN_RATE, CLK_GPIO9_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO9_ENABLE_REG_ADDR, CLK_GPIO9_ENABLE_BIT_OFFSET, CLK_GPIO9_CLKSEL_REG_ADDR, CLK_GPIO9_CLKSEL_MASK, \
        CLK_GPIO9_CLKSEL_SET_VALID, CLK_GPIO9_CLKDIV_REG_ADDR, CLK_GPIO9_CLKDIV_MASK, CLK_GPIO9_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio10, CLK_GPIO10, OFF, CLK_GPIO10_RATE, CLK_GPIO10_MIN_RATE, CLK_GPIO10_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO10_ENABLE_REG_ADDR, CLK_GPIO10_ENABLE_BIT_OFFSET, CLK_GPIO10_CLKSEL_REG_ADDR, CLK_GPIO10_CLKSEL_MASK, \
        CLK_GPIO10_CLKSEL_SET_VALID, CLK_GPIO10_CLKDIV_REG_ADDR, CLK_GPIO10_CLKDIV_MASK, CLK_GPIO10_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio11, CLK_GPIO11, OFF, CLK_GPIO11_RATE, CLK_GPIO11_MIN_RATE, CLK_GPIO11_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO11_ENABLE_REG_ADDR, CLK_GPIO11_ENABLE_BIT_OFFSET, CLK_GPIO11_CLKSEL_REG_ADDR, CLK_GPIO11_CLKSEL_MASK, \
        CLK_GPIO11_CLKSEL_SET_VALID, CLK_GPIO11_CLKDIV_REG_ADDR, CLK_GPIO11_CLKDIV_MASK, CLK_GPIO11_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio12, CLK_GPIO12, OFF, CLK_GPIO12_RATE, CLK_GPIO12_MIN_RATE, CLK_GPIO12_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO12_ENABLE_REG_ADDR, CLK_GPIO12_ENABLE_BIT_OFFSET, CLK_GPIO12_CLKSEL_REG_ADDR, CLK_GPIO12_CLKSEL_MASK, \
        CLK_GPIO12_CLKSEL_SET_VALID, CLK_GPIO12_CLKDIV_REG_ADDR, CLK_GPIO12_CLKDIV_MASK, CLK_GPIO12_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio13, CLK_GPIO13, OFF, CLK_GPIO13_RATE, CLK_GPIO13_MIN_RATE, CLK_GPIO13_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO13_ENABLE_REG_ADDR, CLK_GPIO13_ENABLE_BIT_OFFSET, CLK_GPIO13_CLKSEL_REG_ADDR, CLK_GPIO13_CLKSEL_MASK, \
        CLK_GPIO13_CLKSEL_SET_VALID, CLK_GPIO13_CLKDIV_REG_ADDR, CLK_GPIO13_CLKDIV_MASK, CLK_GPIO13_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio14, CLK_GPIO14, OFF, CLK_GPIO14_RATE, CLK_GPIO14_MIN_RATE, CLK_GPIO14_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO14_ENABLE_REG_ADDR, CLK_GPIO14_ENABLE_BIT_OFFSET, CLK_GPIO14_CLKSEL_REG_ADDR, CLK_GPIO14_CLKSEL_MASK, \
        CLK_GPIO14_CLKSEL_SET_VALID, CLK_GPIO14_CLKDIV_REG_ADDR, CLK_GPIO14_CLKDIV_MASK, CLK_GPIO14_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio15, CLK_GPIO15, OFF, CLK_GPIO15_RATE, CLK_GPIO15_MIN_RATE, CLK_GPIO15_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO15_ENABLE_REG_ADDR, CLK_GPIO15_ENABLE_BIT_OFFSET, CLK_GPIO15_CLKSEL_REG_ADDR, CLK_GPIO15_CLKSEL_MASK, \
        CLK_GPIO15_CLKSEL_SET_VALID, CLK_GPIO15_CLKDIV_REG_ADDR, CLK_GPIO15_CLKDIV_MASK, CLK_GPIO15_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio16, CLK_GPIO16, OFF, CLK_GPIO16_RATE, CLK_GPIO16_MIN_RATE, CLK_GPIO16_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO16_ENABLE_REG_ADDR, CLK_GPIO16_ENABLE_BIT_OFFSET, CLK_GPIO16_CLKSEL_REG_ADDR, CLK_GPIO16_CLKSEL_MASK, \
        CLK_GPIO16_CLKSEL_SET_VALID, CLK_GPIO16_CLKDIV_REG_ADDR, CLK_GPIO16_CLKDIV_MASK, CLK_GPIO16_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio17, CLK_GPIO17, OFF, CLK_GPIO17_RATE, CLK_GPIO17_MIN_RATE, CLK_GPIO17_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO17_ENABLE_REG_ADDR, CLK_GPIO17_ENABLE_BIT_OFFSET, CLK_GPIO17_CLKSEL_REG_ADDR, CLK_GPIO17_CLKSEL_MASK, \
        CLK_GPIO17_CLKSEL_SET_VALID, CLK_GPIO17_CLKDIV_REG_ADDR, CLK_GPIO17_CLKDIV_MASK, CLK_GPIO17_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio18, CLK_GPIO18, OFF, CLK_GPIO18_RATE, CLK_GPIO18_MIN_RATE, CLK_GPIO18_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO18_ENABLE_REG_ADDR, CLK_GPIO18_ENABLE_BIT_OFFSET, CLK_GPIO18_CLKSEL_REG_ADDR, CLK_GPIO18_CLKSEL_MASK, \
        CLK_GPIO18_CLKSEL_SET_VALID, CLK_GPIO18_CLKDIV_REG_ADDR, CLK_GPIO18_CLKDIV_MASK, CLK_GPIO18_CLKDIV_SET_VALID)

MACRO_CLK(clk_gpio19, CLK_GPIO19, OFF, CLK_GPIO19_RATE, CLK_GPIO19_MIN_RATE, CLK_GPIO19_MAX_RATE, NULL, NULL, \
        NULL, CLK_GPIO19_ENABLE_REG_ADDR, CLK_GPIO19_ENABLE_BIT_OFFSET, CLK_GPIO19_CLKSEL_REG_ADDR, CLK_GPIO19_CLKSEL_MASK, \
        CLK_GPIO19_CLKSEL_SET_VALID, CLK_GPIO19_CLKDIV_REG_ADDR, CLK_GPIO19_CLKDIV_MASK, CLK_GPIO19_CLKDIV_SET_VALID)


#define _REGISTER_CLOCK(d, n, c) \
		.dev_id = d, \
		.con_id = n, \
		.clk = &c,

struct clk_lookup k3v2_clk_lookups[] = {
	/*source  clock*/
	{_REGISTER_CLOCK(NULL,	"clkin_sys", 		clkin_sys)},
	{_REGISTER_CLOCK(NULL,	"clk_ref", 		clk_ref)},	
	{_REGISTER_CLOCK(NULL,	"clk_ref32k", 	clk_ref32k)},
	{_REGISTER_CLOCK(NULL,	"clk_dsppll", 	clk_dsppll)},
	{_REGISTER_CLOCK(NULL,	"clk_gpll0", 		clk_gpll0)},
	{_REGISTER_CLOCK(NULL,	"clk_gpll1", 		clk_gpll1)}, 
	{_REGISTER_CLOCK(NULL,	"clk_peripll", 	clk_peripll)},
	{_REGISTER_CLOCK(NULL,	"clk_hdmipll", 	clk_hdmipll)},
	{_REGISTER_CLOCK(NULL,	"clk_ddrpll", 	clk_ddrpll)},  
	{_REGISTER_CLOCK(NULL,	"clk_300m_src", 	clk_300m_src)},
	{_REGISTER_CLOCK(NULL,	"clk_100m_src", 	clk_100m_src)},
	{_REGISTER_CLOCK(NULL,	"clk_bus_src", 	clk_bus_src)},
    /* PMU 32K clock */
	{_REGISTER_CLOCK(NULL,	"clk_pmu32kb", 	clk_pmu32kb)},
	{_REGISTER_CLOCK(NULL,	"clk_pmu32kc", 	clk_pmu32kc)},
    /* media axi bus */
	{_REGISTER_CLOCK(NULL,	"clk_axi_video_bus", 			clk_axi_video_bus)},
	{_REGISTER_CLOCK(NULL,	"clk_axi_img_bus", 			clk_axi_img_bus)},
    /* edc0 clocks */
	{_REGISTER_CLOCK(NULL,	"clk_dsppll_edc0_core_gated", 	clk_dsppll_edc0_core_gated)},
	{_REGISTER_CLOCK(NULL,	"clk_edc0_core", 				clk_edc0_core)},
	{_REGISTER_CLOCK(NULL,	"clk_mux_edc0_pix_gated", 		clk_mux_edc0_pix_gated)},
	{_REGISTER_CLOCK(NULL,	"clk_edc0_pix_ldi", 			clk_edc0_pix_ldi)},
    {_REGISTER_CLOCK(NULL,  "clk_edc0_cfg_clk",             clk_edc0_cfg_clk)},	
	{_REGISTER_CLOCK(NULL,	"clk_aclk_edc0", 			clk_aclk_edc0)},
	{_REGISTER_CLOCK(NULL,	"clk_dsio_cfg_clk", 			clk_dsio_cfg_clk)},
	/* g2d clocks */
	{_REGISTER_CLOCK(NULL,	"clk_dsppll_g2dcore_gated", 	clk_dsppll_g2dcore_gated)},
	{_REGISTER_CLOCK(NULL,	"clk_5g2d_core_clk", 			clk_5g2d_core_clk)},
	{_REGISTER_CLOCK(NULL,	"clk_4g2d_axi_clkhb", 			clk_4g2d_axi_clkhb)},
	{_REGISTER_CLOCK(NULL,	"clk_3g2d_cfg_clk", 			clk_3g2d_cfg_clk)},
	/* mali clocks */
	{_REGISTER_CLOCK(NULL,	"clk_mali", 					clk_mali)},	
	{_REGISTER_CLOCK(NULL,	"clk_p2p_mali_brg_s", 			clk_p2p_mali_brg_s)},
	{_REGISTER_CLOCK(NULL,	"clk_x2x_mali_brg_s", 			clk_x2x_mali_brg_s)},
	{_REGISTER_CLOCK(NULL,	"clk_x2x_mali_brg_m", 			clk_x2x_mali_brg_m)},
	{_REGISTER_CLOCK(NULL,	"clk_axi_mali_bus", 			clk_axi_mali_bus)},
/* edc1 clocks */	/* edc1 clocks */
    {_REGISTER_CLOCK(NULL,	"clk_edc1_core", 				clk_edc1_core)}, 
	{_REGISTER_CLOCK(NULL,	"clk_edc1_pix_ldi", 			clk_edc1_pix_ldi)},
	{_REGISTER_CLOCK(NULL,	"clk_edc1_axi", 				clk_edc1_axi)},
	{_REGISTER_CLOCK(NULL,	"clk_edc1_cfg_clk", 			clk_edc1_cfg_clk)},
	{_REGISTER_CLOCK(NULL,	"clk_hdmi_slave", 			clk_hdmi_slave)},
	/* asp clocks */
	{_REGISTER_CLOCK(NULL,	"clk_hdmi_sck", 				clk_hdmi_sck)},
	{_REGISTER_CLOCK(NULL,	"clk_mclk_hdmi", 				clk_mclk_hdmi)},
	{_REGISTER_CLOCK(NULL,	"clk_asp_hdmi_adws", 			clk_asp_hdmi_adws)},
	{_REGISTER_CLOCK(NULL,	"clk_asp_hdmi_bclk", 			clk_asp_hdmi_bclk)},
	{_REGISTER_CLOCK(NULL,	"clk_asp_hdmi_ref", 			clk_asp_hdmi_ref)},
	{_REGISTER_CLOCK(NULL,	"clk_asp_spdif_ref", 		clk_asp_spdif_ref)},
	{_REGISTER_CLOCK(NULL,	"clk_asp_cfg", 		        clk_asp_cfg)},
       /* isp clocks */
	{_REGISTER_CLOCK(NULL,	"clk_isp_cfg_clk", 			clk_isp_cfg_clk)},
	{_REGISTER_CLOCK(NULL,	"clk_isp_axi", 				clk_isp_axi)},
	{_REGISTER_CLOCK(NULL,	"clk_peripll_isp_gated", 		clk_peripll_isp_gated)},
	{_REGISTER_CLOCK(NULL,	"clk_isp", 					clk_isp)},
	{_REGISTER_CLOCK(NULL,	"clk_peripll_isp_ref_gated", 	clk_peripll_isp_ref_gated)},
	{_REGISTER_CLOCK(NULL,	"clk_isp_ref", 				clk_isp_ref)},
	{_REGISTER_CLOCK(NULL,		"clk_csi_apb_mux", 				clk_csi_apb_mux)},
	{_REGISTER_CLOCK(NULL,		"clk_csio_cfg", 					clk_csio_cfg)},
	{_REGISTER_CLOCK(NULL,		"csi2_cfg_clk", 					csi2_cfg_clk)},
       /* vpp clocks */
	{_REGISTER_CLOCK(NULL,	"clk_peripll_vpp_gated", 		clk_peripll_vpp_gated)},
	{_REGISTER_CLOCK(NULL,	"clk_2vpp_slave_clk", 			clk_2vpp_slave_clk)},
	{_REGISTER_CLOCK(NULL,	"clk_x2x_vpp_brg_s", 			clk_x2x_vpp_brg_s)},
	{_REGISTER_CLOCK(NULL,	"clk_p2p_vpp_brg_s", 			clk_p2p_vpp_brg_s)},
	/* venc clocks */
	{_REGISTER_CLOCK(NULL,	"clk_peripll_venc_gated", 		clk_peripll_venc_gated)},
      {_REGISTER_CLOCK(NULL,	"clk_0venc_slave_clk", 		clk_0venc_slave_clk)},
	{_REGISTER_CLOCK(NULL,	"clk_x2x_venc_brg_s", 			clk_x2x_venc_brg_s)},
	{_REGISTER_CLOCK(NULL,	"clk_p2p_venc_brg_s", 			clk_p2p_venc_brg_s)},
	/* vdec clocks */
	{_REGISTER_CLOCK(NULL,	"clk_peripll_vdec_gated", 		clk_peripll_vdec_gated)},
	{_REGISTER_CLOCK(NULL,	"clk_1vdec_slave_clk", 		clk_1vdec_slave_clk)},
	{_REGISTER_CLOCK(NULL,	"clk_x2x_vdec_brg_s", 			clk_x2x_vdec_brg_s)},
	{_REGISTER_CLOCK(NULL,	"clk_p2p_vdec_brg_s", 			clk_p2p_vdec_brg_s)},
       /* dphy clocks */
	{_REGISTER_CLOCK(NULL,	"clk_dphy0_ref", 				clk_dphy0_ref)}, 	
	{_REGISTER_CLOCK(NULL,	"clk_dphy0_cfg", 				clk_dphy0_cfg)},
	{_REGISTER_CLOCK(NULL,	"clk_dphy1_cfg", 				clk_dphy1_cfg)},
	{_REGISTER_CLOCK(NULL,	"clk_dphy2_cfg", 				clk_dphy2_cfg)},
	/* uart clocks */
	{_REGISTER_CLOCK("amba-uart.0",	NULL, 				clk_uart0)},
	{_REGISTER_CLOCK("amba-uart.1",	NULL, 				clk_uart1)},
	{_REGISTER_CLOCK("amba-uart.2",	NULL, 				clk_uart2)},
	{_REGISTER_CLOCK("amba-uart.3",	NULL, 				clk_uart3)},
	{_REGISTER_CLOCK("amba-uart.4",	NULL, 				clk_uart4)},
	{_REGISTER_CLOCK("amba-uart.5",	NULL, 				clk_uart5)},
	{_REGISTER_CLOCK("amba-uart.6",	NULL, 				clk_uart6)},
	{_REGISTER_CLOCK("amba-uart.0",	"uart_pclk", 				pclk_uart0)},
	{_REGISTER_CLOCK("amba-uart.1",	"uart_pclk", 				pclk_uart1)},
	{_REGISTER_CLOCK("amba-uart.2",	"uart_pclk", 				pclk_uart2)},
	{_REGISTER_CLOCK("amba-uart.3",	"uart_pclk", 				pclk_uart3)},
	{_REGISTER_CLOCK("amba-uart.4",	"uart_pclk", 				pclk_uart4)},
	{_REGISTER_CLOCK("amba-uart.5",	"uart_pclk", 				pclk_uart5)},
	{_REGISTER_CLOCK("amba-uart.6",	"uart_pclk", 				pclk_uart6)},
	/* nandc clocks */
	{_REGISTER_CLOCK(NULL,			"hclk_nandc", 			hclk_nandc)},
	/* mmc clocks */
	{_REGISTER_CLOCK(NULL,			"clk_dsppll_mmc0_gated", 			clk_dsppll_mmc0_gated)},
	{_REGISTER_CLOCK(NULL,			"clk_dsppll_mmc1_gated", 			clk_dsppll_mmc1_gated)},
	{_REGISTER_CLOCK(NULL,			"clk_dsppll_mmc2_gated", 			clk_dsppll_mmc2_gated)},
	{_REGISTER_CLOCK(NULL,			"clk_mmc0high", 			clk_mmc0high)},
	{_REGISTER_CLOCK(NULL,			"clk_mmc1high", 			clk_mmc1high)},
	{_REGISTER_CLOCK(NULL,			"clk_mmc2high", 			clk_mmc2high)},
	{_REGISTER_CLOCK(NULL,			"clk_mmc0low", 			clk_mmc0low)},
	{_REGISTER_CLOCK(NULL,			"clk_mmc1low", 			clk_mmc1low)},
	{_REGISTER_CLOCK(NULL,			"clk_mmc2low", 			clk_mmc2low)},
	{_REGISTER_CLOCK(NULL,			"hclk_mmc0", 			        hclk_mmc0)},
	{_REGISTER_CLOCK(NULL,			"hclk_mmc1", 			        hclk_mmc1)},
	{_REGISTER_CLOCK(NULL,			"hclk_mmc2", 			        hclk_mmc2)},
	/* i2c clocks */
	{_REGISTER_CLOCK("dw-i2c.0",		NULL, 					clk_i2c0)},
	{_REGISTER_CLOCK("dw-i2c.1",		NULL, 					clk_i2c1)},
	{_REGISTER_CLOCK("dw-i2c.2",		NULL, 					clk_i2c2)},
	{_REGISTER_CLOCK("dw-i2c.3",	      NULL, 					clk_i2c3)},
	{_REGISTER_CLOCK("dw-i2c.4",		NULL, 					clk_i2c4)},
	{_REGISTER_CLOCK("dw-i2c.5",		NULL, 					clk_i2c5)},
      {_REGISTER_CLOCK("dw-i2c.0",		"i2c_pclk", 					pclk_i2c0)},
	{_REGISTER_CLOCK("dw-i2c.1",		"i2c_pclk", 					pclk_i2c1)},
	{_REGISTER_CLOCK("dw-i2c.2",		"i2c_pclk", 					pclk_i2c2)},
	{_REGISTER_CLOCK("dw-i2c.3",	      "i2c_pclk", 					pclk_i2c3)},
	{_REGISTER_CLOCK("dw-i2c.4",		"i2c_pclk", 					pclk_i2c4)},
	{_REGISTER_CLOCK("dw-i2c.5",		"i2c_pclk", 					pclk_i2c5)},
	/* pwm clocks */
	{_REGISTER_CLOCK(NULL,	"clk_pwm0", 					clk_pwm0)},
	{_REGISTER_CLOCK(NULL,	"clk_pwm1", 					clk_pwm1)},
	{_REGISTER_CLOCK(NULL,		"pclk_pwm0", 					pclk_pwm0)},
	{_REGISTER_CLOCK(NULL,		"pclk_pwm1", 					pclk_pwm1)},
      /* usb clocks */
	{_REGISTER_CLOCK(NULL,	"hclk_usbotg_on", 					hclk_usbotg_on)},
	{_REGISTER_CLOCK(NULL,	"hclk_usbotg_off", 					hclk_usbotg_off)},
	{_REGISTER_CLOCK(NULL,	"clk_usbotg_off", 					clk_usbotg_off)},
	{_REGISTER_CLOCK(NULL,	"clk_picophy", 					clk_picophy)},
	{_REGISTER_CLOCK(NULL,	"clk_picophy_test", 					clk_picophy_test)},
	/* spi clocks */
	{_REGISTER_CLOCK("dev:ssp0",	NULL,					clk_spi0)},
	{_REGISTER_CLOCK("dev:ssp1",	NULL, 					clk_spi1)},
	{_REGISTER_CLOCK("dev:ssp0",	"spi_pclk",					pclk_spi0)},
	{_REGISTER_CLOCK("dev:ssp1",	"spi_pclk", 					pclk_spi1)},
       /* rtc clocks */
	{_REGISTER_CLOCK(NULL,      "clk_rtc",                     clk_rtc)},
	/* watchdog clocks */
	{_REGISTER_CLOCK(NULL,      "clk_watchdog0",                     clk_watchdog0)},
	{_REGISTER_CLOCK(NULL,      "pclk_watchdog0",                     pclk_watchdog0)},
       /* dma clocks */
	{_REGISTER_CLOCK(NULL,      "clk_ap_dmac_axi0",                       clk_ap_dmac_axi0)},    
	{_REGISTER_CLOCK(NULL,      "clk_ap_dmac_axi1",                     clk_ap_dmac_axi1)},  
	/* gps clocks */
	{_REGISTER_CLOCK(NULL,      "clk_gps",                     clk_gps)}, 
	/* ts clocks */
	{_REGISTER_CLOCK(NULL,      "clk_ts",                       clk_ts)},    
	{_REGISTER_CLOCK(NULL,      "hclk_ts",                     hclk_ts)}, 
	/* tsensor clocks */
	{_REGISTER_CLOCK(NULL,      "clk_tsensor0",                       clk_tsensor0)},    
	{_REGISTER_CLOCK(NULL,      "clk_tsensor1",                     clk_tsensor1)}, 
	/* timer clocks */
	{_REGISTER_CLOCK(NULL,      "pclk_timer0",                       pclk_timer0)},    
	{_REGISTER_CLOCK(NULL,      "clk_timer0",                         clk_timer0)},   
	{_REGISTER_CLOCK(NULL,      "pclk_timer1",                       pclk_timer1)},    
	{_REGISTER_CLOCK(NULL,      "clk_timer1",                         clk_timer1)},
	{_REGISTER_CLOCK(NULL,      "pclk_timer2",                       pclk_timer2)},    
	{_REGISTER_CLOCK(NULL,      "clk_timer2",                         clk_timer2)},
	{_REGISTER_CLOCK(NULL,      "pclk_timer3",                       pclk_timer3)},    
	{_REGISTER_CLOCK(NULL,      "clk_timer3",                         clk_timer3)},
	{_REGISTER_CLOCK(NULL,      "pclk_timer4",                       pclk_timer4)},    
	{_REGISTER_CLOCK(NULL,      "clk_timer4",                         clk_timer4)},
	{_REGISTER_CLOCK(NULL,      "pclk_timer5",                       pclk_timer5)},    
	{_REGISTER_CLOCK(NULL,      "clk_timer5",                         clk_timer5)},
	{_REGISTER_CLOCK(NULL,      "pclk_timer6",                       pclk_timer6)},    
	{_REGISTER_CLOCK(NULL,      "clk_timer6",                         clk_timer6)},
	{_REGISTER_CLOCK(NULL,      "pclk_timer7",                       pclk_timer7)},    
	{_REGISTER_CLOCK(NULL,      "clk_timer7",                         clk_timer7)},
	{_REGISTER_CLOCK(NULL,      "pclk_timer8",                       pclk_timer8)},    
	{_REGISTER_CLOCK(NULL,      "clk_timer8",                         clk_timer8)},
	/* no body */
	{_REGISTER_CLOCK(NULL,      "clk_27m_gated",                       clk_27m_gated)},     
	{_REGISTER_CLOCK(NULL,      "clk_27m",                       clk_27m)},    
	{_REGISTER_CLOCK(NULL,      "clk_90k",                         clk_90k)},  
	{_REGISTER_CLOCK(NULL,      "clk_pmussi",                         clk_pmussi)},	
    /*gpio*/
    {_REGISTER_CLOCK("gpio0",               NULL,                                   clk_gpio0)},
    {_REGISTER_CLOCK("gpio1",       NULL,                   clk_gpio1)},
    {_REGISTER_CLOCK("gpio2",       NULL,                   clk_gpio2)},
    {_REGISTER_CLOCK("gpio3",       NULL,                   clk_gpio3)},
    {_REGISTER_CLOCK("gpio4",       NULL,                   clk_gpio4)},
    {_REGISTER_CLOCK("gpio5",       NULL,                   clk_gpio5)},
    {_REGISTER_CLOCK("gpio6",       NULL,                   clk_gpio6)},
    {_REGISTER_CLOCK("gpio7",       NULL,                   clk_gpio7)},
    {_REGISTER_CLOCK("gpio8",       NULL,                   clk_gpio8)},
    {_REGISTER_CLOCK("gpio9",       NULL,                   clk_gpio9)},
    {_REGISTER_CLOCK("gpio10",       NULL,                   clk_gpio10)},
    {_REGISTER_CLOCK("gpio11",       NULL,                   clk_gpio11)},
    {_REGISTER_CLOCK("gpio12",       NULL,                   clk_gpio12)},
    {_REGISTER_CLOCK("gpio13",       NULL,                   clk_gpio13)},
    {_REGISTER_CLOCK("gpio14",       NULL,                   clk_gpio14)},
    {_REGISTER_CLOCK("gpio15",       NULL,                   clk_gpio15)},
    {_REGISTER_CLOCK("gpio16",       NULL,                   clk_gpio16)},
    {_REGISTER_CLOCK("gpio17",       NULL,                   clk_gpio17)},
    {_REGISTER_CLOCK("gpio18",       NULL,                   clk_gpio18)},
	{NULL, NULL, NULL},
};

