##############################################
#     Make file of OV5642 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hi6620/capture/ov5642
EXTRA_CFLAGS += -fno-pic 
obj-$(CONFIG_HI6620_CAMERA_OV5642) += ov5642.o
#obj-m += ov5642.o

#################### END #####################
