# Makefile for mini isp


subdir-ccflags-y += -Idrivers/huawei/camera/common/
subdir-ccflags-y += -Idrivers/huawei/camera/mini_isp/
obj-y += sonyimx179/
obj-y += sonyimx214/
obj-y += camera_agent.o
obj-y += mini_isp_agent.o
obj-y += mini_isp.o
