#
# Makefile for huawei camera sensors
#


obj-$(CONFIG_HI6210_CAMERA_FLASH) += flash/

subdir-ccflags-y += -Idrivers/media/platform/ovisp22/capture/isp/
subdir-ccflags-y += -Idrivers/media/platform/ovisp22/capture/isp_for_misp/
subdir-ccflags-y += -Idrivers/media/platform/ovisp22/capture/common/
subdir-ccflags-y += -Idrivers/videocom/videoconfig/


obj-$(CONFIG_CAMERA_MINI_ISP) += mini_isp/

#obj-$(CONFIG_HI6210_CAMERA_OV5642) += ov5642/
obj-$(CONFIG_HI6210_CAMERA_OV5648_FOXCONN) += ov5648_foxconn/
obj-$(CONFIG_HI6210_CAMERA_OV5648_SUNNY) += ov5648_sunny/
obj-$(CONFIG_HI6210_CAMERA_OV13850) += ov13850/
obj-$(CONFIG_HI6210_CAMERA_OV13850_OFILM) += ov13850_ofilm/
obj-$(CONFIG_HI6210_CAMERA_OV13850_LITEON_171) += ov13850_liteon_171/
#obj-$(CONFIG_HI6210_CAMERA_OV8830) += ov8830/
#obj-$(CONFIG_HI6210_CAMERA_OV8850) += ov8850/

obj-$(CONFIG_HI6210_CAMERA_SONYIMX134) += sonyimx134/
obj-$(CONFIG_HI6210_CAMERA_SONYIMX135) += sonyimx135/
obj-$(CONFIG_HI6210_CAMERA_SONYIMX179) += sonyimx179/
obj-$(CONFIG_HI6210_CAMERA_SONYIMX214) += sonyimx214/
obj-$(CONFIG_HI6210_CAMERA_SONYIMX328) += sonyimx328/
obj-$(CONFIG_HI6210_CAMERA_SONYIMX328_171) += sonyimx328_171/

obj-$(CONFIG_HI6210_CAMERA_S5K4E1GA_FOXCONN) += s5k4e1ga_foxconn/
obj-$(CONFIG_HI6210_CAMERA_S5K4E1GX_FOXCONN) += s5k4e1gx_foxconn/
obj-$(CONFIG_HI6210_CAMERA_S5K4E1GA_SUNNY) += s5k4e1ga_sunny/
obj-$(CONFIG_HI6210_CAMERA_OV5648_OFILM) += ov5648_ofilm/