# MD5: 1a4438e9856657ffc0f4b14c5b9d28d0
set(CFG_TENSILICA_BUILDS_HIFI $(ROOT_XTENSA_PATH_W)/XtDevTools/install/builds/RE-2014.5-linux) 

set(CFG_TENSILICA_TOOLS_HIFI $(ROOT_XTENSA_PATH_W)/XtDevTools/install/tools/RE-2014.5-linux) 

set(CFG_FEATURE_HIFI FEATURE_OFF) 

set(CFG_FEATURE_HIFI_USE_ICC FEATURE_OFF) 

set(CFG_FEATURE_MBB_MODULE_AUDIO FEATURE_OFF) 

set(CFG_FEATURE_VOICE_UP FEATURE_OFF) 

set(CFG_PLATFORM_CHIP_TYPE p532) 

