# MD5: 725b7bddaf95da025c6e548610189761
set(CFG_FEATURE_IMS FEATURE_ON) 

set(CFG_FEATURE_LTE_R11 FEATURE_ON) 

set(CFG_FEATURE_LTE_MBMS FEATURE_OFF) 

set(CFG_FEATURE_LTE_NAS_R11 FEATURE_OFF) 

set(CFG_FEATURE_LTE_CDMA_R11 FEATURE_OFF) 

set(CFG_FEATURE_PTM FEATURE_OFF) 

set(CFG_FEATURE_BALONG_CL FEATURE_UE_MODE_CDMA) 

set(CFG_FEATURE_LTE_CAT_PART_R11 NO) 

set(CFG_TL_PS_MAX_TRCH_NUM_8 YES) 

set(CFG_FEATURE_LPP FEATURE_OFF) 

set(CFG_FEATURE_TDS_WCDMA_DYNAMIC_LOAD FEATURE_OFF) 

set(CFG_FEATURE_CSG FEATURE_OFF) 

set(CFG_FEATURE_CSS_CLOUD_MEMORY_IMPROVE FEATURE_ON) 

