#sensor unification for differ platform
obj-$(CONFIG_HUAWEI_SENSORS_INPUT_INFO)	+= sensor_info.o
obj-y	+= light/
obj-y	+= accelerometer/
obj-y	+= compass/
obj-y	+= hall/
obj-$(CONFIG_FINGERPRINT)          += fingerprint/
obj-$(CONFIG_HUAWEI_HALL_INPUTHUB) += hall_inputhub/
