#
# Makefile for hisilicon K3 soc camera v4l2 driver
#
EXTRA_CFLAGS += -Idrivers/media/video/hisi/camera/vcm
EXTRA_CFLAGS += -fno-pic

obj-$(CONFIG_HISI_CAMERA_VCM) += vcm_driver.o

obj-$(CONFIG_HISI_CAMERA_AD5823) += ad5823.o
obj-$(CONFIG_HISI_CAMERA_DW9714) += dw9714.o
obj-$(CONFIG_HISI_CAMERA_AD5823) += ad5816.o