##############################################
#     Make file of S5K4E1GX_FOXCONN camera sensor
##############################################

#EXTRA_CFLAGS += -fno-pic
obj-$(CONFIG_HI6620_CAMERA_S5K4E1GX_FOXCONN) += s5k4e1gx_foxconn.o

#################### END #####################
