ccflags-y += -Idrivers/media/huawei/camera/isp
ccflags-y += -Idrivers/media/huawei/camera/io
ccflags-y += -Idrivers/media/huawei/camera
ccflags-y += -Idrivers/media/huawei/camera/platform
ccflags-y += -Idrivers/media/huawei/camera/platform/hi3635
ccflags-y += -Idrivers/media/huawei/camera/csi

obj-y += ovisp2.3.o
obj-y += isp_ops.o

CFLAGS_isp_ops.o = -I$(src)

