ccflags-y += -Idrivers/media/huawei/camera
ccflags-y += -Idrivers/media/huawei/camera/cci
ccflags-y += -Idrivers/media/huawei/camera/csi
ccflags-y += -Idrivers/media/huawei/camera/io
ccflags-y += -Idrivers/media/huawei/camera/sensor
ccflags-y += -Idrivers/media/huawei/camera/extisp
ccflags-y += -Idrivers/media/huawei/camera/extisp/altek6045
ccflags-y += -Idrivers/media/huawei/camera/isp/ovisp2.3
ccflags-y += -Idrivers/media/huawei/camera/pmic
ccflags-y += -Idrivers/media/huawei/camera/platform

obj-y += sensor_common.o
