obj-y +=hisi_mailbox.o
obj-$(CONFIG_HISI_MAILBOX_DEBUGFS) +=hisi_mailbox_debugfs.o
obj-y +=hisi_rproc.o
obj-y +=hisi_rproc_test.o
obj-$(CONFIG_HISI_RPROC_DEBUGFS) +=hisi_rproc_debugfs.o
obj-$(CONFIG_HISI_MAILBOX) +=hisi_mailbox_dev.o
subdir-ccflags-$(CONFIG_HISI_BB)    += -Idrivers/hisi/mntn/blackbox/


