#
# Makefile for Hisilicon Hi36xx/Hi37xx processors line
#

obj-$(CONFIG_MACH_HS_DT)	+= hs-dt.o system.o
obj-$(CONFIG_SMP)		+= platsmp.o
obj-$(CONFIG_HOTPLUG_CPU)	+= hotplug.o
obj-$(CONFIG_PM)		+= pm.o
obj-$(CONFIG_PM)		+= hilpm-cpugodp.o
obj-$(CONFIG_PM)		+= lowpmregs.o
obj-$(CONFIG_IPPS_SUPPORT)      += ipps-core.o ipps2.o
obj-$(CONFIG_CPU_IDLE)		+= cpuidle-hs.o
