# MD5: 6b8c988f4792d5e9f2c0b744b604ea66
set(CFG_ENABLE_BUILD_VARS YES) 

set(CFG_FEATURE_UPGRADE_TL YES) 

set(CFG_PRODUCT_NAME "hi6932_udp_128") 

set(CFG_PRODUCT_CFG_CHIP_SOLUTION_NAME "Balong") 

set(CFG_BUILD_TYPE RELEASE) 

set(CFG_PRODUCT_VERSION V700R220C30B120) 

set(CFG_PRODUCT_VERSION_STR "V700R220C30B120") 

set(CFG_PRODUCT_FULL_VERSION_STR "Balong V700R220C30B120") 

set(CFG_PRODUCT_FILE_VERSION_STR "2.1.6.8") 

set(CFG_PRODUCT_DLOAD_SOFTWARE_VER "21.120.00.00.010") 

set(CFG_PLATFORM hi6932) 

set(CFG_PLATFORM_HISI_BALONG hi6932) 

set(CFG_ARCH_TYPE	 3339) 

set(CFG_OS_LINUX_PRODUCT_NAME hi6932_udp_128_defconfig) 

set(CFG_TARGET_BALONG_PRODUCT hi6932_udp) 

set(CFG_BSP_CONFIG_EDA NO) 

set(CFG_BSP_CONFIG_EMU NO) 

set(CFG_BSP_CONFIG_NOT_DDR_BYPASSPLL NO) 

set(CFG_CONFIG_SMART_SYSTEM_MODEM NO) 

set(CFG_CONFIG_FASTBOOT_DEBUG NO) 

set(CFG_CONFIG_NVIM YES) 

set(CFG_FEATURE_NV_FLASH_ON YES) 

set(CFG_FEATURE_NV_EMMC_ON NO) 

set(CFG_FEATURE_NV_LFILE_ON NO) 

set(CFG_FEATURE_NV_RFILE_ON NO) 

set(CFG_FEATURE_TLPHY_MAILBOX YES) 

set(CFG_CONFIG_MAILBOX_TYPE YES) 

set(CFG_CONFIG_HIFI_MAILBOX YES) 

set(CFG_ENABLE_BUILD_OM YES) 

set(CFG_FEATURE_OM_PHONE NO) 

set(CFG_ENABLE_BUILD_SYSVIEW YES) 

set(CFG_ENABLE_BUILD_CPUVIEW YES) 

set(CFG_ENABLE_BUILD_MEMVIEW YES) 

set(CFG_ENABLE_BUILD_AMON YES) 

set(CFG_ENABLE_BUILD_UTRACE NO) 

set(CFG_ENABLE_BUILD_SOCP YES) 

set(CFG_FEATURE_SOCP_DECODE_INT_TIMEOUT FEATURE_ON) 

set(CFG_FEATURE_SIM_NOTIFY NO) 

set(CFG_CONFIG_SC NO) 

set(CFG_CONFIG_DSP YES) 

set(CFG_CONFIG_VERSION_STUB YES) 

set(CFG_HW_VERSION_STUB 0x72000010) 

set(CFG_CONFIG_GPIO_SYNOPSYS NO) 

set(CFG_CONFIG_GPIO_PL061 YES) 

set(CFG_CONFIG_GPIO_EXPANDER NO) 

set(CFG_CONFIG_PMU_GPIO YES) 

set(CFG_CONFIG_PINCTRL_BALONG YES) 

set(CFG_CONFIG_ONOFF YES) 

set(CFG_CONFIG_COMPRESS_CCORE_IMAGE YES) 

set(CFG_BSP_HAS_SEC_FEATURE NO) 

set(CFG_CONFIG_SEC_BOOT_BALONG NO) 

set(CFG_CONFIG_DX_LIB YES) 

set(CFG_CONFIG_RSA NO) 

set(CFG_USE_USBLOADER_MERGE 			 YES) 

set(CFG_BSP_ENBALE_PACK_IMAGE			 YES) 

set(CFG_BSP_USB_BURN					 YES) 

set(CFG_FEATURE_DELAY_MODEM_INIT FEATURE_OFF) 

set(CFG_CONFIG_HIFI YES) 

set(CFG_BUILD_PTABLE YES) 

set(CFG_CONFIG_PMU_NEW YES) 

set(CFG_CONFIG_COUL NO) 

set(CFG_CONFIG_HKADC YES) 

set(CFG_CONFIG_TEMPERATURE_PROTECT YES) 

set(CFG_CONFIG_MIPI YES) 

set(CFG_CONFIG_CROSS_MIPI NO) 

set(CFG_CONFIG_RFFE_MIPI YES) 

set(CFG_CONFIG_RFFE_ANTEN YES) 

set(CFG_CONFIG_RFFE_POWER YES) 

set(CFG_CONFIG_ABB YES) 

set(CFG_CONFIG_BBP YES) 

set(CFG_CONFIG_LEDS_CCORE YES) 

set(CFG_CONFIG_FB_SPI_BALONG NO) 

set(CFG_CONFIG_FB_EMI_BALONG YES) 

set(CFG_CONFIG_FB_1_4_5_INCH_BALONG YES) 

set(CFG_CONFIG_FB_2_4_INCH_BALONG NO) 

set(CFG_CONFIG_PCIE_CFG YES) 

set(CFG_CONFIG_SFLASH NO) 

set(CFG_CONFIG_SLIC m) 

set(CFG_CONFIG_AUDIO m) 

set(CFG_CONFIG_ANTEN NO) 

set(CFG_CONFIG_EFUSE YES) 

set(CFG_CONFIG_DDM YES) 

set(CFG_CONFIG_DESIGNWARE_I2C NO) 

set(CFG_FEATURE_E5_ONOFF NO) 

set(CFG_CONFIG_FASTBOOT_UART_NUM 0) 

set(CFG_CONFIG_MODULE_VIC NO) 

set(CFG_CONFIG_AT_UART NO) 

set(CFG_CONFIG_CSHELL YES) 

set(CFG_CONFIG_ICC YES) 

set(CFG_CONFIG_OF YES) 

set(CFG_CONFIG_CPUFREQ YES) 

set(CFG_CONFIG_CCORE_REGULATOR YES) 

set(CFG_CONFIG_CCORE_WDT YES) 

set(CFG_CONFIG_ACORE_WDT YES) 

set(CFG_CONFIG_PM_OM YES) 

set(CFG_CONFIG_BALONG_CCLK YES) 

set(CFG_CONFIG_RSR_ACC YES) 

set(CFG_CONFIG_CCORE_CPU_IDLE YES) 

set(CFG_CONFIG_CCORE_PM YES) 

set(CFG_CONFIG_MODULE_IPC YES) 

set(CFG_CONFIG_MODULE_TIMER YES) 

set(CFG_CONFIG_MODULE_SYNC YES) 

set(CFG_CONFIG_HAS_CCORE_WAKELOCK YES) 

set(CFG_CONFIG_CCORE_BALONG_PM YES) 

set(CFG_CONFIG_BALONG_EDMA YES) 

set(CFG_CONFIG_BALONG_EDMA_TEST YES) 

set(CFG_CONFIG_DDR_SECURITY NO) 

set(CFG_CONFIG_HWADP YES) 

set(CFG_CONFIG_BALONG_HPM_TEMP NO) 

set(CFG_CONFIG_MEM YES) 

set(CFG_CONFIG_TCXO_BALONG NO) 

set(CFG_CONFIG_BALONG_DPM NO) 

set(CFG_CONFIG_USE_TIMER_STAMP NO) 

set(CFG_CONFIG_MODULE_BUSSTRESS NO) 

set(CFG_CONFIG_M3PM YES) 

set(CFG_CONFIG_M3PM_TEST YES) 

set(CFG_CONFIG_BALONG_L2CACHE NO) 

set(CFG_CONFIG_IPF YES) 

set(CFG_CONFIG_PSAM YES) 

set(CFG_CONFIG_CIPHER YES) 

set(CFG_CONFIG_IPF_VESION 2) 

set(CFG_CONFIG_IPF_ADQ_LEN 2) 

set(CFG_CONFIG_IPF_PROPERTY_MBB YES) 

set(CFG_CONFIG_USB_DWC3_VBUS_DISCONNECT YES) 

set(CFG_USB3_SYNOPSYS_PHY YES) 

set(CFG_CONFIG_USB_FORCE_HIGHSPEED NO) 

set(CFG_ENABLE_TEST_CODE NO) 

set(CFG_BSP_CONFIG_SFT NO) 

set(CFG_BSP_CONFIG_EMU_PALADIN NO) 

set(CFG_BSP_CONFIG_EMU_ZEBU NO) 

set(CFG_BSP_CONFIG_HI6932 YES) 

set(CFG_BSP_CONFIG_LPDDR2 YES) 

set(CFG_BSP_CONFIG_LPDDR3 NO) 

set(CFG_BSP_CONFIG_HIMDDRCV510_533 NO) 

set(CFG_BSP_CONFIG_HIMDDRCV510_333 NO) 

set(CFG_BSP_CONFIG_HIMDDRCV510_133 NO) 

set(CFG_BSP_CONFIG_HIMDDRCV510_ALL YES) 

set(CFG_CONFIG_RTC_BUILD_CTRL YES) 

set(CFG_CONFIG_RTC_ON_PMU YES) 

set(CFG_CONFIG_SRAM_SECURE YES) 

set(CFG_ENABLE_SHELL_SYM YES) 

set(CFG_ENABLE_DEBUG YES) 

set(CFG_BUILD_DRV_ONLY NO) 

set(CFG_CONFIG_CORESIGHT YES) 

set(CFG_CONFIG_WATCHPOINT YES) 

set(CFG_CONFIG_BSP_TEST_CCORE NO) 

set(CFG_CONFIG_TRUSTZONE NO) 

set(CFG_CONFIG_ACTRL_SMP YES) 

set(CFG_CONFIG_SYSBUS NO) 

set(CFG_DFS_DDR_TRANING_DATA_OFFSET 0x17000) 

set(CFG_OS_PATH modem/config/product/hi6932_udp_128/os) 

set(CFG_OS_IMG_FILE VXWORKS.6.8.3.IMG.wpj) 

set(CFG_OS_LIB VXWORKS.6.8.3.LIB.RELEASE) 

set(OBB_SEPARATE false) 

set(CFG_FTP_REPLY_TIME_OUT 0) 

set(CFG_PLATFORM_CHIP_TYPE hi6932) 

set(CFG_CHIP_MODEM_ARM_ARCH CORTEX_A9) 

set(CFG_PRODUCT_CFG_PTABLE_VER_NAME "V7R220_UDP") 

set(CFG_PRODUCT_CFG_PTABLE_VER_ID			 "ptable 1.00") 

set(CFG_PRODUCT_CFG_FLASH_M3BOOT_LEN     	 0x80000) 

set(CFG_PRODUCT_CFG_FLASH_FASTBOOT_LEN 0x80000) 

set(CFG_PRODUCT_CFG_FLASH_NV_LTE_LEN 0x400000) 

set(CFG_PRODUCT_CFG_FLASH_NV_IMG_LEN 0x400000) 

set(CFG_PRODUCT_CFG_FLASH_NV_DLD_LEN      	 0x300000) 

set(CFG_PRODUCT_CFG_FLASH_SEC_STORAGE_LEN 0x600000) 

set(CFG_PRODUCT_CFG_FLASH_NV_FACTORY_LEN   	 0x300000) 

set(CFG_PRODUCT_CFG_FLASH_OEMINFO_LEN 0x200000) 

set(CFG_PRODUCT_CFG_FLASH_YAFFS_USERDATA_LEN 0x600000) 

set(CFG_PRODUCT_CFG_FLASH_YAFFS_ONLINE_LEN 0) 

set(CFG_PRODUCT_CFG_FLASH_BOOTIMG_LEN	 0x600000) 

set(CFG_PRODUCT_CFG_FLASH_BOOTIMGBAK_LEN	 0) 

set(CFG_PRODUCT_CFG_FLASH_LOGO_LEN 0x100000) 

set(CFG_PRODUCT_CFG_FLASH_HIFI_LEN  	 0x300000) 

set(CFG_PRODUCT_CFG_FLASH_MISC_LEN 0x100000) 

set(CFG_PRODUCT_CFG_FLASH_M3IMAGE_LEN 	 0x100000) 

set(CFG_PRODUCT_CFG_FLASH_RESERVE1_LEN 0) 

set(CFG_PRODUCT_CFG_FLASH_RESERVE2_LEN 0) 

set(CFG_PRODUCT_CFG_FLASH_RESERVE3_LEN 0) 

set(CFG_PRODUCT_CFG_FLASH_OM_LEN 0xC00000) 

set(CFG_PRODUCT_CFG_FLASH_YAFFS_APP_LEN 0x0) 

set(CFG_PRODUCT_CFG_FLASH_YAFFS_WEBUI_LEN 	 0x0) 

set(CFG_PRODUCT_CFG_FLASH_SYSIMG_LEN 0x2400000) 

set(CFG_PRODUCT_CFG_FLASH_DTIMG_LEN 0x00200000) 

set(CFG_PRODUCT_CFG_FLASH_ISO_LEN 0x1000000) 

set(CFG_PRODUCT_CFG_FLASH_CACHE_LEN   	 0x400000) 

set(CFG_PRODUCT_CFG_FLASH_TEEOS_LEN	 0x400000) 

set(CFG_PRODUCT_CFG_FLASH_RECOVERY_LEN 0x400000) 

set(CFG_PRODUCT_CFG_FLASH_MULTI_CARRIER_LEN 0x00000) 

set(CFG_FLASH_PTABLE_OFFSET						 0x1F800) 

set(CFG_PRODUCT_CFG_FLASH_MODEM_FW_LEN 0x01400000) 

set(CFG_MCORE_TEXT_START_ADDR 0xA0400000) 

set(CFG_FASTBOOT_DDR_ENTRY 0xA7D00000) 

set(CFG_PRODUCT_CFG_KERNEL_ENTRY 		 0xA5708000) 

set(CFG_PRODUCT_KERNEL_PARAMS_PHYS		 0xA5700100) 

set(CFG_ONCHIP_FASTBOOT_ADDR 0xA78FF000) 

set(CFG_RTX_KERNEL_ENTRY 0x10000000) 

set(CFG_HI_SRAM_MEM_ADDR 0x80800000) 

set(CFG_HI_SRAM_SIZE 0x2000) 

set(CFG_DRV_SRAM_ADDR               		 (HI_SRAM_MEM_ADDR)) 

set(CFG_DRV_SRAM_SIZE						 0x2000) 

set(CFG_DDR_MEM_ADDR 0xA0000000) 

set(CFG_DDR_MEM_SIZE 0x08000000) 

set(CFG_DDR_APP_ACP_ADDR (DDR_MEM_ADDR)) 

set(CFG_DDR_APP_ACP_SIZE 0x000000) 

set(CFG_DDR_GU_ADDR ((DDR_APP_ACP_ADDR) + (DDR_APP_ACP_SIZE))) 

set(CFG_DDR_GU_SIZE 0x00C0000) 

set(CFG_DDR_UPA_ADDR DDR_GU_ADDR) 

set(CFG_DDR_UPA_SIZE 0x00024000) 

set(CFG_DDR_CQI_ADDR ((DDR_UPA_ADDR) + (DDR_UPA_SIZE))) 

set(CFG_DDR_CQI_SIZE 0x00003400) 

set(CFG_DDR_APT_ADDR ((DDR_CQI_ADDR) + (DDR_CQI_SIZE))) 

set(CFG_DDR_APT_SIZE 0x00008400) 

set(CFG_DDR_ET_ADDR ((DDR_APT_ADDR) + (DDR_APT_SIZE))) 

set(CFG_DDR_ET_SIZE 0x00004800) 

set(CFG_DDR_NV_ADDR ((DDR_ET_ADDR) + (DDR_ET_SIZE))) 

set(CFG_DDR_NV_SIZE 0x00000000) 

set(CFG_DDR_ZSP_UP_ADDR ((DDR_NV_ADDR) + (DDR_NV_SIZE))) 

set(CFG_DDR_ZSP_UP_SIZE 0x00008000) 

set(CFG_DDR_ECS_TEE_ADDR ((DDR_ZSP_UP_ADDR) + (DDR_ZSP_UP_SIZE))) 

set(CFG_DDR_ECS_TEE_SIZE 0x00001800) 

set(CFG_DDR_RESERVE_ADDR ((DDR_ECS_TEE_ADDR) + (DDR_ECS_TEE_SIZE))) 

set(CFG_DDR_RESERVE_SIZE 0x00082800) 

set(CFG_DDR_TLPHY_IMAGE_ADDR     	 ((DDR_RESERVE_ADDR) + (DDR_RESERVE_SIZE))) 

set(CFG_DDR_TLPHY_IMAGE_SIZE     	 0x340000) 

set(CFG_DDR_SECURE_OS_ADDR ((DDR_TLPHY_IMAGE_ADDR) + (DDR_TLPHY_IMAGE_SIZE))) 

set(CFG_DDR_SECURE_OS_SIZE 0x0000000) 

set(CFG_DDR_MCORE_ADDR ((DDR_SECURE_OS_ADDR ) + (DDR_SECURE_OS_SIZE))) 

set(CFG_DDR_MCORE_SIZE 0x4700000) 

set(CFG_DDR_MCORE_DTS_ADDR ((DDR_MCORE_ADDR) + (DDR_MCORE_SIZE))) 

set(CFG_DDR_MCORE_DTS_SIZE 0x0080000) 

set(CFG_DDR_LPHY_SDR_ADDR ((DDR_MCORE_DTS_ADDR) + (DDR_MCORE_DTS_SIZE))) 

set(CFG_DDR_LPHY_SDR_SIZE 0x280000) 

set(CFG_DDR_LCS_ADDR ((DDR_LPHY_SDR_ADDR) + (DDR_LPHY_SDR_SIZE))) 

set(CFG_DDR_LCS_SIZE 0x280000) 

set(CFG_DDR_MNTN_ADDR ((DDR_LCS_ADDR) + (DDR_LCS_SIZE))) 

set(CFG_DDR_MNTN_SIZE 0x100000) 

set(CFG_DDR_SHARED_MEM_ADDR ((DDR_MNTN_ADDR) + (DDR_MNTN_SIZE))) 

set(CFG_DDR_SHARED_MEM_SIZE 0x380000) 

set(CFG_DDR_HIFI_ADDR ((DDR_SHARED_MEM_ADDR) + (DDR_SHARED_MEM_SIZE))) 

set(CFG_DDR_HIFI_SIZE 0x200000) 

set(CFG_DDR_ACORE_ADDR ((DDR_HIFI_ADDR) + (DDR_HIFI_SIZE))) 

set(CFG_DDR_ACORE_SIZE 0x1E00000) 

set(CFG_DDR_ACORE_DTS_ADDR ((DDR_ACORE_ADDR) + (DDR_ACORE_SIZE))) 

set(CFG_DDR_ACORE_DTS_SIZE 0x0100000) 

set(CFG_DDR_SOCP_ADDR ((DDR_ACORE_DTS_ADDR) + (DDR_ACORE_DTS_SIZE))) 

set(CFG_DDR_SOCP_SIZE 0xA00000) 

set(CFG_DDR_MDM_ACP_ADDR ((DDR_SOCP_ADDR) + (DDR_SOCP_SIZE))) 

set(CFG_DDR_MDM_ACP_SIZE 0x0) 

set(CFG_DDR_HIFI_MBX_ADDR (DDR_SHARED_MEM_ADDR)) 

set(CFG_DDR_HIFI_MBX_SIZE (0X9800)) 

set(CFG_NV_DDR_SIZE 0x200000) 

set(CFG_SHM_SIZE_HIFI_MBX (DDR_HIFI_MBX_SIZE)) 

set(CFG_SHM_SIZE_HIFI (10*1024)) 

set(CFG_SHM_SIZE_TLPHY (12*1024)) 

set(CFG_SHM_SIZE_TEMPERATURE (3*1024)) 

set(CFG_SHM_SIZE_DDM_LOAD (1*1024)) 

set(CFG_SHM_SIZE_MEM_APPA9_PM_BOOT (0x10000)) 

set(CFG_SHM_SIZE_MEM_MDMA9_PM_BOOT (0x2000)) 

set(CFG_SHM_SIZE_TENCILICA_MULT_BAND (0x8000)) 

set(CFG_SHM_SIZE_ICC (0x61800)) 

set(CFG_SHM_SIZE_IPF (0x10000)) 

set(CFG_SHM_SIZE_PSAM (0x1000)) 

set(CFG_SHM_SIZE_WAN (0x8000)) 

set(CFG_SHM_SIZE_NV (NV_DDR_SIZE)) 

set(CFG_SHM_SIZE_M3_MNTN (0x20000)) 

set(CFG_SHM_SIZE_TIMESTAMP (1*1024)) 

set(CFG_SHM_SIZE_IOS (6*1024)) 

set(CFG_SHM_SIZE_RESTORE_AXI (96*1024)) 

set(CFG_SHM_SIZE_PMU (3*1024)) 

set(CFG_SHM_SIZE_PTABLE (2*1024)) 

set(CFG_SHM_SIZE_CCORE_RESET (0x400)) 

set(CFG_SHM_SIZE_PM_OM (256*1024)) 

set(CFG_SHM_SIZE_M3PM (0x1000)) 

set(CFG_SHM_SIZE_SLICE_MEM (0x1000)) 

set(CFG_SHM_SIZE_OSA_LOG (1024)) 

set(CFG_SHM_SIZE_WAS_LOG (1024)) 

set(CFG_SHM_SIZE_SRAM_BAK (HI_SRAM_SIZE)) 

set(CFG_SHM_SIZE_SRAM_TO_DDR (HI_SRAM_SIZE)) 

set(CFG_SHM_SIZE_M3RSRACC_BD (1024)) 

