##############################################
#     Make file of SONYIMX214 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/huawei/camera/sonyimx214/
#EXTRA_CFLAGS += -fno-pic 
obj-$(CONFIG_HI6620_CAMERA_SONYIMX214) += sonyimx214.o
obj-y += sonyimx214.o
#################### END #####################