
# InputHub Driver
obj-$(CONFIG_CONTEXTHUB)       += inputhub_bridge.o
obj-$(CONFIG_CONTEXTHUB)       += inputhub_route.o
obj-$(CONFIG_CONTEXTHUB)       += sensor_info.o
obj-$(CONFIG_CONTEXTHUB)       += sensorhub_logbuff.o
obj-$(CONFIG_CONTEXTHUB)       += sensor_debug.o

obj-$(CONFIG_CONTEXTHUB)       += sensorhub_channel.o
obj-$(CONFIG_CONTEXTHUB)       += motionhub_channel.o

#obj-$(CONFIG_CONTEXTHUB)      += touch_events_channel.o

obj-$(CONFIG_CONTEXTHUB)       += sensor_sys_info.o

ifdef CONFIG_HISI_BB
obj-$(CONFIG_CONTEXTHUB)       += rdr_sensorhub.o
endif