#
# Makefile for SRecorder.
#

obj-$(CONFIG_SRECORDER) += srecorder_main.o \
	srecorder_allcpu_stack.o \
	srecorder_allps_info.o \
	srecorder_crash_time.o \
	srecorder_current_ps_backtrace.o \
	srecorder_dmesg.o \
	srecorder_kernel_symbols.o \
	srecorder_slabinfo.o \
	srecorder_sys_info.o \
	srecorder_save_log.o \
	srecorder_common.o \
	srecorder_dump_backtrace.o \
    srecorder_modem_log.o \
    srecorder_snprintf.o \
    srecorder_memory.o \
    srecorder_backtrace.o \
	srecorder_dev.o 

