/*---------------------------------------------------------------------------
 * This file is autogenerated file using huawei LCD parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * Parser location: device/hisilicon/common/display/tools/huawei_lcd_panel 
 *---------------------------------------------------------------------------*/


#ifndef _HW_LCD_EFFECT_H_

#define _HW_LCD_EFFECT_H_

#include "hw_lcd_ext.h"
#include "hw_lcd_effect_auo_otm1901a_5p2_1080p_video.h"
#include "hw_lcd_effect_boe_otm1901a_5p2_1080p_video.h"
#include "hw_lcd_effect_boe_otm1906c_5p2_1080p_cmd.h"
#include "hw_lcd_effect_ebbg_otm1906c_5p2_1080p_cmd.h"
#include "hw_lcd_effect_inx_otm1901a_5p2_1080p_video.h"
#include "hw_lcd_effect_inx_otm1906c_5p2_1080p_cmd.h"
#include "hw_lcd_effect_jdi_nt35695_5p2_1080p_cmd.h"
#include "hw_lcd_effect_lg_r69006_5p2_1080p_cmd.h"
#include "hw_lcd_effect_tm_otm1901a_5p2_1080p_video.h"
static void hw_lcd_effect_get_data(uint8_t panel_id, struct hisi_panel_info* pinfo)
{
	switch (panel_id) {
	case AUO_OTM1901A_5P2_1080P_VIDEO_PANEL:
		if (pinfo->acm_support == 1)
		{
			pinfo->acm_lut_hue_table = auo_otm1901a_5p2_1080p_video_acm_lut_hue_table;
			pinfo->acm_lut_hue_table_len = ARRAY_SIZE(auo_otm1901a_5p2_1080p_video_acm_lut_hue_table);
			pinfo->acm_lut_sata_table = auo_otm1901a_5p2_1080p_video_acm_lut_sata_table;
			pinfo->acm_lut_sata_table_len = ARRAY_SIZE(auo_otm1901a_5p2_1080p_video_acm_lut_sata_table);
			pinfo->acm_lut_satr_table = auo_otm1901a_5p2_1080p_video_acm_lut_satr_table;
			pinfo->acm_lut_satr_table_len = ARRAY_SIZE(auo_otm1901a_5p2_1080p_video_acm_lut_satr_table);
		}
		if (pinfo->gamma_support == 1)
		{
			pinfo->gamma_lut_table_R = auo_otm1901a_5p2_1080p_video_gamma_lut_table_R;
			pinfo->gamma_lut_table_G = auo_otm1901a_5p2_1080p_video_gamma_lut_table_G;
			pinfo->gamma_lut_table_B = auo_otm1901a_5p2_1080p_video_gamma_lut_table_B;
			pinfo->gamma_lut_table_len = ARRAY_SIZE(auo_otm1901a_5p2_1080p_video_gamma_lut_table_R);
			pinfo->igm_lut_table_R = auo_otm1901a_5p2_1080p_video_igm_lut_table_R;
			pinfo->igm_lut_table_G = auo_otm1901a_5p2_1080p_video_igm_lut_table_G;
			pinfo->igm_lut_table_B = auo_otm1901a_5p2_1080p_video_igm_lut_table_B;
			pinfo->igm_lut_table_len = ARRAY_SIZE(auo_otm1901a_5p2_1080p_video_igm_lut_table_R);
			pinfo->gmp_lut_table_low32bit = &auo_otm1901a_5p2_1080p_video_gmp_lut_table_low32bit[0][0][0];
			pinfo->gmp_lut_table_high4bit = &auo_otm1901a_5p2_1080p_video_gmp_lut_table_high4bit[0][0][0];
			pinfo->gmp_lut_table_len = ARRAY_SIZE(auo_otm1901a_5p2_1080p_video_gmp_lut_table_low32bit);
			pinfo->xcc_table = auo_otm1901a_5p2_1080p_video_xcc_table;
			pinfo->xcc_table_len = ARRAY_SIZE(auo_otm1901a_5p2_1080p_video_xcc_table);
		}
		break;
	case BOE_OTM1901A_5P2_1080P_VIDEO_PANEL:
		if (pinfo->acm_support == 1)
		{
			pinfo->acm_lut_hue_table = boe_otm1901a_5p2_1080p_video_acm_lut_hue_table;
			pinfo->acm_lut_hue_table_len = ARRAY_SIZE(boe_otm1901a_5p2_1080p_video_acm_lut_hue_table);
			pinfo->acm_lut_sata_table = boe_otm1901a_5p2_1080p_video_acm_lut_sata_table;
			pinfo->acm_lut_sata_table_len = ARRAY_SIZE(boe_otm1901a_5p2_1080p_video_acm_lut_sata_table);
			pinfo->acm_lut_satr_table = boe_otm1901a_5p2_1080p_video_acm_lut_satr_table;
			pinfo->acm_lut_satr_table_len = ARRAY_SIZE(boe_otm1901a_5p2_1080p_video_acm_lut_satr_table);
		}
		if (pinfo->gamma_support == 1)
		{
			pinfo->gamma_lut_table_R = boe_otm1901a_5p2_1080p_video_gamma_lut_table_R;
			pinfo->gamma_lut_table_G = boe_otm1901a_5p2_1080p_video_gamma_lut_table_G;
			pinfo->gamma_lut_table_B = boe_otm1901a_5p2_1080p_video_gamma_lut_table_B;
			pinfo->gamma_lut_table_len = ARRAY_SIZE(boe_otm1901a_5p2_1080p_video_gamma_lut_table_R);
			pinfo->igm_lut_table_R = boe_otm1901a_5p2_1080p_video_igm_lut_table_R;
			pinfo->igm_lut_table_G = boe_otm1901a_5p2_1080p_video_igm_lut_table_G;
			pinfo->igm_lut_table_B = boe_otm1901a_5p2_1080p_video_igm_lut_table_B;
			pinfo->igm_lut_table_len = ARRAY_SIZE(boe_otm1901a_5p2_1080p_video_igm_lut_table_R);
			pinfo->gmp_lut_table_low32bit = &boe_otm1901a_5p2_1080p_video_gmp_lut_table_low32bit[0][0][0];
			pinfo->gmp_lut_table_high4bit = &boe_otm1901a_5p2_1080p_video_gmp_lut_table_high4bit[0][0][0];
			pinfo->gmp_lut_table_len = ARRAY_SIZE(boe_otm1901a_5p2_1080p_video_gmp_lut_table_low32bit);
			pinfo->xcc_table = boe_otm1901a_5p2_1080p_video_xcc_table;
			pinfo->xcc_table_len = ARRAY_SIZE(boe_otm1901a_5p2_1080p_video_xcc_table);
		}
		break;
	case BOE_OTM1906C_5P2_1080P_CMD_PANEL:
		if (pinfo->acm_support == 1)
		{
			pinfo->acm_lut_hue_table = boe_otm1906c_5p2_1080p_cmd_acm_lut_hue_table;
			pinfo->acm_lut_hue_table_len = ARRAY_SIZE(boe_otm1906c_5p2_1080p_cmd_acm_lut_hue_table);
			pinfo->acm_lut_sata_table = boe_otm1906c_5p2_1080p_cmd_acm_lut_sata_table;
			pinfo->acm_lut_sata_table_len = ARRAY_SIZE(boe_otm1906c_5p2_1080p_cmd_acm_lut_sata_table);
			pinfo->acm_lut_satr_table = boe_otm1906c_5p2_1080p_cmd_acm_lut_satr_table;
			pinfo->acm_lut_satr_table_len = ARRAY_SIZE(boe_otm1906c_5p2_1080p_cmd_acm_lut_satr_table);
		}
		if (pinfo->gamma_support == 1)
		{
			pinfo->gamma_lut_table_R = boe_otm1906c_5p2_1080p_cmd_gamma_lut_table_R;
			pinfo->gamma_lut_table_G = boe_otm1906c_5p2_1080p_cmd_gamma_lut_table_G;
			pinfo->gamma_lut_table_B = boe_otm1906c_5p2_1080p_cmd_gamma_lut_table_B;
			pinfo->gamma_lut_table_len = ARRAY_SIZE(boe_otm1906c_5p2_1080p_cmd_gamma_lut_table_R);
			pinfo->igm_lut_table_R = boe_otm1906c_5p2_1080p_cmd_igm_lut_table_R;
			pinfo->igm_lut_table_G = boe_otm1906c_5p2_1080p_cmd_igm_lut_table_G;
			pinfo->igm_lut_table_B = boe_otm1906c_5p2_1080p_cmd_igm_lut_table_B;
			pinfo->igm_lut_table_len = ARRAY_SIZE(boe_otm1906c_5p2_1080p_cmd_igm_lut_table_R);
			pinfo->gmp_lut_table_low32bit = &boe_otm1906c_5p2_1080p_cmd_gmp_lut_table_low32bit[0][0][0];
			pinfo->gmp_lut_table_high4bit = &boe_otm1906c_5p2_1080p_cmd_gmp_lut_table_high4bit[0][0][0];
			pinfo->gmp_lut_table_len = ARRAY_SIZE(boe_otm1906c_5p2_1080p_cmd_gmp_lut_table_low32bit);
			pinfo->xcc_table = boe_otm1906c_5p2_1080p_cmd_xcc_table;
			pinfo->xcc_table_len = ARRAY_SIZE(boe_otm1906c_5p2_1080p_cmd_xcc_table);
		}
		break;
	case EBBG_OTM1906C_5P2_1080P_CMD_PANEL:
		if (pinfo->acm_support == 1)
		{
			pinfo->acm_lut_hue_table = ebbg_otm1906c_5p2_1080p_cmd_acm_lut_hue_table;
			pinfo->acm_lut_hue_table_len = ARRAY_SIZE(ebbg_otm1906c_5p2_1080p_cmd_acm_lut_hue_table);
			pinfo->acm_lut_sata_table = ebbg_otm1906c_5p2_1080p_cmd_acm_lut_sata_table;
			pinfo->acm_lut_sata_table_len = ARRAY_SIZE(ebbg_otm1906c_5p2_1080p_cmd_acm_lut_sata_table);
			pinfo->acm_lut_satr_table = ebbg_otm1906c_5p2_1080p_cmd_acm_lut_satr_table;
			pinfo->acm_lut_satr_table_len = ARRAY_SIZE(ebbg_otm1906c_5p2_1080p_cmd_acm_lut_satr_table);
		}
		if (pinfo->gamma_support == 1)
		{
			pinfo->gamma_lut_table_R = ebbg_otm1906c_5p2_1080p_cmd_gamma_lut_table_R;
			pinfo->gamma_lut_table_G = ebbg_otm1906c_5p2_1080p_cmd_gamma_lut_table_G;
			pinfo->gamma_lut_table_B = ebbg_otm1906c_5p2_1080p_cmd_gamma_lut_table_B;
			pinfo->gamma_lut_table_len = ARRAY_SIZE(ebbg_otm1906c_5p2_1080p_cmd_gamma_lut_table_R);
			pinfo->igm_lut_table_R = ebbg_otm1906c_5p2_1080p_cmd_igm_lut_table_R;
			pinfo->igm_lut_table_G = ebbg_otm1906c_5p2_1080p_cmd_igm_lut_table_G;
			pinfo->igm_lut_table_B = ebbg_otm1906c_5p2_1080p_cmd_igm_lut_table_B;
			pinfo->igm_lut_table_len = ARRAY_SIZE(ebbg_otm1906c_5p2_1080p_cmd_igm_lut_table_R);
			pinfo->gmp_lut_table_low32bit = &ebbg_otm1906c_5p2_1080p_cmd_gmp_lut_table_low32bit[0][0][0];
			pinfo->gmp_lut_table_high4bit = &ebbg_otm1906c_5p2_1080p_cmd_gmp_lut_table_high4bit[0][0][0];
			pinfo->gmp_lut_table_len = ARRAY_SIZE(ebbg_otm1906c_5p2_1080p_cmd_gmp_lut_table_low32bit);
			pinfo->xcc_table = ebbg_otm1906c_5p2_1080p_cmd_xcc_table;
			pinfo->xcc_table_len = ARRAY_SIZE(ebbg_otm1906c_5p2_1080p_cmd_xcc_table);
		}
		break;
	case INX_OTM1901A_5P2_1080P_VIDEO_PANEL:
		if (pinfo->acm_support == 1)
		{
			pinfo->acm_lut_hue_table = inx_otm1901a_5p2_1080p_video_acm_lut_hue_table;
			pinfo->acm_lut_hue_table_len = ARRAY_SIZE(inx_otm1901a_5p2_1080p_video_acm_lut_hue_table);
			pinfo->acm_lut_sata_table = inx_otm1901a_5p2_1080p_video_acm_lut_sata_table;
			pinfo->acm_lut_sata_table_len = ARRAY_SIZE(inx_otm1901a_5p2_1080p_video_acm_lut_sata_table);
			pinfo->acm_lut_satr_table = inx_otm1901a_5p2_1080p_video_acm_lut_satr_table;
			pinfo->acm_lut_satr_table_len = ARRAY_SIZE(inx_otm1901a_5p2_1080p_video_acm_lut_satr_table);
		}
		if (pinfo->gamma_support == 1)
		{
			pinfo->gamma_lut_table_R = inx_otm1901a_5p2_1080p_video_gamma_lut_table_R;
			pinfo->gamma_lut_table_G = inx_otm1901a_5p2_1080p_video_gamma_lut_table_G;
			pinfo->gamma_lut_table_B = inx_otm1901a_5p2_1080p_video_gamma_lut_table_B;
			pinfo->gamma_lut_table_len = ARRAY_SIZE(inx_otm1901a_5p2_1080p_video_gamma_lut_table_R);
			pinfo->igm_lut_table_R = inx_otm1901a_5p2_1080p_video_igm_lut_table_R;
			pinfo->igm_lut_table_G = inx_otm1901a_5p2_1080p_video_igm_lut_table_G;
			pinfo->igm_lut_table_B = inx_otm1901a_5p2_1080p_video_igm_lut_table_B;
			pinfo->igm_lut_table_len = ARRAY_SIZE(inx_otm1901a_5p2_1080p_video_igm_lut_table_R);
			pinfo->gmp_lut_table_low32bit = &inx_otm1901a_5p2_1080p_video_gmp_lut_table_low32bit[0][0][0];
			pinfo->gmp_lut_table_high4bit = &inx_otm1901a_5p2_1080p_video_gmp_lut_table_high4bit[0][0][0];
			pinfo->gmp_lut_table_len = ARRAY_SIZE(inx_otm1901a_5p2_1080p_video_gmp_lut_table_low32bit);
			pinfo->xcc_table = inx_otm1901a_5p2_1080p_video_xcc_table;
			pinfo->xcc_table_len = ARRAY_SIZE(inx_otm1901a_5p2_1080p_video_xcc_table);
		}
		break;
	case INX_OTM1906C_5P2_1080P_CMD_PANEL:
		if (pinfo->acm_support == 1)
		{
			pinfo->acm_lut_hue_table = inx_otm1906c_5p2_1080p_cmd_acm_lut_hue_table;
			pinfo->acm_lut_hue_table_len = ARRAY_SIZE(inx_otm1906c_5p2_1080p_cmd_acm_lut_hue_table);
			pinfo->acm_lut_sata_table = inx_otm1906c_5p2_1080p_cmd_acm_lut_sata_table;
			pinfo->acm_lut_sata_table_len = ARRAY_SIZE(inx_otm1906c_5p2_1080p_cmd_acm_lut_sata_table);
			pinfo->acm_lut_satr_table = inx_otm1906c_5p2_1080p_cmd_acm_lut_satr_table;
			pinfo->acm_lut_satr_table_len = ARRAY_SIZE(inx_otm1906c_5p2_1080p_cmd_acm_lut_satr_table);
		}
		if (pinfo->gamma_support == 1)
		{
			pinfo->gamma_lut_table_R = inx_otm1906c_5p2_1080p_cmd_gamma_lut_table_R;
			pinfo->gamma_lut_table_G = inx_otm1906c_5p2_1080p_cmd_gamma_lut_table_G;
			pinfo->gamma_lut_table_B = inx_otm1906c_5p2_1080p_cmd_gamma_lut_table_B;
			pinfo->gamma_lut_table_len = ARRAY_SIZE(inx_otm1906c_5p2_1080p_cmd_gamma_lut_table_R);
			pinfo->igm_lut_table_R = inx_otm1906c_5p2_1080p_cmd_igm_lut_table_R;
			pinfo->igm_lut_table_G = inx_otm1906c_5p2_1080p_cmd_igm_lut_table_G;
			pinfo->igm_lut_table_B = inx_otm1906c_5p2_1080p_cmd_igm_lut_table_B;
			pinfo->igm_lut_table_len = ARRAY_SIZE(inx_otm1906c_5p2_1080p_cmd_igm_lut_table_R);
			pinfo->gmp_lut_table_low32bit = &inx_otm1906c_5p2_1080p_cmd_gmp_lut_table_low32bit[0][0][0];
			pinfo->gmp_lut_table_high4bit = &inx_otm1906c_5p2_1080p_cmd_gmp_lut_table_high4bit[0][0][0];
			pinfo->gmp_lut_table_len = ARRAY_SIZE(inx_otm1906c_5p2_1080p_cmd_gmp_lut_table_low32bit);
			pinfo->xcc_table = inx_otm1906c_5p2_1080p_cmd_xcc_table;
			pinfo->xcc_table_len = ARRAY_SIZE(inx_otm1906c_5p2_1080p_cmd_xcc_table);
		}
		break;
	case JDI_NT35695_5P2_1080P_CMD_PANEL:
		if (pinfo->acm_support == 1)
		{
			pinfo->acm_lut_hue_table = jdi_nt35695_5p2_1080p_cmd_acm_lut_hue_table;
			pinfo->acm_lut_hue_table_len = ARRAY_SIZE(jdi_nt35695_5p2_1080p_cmd_acm_lut_hue_table);
			pinfo->acm_lut_sata_table = jdi_nt35695_5p2_1080p_cmd_acm_lut_sata_table;
			pinfo->acm_lut_sata_table_len = ARRAY_SIZE(jdi_nt35695_5p2_1080p_cmd_acm_lut_sata_table);
			pinfo->acm_lut_satr_table = jdi_nt35695_5p2_1080p_cmd_acm_lut_satr_table;
			pinfo->acm_lut_satr_table_len = ARRAY_SIZE(jdi_nt35695_5p2_1080p_cmd_acm_lut_satr_table);
		}
		if (pinfo->gamma_support == 1)
		{
			pinfo->gamma_lut_table_R = jdi_nt35695_5p2_1080p_cmd_gamma_lut_table_R;
			pinfo->gamma_lut_table_G = jdi_nt35695_5p2_1080p_cmd_gamma_lut_table_G;
			pinfo->gamma_lut_table_B = jdi_nt35695_5p2_1080p_cmd_gamma_lut_table_B;
			pinfo->gamma_lut_table_len = ARRAY_SIZE(jdi_nt35695_5p2_1080p_cmd_gamma_lut_table_R);
			pinfo->igm_lut_table_R = jdi_nt35695_5p2_1080p_cmd_igm_lut_table_R;
			pinfo->igm_lut_table_G = jdi_nt35695_5p2_1080p_cmd_igm_lut_table_G;
			pinfo->igm_lut_table_B = jdi_nt35695_5p2_1080p_cmd_igm_lut_table_B;
			pinfo->igm_lut_table_len = ARRAY_SIZE(jdi_nt35695_5p2_1080p_cmd_igm_lut_table_R);
			pinfo->gmp_lut_table_low32bit = &jdi_nt35695_5p2_1080p_cmd_gmp_lut_table_low32bit[0][0][0];
			pinfo->gmp_lut_table_high4bit = &jdi_nt35695_5p2_1080p_cmd_gmp_lut_table_high4bit[0][0][0];
			pinfo->gmp_lut_table_len = ARRAY_SIZE(jdi_nt35695_5p2_1080p_cmd_gmp_lut_table_low32bit);
			pinfo->xcc_table = jdi_nt35695_5p2_1080p_cmd_xcc_table;
			pinfo->xcc_table_len = ARRAY_SIZE(jdi_nt35695_5p2_1080p_cmd_xcc_table);
		}
		break;
	case LG_R69006_5P2_1080P_CMD_PANEL:
		if (pinfo->acm_support == 1)
		{
			pinfo->acm_lut_hue_table = lg_r69006_5p2_1080p_cmd_acm_lut_hue_table;
			pinfo->acm_lut_hue_table_len = ARRAY_SIZE(lg_r69006_5p2_1080p_cmd_acm_lut_hue_table);
			pinfo->acm_lut_sata_table = lg_r69006_5p2_1080p_cmd_acm_lut_sata_table;
			pinfo->acm_lut_sata_table_len = ARRAY_SIZE(lg_r69006_5p2_1080p_cmd_acm_lut_sata_table);
			pinfo->acm_lut_satr_table = lg_r69006_5p2_1080p_cmd_acm_lut_satr_table;
			pinfo->acm_lut_satr_table_len = ARRAY_SIZE(lg_r69006_5p2_1080p_cmd_acm_lut_satr_table);
		}
		if (pinfo->gamma_support == 1)
		{
			pinfo->gamma_lut_table_R = lg_r69006_5p2_1080p_cmd_gamma_lut_table_R;
			pinfo->gamma_lut_table_G = lg_r69006_5p2_1080p_cmd_gamma_lut_table_G;
			pinfo->gamma_lut_table_B = lg_r69006_5p2_1080p_cmd_gamma_lut_table_B;
			pinfo->gamma_lut_table_len = ARRAY_SIZE(lg_r69006_5p2_1080p_cmd_gamma_lut_table_R);
			pinfo->igm_lut_table_R = lg_r69006_5p2_1080p_cmd_igm_lut_table_R;
			pinfo->igm_lut_table_G = lg_r69006_5p2_1080p_cmd_igm_lut_table_G;
			pinfo->igm_lut_table_B = lg_r69006_5p2_1080p_cmd_igm_lut_table_B;
			pinfo->igm_lut_table_len = ARRAY_SIZE(lg_r69006_5p2_1080p_cmd_igm_lut_table_R);
			pinfo->gmp_lut_table_low32bit = &lg_r69006_5p2_1080p_cmd_gmp_lut_table_low32bit[0][0][0];
			pinfo->gmp_lut_table_high4bit = &lg_r69006_5p2_1080p_cmd_gmp_lut_table_high4bit[0][0][0];
			pinfo->gmp_lut_table_len = ARRAY_SIZE(lg_r69006_5p2_1080p_cmd_gmp_lut_table_low32bit);
			pinfo->xcc_table = lg_r69006_5p2_1080p_cmd_xcc_table;
			pinfo->xcc_table_len = ARRAY_SIZE(lg_r69006_5p2_1080p_cmd_xcc_table);
		}
		break;
	case TM_OTM1901A_5P2_1080P_VIDEO_PANEL:
		if (pinfo->acm_support == 1)
		{
			pinfo->acm_lut_hue_table = tm_otm1901a_5p2_1080p_video_acm_lut_hue_table;
			pinfo->acm_lut_hue_table_len = ARRAY_SIZE(tm_otm1901a_5p2_1080p_video_acm_lut_hue_table);
			pinfo->acm_lut_sata_table = tm_otm1901a_5p2_1080p_video_acm_lut_sata_table;
			pinfo->acm_lut_sata_table_len = ARRAY_SIZE(tm_otm1901a_5p2_1080p_video_acm_lut_sata_table);
			pinfo->acm_lut_satr_table = tm_otm1901a_5p2_1080p_video_acm_lut_satr_table;
			pinfo->acm_lut_satr_table_len = ARRAY_SIZE(tm_otm1901a_5p2_1080p_video_acm_lut_satr_table);
		}
		if (pinfo->gamma_support == 1)
		{
			pinfo->gamma_lut_table_R = tm_otm1901a_5p2_1080p_video_gamma_lut_table_R;
			pinfo->gamma_lut_table_G = tm_otm1901a_5p2_1080p_video_gamma_lut_table_G;
			pinfo->gamma_lut_table_B = tm_otm1901a_5p2_1080p_video_gamma_lut_table_B;
			pinfo->gamma_lut_table_len = ARRAY_SIZE(tm_otm1901a_5p2_1080p_video_gamma_lut_table_R);
			pinfo->igm_lut_table_R = tm_otm1901a_5p2_1080p_video_igm_lut_table_R;
			pinfo->igm_lut_table_G = tm_otm1901a_5p2_1080p_video_igm_lut_table_G;
			pinfo->igm_lut_table_B = tm_otm1901a_5p2_1080p_video_igm_lut_table_B;
			pinfo->igm_lut_table_len = ARRAY_SIZE(tm_otm1901a_5p2_1080p_video_igm_lut_table_R);
			pinfo->gmp_lut_table_low32bit = &tm_otm1901a_5p2_1080p_video_gmp_lut_table_low32bit[0][0][0];
			pinfo->gmp_lut_table_high4bit = &tm_otm1901a_5p2_1080p_video_gmp_lut_table_high4bit[0][0][0];
			pinfo->gmp_lut_table_len = ARRAY_SIZE(tm_otm1901a_5p2_1080p_video_gmp_lut_table_low32bit);
			pinfo->xcc_table = tm_otm1901a_5p2_1080p_video_xcc_table;
			pinfo->xcc_table_len = ARRAY_SIZE(tm_otm1901a_5p2_1080p_video_xcc_table);
		}
		break;
	default:
		HISI_FB_INFO("Panel ID not detected %d\n", panel_id);
		break;
	}
}


#endif /*_HW_LCD_EFFECT_H_*/
