##############################################
#     Make file of OV5648 camera sensor
##############################################

EXTRA_CFLAGS += -fno-pic
obj-$(CONFIG_HI6210_CAMERA_OV5648_OFILM) += ov5648_ofilm.o

#################### END #####################
