#
# Makefile for the hisi Linux kernel device drivers.
#
#
obj-$(CONFIG_HISILICON_PLATFORM_MUTEX_SERVICE)+= mutex_service.o
obj-$(CONFIG_HISILICON_PLATFORM_MUTEX_SERVICE)+= test_mutex_service_ker.o