ccflags-y += -I$(BALONG_TOPDIR)/modem/drv/acore/kernel/drivers/hisi/modem/drv/ipf
ccflags-y += -I$(BALONG_TOPDIR)/modem/drv/acore/kernel/drivers/hisi/modem/drv/socp
obj-y += ipf_stress_test.o
obj-y += k3_busstress_balong.o
obj-y += socp_balong_test.o
