##############################################

#EXTRA_CFLAGS += -Idrivers/huawei/camera/miniisp/camera/sonyimx214
#EXTRA_CFLAGS += -Idrivers/huawei/camera/miniISP/camera

obj-y += sonyimx214.o

#################### END #####################
