obj-$(CONFIG_HISI_COUL_HI6421V500)	+= hi6421v500/
obj-$(CONFIG_HISI_COUL_HI6555V100)	+= hi6555v100/
obj-$(CONFIG_HISI_COUL)	            += hisi_coul_core.o hisi_coul_drv.o
obj-$(CONFIG_HISI_COUL_TEST)        += hisi_coul_drv_test.o

